### ISSUE TITLE
Change ObjectWriter::withAttributes() to take a Map with some kind of wildcard types

### ISSUE THREAD

**Issue by david-bakin** [FasterXML/jackson-databind#1011]
If I've got a `Map<String,String>` I'd like to use with `ObjectWriter::withAttributes` I can't directly pass it to the method because `withAttributes()` takes a `Map<Object,Object>`.  I can cast to `Map` (with a `@SuppressWarnings("unchecked")`, but ... instead, please consider changing the argument type of `withAttributes` to something wildcardish.  I'm not sure what it should be, maybe simply `Map<?,?>`?

BTW, thanks for `withAttributes()` .. very useful!

**Comment by cowtowncoder** [comment]
Ok. Usually change in signatures is risky, but unless I am mistaken such change should be safe from binary compatibility perspective, as erased type does not change.
I will have to do this for 2.7 (and not 2.6.x), still, since it is API change and changes compilation. Might be safe but I have learnt to try to play things safe in this regard.
