### ISSUE TITLE
ObjectNode comparison fails with out of order Lists as children values 

### ISSUE THREAD

**Issue by PeterGroesbeck** [FasterXML/jackson-databind#1021]
Hi, this is my first time reaching out to an open source project so apologies in advance if I am mistaken.

For context, I am using the ObjectNode class to compare Json records and according to both of the following links, ordering should not matter:

http://stackoverflow.com/a/2255893/1467961

https://github.com/FasterXML/jackson-databind/issues/366

While ObjectNode's LinkedHashMap _children will allow comparison regardless of order due to the logic in the equals method in AbstractMap (line 452), the ArrayList object in ArrayNode will fail when comparing 2 Lists that are out of order in AbstractList (line 512). ObjectNode's children can include ArrayNodes so this can cause a failure when calling the equals method from an ObjectNode when one of it's children's list order is non deterministic.

The following question provides some suggestions when doing a List comparison, my personal favorite being:
 
```
listA.containsAll(listB) && listB.containsAll(listA)
```

http://stackoverflow.com/questions/13501142/java-arraylist-how-can-i-tell-if-two-lists-are-equal-order-not-mattering

**Comment by cowtowncoder** [comment]
As far as I understand, ordering of elements in JSON Arrays does matter, unlike in JSON Objects.
While JSON specification does not actually specify expected equality semantics, I think this is what is commonly expected. It is also behavior that Jackson has had ever since equality was fully implemented, so it is unlikely this would be changed.

If your use case does require or benefit from different equality rules, I think you will need to use custom comparison logic. One things that may make it bit easier to do structural (recursive) comparison is to use

    public boolean equals(Comparator<JsonNode> comparator, JsonNode other)

method in `JsonNode`: it will invoke `Comparator.compareTo(...)` method appropriately, although you will need to take care to override handling in case of `ArrayNode` as noted and not rely on its delegation. This will get rather difficult and potentially inefficient with nested arrays, but it is doable.

**Comment by PeterGroesbeck** [comment]
The issue is that ObjectNode comparison fails when the Json contains a List as a value to one of it's children. You have said in the past:

"This is not intentional: ordering should NOT be taken into account."

https://github.com/FasterXML/jackson-databind/issues/366

If I'm understanding correctly, 2 ObjectNode objects should evaluate as equal regardless of their ordering, which is not the behavior I'm seeing. According to the Stack Overflow answer below, Jackson previously supported order agnostic equality, so it would seem to me that this is a regression:

http://stackoverflow.com/questions/2253750/compare-two-json-objects-in-java/2255893#2255893

On my end I could write an algorithm to order the Json's elements prior to making a comparison, however if I want to do any sort of comparison that delegates to the normal equals method, for example an assert statement or a set comparison, I'm not sure that solution would work.

**Comment by cowtowncoder** [comment]
Yes, but that means "children" and not all descendants. Contents of a child JSON Array are not children of JSON Object that contains the List. `ObjectNode` simply looks for matching properties, and calls `equals()` on them, recursively, and definition of equality for `ArrayNode` includes ordering.

**Comment by PeterGroesbeck** [comment]
While 2 arrays are not equal if they are out of order, from my understanding of the javadocs the objects themselves should still be considered equivalent:

"Equality for node objects is defined as full (deep) value equality."

From the Stack Overflow answer below, an explanation of deep equivalency would be:

"deep means that you compare contents of your objects recursively until all you need to compare is primitive fields."

http://stackoverflow.com/a/5703797/1467961

Thanks for the quick responses by the way! I understand the current logic but it still seems odd to me that you couldn't make a valid object comparison that takes into account nesting as that seems common.

**Comment by cowtowncoder** [comment]
@PeterGroesbeck What I am saying is that I think current equality definition is what makes most sense for general-purpose JSON equality purposes, and that it is unlikely this would be changed. Use of `Object#equals()` is problematic in many ways, since it can not really be externally configured, as well, so the need to use external equality comparison logic is quite common.
It is also possible that documentation could be improved, if it does not explain how things work in enough detail.

I am not trying to argue that comparisons that you would like to have would not make sense for your use case. Just that as far as I see things, order of values is absolutely meaningful for JSON arrays, in general; similar to, say, distinction for casing (upper/lower/title case) matters for JSON Object property names, even if there are use cases where one would prefer not to make such distinction. If so, it is not unreasonable to want to, say, do property-name-case-insensitive comparison. But I would not want to change the baseline equality comparison because of such use case.

**Comment by PeterGroesbeck** [comment]
Ok makes sense, thanks again for taking the time to respond!
