### ISSUE TITLE
Bad Request when sending a big number at json

### ISSUE THREAD

**Issue by gustavolira** [FasterXML/jackson-databind#1030]
Hi,

If I send a number with 10 digits Spring accept my request, but if I send a number with more than 10 digits Spring return status 400 (Bad request).
I configured Jackson to accept receive fields at json without quotes, I need this behavior for numbers.

So when I send for example:
```JSON
{
"number": 12345678912
}
```
I always receive status 400

I'm using Spring Boot 1.3

**Comment by cowtowncoder** [comment]
This is unfortunately not enough information to know what is going on; at minimum you would need to show what Java class you are trying to bind data to. Actual exception would also be necessary; and the problem itself may well reside within Spring boot handlers.

Numbers are always included without quotes in JSON, so that should be fine.
