### ISSUE TITLE
ArrayNode: support passing in child collection in constructor

### ISSUE THREAD

**Issue by phraktle** [FasterXML/jackson-databind#1048]
Similar to ObjectNode, ArrayNode should support taking a List parameter explicitly.

The use case is to support creating immutable instances that are safe to cache. This can be done with ObjectNode by passing in an immutable Map, however, ArrayNode does not support the same.  (See also older discussion #115)

**Comment by cowtowncoder** [comment]
Added minimal patch to allow passing of specific `List`. Not sure if that is sufficient in itself but hopefully a good start. Please let me know if you have other ideas, as they could still make it in 2.7.0 which will be released quite soon (during December 2015).

**Comment by phraktle** [comment]
Thanks, that should do it! Any chance it can be backported to a 2.6.x release as well?

**Comment by cowtowncoder** [comment]
@phedny Unfortunately this is bit tricky, since it is technically public API, and as such should not be backported. Hmmh...

2.7 should still work on Java 6 platform, as I've tried to keep loading of Java 7 types dynamic, even if it can not be compiled on Java 6 any more. One thing that would be helpful would be to see if you could locally use 2.7.0-rc2 on Java 6 JVM -- it should work (and does for my testing), although I don't know if Maven would complain.

**Comment by phraktle** [comment]
To be certain that 2.7 works on Java 6, you would have to build it with -source 1.7 -target 1.6 and -Xbootclasspath:/jdk16/jre/lib/rt.jar

In any case, I'm also trying to raise the target version of the library in question, since I also believe no current developments should support Java 6 (people stuck on that should be stuck with older libraries as well :)
