### ISSUE TITLE
@JsonCreator annotated class inside regular class does not get deserialized

### ISSUE THREAD

**Issue by uyilmaz** [FasterXML/jackson-databind#1063]
When there is a class with single arg constructor annotated with @JsonCreator inside another reqular bean:

	public class Sample implements Serializable {
		private static final long serialVersionUID = 1L;
		
		EmailAddress email;
		
		public Sample() {
		}

		public EmailAddress getEmail() {
			return email;
		}

		public void setEmail(EmailAddress email) {
			this.email = email;
		}
	}
	
	
	public class EmailAddress implements Serializable {
		String email;
		
		@JsonCreator
		public EmailAddress(@JsonProperty("email") String email) {
			Validate.notNull(email);
			this.email = email;
		}
		
		public String getEmail() {
			return email;
		}	
	}

with a json for Sample:

	{
	  "email": "dsafdsa@dsfsd.com"
	}

fails with:

 com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.blabla.vo.EmailAddress] from String value ('dsafdsa@dsfsd.com'); no single-String constructor/factory method

however, this seems to work:

	{
	  "email": {
                  "email" : "asdfsdf@dsfdsf.com"
           }
	}

Is there something wrong I am doing or is there an issue here?

**Comment by kdkeck** [comment]
Does it work as expected if you remove the annotations from the `EmailAddress` constructor?

**Comment by uyilmaz** [comment]
Yes, when I remove @JsonProperty from the constructor (not the JsonCreator) it works, a single String is converted to an object. It's the <i>Delegate-based creator</i> mentioned in the docs I think. Plus, you need to annotate getEmail() with JsonValue to convert it to a single string when serializing.

**Comment by cowtowncoder** [comment]
@uyilmaz This is because you are indicating that the expected JSON format should be:

```json
{
    "email" : "...."
}
```

instead of JSON String.

There are couple of ways to fix this: the most explicit one is to use

```java
@JsonCreator(mode=Mode.DELEGATING)
```

although you can also alternatively just remove `@JsonProperty` from the argument. Either should make `@JsonCreator` accept JSON String.

Difference here is whether that one argument is to be passed as the "delegating" value (that is, bound from JSON into type of the argument, in this case, from JSON String to java.lang.String); or, whether it is expected to be one property of a full JSON Object, with specific name. If there were more than argument, only latter would be possible, but with one argument there are two possibilities.
