### ISSUE TITLE
Broken/Poor test for node.equals(comparator, value)

### ISSUE THREAD

**Issue by tsarna** [FasterXML/jackson-databind#1067]
Have a look at the compare method in testCustomComparators in /src/test/java/com/fasterxml/jackson/databind/node/TestJsonNode.java. It returns 0 (equal) in every case!

Note that the test passes anyway, because the conditions tested are insufficient.

Also notice that vital functionality like traversing through nested objects and arrays is not tested at all. I think you will find when such tests are added, they'll fail. Try something like: {"x":[5]} vs {"x":[5.0]}

The main value of this interface is that, as the documentation says (emphasis added), "*Nodes will handle traversal of structured types* (arrays, objects), but defer to comparator for *scalar* value comparisons." A good test should verify this (and find that currently, that's not what's implemented).

**Comment by cowtowncoder** [comment]
PRs welcome.

**Comment by danielnorberg** [comment]
I tried using the custom comparator equals and my custom comparator got called with a pair of `ObjectNode`s :smile: 

Seems nested Object/ArrayNode traversal might be broken.

This code in the ObjectNode custom comparator equals:
```java
for (Map.Entry<String, JsonNode> entry : m1.entrySet()) {
    JsonNode v2 = m2.get(entry.getKey());
    if ((v2 == null) || comparator.compare(entry.getValue(), v2) != 0) {
        return false;
    }
}
```

Should perhaps be something like:

```java
for (Map.Entry<String, JsonNode> entry : m1.entrySet()) {
    JsonNode v2 = m2.get(entry.getKey());
    if (v2 == null || entry.getValue().equals(comparator, v2) != 0) {
        return false;
    }
}
```

And similarly in ArrayNode:

```java
for (int i = 0; i < len; ++i) {
    if (comparator.compare(l1.get(i), l2.get(i)) != 0) {
        return false;
    }
}
```

Should be something like:

```java
for (int i = 0; i < len; ++i) {
    if (!l1.get(i).equals(comparator, l2.get(i))) {
        return false;
    }
}
```

In order to actually traverse multiple levels of Object/ArrayNode.

Haven't tested and/or tried compiling the above fixes.

I can put together a PR unless someone beats me to it.

**Comment by cowtowncoder** [comment]
@danielnorberg You may be right, wrt calls here; delegation would not work as is (took a while to wrap my brain around it -- but yes, I see what you mean).

It would be great to get reproductions of failures for Object, Array first, and then fix.
