### ISSUE TITLE
New feature: JsonTypeInfo.Id.GENERIC_TYPE

### ISSUE THREAD

**Issue by hoomanv** [FasterXML/jackson-databind#1086]
I'm wondering why there is no such JsonTypeInfo.Id.GENERIC_TYPE yet available.
The existing JsonTypeInfo.Id.CLASS is not generics friendly, so why not simply introduce a new TypeIdResolver that handles generic signature as well?

Consider the following class assuming that JsonTypeInfo.Id.GENERIC_TYPE exists.
We use a Payload to wrap everything before sending it on the wire.

``` java
private static final class Payload<T>
{
        @JsonTypeInfo(use = JsonTypeInfo.Id.GENERIC_TYPE)
        private T payload;
}
```

To write a payload containing a List&lt;MyModel&gt; we would do

``` java
objectMapper.writerFor(new TypeReference<Payload<List<MyModel>>>() {}).write( ...
```

That should generate something like this

``` json
{"payload": {"@type": "java.util.List<com.mydomain.MyModel>", "key": "value", ... } }
```

And the receiver is expected to use "java.util.List&lt;com.mydomain.MyModel&gt;" to construct the proper JavaType for deserialization. No more type erasure hassle right ?

Is it not feasible?

**Comment by cowtowncoder** [comment]
One challenge is that the only level at which generic types are available at runtime is the root value: anything deeper will have type-erasure kick in, and lose type. In your example root value is nested, and you can indeed provide the type.

Given this, would it make more sense to try to improve `Id.CLASS` to support generics in cases where possible? It may be difficult to figure out whether parameterization is available of course, and we would not want to use generic notation if types are just default ones.

**Comment by cowtowncoder** [comment]
One more note: actually realized that nesting itself is not the limiting factor, but rather that generic types must be brought from outside (via `TypeReference` or `JavaType` constructed directly via `TypeFactory`) to whatever level necessary.

Internally there is a way to decode generic types, I think, since this is actually used for some special cases (can't remember exactly where, but it is done). So support might be doable, if distinction can be made wrt placeholder type variables (so "raw" type `List`, is seen as basically `List<Object>`; but similarly also for type bounds).

**Comment by hoomanv** [comment]
I just noticed that this generic notation is already used for EnumSet class
```
["java.util.EnumSet<mydomain.MyModel>",["CONSTANT"]]
```

**Comment by cowtowncoder** [comment]
@hoomanv yes, I think that was the special case I vaguely remembered, and that was required by oddities of `EnumSet` and/or `EnumMap`, where type is otherwise impossible to read back. I don't recall all the details (like, why does that differ from `Set` in general...), but there was some oddity.

So the underlying mechanism that already exists could perhaps help here.

Providing a unit test would also help: I get the basic problem, but concrete code, even if simple, would be useful to show the issue (writing, reading sample type fails currently), verify solution.

**Comment by cowtowncoder** [comment]
One thing here: I think a unit test that shows the problem (and does not try to use new hypothetical type info marker) would make sense here.

**Comment by cowtowncoder** [comment]
One more note: current internal api for type id handler is not sufficient to work here -- for serialization, only type-erased `Class` (and possible value instance) are passed, not `JavaType`. And without `JavaType`, there is no generic type information available. So while actual handling of generic type signature is actually supported (for `EnumSet` and `EnumMap`), that only works there since type happens to be available (with some massaging).

**Comment by cowtowncoder** [comment]
I don't think this can be implemented with current system, unfortunately; closing for now.
