### ISSUE TITLE
deserialize json  `{"xx":{"x":"x"}}` to Map<String,String>

### ISSUE THREAD

**Issue by Dreampie** [FasterXML/jackson-databind#1096]
json from Map<String,Object> ,value contains many Model,so can't use TypeRefrence,I want deserialize first level to string,and deserialize second level when needed
```java
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {"xx":{"x":"x"}}; line: 1, column: 2] (through reference chain: java.util.LinkedHashMap["xx"])
```

**Comment by cowtowncoder** [comment]
There is no way to do that.

You may want to read a `Map<String,Object>`, or `Map<String,JsonNode>`, in which case values can be `Map`s (first case), or tree nodes (second case).

But there is no way to try to "extract" raw JSON out of input; since input needs to be tokenized anyway (to ensure validity, find token boundaries), it will need to be presented in some form.

Alternatively you just read the whole value as `JsonNode`, and traverse it explicitly.

I hope this helps.
