### ISSUE TITLE
Support JsonTypeInfo.Id.MARKER_FIELD request

### ISSUE THREAD

**Issue by lex-em** [FasterXML/jackson-databind#1100]
Hi, does this capability can be realized?
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.MARKER_FIELD)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ComplexTypeDto.class, name = "fields")
})
public class SimpleTypeDto {

    private String id;

    private String name;

   ...
}
````

```java
public class ComplexTypeDto extends SimpleTypeDto {
    private Collection<FieldDto> fields;
}
```

Serialization example data:
```java
List<SimpleTypeDto> types = new ArrayList<>();
types.add(new SimpleTypeDto(123, "simple type"));
types.add(new ComplexTypeDto(345, "complex type", Arrays.asList(new FieldDto("field")));
```

Json:
```json
[
  {
    "id":123,
    "name":"simple type"
  },
  {
    "id":345,
    "name":"complex type",
    "fields":[
        {
             "name":"field"
        }
    ]
  }
]
```

**Comment by lex-em** [comment]
for more convenience can be added annotation @JsonSubTypesByFields (with multiple names):
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.MARKER_FIELD)
@JsonSubTypesByFields({
        @JsonSubTypesByFields.Type(value = ComplexTypeDto.class, names = {"fields"})
})
public class SimpleTypeDto {

    private String id;

    private String name;

   ...
}
```

**Comment by cowtowncoder** [comment]
There is an existing issue for something along those lines, to allow inference of type information from existence of fields: #43 

I don't think anyone is actively implementing such functionality: the main problem is that this does require holding the whole JSON Object in memory (currently this is not needed; property values are handled incrementally, with some exceptions related to buffering of type and/or object ids).

I will add a link to this issue from there (since these are additional ideas), but will close this as duplicate.
Feel free to add notes to #43 as relevant.

**Comment by lex-em** [comment]
@cowtowncoder thank you for detailed answer

**Comment by cowtowncoder** [comment]
@lex-em no problem, thank you for suggestion -- this is desired piece of functionality, but unfortunately not yet implemented.
