### ISSUE TITLE
DateDeserializer changes the timezone of local dates to UTC

### ISSUE THREAD

**Issue by aseovic** [FasterXML/jackson-databind#1110]
If a local date is written out without timezone information (using `yyyy-MM-dd` pattern, for example) its timezone is defaulted to UTC on deserialization, which effectively breaks date round tripping:

```java
public void testLocalDateRoundTrip() throws Exception
    {
    Person p1 = new Person();
    p1.dateOfBirth = new Date(107, 11, 28); // 2007-12-28, in default (local) timezone;

    String json = MAPPER.writeValueAsString(p1);
    System.out.println(json);
    Person p2 = MAPPER.readValue(json, Person.class);

    assertEquals(p1.dateOfBirth, p2.dateOfBirth);
    }
```
fails with:
```
junit.framework.AssertionFailedError: 
Expected :Fri Dec 28 00:00:00 EST 2007
Actual   :Thu Dec 27 19:00:00 EST 2007
```
This is nonintuitive, to say the least, and is caused by the UTC being used as the default timezone. 

It probably makes more sense to use the default (local) JVM timezone (`TimeZone.getDefault`) as the default instead for values that do not specify timezone explicitly one way or another.

**Comment by cowtowncoder** [comment]
Unfortunately I think this is design flaw of `java.util.Date` -- values are internally `long`s and there is no associated `TimeZone`. As such they must be serialized either as numbers, or textual representation that includes timezone information.

Note that line:

    new Date(107, 11, 28);

does NOT assign any timezone for value, although it obviously does use some timezone for calculating timestamp. This is probably why this constructor has been deprecated since Java 1.1.

You can set the default `TimeZone` for `ObjectMapper` to use instead of UTC if you want to; if so, that will be used for `java.util.Date` values (unless specified by format used).

So I agree that this is unfortunate handling, but I don't think there is a good way around this. Relying on JVM default TimeZone is no less problematic than using UTC in my opinion.
Further, changing this default would be likely to cause a flurry of bug reports by users who are relying on UTC based on past experiences.

**Comment by aseovic** [comment]
This is a tough one, I admit, as changing the default could have negative impact on anyone trying to upgrade, and it's easy enough to explicitly configure the timezone in `DeserializationConfig`.

That said, I don't think the test above should fail when using Jackson's default configuration, and it's easy enough to change the default if necessary.

**Comment by aseovic** [comment]
Yeah, I have nothing nice to say about `java.util.Date` either -- hopefully people will start moving to Java 8 and start using java.time.* classes, which are much better.

I think I agree that in this particular case leaving behavior as-is is probable the lesser of two evils, so I'll close this issue.

**Comment by cowtowncoder** [comment]
@aseovic Agreed. I appreciate your filing the issues and improving code quality here. Let's indeed hope that Joda, Java 8 date/time will keep on replacing old java.util.Date/Calendar usage.
