### ISSUE TITLE
UnrecognizedPropertyException in 2.7.1 for properties that work with version 2.6.5 

### ISSUE THREAD

**Issue by Roleek** [FasterXML/jackson-databind#1128]
The attached test case works fine with version 2.6.5 but it produces com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" with version 3.7.1.
[QuickTestJacksonIssue.zip](https://github.com/FasterXML/jackson-databind/files/128566/QuickTestJacksonIssue.zip)

**Comment by cowtowncoder** [comment]
Thank you for reporting this, providing test case.

**Comment by cowtowncoder** [comment]
Ah-ha. Looks like self-referential recursive type (`ResolvedRecursiveType`) is part of the problem here.
Not yet sure how, but seems to be the type that is missing properties.

**Comment by cowtowncoder** [comment]
Fixed part of the problem, so that `id` field is handled. Remaining issue with field `p1` seems like something that should be resolvable; but it also appears to not fail only if `p1` is suppressed during serialization; if value is not `0`, for example, it fails with 2.6. as well.

**Comment by cowtowncoder** [comment]
Actually, looking through the example with more thought, I realize that code now does work: the issue is with class definition. Field `parent` can not be resolved to anything higher than `DevBase` due to declaration of:

    class DevBase extends HObj<DevBase>

during deserialization; but during serialization, actual type of `parent` is `DevM`. To solve that, either type parameterization would have to be carried through class hierarchy (if possible), or, polymorphic handling should be enabled for `HObj` (or perhaps `DevBase`).
Anyway, I think fix is actually complete here.
