### ISSUE TITLE
2.7.1 with parameter-names module fails to deserialize into map

### ISSUE THREAD

**Issue by jebl01** [FasterXML/jackson-databind#1141]
I'm having a model in a service that heavily depends on custom serializations. Everything is fine and dandy with that. But - when I tested the service (spring boot) I noticed that the actuator endpoint failed with NPE (message: "Can not pass null fieldName")

Test showcasing the problem:
https://github.com/jebl01/jackson-test

**Comment by cowtowncoder** [comment]
Thank you for providing the test case.
Looks like NPE you get first is a side-effect of passing `null` to exception handling code; I'll straighten that out first. But there is also a more fundamental problem which seems to be caused by parameter names module.

**Comment by cowtowncoder** [comment]
@jebl01 I suspect your best bet is simply to NOT specify `JsonCreator.Mode.PROPERTIES` when constructing module (either use zero-arg constructor, or pass `null`). I think the problem here is the auto-detection of single-argument constuctor of `HashMap`; and this is exactly why I have been against various auto-detection schemes -- there is non-trivial possibility of false matches. And I think this is what happens here: `HashMap` happens to have a public 1-argument constructor, into which data is bound.
It really should not be auto-detected, but all the checks are marked; it's just a Java object that is eligible to use creator method.

**Comment by cowtowncoder** [comment]
Since the remaining issue is due to parameter names module, recreating over there.

**Comment by jebl01** [comment]
ok, thanks!
Solved it right now by having two mappers registered in spring and being explicit which one to inject where...
