### ISSUE TITLE
Could not find class 'java.beans.Transient'

### ISSUE THREAD

**Issue by AnkurJagani** [FasterXML/jackson-databind#1158]
Would you please help me with below screenshot. Thanks in advance. 
![screen shot 2016-03-10 at 2 47 05 pm](https://cloud.githubusercontent.com/assets/7710697/13664850/7da0bc8c-e6cf-11e5-982d-b0267859ab42.png)

**Comment by cowtowncoder** [comment]
Not really without some actual explanation of your use case, Jackson version used, code, everything.

**Comment by cowtowncoder** [comment]
I assume this is related to Android.

But aside from warnings, is there an actual failure? Warnings from inability to dynamically load a class that is not there should be find; that is the point of dynamic loading.

**Comment by biaomingzhong** [comment]
@cowtowncoder I ran into the same error.
I am using
`  compile 'com.fasterxml.jackson.core:jackson-core:2.7.1'
  compile 'com.fasterxml.jackson.core:jackson-databind:2.7.1'`

Here is my use case: 
`
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Result<T> {

  private T data;
  private int status;
  private String info;

  @JsonCreator public Result(@JsonProperty("data") T data, @JsonProperty("status") int status,
      @JsonProperty("info") String info) {
    this.data = data;
    this.status = status;
    this.info = info;
  }

  public T getData() {
    return data;
  }

  public int getStatus() {
    return status;
  }

  public String getInfo() {
    return info;
  }
}
`

**Comment by cowtowncoder** [comment]
@biaomingzhong that information does not help: it is not code that is problematic, but deployment.

But since no one has been able to explain what actually happens that is a problem -- logging warnings are not a problem -- I don't know how I can help here.

**Comment by biaomingzhong** [comment]
@cowtowncoder Thanks

**Comment by Soulcyber** [comment]
i have the same warning logs. but i'm not explaining where they are coming from...
if i have time i will investigate a bit more ;)

for me it's happening with 2.7.2 version

**Comment by havri** [comment]
@AnkurJagani Maybe you're just missing the Apache Commons BeanUtils library. Try to add it into your project: http://commons.apache.org/proper/commons-beanutils/

I know this thread is already dead, but I faced this error message today and nowhere found any resolution related to jackson and java.beans.

**Comment by lin1987www** [comment]
Try add below line to proguard-rules.pro file

-keep class java.beans.** { *;}

It is work

**Comment by atonamy** [comment]
@havri 
same for me. Anyone know how to fix it?

**Comment by cowtowncoder** [comment]
@atonamy What "same for me"? What is there to fix? Why did you add a note without adding any new information? Did you not bother reading any of earlier discussion?

`java.beans` is standard JDK package that has existed since JDK 1.0. New classes have been added, most notably some new classes were added in 1.7, like annotations `java.beans.Transient`.
These are not included on some broken platforms like Android.
Jackson tries to load these, but not finding them prints a warning, leaves.

As far as I know there is nothing to fix here.

Since there is no useless information here, I'll lock the discussion here; new issue with actual description of what supposed issue may be filed.
