### ISSUE TITLE
Jackson Databind InvalidPackage

### ISSUE THREAD

**Issue by maksim88** [FasterXML/jackson-databind#1192]
Hey,

when running lint in my project (jackson-core and jackson-databind version 2.7.3) i get a lint error 
`InvalidPackage: Package not included in Android`

The whole message: 
`../../../../../../.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.7.3/f12e6cd05cbaecd74d16e685d45b627732939e42/jackson-databind-2.7.3.jar: Invalid package reference in library; not included in Android: java.nio.file. Referenced from com.fasterxml.jackson.databind.ext.PathDeserializer.`

Can something be done here apart from disabling `InvalidPackage` checks or converting them into warnings?

Thanks a lot!

**Comment by cowtowncoder** [comment]
@maksim88 Unfortunately I don't think anything else is possible since the reference is needed for dynamic loading of handler for `java.nio.file.Path`, if (but only if!) it exists. As such code works on Android, too, while also supporting full range of regular J2SE types.

If anyone has better ideas for being able to avoid the warning I am open to suggestions.

**Comment by maksim88** [comment]
Thanks a lot for you answer. Then i'll just convert it to a warning.
You may close the ticket or leave it there as a reference if someone else is wondering

**Comment by cowtowncoder** [comment]
@maksim88 Thanks -- I'll close it, mostly because there are so many open issues. I hope search will still find it regardless.
