### ISSUE TITLE
Wrong Return type of  com.fasterxml.jackson.databind.node.ObjectNode#set

### ISSUE THREAD

**Issue by oemaix** [FasterXML/jackson-databind#1212]
The Return type of the method (`objectNode.set(value)`) should be `ObjectNode` rather then `JsonObject`. The logic of the method is set a child of this `ObjectNode` and return itself, if the return type is `ObjectNode`, we could chain the invocation to set multi children.
`com.fasterxml.jackson.databind.node.ObjectNode#setAll` also has the same problem.

**Comment by cowtowncoder** [comment]
I agree, but unfortunately this can not be change at this point: any change would be binary incompatible and break lots of existing code that calls these methods. There should be an earlier issue filed for this as well.

**Comment by oemaix** [comment]
Should this problem be solved in the later major version or would never be solved any more?
In most occasions this should not be a big problem, cause `ObjectNode` is a subtype of `JsonNode`.

**Comment by cowtowncoder** [comment]
@oemaix It can not be solved for 2.x. If there is a major version (like 3.x), it could be fixed.

As to severity, I am not sure you fully understand it: problem is NOT with case where you directly use object model and recompile code, it is in case where existing code (a dependency) has been compiled against existing Jackson version, and something tries to load that version with newer definition. In this case class loader throws an error, pointing out it can not find the method (since its signature has changed -- it is not the same method from CL perspective). Compiler can find the definition just fine (change of return type does not change matching there), however.

Such problem occurred at least once with Jackson 1.x, causing lots of grief for Hadoop users (between 1.1 and 1.2 of Jackson, or so). It's a really, really nasty problem to have: when recompiling, you are unlikely see an issue (since assignment works), but when upgrading, you crash during runtime.

**Comment by oemaix** [comment]
Since there's no clear plan for a new major version and it cannot be solved in 2.x. I think it is better to close it now.

**Comment by victornoel** [comment]
@cowtowncoder @oemaix please consider reopening this and adding a new method until a new major version can be released, creating new ObjectNode is hell to use without chaining :)

**Comment by victornoel** [comment]
I've opened a new issue #2339 for this
