### ISSUE TITLE
Released library versions

### ISSUE THREAD

**Issue by guidomedina** [FasterXML/jackson-databind#1216]
I see there is `jackson-core` and `jackson-annotations` at version 2.7.4 and `jackson-databind` still at version 2.7.3

For some projects it is difficult sometimes to update because of version inconsistency among modules, I wonder if this can be handled in a way that versions are released in a consistent manner.

My apologies for the complain though as you guys still do an amazing job with Jackson APIs.

**Comment by cowtowncoder** [comment]
@guidomedina This is only because I have started the release process, but given large number of repos, it has not been completed. So rest assured that the full set will be released. :)
Additionally there was one glitch specifically wrt getting `jackson-databind` out; but we will proceed with that next.
