### ISSUE TITLE
TypeFactory.uncheckedSimpleType not including super-type info causing missing field property definitions during POJO property collection

### ISSUE THREAD

**Issue by headw01** [FasterXML/jackson-databind#1222]
When using the TypeFactory to create an "unchecked simple type" from a Class, the BasicClassIntrospector doesn't assign the Class fields to the BeanPropertyDefinition list.

This appears to be due to the TypeFactory.uncheckedSimpleType not including the super-type info.  The AnnotatedClass._findFields checks to see if the superclass is NULL before processing the fields. 

This commit is where the change to uncheckedSimpleType was added: https://github.com/FasterXML/jackson-databind/commit/07d946c11d447ba88b62d28750a33651c897da29

In this code, the BeanPropertyDefinition list would not have any of the Java Field properties (even with @JsonProperty annotation).

        Class<T> type = ...
        ObjectMapper mapper = ...
        JavaType javaType = mapper.getTypeFactory().uncheckedSimpleType(type);
        BasicClassIntrospector introspector = new BasicClassIntrospector();
        BasicBeanDescription bdesc = introspector.forDeserialization(mapper.getDeserializationConfig(), javaType, null);
        List<BeanPropertyDefinition> bprops = bdesc.findProperties();
        
        bprops.stream().forEach((BeanPropertyDefinition bprop) -> {
            String name = bprop.getName();
            properties.put(name.toLowerCase(), bprop);
        });

**Comment by headw01** [comment]
A workaround is to use TypeFactory.constructParametricType instead of uncheckedSimpleType:

    Class<T> type = ...
    JavaType javaType = mapper.getTypeFactory().constructParametricType(type, new JavaType [] {});

**Comment by cowtowncoder** [comment]
@headw01 User code should really never call `uncheckedSimpleType`, as it has multiple issues. I will need to address this better in Javadocs, and perhaps even deprecate it. There is really no reason to use it.

So: wherever this method is used, `constructType` should be called.

**Comment by cowtowncoder** [comment]
That is to say: thank you for reporting this -- I take it as RFE for making it clear to everyone that this method should not be called, ever; existing documentation is not clear here.

**Comment by headw01** [comment]
Thanks for the feedback... I wrote that code a long time ago, and I guess I didn't notice the constructType method on TypeFactory.

Is the introspection supposed to honor the MapperFeature.AUTO_DETECT_GETTERS/SETTERS setting (set to false) on the MapperConfig?  When I tried this and looked at the List<BeanPropertyDefinition> result, there were properties for get/setValue methods that didn't have the @JsonProperty annotation on them.

**Comment by cowtowncoder** [comment]
@headw01 Ok to start, `TypeFactory` just constructs type hierarchy and resolves type parameters. It does nothing to introspect member information itself (although `JavaType`s are needed to further resolve member types, method parameters, return types etc).

Classes that collect accessors are `POJOPropertiesCollector` and `POJOPropertyBuilder`. They will indeed take into account `AUTO_DETECT_GETTERS` when considering visibility of accessors. But there are many combinations of visibility levels, as well as settings that may "pull" in mutators, so unexpected behavior may occur.

If you do have unexpected behavior feel free to file a separate issue, so that I can keep this one as a reminder for javadoc changes. And other problems you have may lead to other changes.
