### ISSUE TITLE
Polymorphic Serialization issue with google AutoValue

### ISSUE THREAD

**Issue by nlenoire** [FasterXML/jackson-databind#1234]
I'm creating the issue https://github.com/FasterXML/jackson-annotations/issues/88 in the databind package.

In a nutshell, using the annotations `@JsonTypeInfo/@JsonSubTypes` with a type name specified for each sub-types doesn't work if the sub-type is also an abstract class. Each sub-types are required to declare a @JsonTypeName which causes the serialization/deserialisation schem to be spread around the classes.

**Comment by cowtowncoder** [comment]
As per earlier comments, I think the issue is that there is no mechanism to indicate relationship between human-written abstract target class, and class generated for it. Not sure what could be done about this, but I agree that this is problematic. Let's hope someone comes up with useful improvements, whether these include changes in databind, or possibly even a module for addition AutoValue datatype support.

**Comment by cowtowncoder** [comment]
Not sure how to proceed with this one: would need more concrete suggestion of how to improve handling (and/or available annotations).

This could potentially mean something like:

1. New annotation like `@JsonImplementedBy` (roughly just more semantic version of `@JsonDeserialize(as = SubType)`)
2. Use of existing `@JsonDeserialize(as = ...)` during subtype resolution?

If so, this issue could be re-opened with proposal, or, if preferable, file a new issue with that proposal.
