### ISSUE TITLE
JsonTypeInfo.As.PROPERTY - property is omitted when @JsonTypeInfo annotated object is an element in a collection

### ISSUE THREAD

**Issue by bobby-vandiver** [FasterXML/jackson-databind#1265]
Given an abstract base class that is annotated with `@JsonTypeInfo` and `include = JsonTypeInfo.As.PROPERTY`, the type property specified when serializing an instance of the sub type *is* included in the generated JSON. However, when the same object is included within a collection that is serialized, the type information is *not* included in the generated JSON. 

Is the omission of the type information the expected behavior? This metadata is necessary to properly deserialize the JSON back, so it seems that this is a bug.

This [gist](https://gist.github.com/bobby-vandiver/c0d807d8a89e75a298cd2b19946a94dd) includes test cases that demonstrate the issue. This was written against commit 9d1fb75645b528b988005fab2452cda1b514f617.

One possible workaround to this issue is to use `JsonTypeInfo.As.EXISTING_PROPERTY` and explicitly return the type name information.

This [gist](https://gist.github.com/bobby-vandiver/8f517ff705642ec9651c3ab96c5e2cb6) demonstrates this workaround using the same `Animal` class hierarchy in the previous gist.

In addition to master (or at least commit 9d1fb75645b528b988005fab2452cda1b514f617), I have also observed this behavior in version `2.5.4`.

**Comment by cowtowncoder** [comment]
This is a very VERY common FAQ question, and the root cause if Java Type Erasure, something Jackson can do very little about.
I would strongly recommend against ever serializing `List`s or `Map`s (or generic POJOs for that matter) as root values, as doing that leads to the problem. You would not see the same problem if List was a property value.

What happens is that while you may think value is of type `List<Animal>`, all that runtime JDK sees is `List<?>` (which is about same as `List<Object>`). Since known base type of elements is `Object`, no type information is added. And no, type id determination can not and will not be done based on individual elements; type information is always based on statically available information.

There are work-around for this case, if you absolutely want to serialize `List`s (but which I do not recommend):

1. Create helper type like `class AnimalList extends ArrayList<Animal> { }`, use that (type is now non-generic and type information IS available)
2. Force type for `ObjectWriter`, using `mapper.writerFor(new TypeReference<List<Animal>()  { })`

I hope this helps.
