### ISSUE TITLE
`JsonNode` serialization does not consider default serialization inclusion settings

### ISSUE THREAD

**Issue by jlolling** [FasterXML/jackson-databind#1267]
This code:

``` java
public static void testIgnoreNullValue() throws Exception {
        ObjectNode rootNode = new ObjectNode(JsonNodeFactory.instance);
        rootNode.put("nonEmpty", "value");
        rootNode.set("nullValue", null);
        ObjectMapper m = new ObjectMapper();
        System.out.println(m
                .setSerializationInclusion(Include.NON_NULL)
                .writerWithDefaultPrettyPrinter()
                .writeValueAsString(rootNode));
}
```

creates this result:

``` json
{
  "nonEmpty" : "value",
  "nullValue" : null
}
```

I thought the `Include.NON_NULL` should prevent null values from being serialized.
In the class ObjectNode.serialize() the given SerializerProvider is not used but references the given Include value.

**Comment by cowtowncoder** [comment]
This is one of the complications between POJO / Tree Model (`JsonNode`) where I am not 100% sure how things ought to work; since Tree Model is expected to express JSON content exactly as-is, it could be argued either way whether inclusion criteria should work or not. Or put another way, should it work more like POJOs or `java.util.Map` (handling of which differ quite a bit); typed vs untyped.

But form user perspective I think you are right, this is unexpected.

d

**Comment by jlolling** [comment]
I have created a patch for me. It could be hard if we try to implement all features.
For my customer needs it was important to exclude empty fields and empty arrays.
For this subset my patch works well. I will create a pull request today.

**Comment by cowtowncoder** [comment]
I think the issue of excluding contents of `JsonNode` is valid; and now there is a bigger task:

https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-3

which will go in 3.0 but could perhaps be backported in 2.11.
Either way, I think "Configurability" section there covers this issue, so closing as dup.
