### ISSUE TITLE
Threads getting blocked in Jackson's SerializerCache.

### ISSUE THREAD

**Issue by testark** [FasterXML/jackson-databind#1275]
I would like to gently ask for your attention at http://stackoverflow.com/questions/37978110/threads-getting-blocked-in-jacksons-serializercache. Could you please tell me whether this can be something on Jackson's side?

**Comment by cowtowncoder** [comment]
So, looks like code only invokes "canSerialize()`, and this does not lead to caching of serializer in 2.6; I checked by adding bit of diagnostics. While I do not quite understand how this could lead to congestion, at least code path does get invoked each time, regardless of whether serializer is found.

This was actually fixed for 2.7, since using same test code shows that after first access, serializer is found via non-shared lookup. I would expect avoidance of synchronized access to be helpful regardless of how much actual congestion has effect in 2.6.

Since 2.6 branch is not active any more (nor earlier branches), the way to fix this is to upgrade to 2.7(.5).

**Comment by testark** [comment]
@cowtowncoder thank you so much for looking into this. I understand I need to upgrade, but unfortunately I am locked in the 2.6 branch since Spring Boot 1.3 does not support Jackson 2.7. Isn't threre really anything else I can do besides upgrading?

**Comment by cowtowncoder** [comment]
@testark Not that I know of. 

Have you tested to make sure Spring Boot does not work with 2.7? Build systems usually allow overriding versions to use, unless platform uses something like shade plugin to make private copy.
