### ISSUE TITLE
iso8601 compatibility of 'yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ'

### ISSUE THREAD

**Issue by laoyur** [FasterXML/jackson-databind#1293]
input: 
`2016-07-08T02:55:33.177343+00:00` ( generated by Python `datetime.now()` )

exception:

> com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.util.Date from String value ("2016-07-08T02:55:33.177343+00:00"): not a valid representation (error: Failed to parse Date value '2016-07-08T02:55:33.177343+00:00': Can not parse date "2016-07-08T02:55:33.177343+0000": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null) (at offset 23))
>  at [Source: N/A; line: -1, column: -1] (through reference chain: com.deyims.im.models.Invitation["time"])

**Comment by cowtowncoder** [comment]
Jackson version used?

**Comment by cowtowncoder** [comment]
As to value itself, there seems to be 6 digits for fractional seconds, and this format is not supported, because resolution of `java.util.Date` can not supported anything more granular than milliseconds (that is, 3 digits). To support more granular date/time values, Java 8 date times are needed (or Joda, if supported microsecond resolution).

**Comment by laoyur** [comment]
Thanks for reply.
I'm using Jackson 2.7.0 on Android.
Is it possible to force cast 6-digit to 3-digit when only 3-digit is supported ?
 ( 2016-07-08T02:55:33.**177343**+00:00 --> 2016-07-08T02:55:33.**177**+00:00 )

I known there will be some kind of data losing, but this behavior can save extra code from Python side.
I'm using `datetime.now().replace(microsecond=0).isoformat()` for a workaround now, as you see, sometimes if I forget the `.replace(microsecond=0)` part, Jackson will be unhappy.

**Comment by cowtowncoder** [comment]
@laoyur There are bigger problems here, since support would also require that `SimpleDateFormat` from JDK allowed longer fraction seconds. If you are able to implement support as a simple modification of existing code, we could merge this -- as you say, there is the question of rounding/truncating as well, but I think it seems reasonable to, say, truncate.
