### ISSUE TITLE
Simple string-argument constructor not found if @ConstructorProperties and getter are present

### ISSUE THREAD

**Issue by sgrimm-sg** [FasterXML/jackson-databind#1318]
Upgrading to 2.7.6, I've hit a bug that looks like it was introduced in 2.7.0. It doesn't happen in 2.6.x. Simple wrapper classes for String values used to be deserializable from JSON string values in 2.6, but starting in 2.7 an exception is thrown if there's both a `@ConstructorProperties` annotation on the constructor and a bean-style getter. Example code:

``` java
public class JacksonTest {
  @Test
  public void testConstructor() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    mapper.readValue("\"foobar\"", StringWrapper.class);
  }

  public static class StringWrapper {
    private final String value;

    @java.beans.ConstructorProperties({"value"})
    public StringWrapper(String value) {
      this.value = value;
    }

    public String getValue() {
      return this.value;
    }
  }
}
```

When I run this under 2.7 or higher (tried 2.7.0, 2.7.6, and 2.8.0) I get an error:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of example.JacksonTest$StringWrapper: no String-argument constructor/factory method to deserialize from String value ('foobar')
 at [Source: "foobar"; line: 1, column: 1]
```

Removing either the getter or the annotation on the constructor fixes the problem.

In our actual non-example code, we're using Lombok to generate constructors and getters, so this might be the same as issue #1239. But the problem still occurs when Lombok isn't involved and we're not using any mixins like that issue describes, so I'm filing this as its own issue rather than commenting on that one.

**Comment by sgrimm-sg** [comment]
The short-term workaround if you don't really need the annotation, in case anyone with the same problem is landing here from a search engine, is to tell Lombok not to generate it. This can be done with a single line in the `lombok.config` file:

```
lombok.anyConstructor.suppressConstructorProperties = true
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. The problem here, I think, is a side-effect of 2.7 recognizing `ConstructorProperties` (as part of embedding jdk7 module) AND considering it to imply equivalent of something like:

    @JsonCreator(mode=JsonCreator.Mode.PROPERTIES)

instead of assuming `JsonCreator.Mode.DELEGATING`.
Difference being that "delegating" means that the whole value is to be mapped from one parameter there is; whereas "properties" assumes that all parameters are mapped as properties of the POJO.
So basically annotation is meant to mean that expected structure is

    { "value" : "string" }

This is difficult problem to resolve because of fundamental ambiguity for the case of a single constructor parameter and implicit name -- both interpretations could be legal, and both usages exist.

You could explicitly add

    @JsonCreator(mode=JsonCreator.Mode.DELEGATING)

as a work-around as well.

Now... I am actually not sure if this can be fixed. Unlike with other failures, functionality works as designed (there are other problems with late binding of properties from constructor); it is just fully ambiguous. Furthermore now that 2.7 and 2.8 work certain way, changing behavior would be all but guaranteed to break some existing users use cases.

**Comment by sgrimm-sg** [comment]
Thanks for the detailed response. It seems there is no clearly "correct" behavior here. The `@JsonCreator` annotation should solve the problem for us.

**Comment by cowtowncoder** [comment]
@sgrimm-sg Right; the problem here is that improved heuristics that try to figure out proper choice work wrong way here. Specifically code see name `value` for the sole argument, and also sees indications of such a property (field `value`), and determines that intent is for the parameter to map to logical property.

So I think that it is best to add explicit `@JsonCreator` if that is doable.

**Comment by bfayette** [comment]
with jdk8, I manage to get it work with this :
@AllArgsConstructor(onConstructor=@__({@JsonCreator(mode = JsonCreator.Mode.DELEGATING)}))

**Comment by bric3** [comment]
I got similar error, but this time it is due to the removal of `@ConstructorProperties` in the code. Lombok don't generate those annotations by default to help the migration to Java 9. (`java.beans.ConstructorProperties` belongs to the `java.desktop` module). Adding either 

* a simple `@JsonCreator` on the constructor
* or a annotate the constructor parameter with `@JsonProperty`

did however removed the problem.
