### ISSUE TITLE
Enums not serialized correctly for JsonInclude NON_DEFAULT

### ISSUE THREAD

**Issue by jonpeterson** [FasterXML/jackson-databind#1346]
A user on StackOverflow posted this question:
http://stackoverflow.com/questions/39130401/jackson-included-non-default-not-working-in-2-7-0

After doing some testing of my own, I believe there is a bug in the serialization of enums when marked as `JsonInclude.Include.NON_DEFAULT`.

Spock test case:
```groovy
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.ObjectMapper
import spock.lang.Specification

class NonDefaultEnumTest extends Specification {
    static enum MyEnum { A, B, C }

    static class MyClass {
        String name = 'John'

        @JsonInclude(JsonInclude.Include.NON_DEFAULT)
        MyEnum myEnum = MyEnum.B
    }

    def 'serialize some MyClasses'() {
        given:
        def mapper = new ObjectMapper()

        expect:
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.A)) == '{"name":"John","myEnum":"A"}'
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.B)) == '{"name":"John"}'
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.C)) == '{"name":"John","myEnum":"C"}'
    }
}
```

Test passes on Jackson 2.3.0 and 2.6.7.  Fails (at the `MyEnum.B` expectation) on 2.7.0-rc1, 2.7.0, 2.7.6, 2.8.1.

**Comment by cowtowncoder** [comment]
No I think this actually works as specified for behavior of `NON_DEFAULT`, for 2.7 and beyond.
Unfortunately there was a small but significant change between 2.6 (related to changes to handling of `NON_EMPTY`) so that behavior for this case did change. Expected 2.7+ behavior is included in Javadocs for `@JsonInclude`.

Basically `NON_DEFAULT` means different things when applied to class (POJO that contains property) and property itself:

1. When applied to POJO, value to exclude is the value of property in POJO instance constructed using default constructor. In above case, that would be `MyEnum.B`
2. When applied to property, value to exclude is the default value of that type: for `int`, for example, that would be `0`. Value for surrounding POJO is NOT considered.

In above case, then, annotation should be added to `MyClass`; and if any of properties requires alternative defaulting, per-property override may be used (to change it to, say, `Include.ALWAYS`).

Change itself was necessary to support hierarchic overrides for all defaulting. It is unfortunate that behavior had to change, but this is the definition that is and will be used going forward.

**Comment by jonpeterson** [comment]
Verified that your suggestion works.

```groovy
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.ObjectMapper
import spock.lang.Specification

class NonDefaultEnumTest extends Specification {
    static enum MyEnum { A, B, C }

    @JsonInclude(JsonInclude.Include.NON_DEFAULT)
    static class MyClass {

        @JsonInclude(JsonInclude.Include.ALWAYS)
        String name = 'John'

        MyEnum myEnum = MyEnum.B
    }

    def 'serialize some MyClasses'() {
        given:
        def mapper = new ObjectMapper()

        expect:
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.A)) == '{"name":"John","myEnum":"A"}'
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.B)) == '{"name":"John"}'
        mapper.writeValueAsString(new MyClass(myEnum: MyEnum.C)) == '{"name":"John","myEnum":"C"}'
    }
}
```
