### ISSUE TITLE
ObjectMapper.setSerializationInclusion() Javadoc is wrong

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1348]
The Javadoc for ObjectMapper.setSerializationInclusion() states that it is equivalent to calling:

`setPropertyInclusion(JsonInclude.Value.construct(incl, Include.ALWAYS));`

but if you look at the implementation, the second argument is actually Include.USE_DEFAULTS which is not the same thing.

**Comment by cowtowncoder** [comment]
@cowwoc As far as I see it is actually same thing, functionally, since the ultimate implicit default is still `ALWAYS`. `USE_DEFAULTS` is different for intermediate values, meaning it's "not defined" and lets base defaults to be seen through; but at very lowest level (`ObjectMapper` defaults) there is nothing more to let through.

I am open to verbiage improvements of course, not saying existing javadoc is optimal. Just that I don't think it is factually incorrect.

**Comment by cowwoc** [comment]
That's fine. You can close this issue. One (related) problem I noticed is that the Javadoc for `@JsonInclude` doesn't specify the default behavior/value if the annotation is missing. I believe you specify the value for `@JsonInclude(content)` but not for the `value` or annotation as a whole. Having dug into the source-code, I believe the default is `ALWAYS` but I wish this was explicitly spelled out.

**Comment by cowtowncoder** [comment]
I fully agree in that javadocs should clearly state the defaulting. Would be happy to merge PR, or make changes if you have specific ones to point to. Otherwise will try to keep this in mind and make changes as I work on code.

**Comment by cowwoc** [comment]
https://github.com/FasterXML/jackson-annotations/pull/99 resolves this issue to my satisfaction.
