### ISSUE TITLE
Discriminator property doesn't render inside a Generic conaiter

### ISSUE THREAD

**Issue by loniszczuk** [FasterXML/jackson-databind#1349]
When a List<Foo> is rendered as json and Foo is a class with some subclasses, the property used by json to identify the subclass type is not rendered. 

I'm using jackson 2.8.1.

```java
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;

public class Test {

	@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "subtype", visible = true)
	@JsonSubTypes({
			@JsonSubTypes.Type(value = A.class, name = "A"),
			@JsonSubTypes.Type(value = B.class, name = "B"),
			@JsonSubTypes.Type(value = C.class, name = "C"),
	})
	public static class A {
		public String id;
	}

	public static class B extends A {
		public String name;
	}

	public static class C extends A {
		public String label;
	}

	@org.junit.Test
	public void test() throws JsonProcessingException {
		B b = new B();
		b.id = "id-b";
		b.name = "this is b";

		C c = new C();
		c.id = "id-c";
		c.label = "this is c";

		List<A> list = new ArrayList<>();
		list.add(b);
		list.add(c);

		List<Map<String, Object>> jsonlist = new ObjectMapper().convertValue(list, new TypeReference<List<Map<String, Object>>>() {});

		Map<String, Object> bMap = jsonlist.get(0);
		assertEquals("id-b", bMap.get("id"));
		assertEquals("this is b", bMap.get("name"));
		assertEquals("B", bMap.get("subtype")); // This line fails, the actual value is null

		Map<String, Object> cMap = jsonlist.get(1);
		assertEquals("id-c", cMap.get("id"));
		assertEquals("this is c", cMap.get("label"));
		assertEquals("C", cMap.get("subtype")); // This line fails, the actual value is null
	}
}
```

**Comment by cowtowncoder** [comment]
I think this would belong to an FAQ if we had one: the problem is that you are not passing enough type information for polymorphic type handling to work as you expect.
The problem is that when serializing (or in this case, using `convertValue()`), you can not just pass a `List` instance: Java type erasure will not pass generic type, and type is only seen as `List<?>`, that is, elements are only known to be `java.lang.Object`s. And since `Object` does not have `JsonTypeInfo`, no inclusion occurs. This is by design, as the declared type of elements is used to have deserializer use same definition as serializer.

I would strongly recommend not using generic type for root value, but either use a wrapper POJO that contains real type; something like

```
public class ListAWrapper {
   public List<A> values;
}
```

in which case handling does work (since class definition of `ListAWrapper` has real type information).

But there are other alternatives as well;

* Define helper sub-class: `public class AList extends ArrayList<A> { }` and use that: resulting type is not generic and does proper generic type binding to use
* Pass actual type via `ObjectWriter`: `String json = mapper.writer(new TypeReference<List<A>>() { }).writeValueAsString(list)`
