### ISSUE TITLE
Valid Json followed by some characters(Invalid) parsed without an exception by jackson

### ISSUE THREAD

**Issue by kum-rah** [FasterXML/jackson-databind#1360]
Jackson version-2.8.1
Code: 

```java
           String str="{\"sdf\":\"fsdaf\"}fsafaffgffgf";
	   ObjectMapper mapper=new ObjectMapper();
	   JsonFactory factory= new JsonFactory();
	   try{
           JsonParser parser=factory.createParser(str);
	   JsonNode node=mapper.readTree(parser);
	   System.out.println(str);
	   System.out.println(node);
	   System.out.println("ok");
	   
	   }
	   catch(JsonProcessingException e1)
	   {
		   e1.printStackTrace();
	   }
	   catch(IOException e2)
	   {
		   e2.printStackTrace();
	   }
```

Output:

```
{"sdf":"fsdaf"}fsafaffgffgf
{"sdf":"fsdaf"}
ok
```

In the above piece of code, str is an invalid Json(due to the presence of text after valid Json). But JsonParser is ignoring the text after '}' and reading it into the JsonNode without any exception.
Is there any workaround available, as I need such strings to be declared invalid?

**Comment by cowtowncoder** [comment]
@kum-rah yes, call `parser.nextToken()` and verify it returns `null` -- if there is invalid (non-decodable) content, an exception is thrown (like in your case). And if there is decodeable content (say, token like `true` or `123`), you get a `JsonToken`.

Parser itself does allow sequences of white space separated tokens, to support a common use case of value sequences, where individual values (often JSON Objects, but possibly numbers too) are separated by linefeeds. Because of this, decoding is only attempted when needed.

I think there is a feature request for something like `DeserializationFeature.REQUIRE_SINGLE_DOCUMENT` (or whatever) that would do such a check automatically, as this lack of automatic verification is considered wrong or at least sub-optimal by some users.
