### ISSUE TITLE
Improve `@JsonCreator` detection via `AnnotationIntrospector` by passing `MappingConfig`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1369]
Due to hassle with `@CreatorProperties` annotation, and possible solution via new `MapperFeature`, it seems useful/necessary to change usage of `hasCreatorAnnotation()` so that a new method is added to replace it; and that new method takes `MapperConfig` to allow for configuration setting(s).
It may also make sense to combine handling of `findCreatorBinding()` at same time: maybe replace 2 existing methods with one new one.

For backwards compatibility it will be necessary to keep old methods but make deprecated; but also possible add some routing of old calls for 2.9.

Currently only other modules likely to be affected would be:

* Scala module probably uses/overrides methods
* Kotlin module is quite likely to, as well.

so testing and collaboration would be needed to reduce likelihood of issues.

/cc @nbauernfeind @apatrida

**Comment by cowtowncoder** [comment]
Forgot to make the goal explicit: allow disabling of use of `@CreatorProperties` as implying `@JsonCreator`. With 2.8, the only way to do that is to (re)configure `JacksonAnnotationIntrospector`; for 2.9 would be nicer to allow `MapperFeature`s.

**Comment by apatrida** [comment]
Kotlin module overrides `hasCreatorAnnotation` and implies one if none is explicitly specified by the user (as constructor, as static, or as companion object method), when safe to do so.  The only other method overridden in `AnnotationInspector` is `findImplicitPropertyName`

Rest of the logic is in a `ValueInstantiator`.

**Comment by apatrida** [comment]
Technically we can best fit known parameters coming from the JSON to the available methods and choose from a list of creator methods and therefore work with multiples instead of only 1 creator method.  In my Klutter library you can instantiate an object from a data provider (map, jackson tree, etc) and let it pick the constructor or factory that is best fit (most parameters handled in constructor, fewest set after using setters, no conflicts with readonly properties, fewest data type conversions, fewest uses of default values in constructors, nullability compatibility, etc) or you can pass a reference to the creator at the time of construction or pass a lambda that can decide on the fly by looking at the data to bind.

would be nice if this flexibility made it towards Jackson.

**Comment by cowtowncoder** [comment]
@apatrida I do also have "rewrite property introspection handling, especially wrt JsonCreator detection" on my plate. Here the goal would be bit more modest; make introspection of intent bit more configurable.
It would not change handling of detection signals (like how to choose from more than one possibility); nor change auto-detection. But it would allow immediate resolution of some problems with Auto-values, Immutables and Lombok.

So you can think of this as somewhat orthogonal to the question of adding true flexibility, or support for alternate/adaptive creators.
