### ISSUE TITLE
Expose the Map in ObjectNode directly

### ISSUE THREAD

**Issue by billccn** [FasterXML/jackson-databind#1400]
The `ObjectNode` is effectively a wrapper for a `Map` and there are awkward methods like `Iterator<Map.Entry<String, JsonNode>> fields()` which stops short of exposing the actual `Map`.

I am wondering what is the reason not to expose it?

**Comment by cowtowncoder** [comment]
Good question for `jackson-users` or `jackson-dev` lists.

The main reason is to prevent exposing of implementation details, and to allow (for example) modification contents by doing things like adding `null` entries (all values must be non-null `JsonNode`s). There are 2 schools of thoughts here regarding whether tree nodes that look like `Map`s should actually be `Map`s (or at least exposed as such): I think they should not since if you do want to deal with `Map`s and `List`s, Jackson has all the tools for you to do that. Tree Model is a separate abstraction with its own logical model and access, and this extends beyond what `Map`s (and `List`s for JSON arrays) offer.

Follow-up discussion (and to get other views if you are interested; above is my personal take) please use mailing lists.
