### ISSUE TITLE
DateTimeFormatter 

### ISSUE THREAD

**Issue by mohanr** [FasterXML/jackson-databind#1409]
Does java.time.format.DateTimeFormatter belong in ObjectMapper ? Since SimpleDateFormat isn't thread-safe we couldn't set it when in Spring the annotation is @Bean

**Comment by cowtowncoder** [comment]
Excellent question for the mailing lists.

**Comment by mohanr** [comment]
Is java.time.format.DateTimeFormatter a better alternative to synchronization of 'DataFormat' in the source code ? That was supposed to be the question.

**Comment by cowtowncoder** [comment]
@mohanr As I said this is not a question/answer kind of forum. It is for reporting bugs, or suggesting RFEs. I am not sure why you are worried about synchronization; suffice it to say that as far as I know synchronization is implementing as necessary within Jackson. If you think otherwise, show a unit test, or point out exact specific usage and why that should be problematic.
And yes, I am aware that `SimpleDateFormat` itself is not thread-safe. Code does not assume it was.

As to `DateTimeFormatter`, that's in Java 8 and Jackson only requires Java 6 as runtime; we can not use JDK 8 classes so it is not a replacement.
But there is extension module, https://github.com/FasterXML/jackson-datatype-jdk8 that does provide support for all Java 8 date/time types, for users, if you would like to use those types instead.
