### ISSUE TITLE
Creating CollectionType for non generic collection class broken

### ISSUE THREAD

**Issue by Spikhalskiy** [FasterXML/jackson-databind#1415]
Creation of CollectionType is broken for classes that don't have generic type parameters since version 2.7.0

Test:

```
    class MyList implements List<Long> {...}
    public void testCollectionTypeWithoutGeneric()
    {
        TypeFactory tf = TypeFactory.defaultInstance();

        JavaType t = tf.constructCollectionType(MyList.class, Long.class);

        assertEquals(CollectionType.class, t.getClass());
        assertSame(Long.class, t.getContentType().getRawClass());
    }
```

So, `MyList` is a collection type with `Long`  as an item type.
Test passes for jackson-databind versions 2.5.x and 2.6.x
For jackson-databind versions 2.7.x and 2.8.x and current master test is broken and throws

```
java.lang.IllegalArgumentException: Can not create TypeBindings for class com.fasterxml.jackson.databind.type.TestTypeFactory$MyList with 1 type parameter: class expects 0

    at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:125)
    at com.fasterxml.jackson.databind.type.TypeFactory.constructCollectionType(TypeFactory.java:716)
    at com.fasterxml.jackson.databind.type.TypeFactory.constructCollectionType(TypeFactory.java:702)
    at com.fasterxml.jackson.databind.type.TestTypeFactory.testCollectionTypeWithoutGeneric(TestTypeFactory.java:565)
```

You can find ready to merge test case here: https://github.com/Spikhalskiy/jackson-databind/commit/56b018d96e706183dc66b6424f90722b923abd09

**Comment by cowtowncoder** [comment]
So the problem with

    JavaType t = tf.constructCollectionType(MyList.class, Long.class);

is that type `MyList` does not take any type parameters, and call should really be made to `tf.constructType(MyList.class)` in this case.

However, it would be good if this method (and related Map construction) would work by trying to verify assignments match. I don't know how well this can work in general with things like aliasing, but seems like we should at least support simple case like here.

**Comment by Spikhalskiy** [comment]
@cowtowncoder Yes, we can create is as a ```constructType(MyList.class)``` as any non-collection class and get ordinal ```JavaType```, but there is willing to get ```CollectionType```, that's why constructCollectionType used.

**Comment by cowtowncoder** [comment]
@Spikhalskiy there is no benefit from trying to use `constructCollectionType` here since type is not generic -- this may be a documentation issue in that sense. I understand that naming might suggest that just usage would be preferable but it is not, at least with 2.7 and above where type resolution works reliably.

But I am open to trying to improve this so that while such usage is not intended, it would work; it should be possible to make that happen.

**Comment by rfoltyns** [comment]
I've made a stab on it - have a look at [this commit](https://github.com/rfoltyns/jackson-databind/commit/6340f1cd5aa8af9e213fb872efe44739a975898c), please.

But, since `constructCollectionType` is not used during deserialization of `MyList` - `constructType` is - this fix might create more issues than value. Plus, fast path in `TypeBindings.create` will be omitted.

**Comment by cowtowncoder** [comment]
@rfoltyns Thank you -- I'll have to think this through. This is tricky all in all, because these methods really are troublesome in couple of ways; most importantly since there are 2 different things for which one might want to pass parameters:

1. For specific raw class being passed (but if so, could/should just use general-purpose method)
2. Parameterization of `Collection` / `Map`, which is hidden possibly deep within type stack, different from (1)

and patch would address (1); whereas API suggests (2) (since it requires exactly 1 (Collection) or 2 (Map) parameters).

**Comment by mluisbrown** [comment]
Just to add that this issue affects *any* generic class, not just collection classes:

If you have:
```
public class SpecialFoo extends Foo<Bar> {
    public SpecialFoo() {
        super();
    }
}
```
then:
```
objectMapper.getTypeFactory()
    .constructParameterizedType(SpecialFoo.class, Foo.class, Bar.class);
```

Will fail with:
```
java.lang.IllegalArgumentException: Can not create TypeBindings for class com.fasterxml.jackson.databind.type.TypeFactory$SpecialFoo with 1 type parameter: class expects 0
```

Is this going to be fixed in 2.9?

**Comment by rfoltyns** [comment]
Well, in this case similar patch can be applied, but the result wouldn't be any different than the one from `constructType(Class)` - SimpleType with no bindings at all, since SpecialFoo is not parametrized.

@cowtowncoder do you think it would be a viable solution?

On the other hand, `constructPara*` API could be completely removed as it's deprecated and no longer used since 2.7.

**Comment by cowtowncoder** [comment]
@mluisbrown No, that method should have been marked as deprecated for 2.8 (and will be for 2.9).
As pointed by @rfoltyns you can and should just use `constructType()` as there are no type parameters to bind, in this particular.

The original intent for this method, when added, was to try to allow for specifying exact type bindings for one of super types (generally `Collection` or `Map`), but construct a subtype.
Unfortunately it turns out that this can not be reliably implemented within context of `TypeFactory`. Worse, the original need for this usage was mostly removed with 2.7 when type resolution was rewritten to properly deal with type aliasing.

Because of these reasons, this variant was deprecated. New method, `constructParametricType()`, without secondary type parameter, was added to be used going forward. This method (well, there are 2) will NOT be deprecated and is intended to be used (@rfoltyns while `constructParametrizeType()` is to be deprecated, `constructParametricType()` is not: it does do simple binding to indicated type).
This method will directly bind variables of indicate main Class/JavaType.

For other use cases where binding is needed at lower level, it is possible to use combination of methods, like:

```java
JavaType t = typeFactory.constructType(Collection.class, String.class);
JavaType arrayStringList = typeFactory.constructSpecializedType(t, ArrayList.class);
```

**Comment by mluisbrown** [comment]
Thanks @cowtowncoder. Using `constructType()` has solved my problem.

**Comment by cowtowncoder** [comment]
@rfoltyns I think something along these lines would make sense. Main concern I have is whether this could hide some usage problems (user passing different type variable assignments, expecting type to be changed -- even in case where it is illegal). But... maybe that's ok?

**Comment by cowtowncoder** [comment]
@mluisbrown Ok good. Apologies for the mess of an API here. It's not good; it's just... historical reasons for existence of that (now) unnecessary method. Thank you for pointing it out; at least I can now mark these as properly deprecated.

And maybe @rfoltyns' patch could also be applied in case you included, since it is semantically similar.

**Comment by cowtowncoder** [comment]
@rfoltyns Ok, thinking bit more about this, I think I know what might be good enough solution, and cover all cases.

So, backtracking a bit, I think `createCollectionType()` and `createMapType()` could be seen as convenience methods for (now-)deprecated `createParametrizedType()` as follows:

```java
    // createMapType
    constructParameterizedType(subType, Map.class, keyType, valueType);
    // createCollectionType
    constructParameterizedType(subType, Collection.class, elementType);
```

and so similar approach should work.

There are 2 possible valid cases, I think, that we could support relatively easily:

1. Case where `subType` is non-generic
2. Case where `subType` has same parameter assignments as target type (Map / Collection / x)

Finding out whether `subType` has one of those is easy enough (forgetting for now possibility of incompatible type bounds), but there is one concern: given types SHOULD be bound to target type -- if not, I think exception should be thrown.

Your patch I think actually covers things up until this point (except for validating that parameter count matches target type?), but I think we may be able to add simple validation here as well: after constructing resulting `JavaType`, find actual type assignments for target type:

```java
JavaType sub = ....
JavaType[] params = findTypeParameters(sub, targetType);
```

and verify that they match arguments method was given; if `Class`es given, verify that raw classes are same, if `JavaType`, use `equals` check.

Does this make sense? I don't know if I explained this well, but I think I can see how this could work well enough, reliably, and support common use cases.

**Comment by cowtowncoder** [comment]
I went ahead and fixed this as suggested by @rfoltyns -- thank you everyone for your help!
The only addition beyond this is that I did add a verification to ensure bound parameters match, which to me makes sense.

**Comment by rfoltyns** [comment]
@cowtowncoder glad to help. 

You were right on parametrized vs parametric deprecation - I went too far with the assumptions based on actual usage of `createParametricType` only inside `createParametrizedType` which was noted as deprecated.

**Comment by cowtowncoder** [comment]
@rfoltyns Glad we improved handling here. In ideal world we'd probably only really have `constructType()` and not many esoteric alternatives; but those are due to pre-2.7 ideas of differences between types. With current type resolution there would be much less need.
