### ISSUE TITLE
Serializing root-level `Optional.empty()` with `Include.NON_ABSENT` set produces null

### ISSUE THREAD

**Issue by markelliot** [FasterXML/jackson-databind#1418]
Jackson 2.6.5

```
ObjectMapper mapper = new ObjectMapper()
        .registerModule(new Jdk8Module())
        .setSerializationInclusion(JsonInclude.Include.NON_ABSENT);
System.out.println("Value: " + mapper.writeValueAsString(Optional.empty()));
```

Produces:

```
Value: null
```

Whereas:

```
public class Foo {
    public Optional<String> getBar() {
        return Optional.empty();
    }
}

ObjectMapper mapper = new ObjectMapper()
        .registerModule(new Jdk8Module())
        .setSerializationInclusion(JsonInclude.Include.NON_ABSENT);
System.out.println("Value: " + mapper.writeValueAsString(new Foo()));
```

Produces:

```
Value: {}
```

It seems like the first option ought to emit the empty string, rather than null.

A cursory search of GitHub issues reveals some minor discussion of this behavior related to maps, but I can't find a definitive answer on expected behavior, and I'd claim the present behavior is incorrect.

**Comment by cowtowncoder** [comment]
Jackson 2.6.x is not supported any more and there are many, many fixes in later versions.
So it would be helpful to verify this against either 2.7.8 or 2.8.4.

**Comment by markelliot** [comment]
The behavior is identical in 2.8.4.

**Comment by cowtowncoder** [comment]
Ok. Second behavior (in POJO) is correct.

I also think first behavior makes sense, for couple of reasons:

1. At root level it is not possible to exclude output (a value is expected) -- exclusion is handled by containing type (POJO or Map).
2. Given that a placeholder is needed, `null` seems like the only choice in general
3. There is no generic type available due to Type Erasure; value is of type `Optional<?>` (there is a way to pass full type too, however).

So I think this works as designed.
