### ISSUE TITLE
JavaType isContainerType not extensible

### ISSUE THREAD

**Issue by emmanueltouzery** [FasterXML/jackson-databind#1430]
Several jackson features or extensions make use of the `JavaType.isContainerType()` information (see example at the bottom). 

The problem is that the determination whether a given type is a container type is hardcoded within `jackson-databind`. For a type to be a container type, if I understood right, the type [must implement `java.util.Collection`](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1322) or [must be an Array](https://github.com/FasterXML/jackson-databind/blob/e59194aaff0a6e520184138924c69045160ee9d9/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1233).

Unfortunately none of these conditions apply for list types inside the [javaslang](http://www.javaslang.io/) library. Because javaslang's collections are immutable, it was a conscious decision not to implement `java.util.Collection`, which dictates a mutable API. That means `jackson-databind` doesn't consider this list type a container and [some jackson features don't work](https://github.com/javaslang/javaslang-jackson/issues/82).
Note that Javaslang list [does implement `java.lang.Iterable`](http://static.javadoc.io/io.javaslang/javaslang/2.0.4/javaslang/collection/List.html), though.

I see three possible solutions to this issue:

1. make it possible for jackson modules to influence the decision whether a `JavaType` is a container type;
2. add other criteria besides being an array or implementing `java.util.Collection` to determine whether a `JavaType` is a container (maybe implementing `Iterable`?)
3. not requiring `isContainerType` for some features.

But of course you know better, it's just from the top of my head.

----------

Example of feature making use of `JavaType.isContainerType()`: `jackson-dataformat-xml` offers a feature to wrap collection items, so that instead of

```xml
<item>5</item>
<item>6</item>
```

we can serialize to:

```xml
<items>
  <item>5</item>
  <item>6</item>
</items>
```

However to enable the feature, `jackson-dataformat-xml` checks that the `JavaType` is indeed a container type (see [1](https://github.com/FasterXML/jackson-dataformat-xml/blob/jackson-dataformat-xml-2.6.5/src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlBeanSerializerModifier.java#L54), [2](https://github.com/FasterXML/jackson-dataformat-xml/blob/jackson-dataformat-xml-2.6.5/src/main/java/com/fasterxml/jackson/dataformat/xml/util/TypeUtil.java#L16)).

**Comment by cowtowncoder** [comment]
@emmanueltouzery The choice to keep `CollectionType` strictly for `java.util.Collection` (and `MapType` for `java.util.Map`) and subtypes is intentional, to ensure assignment compatibility and simplify handling by standard (de)serializers.
For things like act like Collections/Maps, you should use `CollectionLikeType` and `MapLikeType`: this is done, for example, to support Scala's native collection/map types.

With that, the expectation is indeed that modules participate in type refinement by adding `TypeModifier` that can upgrade a `SimpleType` into `CollectionLikeType` or `MapLikeType`, and make `jackson-databind` add much more support for handling.
(same is true for `ReferenceType`, used for things like Optionals).

One example that might be useful would be in `jackson-datatypes-collections` repo, file `guava/src/main/java/com/fasterxml/jackson/datatype/guava/GuavaTypeModifier.java`, which makes Guava `MultiMap` type to be `MapLikeType`

Now... various checks should also consider collection-/map-like types, and if not, that may be something that needs to be improved.
XML module is a particularly tricky thing to support for various reasons so there may be rough edges.

Anwyay, I hope this helps in getting to right wrt type system.

**Comment by emmanueltouzery** [comment]
Thank you very much for this crystal-clear detailled answer! Much appreciated! And very helpful. We now fixed the jaxb annotations integration, pure jackson annotations still pending, but we're optimistic!

Thank you again!

**Comment by cowtowncoder** [comment]
@emmanueltouzery excellent! Glad it made sense; this is not necessarily an easy area to understand, things can get quite complicated. But fortunately use case has been encountered before and is supported.
