### ISSUE TITLE
Regression bug on json deserialisation since 2.7.x or 2.8.x (not in 2.6.x) when using some generic in yours objects

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1449]
(filed originally by @alexandrenavarro at https://github.com/FasterXML/jackson-core/issues/331)

-----

Regression bug on json deserialisation since 2.7.x or 2.8.x (not in 2.6.x) when using some generic in yours objects.

A com.fasterxml.jackson.databind.JsonMappingException is thrown with incorrect mappings.
I tried to understant why but I didn't succeed.

I give you a sample with a unit test which works in 2.6.7 but not in 2.8.4 (not in any version >= 2.7.0) .
Don't hesitate to contact me if it is not clear.

[jackson-bug-generic-sample.zip](https://github.com/FasterXML/jackson-core/files/584080/jackson-bug-generic-sample.zip)

**Comment by cowtowncoder** [comment]
Hmmh. Yes, quite complicated. Based on error message, I was expecting it to be due to use of `defaultImpl` being incompatible (something earlier versions did not catch), but this does not seem to be the case.

**Comment by alexandrenavarro** [comment]
When I investigated the problem, first the cladd OProduct in the sample have a defaultImpl does not match the subclass.. I removed it and set all the subtypes and it fixes some problems but not all (notably the one I show un the simple).
It seems to have a link with this problem. https://github.com/FasterXML/jackson-databind/issues/1443 but not exactly the same. The mapping between the property and class to deserialize is not correct but I don't really understand why. Tell me if I can help you to solve the issue by explaining something in the sample.

**Comment by cowtowncoder** [comment]
Ok. So `defaultImpl` is a known problem. There are some complications there, and possible room for improvement, but fundamentally difference is up-front failure instead of possible later one.
I don't know if #1443 was related, possibly not. I think challenge with repro is just sheer size of the code, so one thing could be to try to make it smaller if at all possible.

**Comment by alexandrenavarro** [comment]
Hi,

I try to simplify at the maximum a sample with the problem (but continue to have a lot of classes).

You can clone a sample from https://github.com/alexandrenavarro/jackson-bug-generic-sample

The test ORequestWrapperTest.testORequestGenericWrapper works in 2.6.8 but not in 2.8.x or 2.7.x.

The test try to serialize 
ORequestGenericWrapper with contains just a field ORequest<? extends ORequestLeg> request

Another test ORequestWrapperTest.testORequestObjectWrapper works correctly.
This test tries ORequestObjectWrapper with contains just a field ORequest request without Generic
with exacty the same request.

The definition of ORequest is
`public abstract class ORequest<T extends ORequestLeg> `

with 2 subsclasses
OType1Request
OType2Request

The definition is OType1Request I want to serialize is
`public class OType1Request<P extends OProduct> extends ORequest<OType1Leg<P>> `

After investigating a lit bit, the problem seems to come with generic parameter of OProduct because it is present in the implementation OType1Request but not the ORequest<? extends ORequestLeg> request in the ORequestGenericWrapper I want to serialize. After I don't understand why in jackson it is a problem to have that.

I modified my code in new branch https://github.com/alexandrenavarro/jackson-bug-generic-sample/tree/FIX-GENERIC-MODEL to force to have OProduct in what I want to serialize

The definition of ORequest is now

`public abstract class ORequest<P extends OProduct, L extends ORequestLeg<P>> `
instead of 
`public abstract class ORequest<T extends ORequestLeg> `

and with this kind of code, it works in 2.8.x jackson.

So to fix my problem, I transformed my code as in the sample in the new branch.
It is not blocking anymore for me, so if you want to close, don't hesitate, but it seems to have some weird cases with generic where jackson 2.7/2.8 can serialize some generic object where 2.6 can do it.

Don't hesitate if you want more help from me to fix it in jackson.

**Comment by cowtowncoder** [comment]
@AlejandroRivera thank you for helping with this; I appreciate having test code. I hope to find time to dig deeper with this in future, but right now I don't really know what would be going on as the type hierarchy is bit complicated. I am glad you have a work-around for time being.

**Comment by AlejandroRivera** [comment]
@cowtowncoder I think you meant to tag @alexandrenavarro instead of me, right?

**Comment by cowtowncoder** [comment]
@AlejandroRivera Indeed. Dang auto-completion. :)

**Comment by cowtowncoder** [comment]
Unfortunately at this point I don't have much to go on with this; closing.
