### ISSUE TITLE
wrong json property name for field zIndex

### ISSUE THREAD

**Issue by cfinckler** [FasterXML/jackson-databind#1455]
Hello,
I have a java object with a field called zIndex and a getter called getZIndex()
When I serialize it with jackson, the following json is generated:
{
  zindex: 0
}
The name of the field should be zIndex with big I.

I solved it with the JsonProperty-Annotation.

But I think, the default serialization is generating a wrong field name.

With debugging, I tracked it to the method BeanUtil.stdManglePropertyName('getZIndex', 3).
This method lowercases all letters after the "get" till the first lowercase letter comes instead of lowesercasing only the first.
Then in the corresponding propertyMap, two entries exists, one with 'zindex' from the getter and one with 'zIndex' from the field. Later in the code the property for the method is taken.

So my, expectation is, that BeanUtil.stdManglePropertyName('getZIndex', 3) should return 'zIndex' instead of 'zindex'

**Comment by cowtowncoder** [comment]
@cfinckler Annotation is the right way here, since `getZIndex()` would never result in name like `zIndex` otherwise -- I am not aware of name-mangling rules that would result in such capitalization; neither standard Bean name mangling nor minor variation Jackson uses by default.
There is `MapperFeature.USE_STD_BEAN_NAMING` that would actually choose one of other choices ("standard" bean naming would give "ZIndex", I think, and alternative "zindex").

Since JSON format is case-sensitive (as well as Java), field `zIndex` is not assumed to be associated with logical property "zindex" either; and if field was public that would actually be serialized separately and you would have 2 JSON properties.

There is also possibility of specifying custom `PropertyNamingStrategy` that would allow different translations but unless you have tons of similarly named properties it may not be worth the effort.

**Comment by cfinckler** [comment]
Hello, thank you for your response.
I realized, that using the JsonProperty also does not work as expected, because the filed then gets rendered twice into the jsonstring:
{
zindex: 0,
zIndex: 0
}

I have now used the workaround to rename the java-field to zindex. 

For me, it still looks like the method  BeanUtil.stdManglePropertyName should only lowercase the first letter after the "get" instead of all.

**Comment by cowtowncoder** [comment]
@cfinckler No, that's not how name mangling works. Currently there are 2 options by Jackson (depending on `MapperFeature.USE_STD_BEAN_NAMING`):

1. All leading capitalized letters are lower-case (default Jackson setting): so `getZIndex` becomes `zindex`
2. Only the first capital letter is lower-cased; and that only if there aren't other capital letters: so `getZIndex` becomes `ZINdex`

Of these, (2) is what Java Bean specification defines.

If you want some other logic, you will need to implement `PropertyNamingStrategy`: there are many potential variations for name-mangling and ideally anything other than Bean naming (option (2)) should be custom setting.

**Comment by ducquoc** [comment]
Hi all, I also met a similar issue to this problem. I tried `@JsonProperty` but it would produce more properties than expected. 

Then I tried using "lowerCase" Getter Setter , and it works ! 

Therefore, I would recommend using "custom" getter in such case:
```
    public Integer getzIndex() {
        return this.zIndex;
    }

    public void setzIndex(Integer zIndex) {
        this.zIndex = zIndex;
    }
```

I leave the comment here as an optional work-around for people later come into this thread :) .
