### ISSUE TITLE
Deserialization fails when fields have the same name as constructor parameters

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1459]
Jackson 2.8.0, with jackson-module-parameter-names module

Preface: This bug was extremely difficult to track down because the resulting error message is misleading and one has to dig very deep into the code to figure out what is wrong. Please prioritize a fix accordingly :)

Users see `com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of PostsEntity out of START_ARRAY token
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@775c2028; line: 1, column: 1]` which is misleading because there is nothing wrong with their code.

Workaround: Rename the constructor parameter so it differs from the class field (but it isn't obvious to end-users that they need to do this).

Problem description
-----------------------

Given:

```
public final class PostsEntity {
    public final List<URI> value;

    @JsonCreator
    public PostsEntity(List<URI> posts) {
        this.value = posts;
    }
}
```

If I attempt to deserialize this class from an array of URIs, it works. However, if I rename the constructor argument from `posts` to `value` (so it has the same name as the public field) then I see the following behavior:

BasicDeserializerFactory:410 invokes `boolean useProps = _checkIfCreatorPropertyBased(intr, ctor, argDef);`

When the names differ, `useProps` returns `false`. When they are the same, `useProps` returns `true`. 

If the names are the same, the two "properties" are merged into one (meaning, `BasicBeanDescription._properties` contains a single property having the name "value" that has both a field and a constructor associated with it). If the names differ, `BasicBeanDescription._properties` contains two separate entries: one for the field and another for the constructor argument.

The reason that `useProps` is being set to `true` is that `BasicDeserializerFactory._checkIfCreatorPropertyBased` invokes `propDef.couldSerialize()` which returns `true` for the merged properties and `false` for the separate properties.

If `useProps` is set to true, `CreatorCollector.arrayDelegateType` gets set to `null` which means that `PostsEntity` cannot be deserializes from an array.

**Comment by cowtowncoder** [comment]
Please do not report things against old patch versions: literally dozens of fixes have been applied up to 2.8.5.
So the very first I'd ask is to verify this with 2.8.5 before even reading the description.

**Comment by cowwoc** [comment]
Apologies. I had not realized that 2.8.0 was no longer the latest version. I will retest with 2.8.5.

**Comment by cowwoc** [comment]
Confirmed. This bug is reproducible in 2.8.5.

**Comment by cowtowncoder** [comment]
Ok thank you for verifying this & reporting it of course too.
I hope to have a look soon.

**Comment by cowwoc** [comment]
@cowtowncoder Much obliged.

PS: I feel bad for not providing self-contained testcase but quite often I run into these bugs in a commercial project which I cannot share and would be very time-consuming to break down.

It might be useful to publish a sample Maven project that users could fork, inject their bug-specific code, and send to you as a minimal testcase. Not sure if this is feasible but, if it is, both sides would benefit.

**Comment by cowtowncoder** [comment]
@cowwoc Ok. So this is why `@JsonCreator(mode=JsonCreatore.Mode.xxx)` was added. This use case is unfortunately fundamentally ambiguous, as both delegating and properties variant could potentially apply, if (and only if) property name is available. Behavior of verifying whether there are other accessors (that is, is there a field or getter with name to match) is intentional, to try to determine intent of using properties-based approach.
I don't really know how to improve this detection: there are developers that strongly feel that ideally even requiring `@JsonCreator` should not occur here. But doing so would then lead to problems with existing usage (and relatively common case in general) of delegating approach.

I am open to improvements in error messaging, with suggestions on what to indicate.

As to solving the issue, I would just suggest indicating mode always for 1-argument creators:

```java
    @JsonCreator(mode=JsonCreator.Mode.DELEGATING)
    public Bean(List<URL> urls) {
      ...
    }
```

**Comment by cowwoc** [comment]
Can't you detect this scenario by checking for `BasicBasicDescription` containing a single property that binds both to a field and a constructor? I assume this doesn't occur for any other scenario?

1. In such a case, I am expecting `Mode.DEFAULT` to behave as `Mode.DELEGATING` (the Javadoc seems to hint as much: "This typically favors use of delegating mode for single-argument creators that take structured types"). If you disagree then let's try improving the error message as you mentioned.
2. If we detect such a scenario and deserialization fails, I am expecting the error message to indicate that the only constructor we found resolved to `Mode.PROPERTIES`.
3. I actually didn't want to use `@JsonCreator` at all in this case, but I remember running into a deserialization failure when I tried omitting the annotation.

**Comment by cowtowncoder** [comment]
I have sort of lost my faith in more elaborate heuristics, and if it wasn't even more intrusive, I might just change behavior to require mode, always, instead of trying to add heuristics. But that boat has sailed.
FWTW there are other developers that strongly object to ever defaulting to delegating mode.

For this specific case, however, I am not sure how match with field and constructor parameter would be a reliable signal for using delegating creator. Field would be usable both as setter and getter, so combination of a field-as-getter and single named creator parameter is a potentially valid combination, when one does not want to add getter methods. Changing the behavior could then break someone else's use case somewhere.

As to error message, sure, I am open to suggestions for detecting special case and handling it in better way. Mismatching input cases are tricky to handle but improvements would be valuable. I definitely agree that these are unnecessarily difficult to troubleshoot.

Note that `master` (2.9.0-SNAPSHOT) has many changes to error reporting and that's where improvements should be made (exception message is part of API in a way).

**Comment by cowwoc** [comment]
> For this specific case, however, I am not sure how match with field and constructor parameter would be a reliable signal for using delegating creator. Field would be usable both as setter and getter, so combination of a field-as-getter and single named creator parameter is a potentially valid combination, when one does not want to add getter methods.

This is precisely my use-case.

If you peak into `BasicBasicDescription._properties` can't you say: "if the collection contains a single element, and that property is associated with both a field and a constructor" then output the error message I mentioned instead of the generic "can't deserialize type X from START_ARRAY"?

In fact... maybe you don't even need to look for this specific case. When you get "can't deserialize type X from START_ARRAY", can't you always include a list of `@JsonCreator` configurations that were considered before giving up? This would prove useful even for other combinations. For example, if I omit the `@JsonCreator` annotation altogether and Jackson falls back on some default behavior, I'd want to see what behavior/configuration it chose as part of that exception message.

**Comment by cowtowncoder** [comment]
There is probably enough information for POJO-deserializer (`BeanDeserializer`) to be able to figure out valid input token shapes; although complications probably arise for polymorphic cases when using array- or object-wrapper approach. Challenge is more in coming up good description of likely issue.
So improving error messaging is something that would be great to do if anyone has time. I do not at this point.

As to your use case, I was assuming that you do _not_ want as-properties matching even when property names are the same, but would rather want delegating approach regardless of the match.

**Comment by cowwoc** [comment]
Correct. I *do* want the delegating approach of the match.

I understand that you don't have time to look at this for now. No worries. Hopefully this bug report will help others who run across a similar problem in the future.

**Comment by cowtowncoder** [comment]
@cowwoc I will leave this open and I think error messaging is important. So not working on this immediately is not a comment on worth at all, just want to emphasize this. I wonder what'd be a good way to indicate work that might actually be easy for others to tackle -- this seems like a potentially good thing to work on, even with moderate amount of experience with codebase.

I assume code snippet above is enough to trigger error, so it's easy to see what it is and see how it could be changed most easily?

**Comment by cowwoc** [comment]
> I assume code snippet above is enough to trigger error, so it's easy to see what it is and see how it could be changed most easily?

Yes, assuming your input looks something like this:

`["http://first.com/", "http://second.com/", "http://third.com/"]`

and your project depends on `jackson-module-parameter-names` with the `-parameters` compiler option.

**Comment by lpandzic** [comment]
@cowwoc, are you aware that with `jackson-module-parameter-names` you don't need to add @JsonCreator to non single arg constructors?
Also, there were dozen of requests that the default be Property based creator, so I'm more in favor of property based ones (I've personally rarely used delegating creator behavior), but a flag might be a good idea to support both cases.

**Comment by cowwoc** [comment]
> a flag might be a good idea to support both cases.

This is precisely what `@JsonCreator` already does, hence (if you change the default) users who want my use-case will be forced to keep on adding the `@JsonCreator` annotation.

**Comment by lpandzic** [comment]
It does, but only per class. What I'm suggesting is specifying the behavior per ObjectMapper instance.
@cowtowncoder maybe a new poll is in order?

**Comment by cowtowncoder** [comment]
For Jackson 2.x, I don't plan on changing either defaults or heuristics: too much code relies on existing logic. For Jackson 3.x we can choose different defaults and I plan on polling & discussing suitable determination logic. This as part of reimplementing creator/properties discovery since there are fundamental flaws in merging the two.
Will close this issue as I don't think much progress can be made pre-3.x.

**Comment by cowwoc** [comment]
@cowtowncoder How will you remember to revisit this in 3.x if the issue is closed?

**Comment by cowtowncoder** [comment]
@cowwoc It's a big ticket item and covered here:

https://github.com/FasterXML/jackson-future-ideas/wiki

like

https://github.com/FasterXML/jackson-future-ideas/wiki/Major-Design-Issues

and in some form 

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson3-Changes
