### ISSUE TITLE
Allow inspection of modules registered in the current ObjectMapper

### ISSUE THREAD

**Issue by odrotbohm** [FasterXML/jackson-databind#1478]
We've just fixed [an issue](https://jira.spring.io/browse/DATAREST-899) in Spring Data that basically dealt with the order of module registrations. I could fix that but failed to come up with a reasonable way to actually test the fix as there's no way to inspect the registered modules or the module specific features enabled. It would be cool if the module setup could be inspected from the outside.

**Comment by cowtowncoder** [comment]
Hmmh. Unfortunately design explicitly does NOT keep track of modules; that is, `ObjectMapper` does not hold references to modules. Only ids are optionally kept.
However, perhaps access to ids should be sufficient for this purpose?

**Comment by olivergierke** [comment]
Yes, any way to check whether has already been added would be highly appreciated.

**Comment by cowtowncoder** [comment]
So, if (and only if) `MapperFeature.IGNORE_DUPLICATE_MODULE_REGISTRATIONS` is enabled, `ObjectMapper` keeps track of ids of registered modules (as determined by `Module.getTypeId()`).
I could expose this in two ways: either by something like `isModuleRegistered(String typeId)`, or by exposing (copy of) internal set of ids. Former is simpler and safer, but would not expose ordering.
Ordering is actually preserved as the underlying data structure is `LinkedHashSet`.

**Comment by olivergierke** [comment]
Oh, actually that's a good point. In our case, we register a certain module with some default setting but allow users to override this setting. Assuming the module the user registers, how could I then check that it's her module registered, not the default one?

Maybe there's rather a way to let me test whether module specific features were enabled?

Another way' be to introduce an even stricter registration mode that rejects duplicate registrations with an exception. AFAIR the ones currently available are override (last one wins) or skip (first one wins).

**Comment by cowtowncoder** [comment]
So, not keeping around references to modules is intentional, to avoid potentially undesirable dangling references. Whether this is a valid concern is debatable, but at this point it is guaranteed; module is of interest only during its setup after which `ObjectMapper` does not care.
So unfortunately it is not possible to introspect features of an earlier registration; and in fact if re-registering, previously registered handlers are not removed. You may end up with duplicate sets of (de)serializers, for example.

Rejecting attempts to re-register could be a new `MapperFeature`, and easy one to add. Let me know if that is something you'd like to get added.

And also whether ability to check purely that "some instance" has been registered or not; I don't want to add it unless it would be useful.

**Comment by dinomite** [comment]
I'd love to just be able to get the class names of registered modules.  We're using a shared library to create our ObjectMapper and I would like to be able to log all of the modules they load.

**Comment by cowtowncoder** [comment]
With 3.0 registration will be changed drastically and full set of modules will be at least accessible via `ObjectMapper.Builder()` (and some aspects possibly even via mapper, since registrations will be retained to allow `rebuild()`, which requires re-registration etc etc).

But with 2.x I think accessibility is limited to what exists now in 2.9... and although set of ids is retained (to optionally prevent duplicate registration), I don't see public accessors in `ObjectMapper` unfortunately.
That said, @dinomite if you have time to look into `ObjectMapper` and if it seems that adding an accessor could work, I might be talked into adding an accessor. Even if it's in patch release, because this is the last 2.x minor release.

**Comment by cowtowncoder** [comment]
I think that looks fine; the only minor request is to wrap this in "unmodifiable" set via `Collections`.

Well, actually first one. The other is to add Javadoc with brief description, along with `@since 2.9.6` tag.
With those I'm happy to merge this in.
(there's one more step wrt CLA, I'll add that to PR).

Thank you!

**Comment by dinomite** [comment]
PRed: https://github.com/FasterXML/jackson-databind/pull/2035

**Comment by cowtowncoder** [comment]
PR was merged, `ObjectMapper. getRegisteredModuleIds()` available since 2.10.0.
