### ISSUE TITLE
DateTimeSerializerBase doesn't use WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS with `java.sql.Timestamp`

### ISSUE THREAD

**Issue by hadrienk** [FasterXML/jackson-databind#1499]
When converted using DateTimeSerializerBase, java.sql.Timestamp instances are not written in nanoseconds, even if the WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS feature is enabled.

I found this error doing the following: 

````java
ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JavaTimeModule());
mapper.configure(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS, true);
mapper.configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, true);
mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, true);
mapper.convertValue(new Timestamp(1456412409000), Instant.class)
````

**Comment by cowtowncoder** [comment]
@hadrienk Unfortunately timestamp resolution with pre-Java8 JDK types is limited to milliseconds, and as such this feature is only supported by Java 8 date/time types. This is mentioned in Javadocs.

**Comment by cowtowncoder** [comment]
Actually looking at javadocs for `java.sql.Timestamp`, it sounds like it could actually retain the additional part, so in theory perhaps this could be supportable.

The challenge here is that of choosing proper representation. Although in theory one could simply multiply value by 1 billion, this would likely cause problems with interoperability and/or backwards compatibility. It would seem preferable to either:

1. Use floating point number, so that milliseconds would be stored in integral part, and fractional part would define fraction of milliseconds.
2. Use a (JSON) Object with two properties
3. Use a 2-element array.

I can't remember how exactly Java 8 date/time module (https://github.com/FasterXML/jackson-modules-java8) handles this, but it would probably be worth checking it out for guidance.

**Comment by hadrienk** [comment]
Actually I should have written this bug in the java 8 data/time module.

**Comment by hadrienk** [comment]
I am closing it, feel free to reopen it is you think it is worth a fix :)

**Comment by cowtowncoder** [comment]
Actually this is the right place since `java.sql.Timestamp` is part of core JDK, not something added in Java 8.
Further I think it should be quite possible to add support as requested.

**Comment by cowtowncoder** [comment]
Rethinking this again since 2.9.0 release is looming. While it would be technically possible to add this, realized that there is no separate serializer for `java.sql.Timestamp` yet. And with usage of pre-Java8 datetime types going down addition for separate serializer is probably not worth the hassle.
So, closing.
