### ISSUE TITLE
jackson-core & jackson-databind compiled with different target JDK's

### ISSUE THREAD

**Issue by mbazos** [FasterXML/jackson-databind#1500]
Pulled in the latest jackson-core and jackson-databind and noticed that the JDK compiled versions are different:
jackson-core-2.8.6.jar
X-Compile-Source-JDK: 1.6
X-Compile-Target-JDK: 1.6

jackson-databind-2.8.6.jar:
X-Compile-Source-JDK: 1.7
X-Compile-Target-JDK: 1.7

I am not sure if this is intended, but I also have not done the investigation to see if the latest databind can be compiled with 1.6.

**Comment by cowtowncoder** [comment]
@mbazos Yes, this is fully intentional. While other Jackson components moved to Java 7 with 2.8, `jackson-annotations` and `jackson-core` are to be fully Java 6 compatible for now.

Conversely, the latest `jackson-databind` can not be compiled on Java 6 (since it refers to Java 7 JDK classes), and although it actually does work on platforms with only JDK 6 classes (access to JDK 7 types is made via reflection), `javac` does not support cross-compilation -- as far as I know -- any more.
If there is a way to do cross-compilation, I would be interested to know how, since that would be nice.

However: plan is to move to Java 8 after Jackson 2.9 (which is likely Jackson 3.0), so Java 7 as baseline is somewhat temporary. Whether we'll move annotations and core (streaming) too is an open question, however, as there is not much benefit at that level (unlike with other modules that benefit more from new features).

**Comment by mbazos** [comment]
Thanks for the quick reply.

**Comment by srilakshmiG** [comment]
Hi,
Is jackson-databind-2.9.8.jar is not compatible with JDK 1.7 ? because I am getting following warning during compile time
warning: **_com/fasterxml/jackson/databind/ObjectMapper.class(com/fasterxml/jackson/databind:ObjectMapper.class): major version 51 is newer than 50, the highest major version supported by this compiler_** 

**What would be the compatible versions for the following with Java 1.7**
jackson-databind
jackson-core
jackson-annotations

**Comment by cowtowncoder** [comment]
@srilakshmiG That is odd. While build must occur on JDK 8 these days (can not push to Sonatype OSS repo with earlier), target bytecode should be Java 7.
