### ISSUE TITLE
ProGuard definition

### ISSUE THREAD

**Issue by johnjohndoe** [FasterXML/jackson-databind#1504]
Where can I find the recommended configuration for using Jackson with ProGuard?

**Comment by cowtowncoder** [comment]
@johnjohndoe Please use mailing lists for questions (https://groups.google.com/forum/#!forum/jackson-user).

I do not the answer, but if one is found I can add to FAQ.

**Comment by johnjohndoe** [comment]
https://groups.google.com/forum/#!topic/jackson-user/jKagJB0YSEg

**Comment by cowtowncoder** [comment]
@johnjohndoe Thanks!

Official documentation, like everything, is based on contributions, so the lack is because no one has shared their definitions for documentation (I presume there are enough Android developers that need them so they exist). I don't develop on Android personally, for example, so I can't directly help here. So let's hope some community member is able and willing to help here.

**Comment by johnjohndoe** [comment]
Here is what I use since a while in production:

```
# Jackson
-keep @com.fasterxml.jackson.annotation.JsonIgnoreProperties class * { *; }
-keep class com.fasterxml.** { *; }
-keep class org.codehaus.** { *; }
-keepnames class com.fasterxml.jackson.** { *; }
-keepclassmembers public final enum com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility { 
    public static final com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility *;
}

# Generell
-keepattributes SourceFile,LineNumberTable,*Annotation*,EnclosingMethod,Signature,Exceptions,InnerClasses
```

**Comment by cowtowncoder** [comment]
@johnjohndoe thank you! I can add this with some verbiage on `jackson-docs`:

https://github.com/FasterXML/jackson-docs

although if you had time it would be great to get a section (either on main README, or as a wiki page) outlining other things about use on Android platform. But I think this should be valuable since as you pointed out this is needed by many and having baseline can save lots of time.

**Comment by cowtowncoder** [comment]
Added sample settings at: https://github.com/FasterXML/jackson-docs/wiki/JacksonOnAndroid
Thank you again!

**Comment by humblerookie** [comment]
This library is too heavy 444kB after proguarding? Not sure why. These rules don't help in reducing it either. Can someone helpout?

**Comment by patrickfav** [comment]
Do you maybe have `-dontshrink` in your config?

**Comment by AdityaAnand1** [comment]
-keep class com.fasterxml.** { *; }
-keep class org.codehaus.** { *; }

!!

@johnjohndoe Those rules are extremely broad. We might as not be using proguard :/

**Comment by thebehera** [comment]
Are there any better proguard rules? @AdityaAnand1 nailed it... this is incredibly broad. why even use proguard then?

**Comment by cowtowncoder** [comment]
@thebehera This is not a discussion board (esp. closed issues...): for questions, discussion, please use mailing list:

https://groups.google.com/forum/#!forum/jackson-user

as to definitions, this is an OSS project so if you have something to contribute, please do so. 
I gather many other Android developers would find them useful.
Commentary on goodness or lack thereof of others suggestion is counter-productive if you nothing positive to contribute.

**Comment by AdityaAnand1** [comment]
Completely agree @cowtowncoder, however...

* I feel it is almost wrong to not intervene or "comment on the lack of goodness" of the most upvoted "solution" in the thread when essentially all it does is turn off proguard. Everyone who has commented on (or subscribed to) this thread clearly considers proguard a priority and the ones who merrily copy-pasted the highly upvoted solution deserve to know that it is **incorrect**.
* Something like proguard, which should be considered reasonably important in 2018, specially for large libraries like Jackson, could definitely benefit from direct input from it's creators. You know the library better than we ever could.

From personal experience, I have to set aside an entire day before pushing to production to just deal with proguard errors because so many libraries simply offer such broad rules instead of a real solution. So I have to manually dissect each warning and traverse the inner workings of every single library to figure out which ones I have to `-keep` and which ones I can `-dontwarn`. 

Just my 2 cents 😄

**Comment by cowtowncoder** [comment]
@AdityaAnand1 Yes, I agree in that all-around feedback is useful. Maybe it's more about just formulating way to point out things in respectful way. I do not mean to say only positive comments serve purpose.

How about this: could you file another issue, requesting improved, more selective ProGuard definitions. And then, bring it up on the user mailing list? Thing is, I personally do not (alas!) have experience with ProGuard, as I do not develop on Android. I do have general idea to know what I do not know, and I am not aware of other active contributors with knowledge either. But it is rather possible someone might have background and just could use a nudge or reminder. As you said, it is a very important area, and I fully agree with that.

Thank you for the discussion here: this is how things improve in my opinion.

**Comment by CCorrado** [comment]
I came across this proguard config that resolved my issues (and seems to be a bit better on the shrinking front, as it only keeps the names aka doesnt obfuscate the classes/members but still removes unused code)

```
# Proguard configuration for Jackson 2.x
-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}
-keepnames class com.fasterxml.jackson.** { *; }
-dontwarn com.fasterxml.jackson.databind.**
```

**Comment by cowtowncoder** [comment]
@CCorrado thank you for sharing this. I'll add it on:

https://github.com/FasterXML/jackson-docs/wiki/JacksonOnAndroid

**Comment by muzammil-meister** [comment]
I was constantly getting this error, after upgrading to AGP `1.8`

"Internal error: TypeReference constructed without actual type information"

It got fixed after adding this rule to the proguard. 

`-keep class * implements com.fasterxml.jackson.core.type.TypeReference`

**Comment by PavelGP** [comment]
Also want to add my five coins. Don't use abstract class `TypeReference` to create an anonimous object in the code like this:
`new TypeReference<YourModel>() {}`
You will get IllegalArgumentException with ProGuard enabled and looks like any general rules will not help you. 
It is better to inherit `TypeReference` and create `YourModelTypeReference` class. 
`public class YourModelTypeReference extends TypeReference<YourModel> {}`
Also don't forget to add proguard rule:
`-keep class * extends com.fasterxml.jackson.core.type.TypeReference`

**Comment by ashishbdhane** [comment]
For these dependencies which are required for JacksonXML on Android
```
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.18.2'
    implementation 'javax.xml.stream:stax-api:1.0-2'
```
This configuration worked for me.
```
-keepnames @interface com.fasterxml.jackson.** { *; }

-keepclassmembernames class com.fasterxml.jackson.** { *; }

-keepclassmembers, allowobfuscation class * {
    @com.fasterxml.jackson.annotation.JsonProperty *;
    @com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty *;
}

-keep class com.ctc.wstx.stax.WstxInputFactory { *; }
-keep class com.ctc.wstx.stax.WstxOutputFactory { *; }
-keep class org.codehaus.stax2.XMLInputFactory2 { *; }
-keep class javax.xml.stream.XMLInputFactory { *; }

-keepclassmembers class javax.xml.stream.XMLInputFactory {
    public static javax.xml.stream.XMLInputFactory newFactory(...);
}
-keepclassmembers class javax.xml.stream.XMLOutputFactory {
    public static javax.xml.stream.XMLOutputFactory newFactory(...);
}

# Suppress warnings for missing optional dependencies
-dontwarn com.fasterxml.jackson.**
-dontwarn com.ctc.wstx.**
-dontwarn org.codehaus.stax2.**
```
