### ISSUE TITLE
NumberSerializers unboxes values which are boxed directly afterwards

### ISSUE THREAD

**Issue by CodingFabian** [FasterXML/jackson-databind#1511]
com.fasterxml.jackson.databind.ser.std.NumberSerializer.serialize(Number, JsonGenerator, SerializerProvider)
contains such code which unboxes values:
```
if (value instanceof Float) {
            g.writeNumber(value.floatValue());
```

or the com.fasterxml.jackson.databind.ser.std.NumberSerializers.FloatSerializer
```
gen.writeNumber(((Float) value).floatValue());
```

But then the token buffer boxes these values again:

```
    @Override
    public void writeNumber(short i) throws IOException {
        _appendValue(JsonToken.VALUE_NUMBER_INT, Short.valueOf(i));
    }

    @Override
    public void writeNumber(int i) throws IOException {
        _appendValue(JsonToken.VALUE_NUMBER_INT, Integer.valueOf(i));
    }

    @Override
    public void writeNumber(long l) throws IOException {
        _appendValue(JsonToken.VALUE_NUMBER_INT, Long.valueOf(l));
    }

    @Override
    public void writeNumber(double d) throws IOException {
        _appendValue(JsonToken.VALUE_NUMBER_FLOAT, Double.valueOf(d));
    }

    @Override
    public void writeNumber(float f) throws IOException {
        _appendValue(JsonToken.VALUE_NUMBER_FLOAT, Float.valueOf(f));
    }
```

I realize that for customization purposes this makes sense, because the `writeNumber(float f)` api of TokenBuffer guarantees types, and allows the Serializer to choose what to do.
However in many cases this default behaviour will perform unnecessary allocations and burn cycles.

I was trying to come up with a PR, but as I am not familiar with the codebase, I was unsure how to redesign this in a backwards compatible way.
Perhaps somebody familiar with the code has an idea?

**Comment by cowtowncoder** [comment]
@CodingFabian Ah yes. The problem is that since `TokenBuffer` has to use boxed versions for buffering (... or very awkward attempts at using multiple native arrays etc etc...), there's extra back and forth.
To try to solve this problem would seem to require addition of a few new method in `JsonGenerator`, with stub implementations that just forward to unboxed versions.
It could even be just a subset (`int`, `long`, `double`... not needed with `boolean`).

On the other hand, I am not sure this would commonly be a measurable performance issue.
`TokenBuffer` is used sometimes, depending on usage patterns, but should not be used extensively; and its use adds overhead regardless of this issue.

So I guess I am bit sceptical of benefits. But if anyone wants to take a stab feel free to, I can help with PR?

**Comment by cowtowncoder** [comment]
No current plans to try to improve this: while I am not opposed to idea of optimizing things this seems like something that is not an obvious bottleneck for performance-optimized usage (only affects cases where buffering is needed, where getting rid of need to buffer would yield more improvements.
