### ISSUE TITLE
JsonNOdeFactory and ObjectNode illogical API

### ISSUE THREAD

**Issue by mgrouch** [FasterXML/jackson-databind#1524]
Object node is lacking some methods.

It is impossible to write something like this:

        final JsonNodeFactory fact = JsonNodeFactory.instance;

        JsonNode value = fact.objectNode()
                             .put("firstName", "John")
                             .put("lastName", "Smith")
                             .put("age", 25)
                             .putObject("address", fact.objectNode()
                                                 .put("streetAddress", "21 2nd Street")
                                                 .put("city", "New York")
                                                 .put("state", "NY")
                                                 .put("postalCode", "10021"))
                             .putArray("phoneNumber", fact.arrayNode()
                                                     .add(fact.objectNode()
                                                              .put("type", "home")
                                                              .put("number", "212 555-1234"))
                                                     .add(fact.objectNode()
                                                              .put("type", "fax")
                                                              .put("number", "646 555-4567")));

Thanks
--MG

**Comment by jlolling** [comment]
Why do you think so? Replace your putObject and putArray simply with the set method thats it.
This is the only difference to your code. That looks illogical to you?

**Comment by mgrouch** [comment]
I tried with set(). It doesn't compile. 
thanks

**Comment by jlolling** [comment]
This is the method signature:
```public JsonNode set(String fieldName, JsonNode value)```
It should compile!

**Comment by jlolling** [comment]
The only strange thing is, why put does not allow JsonObject as parameter.

**Comment by mgrouch** [comment]
That's the issue. It doesn't return NodeObject. It returns JsonNode. 
That breaks compilation

**Comment by mgrouch** [comment]
Yes it looks like a natural way of chaining calls to build json but with current Jackson API it can't be done.

**Comment by cowtowncoder** [comment]
@mgrouch Problem with return value is a well-known design flaw. Unfortunately, however, it basically can not be fixed without breaking lots of existing code as change of return value in this way is binary-incompatible and any code that compiled against old version fails to load with new version and vice versa. Worse, it is source-compatible meaning that recompilation would solve the problem and IDEs would not flag it an issue.

Other than that I wish you tried to use more descriptive titles and description to indicate issues, instead of making blanket statements. It is not very useful to say "Object node is lacking some methods." or "JsonNOdeFactory and ObjectNode illogical API". Latter is an opinion; former vague general statement.
We did eventually get to what you are really saying but it would help a lot if you thought this through on your side and then explained the issue and perhaps suggested an improvement.

**Comment by mgrouch** [comment]
I did propose the solution in original post. You just need to add 2 methods
putObject and putArray returning NodeObject
Thanks

**Comment by jlolling** [comment]
There is a deprecated method:
ObjectNode.put(String, JsonNode)
I do not know why this is deprecated because it would solve this issue.
I would like to have such a method!

**Comment by cowtowncoder** [comment]
@jlolling Did you actually even check out that `put` method signature? It returns `JsonNode`, having exactly same problem.
