### ISSUE TITLE
@JsonTypeInfo: defaultImpl is ignored if use=Id.NONE

### ISSUE THREAD

**Issue by lfrittelli** [FasterXML/jackson-databind#1530]
I have the following annotated class structure:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NONE, defaultImpl = Sub.class)
    public interface Super {
        String getAtt1();
        void setAtt1(String s);
    }
    public class Sub implements Super {
        private String att1;

        public String getAtt1() { return att1;}
        public void setAtt1(String s) {att1 = s;}
    }
```

My intention is that I will always want an instance of Sub whenever Super is referred to.
Example: `new ObjectMapper().mapperFor(Super.class).readValue("{"att1":"test"}"` should be able to successfully deserialize an instance of Sub.

However, the current implementation of Jackson does not honor defaultImpl if use is Id.NONE.

I could trace this back to the following code in `StdTypeResolverBuilder.java`:

```
@Override
    public TypeDeserializer buildTypeDeserializer(DeserializationConfig config,
            JavaType baseType, Collection<NamedType> subtypes)
    {
        if (_idType == JsonTypeInfo.Id.NONE) { return null; }

        TypeIdResolver idRes = idResolver(config, baseType, subtypes, false, true);
        
        // First, method for converting type info to type id:
        switch (_includeAs) {
        case WRAPPER_ARRAY:
            return new AsArrayTypeDeserializer(baseType, idRes,
                    _typeProperty, _typeIdVisible, _defaultImpl);
        case PROPERTY:
        case EXISTING_PROPERTY: // as per [#528] same class as PROPERTY
            return new AsPropertyTypeDeserializer(baseType, idRes,
                    _typeProperty, _typeIdVisible, _defaultImpl, _includeAs);
        case WRAPPER_OBJECT:
            return new AsWrapperTypeDeserializer(baseType, idRes,
                    _typeProperty, _typeIdVisible, _defaultImpl);
        case EXTERNAL_PROPERTY:
            return new AsExternalTypeDeserializer(baseType, idRes,
                    _typeProperty, _typeIdVisible, _defaultImpl);
        }
        throw new IllegalStateException("Do not know how to construct standard type serializer for inclusion type: "+_includeAs);
    }
```

As can be seen, the _defaultImpl is not used when _idType is Id.NONE and thus this preference is lost.

**Comment by cowtowncoder** [comment]
Before trying to address specific question, let me ask another question: wouldn't this work by instead of using annotation

    @JsonDeserialize(as = Sub.class)
    public interface Super { ... }

**Comment by lfrittelli** [comment]
I must say your proposed alternative does work :) I never saw that 'as' hint and was assuming that the only way was through defaultImpl.
The only caveat is that 'as' required me to add a default constructor in Sub whereas JsonTypeInfo does not have such requirement. This is not an impediment in my particular scenario.
Your advise is greatly appreciated!

Going back to the issue raised, and to avoid confusion for other users. It does seem strange at least that Jackson supports a combination of annotations that will mean one of them being silently ignored.

I see the following in defaultImpl javadoc which in hindsight may have intended to indicate that NONE+defaultImpl is discouraged:
```
Placeholder value of {@link JsonTypeInfo} (that is, this annotation type
itself} means "there is no default implementation" (in which
case an error results from unmappable type).
For backwards compatibility with earlier versions (2.5 and below),
value of {@link JsonTypeInfo.None} may also be used.
```
My preference would be that defaultImpl+NONE should not be a valid combination (i.e. it should fire an Exception or at least show a warning) But if backwards compatibility is a concern, could we add stronger wording to the javadoc such as: `Since NONE means no default class, using defaultImpl and NONE will mean that defaultImpl is ignored` ?

**Comment by cowtowncoder** [comment]
@lfrittelli On requiring default constructor: all deserialization would require either that or `@JsonCreator`, at least I can not think of any reason why this would be different. I mean value must be somehow instantiatable, there's no way around that.

On annotation validation: it might make sense to improve validation, but there is no good general mechanism to do so, since general handling (by collectors) has no idea of constraints to validate and actual usage is scattered throughout code. One place where it would work for this particular case would probably be `JacksonAnnotationIntrospector`.

However, I am not sure this usage can actually be found non-compliant solely by looking at annotation itself. The real issue is actually (I think) that use of `Id.NONE` requires additional components to be provided by developer -- standard resolver can not use it since it lacks knowledge. Instead, custom resolver is needed.
But whether one is registered is not something annotation introspector can know. Standard handler could validate it perhaps.

**Comment by dlopuch** [comment]
I too eventually encountered this issue believing that `JsonTypeInfo.Id.NONE / defaultImpl` combination would do what `@JsonDeserialize(as=...)` does, mostly because I wasn't aware of the `@JsonDeserialize` annotation mentioned here.

Perhaps add some quick `@see` javadoc to `defaultImpl` pointing to `@JsonDeserialize`?  

Or since I started my search under the [Jackson Polymorphic Deserialization](https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization) wiki page, add a mention of it there?
