### ISSUE TITLE
"KeyNamingStrategy" - define the capitalization strategy for map keys

### ISSUE THREAD

**Issue by marianowadel** [FasterXML/jackson-databind#1532]
After several attempts, I came to the conclusion that there's no way to define the capitalization strategy for map keys when unmarshalling a JSON body.
For example, converting a JSON string that has properties named with **underscore** strategy into a map with **camel case** key naming strategy.
**@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)** and other similar annotations only work on POJOs where all the properties are defined.
I am using jackson-databind 2.8.0.
Thanks in advance.
Regards

**Comment by cowtowncoder** [comment]
Correct, naming strategy only works for POJOs as they only have properties (Maps have entries).

I am not 100% sure that supporting similar somewhat static approach makes sense for Maps actually. This because there is no benefit from trying to limit functionality, as transformation must be applied for each and every entry; this is not true for POJOs where transformation can be done once and no overhead is needed when (de)serializing.

So I wonder if instead some form of pre-processing for serialization, and post-processing for deserialization would make more sense -- that is, ability to effect transformations by maybe registering handlers for this.

Anyway if anyone wants to work on this, PRs are welcome.

**Comment by cowtowncoder** [comment]
No current plans to implement this: may be reopened (or maybe just refiled) if someone is interested in working on this.
