### ISSUE TITLE
Immutable ObjectWriter

### ISSUE THREAD

**Issue by MartinGeisse** [FasterXML/jackson-databind#1548]
Version: 2.8.7
SO question at: http://stackoverflow.com/questions/42666988/immutable-jackson-objectwriter/42667178#42667178

I want to (de-)serialize JSON in multiple different contexts which require slightly different Jackson configurations, in multiple threads. According to resources both on the web and in the class comments, this should be possible using ObjectWriter and ObjectReader constructed from an ObjectMapper which has a "base" configuration. However, I haven't succeeded in building an immutable ObjectWriter from the ObjectMapper -- it seems to change its configuration together with the mapper.

Here's an example that re-configures WRITE_NUMBERS_AS_STRINGS. Please treat this as "just an example" WRT the fact that I need a solution both for the ObjectReader and ObjectWriter, as well as various configuration objects such as @JacksonInject'ed values, not just low-level JSON format options.

(sorry, GitHub code markup didn't seem to work)

public class Main3 {

    public static void main(String[] args) throws Exception {
        test(false);
        test(true);
    }

    private static void test(boolean enable) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        mapper.disable(JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS);
        ObjectWriter w1 = mapper.writer();
        if (enable) {
            mapper.enable(JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS);
        }
        ObjectWriter w2 = mapper.writer();
        Bean b = new Bean();
        b.setX(42);
        System.out.println(w1.writeValueAsString(b));
        System.out.println(w2.writeValueAsString(b));
    }

    public static class Bean {

        private int x;

        /**
         * Getter method.
         *
         * @return the x
         */
        public int getX() {
            return x;
        }

        /**
         * Setter method.
         *
         * @param x the x
         */
        public void setX(int x) {
            this.x = x;
        }

    }

}

As you can see, I'm running the same test twice, each time creating two ObjectWriters from the same ObjectMapper and serializing a test bean with each of them. In the second run, I'm enabling WRITE_NUMBERS_AS_STRINGS for the second writer. This seems to affect the first writer too.

Expected output:

`{"x":42}
{"x":42}
{"x":42}
{"x":"42"}
`

Actual output:

`{"x":42}
{"x":42}
{"x":"42"}
{"x":"42"}
`

Is there anything else needed to decouple the ObjectWriter from the ObjectMapper? Needless to say, it should be trivial to construct an example based on this one where thread safety is violated, not to mention that the ObjectWriter is obviously NOT immutable.

**Comment by cowtowncoder** [comment]
@MartinGeisse `ObjectWriter` is immutable and all changes to its configuration are done by creating a new separate instance. But you are of course correct in that code you show behaves in an unexpected way.

Unfortunately in this case one of underlying components, lower level `JsonFactory` (used for constructing parsers and generators) is mutable, not unlike `ObjectMapper`.
And this is what `ObjectMapper` does: modifies configuration of that factory, resulting in change being observed, since this factory object is shared being somewhat heavy-weight.
(I won't go into detailed explanation here as to why this is difficult to avoid or prevent -- but it is something that was worked on extensively at and after 2.6 or so, and I'm happy to expand if there are aspects worth discussing)

Fix here is to change configuration of generator/parser setup to use methods in `ObjectWriter`:

    w = w.with(JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS);

which will NOT modify `JsonFactory` configuration (for obvious reasons), but instead only applies them on actual `JsonGenerator` once it is constructed.

It is unfortunate that this discrepancy exists and is quite difficult to fully expose (so it would be obvious); but I will go ahead and add a statement in Javadoc to try to explain immutability concerns regarding changes via `ObjectMapper`.

I hope this helps -- thank you for bringing the issue to our attention.

**Comment by cowtowncoder** [comment]
One follow-up note: recommended/supported configuration pattern for `ObjectMapper`, with respect to thread-safety, is to handle all configuration up-front before any reads or writes; and after this, only use configuration available via `ObjectReader` and `ObjectWriter` (either as part of creation calls on `ObjectMapper`, or "mutant factory" methods of reader/writer instances).
So anything that is NOT available via reader/writer instances is NOT configurable on per-call basis, and is considered static configuration; if variations are needed, separate `ObjectMapper`s are needed.

If this pattern is observed `ObjectReader`s and `ObjectWriter`s should not only be immutable regarding its own state (feel free to check source code: fields are `final`), but also behave so regarding transitive dependencies.

I updated `ObjectMapper` javadocs regarding `enable` / `disable` / `configure` methods that allow changing of `JsonParser.Feature` / `JsonGenerator.Feature` to warn about possibility of changes leaking due to shared `JsonFactory` instance.

**Comment by MartinGeisse** [comment]
Thanks a lot for the explanation. This should help me find a workaround for my case. I'll update the SO thread.

**Comment by cowtowncoder** [comment]
@MartinGeisse you are welcome!
