### ISSUE TITLE
Support deserialization of array field using elementwise addition method

### ISSUE THREAD

**Issue by nmatt** [FasterXML/jackson-databind#1560]
I have a third-party class for which I want to write a mixin. The class has collection-valued properties for which it has regular getters, but no collection-valued setters. Instead, it has "add" methods to add the collection elements one by one. E.g.:
```java
    public Set<Foo> getFoos();
    public void addFoo(Foo foo);
```
It would be nice if some variant of `@JsonProperty` could be used on `addFoo(Foo)` to tell Jackson that, when deserializing `foos`, it should add the elements one by one using `addFoo(Foo)`.

**Comment by cowtowncoder** [comment]
Ok, that is a possible addition.

But just in case, I'll mention that feature #1399 being added in 2.9 (2.9.0.pr1 is out) allows specifying properties to use "merge", like

```java
    @JsonMerge(OptBoolean.TRUE)
    public Set<Foo> getFoos() { }
```

in which case `add()` method will be used to append entries to existing value, instead of default overwriting.
This works for different kinds of types; for POJOs it would avoid new instance construction, similarly for `Map`.

**Comment by nmatt** [comment]
Thanks, #1399 indeed is an alternative when the getter returns a modifiable reference to the internal state.

**Comment by cowtowncoder** [comment]
At this point, I have no plans to implement this feature, so closing.
