### ISSUE TITLE
WRAP_ROOT_VALUE when serializing 

### ISSUE THREAD

**Issue by shavo007** [FasterXML/jackson-databind#1567]
Hi,

i am building a rest api using spring boot. I wanted to wrap a json response with root element "data" to comply with json api spec.

I added in the config to my application.yml

`jackson.serialization.WRAP_ROOT_VALUE: true`

Then i used the annotation in my pojo
`@JsonRootName(value = "data")`

The problem is that i see a root field defined for all my resources, not just this one specifically.

Spring boot version 1.4.0.RELEASE
jackson databind 2.8.1

thanks,
shane.

**Comment by cowtowncoder** [comment]
Yes, behavior makes sense.

But if you are asking about how to change it on per-call basis, please use mailing list:

https://groups.google.com/forum/#!forum/jackson-user

since this is issue tracker, for reporting problems and requesting/suggesting new features.
You will get better response from mailing list which is read by way more developers than issue tracker (in addition to also not filling tracker with questions :) ).

**Comment by shavo007** [comment]
@cowtowncoder  majority of my github issues i raise are questions, which either turn out to be issues or allow other developers to seek clarification on a similar topic.
