### ISSUE TITLE
Json Merge set null (remove) value for merge pathes (following #1399 and #1437)

### ISSUE THREAD

**Issue by Tetradeus** [FasterXML/jackson-databind#1598]
Version : 2.9 r2

Related to #1399 and #1437

Wouldn't it be nice to have an option to enable setting null values at merge pathes ? Ref #1437

Presently in tests about Json merge :

```
    // Also: nulls better not override
    public void testBeanMergingWithNull() throws Exception
    {
        Config config = MAPPER.readerForUpdating(new Config(5, 7))
                .readValue(aposToQuotes("{'loc':null}"));
        assertNotNull(config.loc);
        assertEquals(5, config.loc.a);
        assertEquals(7, config.loc.b);
    }
```

What if I really want to be able to set null for loc ? assertNull(config.loc);
Not totally sure, but this would make it Json Merge Patch compatible.

**Comment by cowtowncoder** [comment]
Sounds reasonable. May need to re-wire handling of `@JsonMerge` quite significantly but other than that.

**Comment by cowtowncoder** [comment]
Toying with an alternate idea of combining this with `@JsonSetter(nulls=Nulls.SET)` (vs `Nulls.SKIP`).
On one hand, that setting already exists, and would work well for per-property annotations.
But on the other hand might be bit messy for defaulting (per-type, globals); and needs of merging may be different from use for straight "regular" deserialization.

So perhaps the best way is to add new property for `@JsonMerge(skipNulls)`, which determines if `null`s are skipped in context of merging. `@JsonSetter` setting could still have effect for non-merging use case.

**Comment by cowtowncoder** [comment]
Actually going with `@JsonSetter` route makes tons of sense because that is fully wired already, and conversely trying to use different settings for merge/non-merge case would be a major PITA.

So: changes I will make are:

1. Default for merge for `null`s is same as regular deserialization setting: that is, just set it as `null` (or replacement `null` value as case may be)
2. To skip `null`s during merging, `JsonSetter.Value` must be used at one of 3 levels (property annotation, per value-type annotation, global defaults) -- `Nulls.SKIP` will achieve this.

And with that it will be possible to make `null`s overwrite non-null values.
