### ISSUE TITLE
Jackson 2.x do not serialize type info in some cases (Map<..,Collection<MyType>>)

### ISSUE THREAD

**Issue by kvaster** [FasterXML/jackson-databind#1606]
Code sample is same for both 2.x and 1.9.x. The only difference is imports.

With jackson-1.9.13 output will be:
```
{"m":{"t":[{"type":"A2"}]}}
{"type":"A2"}
```

With jackson-2.8.8 output will be:
```
{"t":[{}]}
{"type":"A2"}
```

With 2.x jackson no type information is serialized.

Code sample:
```
public class JacksonTest
{
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property="type")
    abstract static class A1
    {
    }

    @JsonTypeName("A2")
    static class A2 extends A1
    {
    }

    public static class A3
    {
        @JsonIgnore
        Map<String,Collection<A1>> m;

        @JsonProperty
        public Map<String,Collection<A1>> m()
        {
            return m;
        }
    }

    public static void main(String[] args) throws Exception
    {
        ObjectMapper om = new ObjectMapper();

        Map<String,Collection<A1>> m = new HashMap<>();
        Collection<A1> c = new ArrayList<>();
        c.add(new A2());
        m.put("t", c);

        A3 a = new A3();
        a.m = m;

        System.out.println(om.writer().writeValueAsString(m));
        System.out.println(om.writer().writeValueAsString(new A2()));
    }
}
```

**Comment by cowtowncoder** [comment]
This is due to Java Type Erasure: you are not providing runtime type information for root value, so it will only be seen as `Map<?,?>` which is about same as `Map<Object,Object>`.
Since `java.lang.Object` does not have `@JsonTypeInfo` information, values will not have polymorphic typing enabled.
Why this happens to include type information with 1.9.x is unclear, but it should not be included as per design.


There are couple of ways of passing type information, but before that I would recommend that in general no generic types are used as root values (generic types are fine for anything reached via properties; issue is only with the immediate root value).

As to type information:

1. Use of helper type like `class MyMap extends Map<String,Collection<A1>> { }` would allow passing type (since it's not generic anymore, just defines bindings via supertype)
2. Specifying exact type via `ObjectWriter`:

     mapper.writerFor(new TypeReference<Map<String,Collection<A1>>>() { });

both of which should work. On deserialization type is needed too, but is usually done anyway (since there is no runtime type information to rely on).

**Comment by kvaster** [comment]
I know about type erasure, but can you please explain why exactly same code worked ok with 1.9.x version ?
The problem is in serialization. During serialization we know all annotations on concrete object we're serializing now. In 1.9.x it's all ok - we know that we're serializing object of type A2 and we include typeinfo. In 2.8.x type info is not included.

**Comment by cowtowncoder** [comment]
@kvaster I do not know why it would work with 1.9: key question there would be weather it can also be read back. I'd be tempted to say that behavior in 1.9 was erroneous, but since that code has not been modified for a few (5?) years, I do not remember.

The key question here is this: type information is NEVER looked for unless it is expected to be there. So deserializer must know such information is to be expected; and from that assumption is made that type information given on serialization (explicit type, or runtime time of instance passed) is the same information deserializer will get.

This logic has been there all the way since 1.5, for years, and will not change. Many users have complained about this, tried to convince me this is wrong. At this point I do not care -- I know how system works, what the constraints are, and if someone wants to implement polymorphic handling differently, they are perfectly free to write their own library and see what the ramifications are. I did spend a lot of time thinking this through, back when implementing system, so this is not a simple oversight. It is a design choice.

**Comment by kvaster** [comment]
My apologies for being incorrect and thank you very much for clarification. It seems that it will not deserialize with 1.9.x. And you should not really care, cause this project is really one of the best libraries I've seen in java world.

**Comment by cowtowncoder** [comment]
@kvaster Thank you for verifying the behavior wrt 1.9: I'd rather problems are reported (even if found they can't be resolved) than not, since bugs may only be fixed once reported.
