### ISSUE TITLE
Wrong serializer causing JsonMappingException

### ISSUE THREAD

**Issue by rafaelgondim** [FasterXML/jackson-databind#1612]
I'm using spring-data-rest (3.0.0), which uses jackson-databind 2.9.0.pr2.
I'm not sure what have changed, since, not so long ago, I had an functional application. But now I'm getting:

`
"Could not write JSON document: java.lang.Double cannot be cast to java.lang.Integer (through reference chain: org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer$1["content"]->**.Contrato["storageUtilizado"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: java.lang.Double cannot be cast to java.lang.Integer (through reference chain: org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer$1["content"]->**.Contrato["storageUtilizado"])"
`

I've been stucked with this problem for a while and I'm just assuming that there is something wrong when de Serializer for this specific field is defined

![Degub_Print](https://s3.amazonaws.com/for-share-around/jacson-databind_problem.png)

I need, at least, some directions...

**Comment by cowtowncoder** [comment]
This is not enough information to help unfortunately. You basically include almost nothing of relevancy: neither classes nor code invoked nor json input. And problem occurs through a framework that does plenty of its own handling which may cause the issue. Stack trace itself only points out that you have type impedance of some sort.

What would help is to write a stand-alone unit test, using your type definitions, input json, and not requiring Spring framework.

**Comment by rafaelgondim** [comment]
Sorry for the short info. I didn't had much time, but I've looked a little further and, I'm pretty sure I found de source of the problem, this block of code:

```
            // and maybe replace filtered property too?
            if (i < filteredCount) {
                BeanPropertyWriter w2 = _filteredProps[i];
                if (w2 != null) {
                    w2.assignSerializer(ser);
                    // 17-Mar-2017, tatu: Typically will lead to chained call to original property,
                    //    which would lead to double set. Not a problem itself, except... unwrapping
                    //    may require work to be done, which does lead to an actual issue.
                    continue;
                }
            }
```

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/BeanSerializerBase.java#L357

My property with type Double get the right serializer, then, in the next iteration, a property with type Integer gets the Integer serializer and the previous property get the serializer reassign.
I didn't get the filtered prop assign. In my case the properties and the filtered properties have different sizes (witch I assume is expected) and, mostly, they won't match (_filteredProps[i] != _props[i]) so why assign the same serializer?

I will try to make a simpler example soon

**Comment by rafaelgondim** [comment]
Here is de test case:

```java
public class Test {

    public Integer a;

    public Integer b;

    public Double c;

    public Test(Integer a, Integer b, Double c) {
        this.a = a;
        this.b = b;
        this.c = c;
    }

    public static void main(String[] args) throws JsonProcessingException {
        Test t = new Test(0, 1, 2d);
        SerializerFactory serializerFactory = BeanSerializerFactory.instance.withSerializerModifier(new TestBeanSerializerModifier());
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setSerializerFactory((serializerFactory));
        System.out.println(objectMapper.writeValueAsString(t));
    }

//TestBeanSerializerModifier mimics the Spring Data Rest class: org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module.AssociationOmittingSerializerModifier
//Which makes the builder have different list sizes for properties and filtered properties (BeanPropertyWriter)
    private static class TestBeanSerializerModifier extends BeanSerializerModifier {
        @Override
        public BeanSerializerBuilder updateBuilder(SerializationConfig config, BeanDescription beanDesc, BeanSerializerBuilder builder) {
            List<BeanPropertyWriter> filtered = new ArrayList<BeanPropertyWriter>(2);
            List<BeanPropertyWriter> properties = builder.getProperties();
            //Make the filtered properties list bigger
            builder.setFilteredProperties(new BeanPropertyWriter[] {properties.get(0), properties.get(1), properties.get(2)});

            //The props will be shorter
            filtered.add(properties.get(1));
            filtered.add(properties.get(2));
            builder.setProperties(filtered);
            return builder;
        }
    }
}
```

**Comment by cowtowncoder** [comment]
@rafaelgondim Thank you!

**Comment by cowtowncoder** [comment]
@rafaelgondim Ok. I can see what code does, although am not exactly certain what it is trying to do.

Anyway: the invariant that is being violated is simply that number of entries in regular (non-filtered) and filtered properties has to be the same; and further that entries must match as well (that is, properties included must be defined in same order, and any `null` entries in filtered sequence must match entries that are to be skipped.
It is not legal for filtered list to have more entries than the non-filtered default list; even if earlier versions managed to allow it.

This is not clearly documented, as these methods were not designed as external extension points; but since they are `public` it probably makes sense.
I will also add a check to throw exception if attempts is made with incompatible number of entries in array argument.

I will verify that test passes with modifications, and start adding checks that help catch this problem.

**Comment by cowtowncoder** [comment]
Forgot to mention: I will see if and why there could be mismatch between two lists, which causes non-sensical error in this particular cases.

And also double-check my assertion that lists have to match: I think internally there are things that require that, but I could be wrong.

Thank you for reporting the issue and providing reproduction.

**Comment by cowtowncoder** [comment]
Ok... so, check for this particular case can not be made in setter, but can (and now will) be made in `build()` method. This will now enforce that the number of properties is compatible (filtered may be set to `null` as short cut; otherwise must have same number of entries).

Such check(s) can only guard against certain kinds of discrepancies, and unfortunately two lists are deeply related and assumed to contain related properties and handers: essentially, filtered list to contain either `null` entries (for anything always filtered out if view handling enabled), or wrapped `BeanPropertyWriter`s; but not unrelated writers -- either unrelated in general, or ones in different order.
The reason for this is that certain initializations -- most importantly, contextualization (`createContextual()` for enclosed `JsonSerializer`s) -- must affect both cases.

So: I don't think this is the ideal answer, but basically use case of unit test is unsupported: it may have worked earlier, but if so not intentionally.

Having said that I do want to try to make actual use case working. That may require some changes in handling (for example, padding `properties` list, perhaps), but I assume it should be possible to achieve intended end result. Just not using technique attempted here.

**Comment by cowtowncoder** [comment]
Forgot to ask the obvious question: what does the original code (from which test was created) try to achieve here? I have no plans to support specific usage, but I would be interested in helping solve the problem whatever it is.

**Comment by rafaelgondim** [comment]
I don't know, as I said, the test was only to mimic what Sprint Data Rest does:
[https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/json/PersistentEntityJackson2Module.java#L243](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/json/PersistentEntityJackson2Module.java#L243)

**Comment by cowtowncoder** [comment]
@rafaelgondim Ok. Then that code has to be fixed. Thank you for reporting this; at least error messaging is now improved.

**Comment by pbergmano360** [comment]
Is there any workaround for this? Or is a fix being worked on? I simply move my attributes around and it works, but it doesn't feel like an optimal solution :-)

Per

**Comment by cowtowncoder** [comment]
@pbergmano360 From Jackson perspective things work as designed. Underlying lists (regular, filtered) must retain position-by-position indexes, and change as designed is not guaranteed to work. Unfortunately it sounds like it may have worked with earlier jackson-databind versions, which perhaps gave impression it would be valid usage.

So from end user perspective it seems there may be work for sping-data (-rest-webmvc?) framework to change its modification of filtered properties. But this would need to be reported to that project; I do not know if authors of that framework follow jackson issues or are on mailing lists (I do know a few Spring developers are, just not specific sub-project).

**Comment by pbergmano360** [comment]
Thanks for the clarification.

**Comment by damogallagher** [comment]
Hi

Has anyone got around this particular issue? Or has anyone seen a recommendation from Spring?
