### ISSUE TITLE
Annotating nested classes causes compiler errors

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1620]
Version 2.8.8, 2.9.0.pr3

Testcase: https://github.com/cowwoc/jackson-annotating-nested-classes

As far as I can tell, the application is perfectly legal but I am getting compiler errors that should be impossible (not being able to find a class that is clearly being imported).

If I remove the Jackson annotations, the compiler errors disappear.

This issue only seems to occur when annotating nested static classes.

**Comment by cowtowncoder** [comment]
I'm sorry but I do not accept test cases that use Lombok any more: too much hassle. Downloading this repo, trying to build fails with:

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project JacksonNestedClasses: Compilation failure: Compilation failure:
[ERROR] /opt/java/tmp/jackson-annotating-nested-classes/src/main/java/com/mycompany/jacksonnestedclasses/Class1.java:[15,6] cannot find symbol
[ERROR] symbol:   class Data
[ERROR] location: class com.mycompany.jacksonnestedclasses.Class1
[ERROR] /opt/java/tmp/jackson-annotating-nested-classes/src/main/java/com/mycompany/jacksonnestedclasses/Class1.java:[16,6] cannot find symbol
[ERROR] symbol:   class Builder
[ERROR] location: class com.mycompany.jacksonnestedclasses.Class1
[ERROR] -> [Help 1]
```

which is consistent with my other experiences.

Would it be possible to reproduce the issue without Lombok?

**Comment by cowwoc** [comment]
@cowtowncoder The testcase is fine. The compiler errors you quoted are precisely the bug I am talking about. If you look at the source, you will see that it is technically impossible for `Data` not to be found as it is being imported above.

I am not a fan of Lombok myself. Unfortunately, it's use is mandated by my co-workers. And no, I have not been able to reproduce this problem without Lombok. Nor have I been able to reproduce a problem with Lombok without Jackson, so this is an problem with integrating these two technologies.

Do any of the Jackson annotations rewrite the source or bytecode? If so, is it possible to dump the intermediate file somewhere? This would help me understand how the compiler is failing with an error that seems to be impossible.

Or are the annotations just markers that get used at runtime using reflection?

**Comment by cowtowncoder** [comment]
No, Jackson core components does not generate or modify bytecode. Some modules (mrbean, afterburner) generate new classes, but none modify existing ones behind your back.

So, yes, annotations really are just markers introspected during runtime; even mix-ins are just folded in . Flattening is handled via `AnnotatedClass` (and `AnnotatedClassResolver`).

But Lombok does do bytecode generation during loading doesn't it? Otherwise its annotations are just annotations: it has to generate actual accessors, fields and so on.

**Comment by cowtowncoder** [comment]
But looking at the error:  yes, it does seem odd that class that should be in classpath is not found. 
I am not sure how Jackson would be causing the issue as the error comes from Java compiler (via maven compiler plug-in).

My understanding is that Lombok does do code manipulation during compilation (not sure if it's at source or bytecode level): and this is the reason I have decided not to accept it as a test dependency (it has nothing to do with its usage which should be fine and that I want to support wrt jackson) -- it does not seem to work without installing additional components (*).
I have also had problems on IDE (Eclipse) with similar setup, although usually maven build from shell still works.
So... I don't know what to do with this one. Maybe I'll try reading bit more about how Lombok actually operates if that'd help.

(*) if it turns out things can be made to work with maven settings or such I'd be fine with test dep -- all I require is that downloading project with `pom.xml`, clean build, works without installing things beyond core git/maven/jdk. But instructions so far have suggested one must install some sort of plugin/jar with jdk, which is a non-starter for me.

**Comment by cowwoc** [comment]
@cowtowncoder Thanks for the investigation. Upon digging further I discovered https://github.com/rzwitserloot/lombok/issues/1249 so I believe this is purely a Lombok bug. Sorry for the false alarm.

**Comment by cowtowncoder** [comment]
@cowwoc Thank you for the update -- I hope it helps others who may hit the same issue.
