### ISSUE TITLE
`PropertyNamingStrategy` is not symmetry. e.g. SNAKE_CASE

### ISSUE THREAD

**Issue by andyzhuangyy** [FasterXML/jackson-databind#1630]
PropertyNamingStrategy is not symmetry. e.g. SNAKE_CASE

when I use PropertyNamingStrategy.SNAKE_CASE as propertyNamingStrategy, 
when serialize, all field name such as

```
class Test {
    protected String userId;
    private String requestId;
}
```

convert to  

`
{
"user_id": 123,
"request_id":123
}
`

BUT, when I deserialize the json 

`
{
"user_id": 123,
"request_id":123
}
`

to class Test. the field name user_id and request_id are not been recognized.

**Comment by cowtowncoder** [comment]
@andyzhuangyy Instead of trying to explain the problem, please include failing unit test: no "see what output is", but actual specific assertion. As far as I can see, input and class you give above should work fine, so I need to know what exactly is failing, and with what specific calls. I can not reproduce this problem otherwise.

Also please include Jackson version used: it should be the latest patch version of minor version you are using (for example, instead of reporting against, say `2.8.1`, verify against `2.8.8`).

**Comment by cowtowncoder** [comment]
Can not reproduced, closing. May be reopened with full test case to show exactly what is not working as expected.
