### ISSUE TITLE
custom root element name for wrapped collections

### ISSUE THREAD

**Issue by cghislai** [FasterXML/jackson-databind#1636]
I would like to provide a custom rootName for a wrapped `Collection<T>`, and having that name depend on the type of T (with the WRAP_ROOT_VALUE feature enabled)

Previously, on a Glassfish3/Jersey1/Jackson1 stack without much customization, a webservice returning a list of jaxb-annotated POJOs would wrap the the JSON array into an object property named with the XmlRootElement name of the annotated POJO:
```
@XmlRootElement(name="MyElementName")
public class MyElement implements Serializable {
   
    @XmlElement
     private String value;
// getter/setter
}
```
Then a List<MyElement> would be serialized as:
`{"MyElementName":[{"value":"test"}]}`

Using jackson 2 (with resteasy on wildfly10, but as well using the ObjectMapper directly), the collection class name is used for the root property:
`{"ArrayList":[{"value":"test"}]}`

To mimick to previous behaviour, and without replacing all the ws return values with wrapper classes, I would like to have access to the generic type information in a custom `AnnotationIntrospector#findRootName` method implementation. 

This type information is not present in the `AnnotatedType` argument, as it seems `com.fasterxml.jackson.databind.util.RootNameLookup#findRootName(com.fasterxml.jackson.databind.JavaType, com.fasterxml.jackson.databind.cfg.MapperConfig<?>)` calls `com.fasterxml.jackson.databind.JavaType#getRawClass`, which results in the loss of the generic type information.

Am I missing something obvious or is this expected behaviour?
Thanks,

Charly

**Comment by cowtowncoder** [comment]
To be honest, I don't think adding such a feature is a good idea. I recommend against ever using generic / polymorphic type as a root value since it is usually problematic due to multiple reasons: one of those being that frameworks tend not to pass enough information to reliably resolve generic types.

As to why non-generic type is passed: this is mostly because annotations are attached to classes, not to generic types: that is, for annotation lookup, resolved type is not needed or useful: annotations can not vary by type parameters (for main type itself, at least). While it may still make sense sometimes to pass `JavaType`, at the time this functionality was added type resolution was not being done early enough. So it is bit of historical leftover: if it was added now `JavaType` would probably be passed.

Given this, I would instead recommend using existing facilities for specifying root name:

1. Use of `@XmlRootElement` should work (with `jackson-module-jaxb-annotations`) -- if not, that might be a bug
2. Jackson's own `@JsonRootName` should similarly work (as long as standard `JacksonAnnotationIntrospector` is used, either along or as part of introspector pair)
3. `ObjectWriter.withRootName(...)` method allows construction of `ObjectWriter` instances with root name override (and similarly for `ObjectReader`). These are not available directly from `ObjectMapper` (since they typically vary call by call, and mapper must be initialized and configured fully before use).

**Comment by cghislai** [comment]
Thanks we will go with wrapping the list in another @XmlRootElement-annotated POJO.
Just out of curiosity, do you see any issue with generic types if I serialize an HashMap<String, List<Pojo>> as `{"key": [{/**pojo properties**/}]` or a List<Pojo> as `[{/** pojo properties**/}]` (root array unwrapped). For the later case, Ive never seen any issue with different frameworks, although it is a generic root element.
Thanks,

Charly
