### ISSUE TITLE
`@JsonAnyGetter` uses different `bean` parameter in `SimpleBeanPropertyFilter`

### ISSUE THREAD

**Issue by georgeflugq** [FasterXML/jackson-databind#1655]
Tried this out on 2.8.5, 2.8.8 and 2.9.0pr3

When extending SimpleBeanPropertyFilter to make a custom filter, the first parameter "Object pojo" of serializeAsField() contains the parent Object of the field in question.

However, when the field is a dynamic field using the @JsonAnyGetter annotation, the pojo parameter contains the field value itself instead of its parent object.

I expected the pojo parameter to contain the same value regardless of whether the field is explicit or dynamic.

As a result, I am not able to filter fields based on the parent object. I can only use the field's name which is not enough information.

Here's an example:
```
public class Main {
	public static void main(String[] args) throws Exception {
		ObjectMapper mapper = new ObjectMapper();
		FilterProvider filters = new SimpleFilterProvider().addFilter("CustomFilter", new CustomFilter());
		String serialized = mapper.writer(filters).writeValueAsString(new OuterObject());
		System.out.println(serialized);
	}
}

@JsonFilter("CustomFilter")
class OuterObject {
	public String getExplicitProperty() {
		return "I will serialize";
	}

	@JsonAnyGetter
	public Map<String, Object> getAny() {
		Map<String, Object> extra = new HashMap<>();
		extra.put("dynamicProperty", "I will not serialize");
		return extra;
	}
}

class CustomFilter extends SimpleBeanPropertyFilter {
	private static final boolean serializeAllFields = false;
	@Override
	public void serializeAsField (Object pojo, JsonGenerator jgen, SerializerProvider provider, PropertyWriter writer) throws Exception {
		if (serializeAllFields || pojo instanceof OuterObject) {
			writer.serializeAsField(pojo, jgen, provider);
		}
	}
}
```
In the example, "dynamicProperty" will not serialize unless I set serializeAllFields to True because pojo equals "I will not serialize" instead of the OuterObject instance.

**Comment by cowtowncoder** [comment]
That does sound wrong, thank you for reporting it.

**Comment by cowtowncoder** [comment]
Hmmh. Crap. This is... not easy to resolve.
The problem is that the way any-getter filtering works is rather convoluted: `Map` accessed using any-getter is passed to `MapSerializer`, and logically enclosing POJO is not passed at all.
Passing `Map` that contains property would be relatively easy, but that wouldn't be much more useful than value (although slightly more correct in a way).

I may be able to fix this, but it can not go in patch version, so 2.9.0 would be the first version with fix.

**Comment by cowtowncoder** [comment]
Ok: with a bit of work, addition of method in `MapSerializer` and fixing of an existing test, things now work as expected.

I hope this won't end up causing issues to users since while I agree that behavior was incorrect, someone somewhere might be relying on first argument being value to serialize for Maps in general, or any properties in this specific case.
