### ISSUE TITLE
Get annotation from field that is being serialized using Custom Serializer

### ISSUE THREAD

**Issue by cunhazera** [FasterXML/jackson-databind#1691]
I'm currently using the version 2.7.4 and I wanted to know if I can access the annotation of the field that is beging serialized, at runtime.

**Comment by cowtowncoder** [comment]
@cunhazera Access to fields is available during contextualization: serializer must implement `ContextualSerializer`, gets call to `createContextual()`, and can access property annotations (as well as annotations from surrounding class). This is called during construction of serializer, and not during serialization itself (or rather, only once when construction triggered by need to serialize for the first time); information is static and can't change. But it needs to be stored by serializer itself: typically a new instance needs to be constructed (since differently configured instances may be needed for different properties).

**Comment by cunhazera** [comment]
@cowtowncoder thanks for the response!
