### ISSUE TITLE
Property annotated with JsonProperty serialized twice under some conditions

### ISSUE THREAD

**Issue by mcdiae** [FasterXML/jackson-databind#1701]
Reproduced in versions:

- 2.5.3
- 2.8.9
- 2.9.0.pr4

The test `brokenBeanShouldSerialize()` fails as the single property becomes the JSON `{"atoz":null,"aToZ":null}`.

```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;

public class A2ZTest {

  @Test
  public void okBeanShouldSerialize() throws IOException {
    String json = new ObjectMapper().writeValueAsString(new OkBean());
    Assert.assertEquals("{\"aToZ\":null}", json);
  }

  @Test
  public void brokenBeanShouldSerialize() throws IOException {
    String json = new ObjectMapper().writeValueAsString(new BrokenBean());
    Assert.assertEquals("{\"aToZ\":null}", json);
  }

  public static class OkBean {
    @JsonProperty("aToZ") private String foo;

    public String getFoo() { return foo; }

    public void setFoo(final String foo) { this.foo = foo; }
  }

  public static class BrokenBean {
    @JsonProperty("aToZ") private String aToz;

    public String getAToz() { return aToz; }

    public void setAToz(final String aToz) { this.aToz = aToz; }
  }
}
```

Java 1.8.0_131 on Mac.

**Comment by cowtowncoder** [comment]
I think this may actually works as expected (if not as desired), because:

1. Property names in JSON and Java are case-sensitive (no attempts made to canonicalize)
2. Whereas for `OkBean` merging of accessors starts with logical name of `foo`, and succeeds, logical name from `getAToz` becomes `atoz`, which does not match field name `aToz` (which is not mangled, unlike getters and setters)

I think what may be needed here (depending on what name you would want in JSON) is second annotation, to reconcile naming.

**Comment by mcdiae** [comment]
Makes sense. Thanks for looking at this.
