### ISSUE TITLE
parse and use as immutable

### ISSUE THREAD

**Issue by neopaf** [FasterXML/jackson-databind#1712]
We want to use JsonNode and everything inside immutably.
We want to know for certain that code would not mutate any of it.

Saw some discussion in #85 about overriding...
com.fasterxml.jackson.databind.node.JsonNodeFactory#objectNode

...but not sure how exactly to go about.
Any suggestions?

**Comment by cowtowncoder** [comment]
There were lengthy discussions, back and forth, but realistically I don't think this is doable in general with `JsonNode`. Plan so far has been to try to make `TreeNode` useful enough that alternate models could be defined and used by users, to use instead of `JsonNode` (i.e. `JsonNode` would be but one of many implementations).

The main problem is that although it is quite possible to define a node hierarchy that is immutable:

1. It is not really (IMO) possible to create general-purposes hierarchy one that also allows backwards compatibility
2. Immutable implementation is great for some use cases (typically read, never modify; or, build once, don't change), but really cumbersome for others (where actual mutability is required)
3. Although some time was spent on figuring out how sub-classing could be used to allow extension, this may not work well for cases other than perhaps adding a field or two in specific sub-classes.

and this is assuming that immutability should be real immutability, not a flag that just prevents changes (which I think is clumsy to implement and not necessarily thread-safe).

However: instead of (1), you may be able to specify hierarchy that is specific to your needs.
If you, `JsonNodeFactory` was indeed envisaged as the way to do it. You would create sub-classes for mutable types (`ObjectNode`, `ArrayNode`), and override methods that would allow mutability.

Or, if you have full control over creation (... and won't give access to `ObjectMapper`), just simple sub-classing could work too. It all depends on details of use case.

**Comment by neopaf** [comment]
thanks for the insight, Tatu.
