### ISSUE TITLE
Make @JsonSubTypes optional

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#1715]
```
@JsonTypeInfo( use = JsonTypeInfo.Id.NAME,  include = JsonTypeInfo.As.PROPERTY, property = "type")
public abstract class Animal {
    private String sound;
    private String type;

    public String getSound() {
        return sound;
    }

    public void setSound(String sound) {
        this.sound = sound;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}

@JsonTypeName("dog")
public class Dog extends Animal {
}

@JsonTypeName("elephant")
public class Elephant extends Animal {
}
```

By default no need to specify `@JsonSubTypes`
But if `@JsonSubTypes` is present use enumerated sub types.

**Comment by cowtowncoder** [comment]
I don't understand what you are asking. What is not possible now, and how? What is the exception, or problem?

**Comment by raderio** [comment]
When I try to deserialize json
```
{
  "sound": "auh",
  "type": "dog"
}
```
I get exception 
`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'dog' into a subtype of [simple type, class frontend.payload.request.Animal]: known type ids = [Animal]`

But if I add `@JsonSubType`
```
@JsonTypeInfo( use = JsonTypeInfo.Id.NAME,  include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({@JsonSubTypes.Type(Dog.class), @JsonSubTypes.Type(Elephant.class)})
public abstract class Animal {
    private String sound;
    private String type;

    public String getSound() {
        return sound;
    }

    public void setSound(String sound) {
        this.sound = sound;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
```

this will work, so I propose by default to scan class children and add them as subtypes without annotation

**Comment by cowtowncoder** [comment]
@raderio Thank you for clarification.

Now, the way I see it, class scanning is a big source of nasty problems, complexity and security issues, so I do not want to add it directly in Jackson core components. I realize that it is a feature many users like so it is not unreasonable to suggest; however, as a project maintainer my perspective is bit different.

But if anyone wants to work on an add-on module that does such thing through existing extensions, that sounds like a good idea. Since `ObjectMapper` allows registration of subtype mappings by modules, and `AnnotationIntrospector` likewise (despite name source of information need not be annotations -- any source is fine), this should be doable.

Perhaps you could re-file this at:

https://github.com/FasterXML/jackson-future-ideas/issues

since I think that would be a better place for possible future extensions?

**Comment by raderio** [comment]
Ok, thanks.

https://github.com/FasterXML/jackson-future-ideas/issues/18
