### ISSUE TITLE
Jackson serialization

### ISSUE THREAD

**Issue by marakogr** [FasterXML/jackson-databind#1728]
Hello everyone! I have a problem with serialization via Jackson.
When i do JsonNode smth = readValueToTree(obj) I get information about class type (e.g.  java.Math.BigInteger, java.lang.ArrayList). This problem pop up for entities contains Map<String, Object> without any serializer. Also in entity which is not full filled. E.g. I have class ContactMethod which contains several fields. If all information is present then problem goes away. But if filled only one field with id (type bigInteger) then i catch class type info:
Expected:

```
"contactMethods": [
"@type": "PhoneNumber",
"id": "9148293419813662646",
```

Actual:

```
"contactMethods": ["java.util.ArrayList", 
"@type": "PhoneNumber",
"id": "9148293419813662646"
```

Another example (with map serialization):
My class have chars (Map<String, Object>). Expected, that when I'll serialize it I'll get:

    "chars": { "char": [ 1 ] },

but actual I get:

    "chars": {"char": ["java.math.BigInteger", 1]}

Anyone knows why it happens? Thanks

**Comment by cowtowncoder** [comment]
Issue tracker is not a discussion forum; please use mailing list:

https://groups.google.com/forum/#!pendingmsg/jackson-user

for usage questions.

From symptoms it looks like you have enabled "default typing" (there are multiple methods in `ObjectMapper` to do that), which forces inclusion of type information similar to what happens when you use `@JsonTypeInfo` annotation.
You will want to disable this setting, or use explicit `@JsonTypeInfo(use = Id.NONE)` to disable polymorphic handling for specific field(s).

**Comment by marakogr** [comment]
@cowtowncoder Yes, I have enablem "default typing" and @JsonTypeInfo(use = Id.CLASS), I need it in the other reasons) but this problem appears strangely)
![problem](https://user-images.githubusercontent.com/28134009/29212746-d60eba78-7ea8-11e7-89a7-82b80a52c436.PNG)
Birthday and contactMethods are located under contacts.
But if contactMethods is located in the first level like contacts - all is ok
![problem2](https://user-images.githubusercontent.com/28134009/29212885-754bf9ac-7ea9-11e7-9f7d-954706b27fba.PNG)
Could you pls look at this again?)
