### ISSUE TITLE
JsonFormat invalid date value

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#1746]
```
@JsonFormat(pattern = "yyyy-MM-dd", shape = JsonFormat.Shape.STRING, lenient = OptBoolean.FALSE)
Date birthday;
```
For value "2000-11-123" throws `InvalidFormatException`, which is expected, and for value "2000-02-31" throws `InvalidFormatException`, but format is ok, the value is not valid.
Is it possible to throw another exception for better error description?
Thanks.

version: 2.9.0

**Comment by cowtowncoder** [comment]
`InvalidFormatException` means that formatting of the value is incompatible; not that format specification was faulty. As per javadocs:

```
 Specialized sub-class of {@link MismatchedInputException}

 * that is used when the underlying problem appears to be that
 * of bad formatting of a value to deserialize.
```

Now, although it is possible that naming of the class could be improved, this type has been used since Jackson 2.1 so renaming would probably cause more problems than value of improved naming.

**Comment by raderio** [comment]
You can make a subclass

**Comment by cowtowncoder** [comment]
@raderio That would be technically possible yes. But I am not sure of benefits from semantics perspective: subtype would follow "is-a".
