### ISSUE TITLE
StdDateFormat: performance improvement of '_parseAsISO8601(...)'

### ISSUE THREAD

**Issue by brenuart** [FasterXML/jackson-databind#1754]
Following the same rational as in https://github.com/FasterXML/jackson-databind/issues/1749, the calendar instance used during parsing in `parseAsISO8601(...)` could be reused across invocations.

What you think ?

**Comment by cowtowncoder** [comment]
I think that might be a good idea. Looking at deserialization side I think `DateFormat` is actually cloned as well (first I thought it wasn't, but `DeserializationContext.getDateFormat()` does actually clone it), so reuse should be possible.
Still, I am almost tempted to attempt writing multi-threaded test just in case ... since failures wrt non-synchronized shared resources can be pretty nasty.

But there's bit of choreography still, wrt ensuring correct timezone and leniency settings are used (and perhaps `Locale` -- not 100% if it has any effect, but it is set on `GregorianCalendar`).

So, +1 for this.
