### ISSUE TITLE
LongNode(3) != IntNode(3)

### ISSUE THREAD

**Issue by larsga** [FasterXML/jackson-databind#1758]
The `equals` method for `IntNode` is implemented so that only `IntNode`s can be equal to other `IntNode`s, regardless of numeric value. This is obvious with just a glance at [the source code](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/node/IntNode.java#L121).

I can do a PR to fix this, but just want to confirm that this isn't so by design first.

**Comment by cowtowncoder** [comment]
I appreciate your reaching out first: makes sense.

This is by design, wrt default behavior. Users are encouraged to use

       public boolean equals(Comparator<JsonNode> comparator, JsonNode other);

method with suitable `Comparator` implementation for customizing equality logic to their liking.

The reason here is simply that attempting to support various kinds of coercion (`DoubleNode`, `FloatNode` too, presumably; `BigIntegerNode`, `BigDecimalNode`) leads to unmaintanable system.
So although I agree in that it is not unreasonable to expect equality here, I am not interested in following this trail down the likely rat hole.

**Comment by larsga** [comment]
Ok. I already have a workaround for my use case (testing, so I just serialize and then reparse the JSON before comparing expected output with real output), so I will not pursue this further. Thank you for making the project's standpoint clear.

**Comment by cowtowncoder** [comment]
Thank you for your offer as well. I'll have to see if this could be somehow documented, too, since it is probably a FAQ.

**Comment by grimsa** [comment]
If anyone stumbles here, know that there is also [`JsonNumEquals` utility](https://github.com/java-json-tools/jackson-coreutils/blob/master/src/main/java/com/github/fge/jackson/JsonNumEquals.java)  in `com.github.java-json-tools:jackson-coreutils` providing numerical equivalence

**Comment by cowtowncoder** [comment]
@grimsa Thank you for sharing this!

I wonder if there was some benefit to adding a configurable (Builder based) JsonNodeComparator on Jackson 2.11 or later? (possibly 3.0, to allow Java 8 method pointers)
