### ISSUE TITLE
`StdDateFormat`: serialize time offset using colon

### ISSUE THREAD

**Issue by challarao** [FasterXML/jackson-databind#1762]
I think it also applies to zone provided that the zone is a 4 or 6 digit offset.

> Either basic or extended formats may be used, but both date and time must use the same format. The date expression may be calendar, week, or ordinal, and must use a complete representation. The time may be represented using a specified reduced accuracy format.[8] It is permitted to omit the 'T' character by mutual agreement.[21]

https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

**Comment by cowtowncoder** [comment]
Note: this is manifestation of https://github.com/FasterXML/jackson3-dev/issues/7 for Jackson 3.x.
For Jackson 2.x, users need to consider #1744 since we can not safely change defaults (based on past experience, seemingly small defaults changes tend to break some users somewhere).

So: change here is change of `StdDateFormat` to generate ISO-8601 representation, if no override specified, that does include colon separating hours and minutes in time offset.
