### ISSUE TITLE
Cannot register custom deserializer for (abstract) base classes

### ISSUE THREAD

**Issue by bwaldvogel** [FasterXML/jackson-databind#1784]
Imagine we have a common base class `BaseClass` with many subclasses.
Example:

```java
class BaseClass {
    // …
}

class Class1 extends BaseClass {
    // …
}

class Class2 extends BaseClass {
    // …
}
```

One can register a serializer for all classes that extend `BaseClass` with:
```java
simpleModule.addSerializer(BaseClass.class, new MySerializer());
```

However, the same doesn’t work for a **deserializer**:
```java
simpleModule.addDeserializer(BaseClass.class, new MyDeserializer());
```

An obvious workaround would be to register the deserializer for all known subclasses.
However, in my use case there are hundreds of classes that extend `BaseClass`.
The classes cannot be annotated or manipulated in any way since they belong to a 3rd party library.

**Comment by cowtowncoder** [comment]
@bwaldvogel This is intentional, as in general assuming that all subtypes should use parent type deserializer is unsafe. This is different from serializers.

But note that this is `Simple` module: you can easily implement your own module that will follow different rules, registering more advanced `Deserializers` (callback that is given a chance to provide actual deserializer for specific type, using whatever logic it wants).
The reason why I don't think it is a good idea to try to make this work with `SimpleModule` (and its `SimpleDeserializers` handler) is that it gets quite complicated to try to design good API to handle potentially complicated matching rules.
So it is not because this use case wouldn't be valid (it may even be relatively common), but that I am not convinced it can be exposed in intuitive and useful way.
I am open to be convinced of a good way to do that of course -- just not convinced yet.

**Comment by bwaldvogel** [comment]
@cowtowncoder: Thanks for your quick answer and the detailed explanation.

Switching from `SimpleModule` to a "normal" module did help, thanks.

I understand that designing a good API in this case could be tricky. On the other hand I’m wondering if deserialization really needs to fail with `JsonMappingException: Can not instantiate value of type …` if there is a deserializer for the base class.
So maybe it would be possible to search for deserializers of a base class if no other deserializer could be found?

**Comment by cowtowncoder** [comment]
@bwaldvogel I am not big fan of heuristics that could work but also could blow up in other ways.
Deserializing using a basetype deserializer can produce assingment-incompatible results; or, in case deserializer was provided by some other module altogether, fail in even more mysterious way.
And since there may be multiple base-types (interfaces implemented, as one can register those as well -- is done for `Collection`s etc), whole traversal of hierarchy gets unwieldy quickly as well.

So while I can see why it'd be nice if library tried to figure out working approach I do not see a simple reliable mechanism to do so here.

**Comment by bwaldvogel** [comment]
Ok, you made valid points.

I’m closing this issue since it can be solved by using a normal module.

**Comment by cowtowncoder** [comment]
@mariofusco Yes, that is possible, just not with `SimpleSerializers` construct: instead, implement specific callback of base interface `Seserializers` to match exact type.

**Comment by mariofusco** [comment]
@cowtowncoder sorry, I'm not fully understanding what you're suggesting. Do you have any practical example or point me to a test case doing this?

**Comment by mariofusco** [comment]
@cowtowncoder ok, I think I see (more or less). Another strategy I was tempted to use (since I know the subclass that I want to be serialized with the standard serializer) is registering a default (reflection-based) serializer for the subclass, but I don't see how to create or obtain it programmatically. What do you think?

**Comment by mariofusco** [comment]
> I hope this helps.

Ok, got it now. Thanks a lot.
