### ISSUE TITLE
Setting WRITE_DATES_AS_TIMESTAMPS to false leads to millisecond trailing zeroes being removed

### ISSUE THREAD

**Issue by chriswilty** [FasterXML/jackson-databind#1798]
When I use ObjectMapper to write a Java 8 LocalDateTime with milliseconds as a string, I can get a different result depending on whether I configure WRITE_DATES_AS_TIMESTAMPS as false, or register a module with a ToStringSerializer for LocalDateTime. Specifically, in the former case, trailing zeroes on the output string (the millliseconds part) are stripped off, but not in the latter case.

According to the docs, they should behave the same for a date-time with milliseconds, as both StdDateFormat and LocalDateTime.toString() use ISO-8601 formats.

Both these tests should pass:

```
// This passes
@Test
public void registerModuleWithToStringSerializer() throws JsonProcessingException {
    testLocalDateTimeSerialization(
        new ObjectMapper()
            .registerModule(
                new SimpleModule().addSerializer(new ToStringSerializer(LocalDateTime.class))
            )
    );
}

// This fails:
// Expected :\"2017-10-17T12:00:00.100\"
// Actual   :\"2017-10-17T12:00:00.1\"
@Test
public void writeDatesAsTimestamps() throws JsonProcessingException {
    testLocalDateTimeSerialization(
        new ObjectMapper()
            .findAndRegisterModules()
            .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
    );
}

private void testLocalDateTimeSerialization(final ObjectMapper mapper) throws JsonProcessingException {
    final LocalDateTime value = LocalDateTime.of(2017,10,17,12,0,0,100000000);
    final String result = mapper.writeValueAsString(value);
    assertThat(result, is("\"2017-10-17T12:00:00.100\""));
}
```

Note that using the `@JsonSerialize(using = ToStringSerializer.class)` annotation on a field also works correctly, preserving trailing zeroes.

We are using
jackson-core 2.8.9
jackson-databind 2.8.9
jackson-datatype-jsr310 2.8.9

**Comment by cowtowncoder** [comment]
Ok, this would really belong under

https://github.com/FasterXML/jackson-modules-java8/issues

since it's about Java8 date/time types.
But I'll add quick notes here.

I don't think this is necessarily a bug as `ToStringSerializer` simply calls `toString()` on value, and serialization of Java 8 date/time types is not specified to use that, or to produce same serialization. It might be good if this was the case, but that is not a design goal per se.

Second, ISO-8601 specification allows a very wide range of possible representations, and I think fractional seconds may use almost any number of digits; while 3 is the most common (for milliseconds), less is legal (but at least 1, if fraction is indicated by period), and more than 3 as well. So I think both representations are valid and represent same value.

That being said difference is not intentional. I don't know why this occurs (I did not write serializers) but I suspect JDK functionality being used uses different heuristics.

If the goal here would be to be able to force serialization to always use 3 fraction digits, for milliseconds, that could be considered an RFE.

**Comment by chriswilty** [comment]
Thanks for the reply; I'll post the issue into jackson-modules-java8 instead. My main gripe is that the documentation is misleading! Consistency in behaviour would be a bonus.

**Comment by chriswilty** [comment]
In fact, the documentation for [StdDateFormat](http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/util/StdDateFormat.html) is incorrect. It states

> For serialization defaults to using an ISO-8601 compliant format (format String "yyyy-MM-dd'T'HH:mm:ss.SSSZ")

but if that were true, the SSS part would lead to preservation of all three millisecond digits.

**Comment by cowtowncoder** [comment]
@chriswilty  `StdDateFormat` has nothing to do with Java 8 date/time.  It is simply an internal implementation to use with `java.util.Date` /  `java.util.Calendar`. It is never used in any shape or form with `LocalDateTime`: this class, as part of Java 8, is not processed using `DateFormat` at all.

Now: I agree in that configuration should indicate what applies where; and so the fact that `DateFormat` is irrelevant with Java 8 should be disclosed. And other settings like "serialize as timestamps" should work as expected.

This is not exactly related to the issue reported here which is probably related to Java 8 date/time handling that tries to be clever and remove trailing zeroes (or not).

**Comment by cowtowncoder** [comment]
Since related to Java 8 date/time functionality, needs to be (re)filed for `jackson-modules-java8`, if still occuring.
