### ISSUE TITLE
Make `JsonNode` serializable?

### ISSUE THREAD

**Issue by jakajancar** [FasterXML/jackson-databind#18]
Would it be possible to make JsonNode `java.io.Serializable`?

**Comment by JWGmeligMeyling** [comment]
I'd love to see this feature and would be willing to pick it up.

From this thread there seem to be two options:

- Implement it as `java.io.Serializable`, mark the `JsonNodeFactory` as `transient`, and possibly define a `readObject` that instantiates this   `JsonNodeFactory` with a default instance.
- Implement it as `java.io.Externalizable`, using the JSON representation as data.  Use a default JsonNodeFactory here as well?

I have two questions:
1) Does `JsonNode` still depend on the `JsonNodeFactory` in the current situation?
2) Wouldn't it be an option to serialize the `JsonNodeFactory` with the `JsonNode`?


BTW, I think commit 92223fe is wrongly pointed to this issue #18 , perhaps it references an issue from core?

**Comment by cowtowncoder** [comment]
@JWGmeligMeyling ok. Just a quick question: what is the use case you are thinking of?

On implementation itself: this would be a bit easier with Jackson 3.0 because of #2176.
That would solve a few issues... 

But if you really want to work on this for 2.10, I am ok with it. I'd probably just go with throw-away `JsonFactory`, if possible; otherwise code must create default `ObjectMapper` and that's guaranteed to make this rather wasteful operation.

**Comment by JWGmeligMeyling** [comment]
My JPA entities need to be serializable in order for my EntityManager to passivate into a stateful session bean. Some of my entities map a JsonNode from JSONB columns, if the data type foe the JSON input is not fixed for that entity. Now I’m required to implement custom serialization for all entity classes that reference such a JsonNode. Even more tedious is that I cant call defaultSerialization in my custom serializer, because transient fields will always be ignored by JPA and there is apparently no way to work around that. So for JPA entities that means you have to manually searialize/deserialize every field which is tedious and error prone. So Id rather make JsonNode serializable in one way or another :)

**Comment by demetrio812** [comment]
Hello, same problem for me, I'm trying to use EhCache with some Entities containing JsonNode and it's not working because of this issue

**Comment by cowtowncoder** [comment]
Actually. Now with 2.10 and #2187 I wonder... 

There would be some limitations, of course:

1. Only `json` would be supported as serialization format (but it's JDK serialization so no one sees it anyway)
2. On deserialization, no configuration of `JsonNode` (via custom `JsonNodeFactory`, or, in future, with `NodeConfig` or such) could be applied; you would get stock vanilla `JsonNode` back
3. `POJONode` would probably lose its identity (although maybe not...)

So... I'll re-consider this issue.

**Comment by demetrio812** [comment]
Hello @cowtowncoder thanks for reconsidering, I think the limitations are fine and understandable but this basic support will help a lot for use cases like the caching one.

Thanks,
Dem
