### ISSUE TITLE
2.9.2 favors valueOf(…) over String constructor

### ISSUE THREAD

**Issue by odrotbohm** [FasterXML/jackson-databind#1810]
In Spring HATEOAS we have a class `Link` that exposes both a constructor taking a `String` as well as a `valueOf(…)` method taking a String. The latter is used to parse RFC5988 link headers.

Jackson versions up to 2.9.1 invoked the constructor from a `StdValueInstantiator.createFromString(…)`. As of version 2.9.2, the `_fromStringCreator` rather points to the `Link.valueOf(…)` method that now fails as the value handed into it is of course no RFC5988-compliant value.

Steps to reproduce:

1. `git clone https://github.com/spring-projects/spring-hateoas`
2. `cd spring-hateoas`
3. `git co 663-jackson-292`
4. `mvn clean test`

In particular, `TypeReferencesIntegrationTest` fails.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, that is unintentional change then. Could be due to refactorings, and apparently preference is either untested, or somehow test was not affected....

I'll try to check out this problem soon: there are a few issues to fix in `2.9.3` so I think this should get in as well, and release probably out sometime in November.

**Comment by olivergierke** [comment]
Thanks, Tatu! I guess we're gonna put some configuration in place to explicitly use the constructor in the meantime.

**Comment by cowtowncoder** [comment]
@olivergierke Yeah might make sense. Apologies for this breakage, as I said isn't intentional. There are fixes resulting from rewrite so it's not just cosmetic, which is obviously also why there was a chance of regression,....

I think explicit `@JsonCreator` should do the trick.

**Comment by cowtowncoder** [comment]
@olivergierke I can clone the project but I think I am missing snapshot dependencies. But I can see `Link` class so that should be enough. Although I am bit suspicious of use of Lombok there, have had some problems with any code that uses that.... but I assume it's not relevant here. Will let you know if I have any trouble.

**Comment by cowtowncoder** [comment]
Hmmh. Odd. I can not actually reproduce this with simplified representation of both public single-String constructor and `valueOf(String)`: constructor is chosen over factory method.
So I think I may need some help with test case after all.

**Comment by cowtowncoder** [comment]
Ok this is odd. Use of Lombok makes it bit difficult to make 100% sure what exactly is happening (since it adds constructors and getters, setters, based on annotations); and there are also mix-ins involved. But despite my best efforts to replicate these (by manually adding what I think Lombok adds) I simply can not reproduce the problem with 2.9 branch (or even with 2.9.2 tag).
No matter what I do, constructor gets preferentially called, unless I use `@JsonCreator` on `valueOf()` method.

So I could really use a simplified test, if possible. If not, we can just leave this open to see if anyone else can provide something trimmed down.

Regardless, I think it's a good idea to add annotation on constructor to take, to remove any conceptual ambiguity (explicit annotation trumps over implicit discovery).

**Comment by cowtowncoder** [comment]
@olivergierke Unfortunately I can not reproduce this problem at this point without external dependencies so I think I am bit stuck. I hope work-around you have (wrt explicit creator annotation) works.

**Comment by sumit4code** [comment]
Using jackson version 2.9.5, still getting the issue.
(although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value

**Comment by cowtowncoder** [comment]
Version `2.9.6` just released last night, and has two fixes in related areas. So while no guarantee there's a fix, may want to quickly check.

**Comment by cowtowncoder** [comment]
@sumit4code Do you still have means to reproduce the problem? `2.9.6` is out with a few fixes in areas of creators, and `2.9` branch has further fixes for 2.9.7. But I do not have a reproduction myself to verify this unfortunately.

**Comment by olivergierke** [comment]
I've just upgraded the feature branch I originally created to show the problem to 2.9.6 and the issue persists. Spring HATEOAS master is not affected anymore as we've changed the serialization setup for the offending class.

**Comment by cowtowncoder** [comment]
@sumit4code Could you share your reproduction? As I mentioned, I haven't been able to reproduce this so something I tried differs from what you have (and Spring HATEOAS had).

@olivergierke thank you for verifying. Still hoping to figure this out for 2.9.7, which has plenty fixes of its own (although not in this area I think)

**Comment by cowtowncoder** [comment]
Will need a new reproduction, with no additional external dependencies (in case of Lombok, need post-processed definitions). May be reopened with repro (or re-filed).
