### ISSUE TITLE
Ability to whitelist properties for deserialization

### ISSUE THREAD

**Issue by stevebread** [FasterXML/jackson-databind#184]
It is possible to whitelist properties for serialization using a FIlterProvider. Whitelisting is more secure than blacklisting and a similar approach should be available for deserialization.

**Comment by cowtowncoder** [comment]
I think this might be covered by #1296, if and when that gets implemented. Mechanism would be different. However, since filters are not used for deserialization, I think I'll close this in favor of the annotation based variant, since adding support for filters for deserialization is not likely to be implemented in near term.
