### ISSUE TITLE
Generic type info lost when using non-default map implementation with no generic parameters (2.9.2)

### ISSUE THREAD

**Issue by taravkov** [FasterXML/jackson-databind#1841]
When using non-default map implementation with no generic parameters, generic type info is lost.
Non-default map implementation used has no generic parameters (see example below).

Jackson version: 2.9.2
Worked until: 2.6.7

This is the test code to reproduce the issue:

    @Test
    public void testDefaultMapImplementation() throws IOException {
        final String json = "{\"map\": {\"key\": [{\"map\": {}}]}}";
        final ObjectMapper mapper = new ObjectMapper();
        final TestClass result = mapper.readValue(json, TestClass.class);
        assertNotNull(result);
        assertNotNull(result.getMap());
        assertTrue(result.getMap().get("key").get(0) instanceof TestClass); // generic info OK
    }

    @Test
    public void testCustomMapImplementation() throws IOException {
        final String json = "{\"map\": {\"key\": [{\"map\": {}}]}}";
        final ObjectMapper mapper = new ObjectMapper();
        final SimpleModule module = new SimpleModule();
        module.addAbstractTypeMapping(Map.class, CustomMap.class);
        mapper.registerModules(module);
        final TestClass result = mapper.readValue(json, TestClass.class);
        assertNotNull(result);
        assertNotNull(result.getMap());
        assertTrue(result.getMap().get("key").get(0) instanceof TestClass); // generic info not OK
    }

    private static class TestClass {
        private Map<String, List<TestClass>> map;

        public Map<String, List<TestClass>> getMap() {
            return map;
        }

        public void setMap(Map<String, List<TestClass>> map) {
            this.map = map;
        }
    }

    private static class CustomMap extends LinkedHashMap<String, Object> {
    }

Expected and actual results:

Expected:
![expected](https://user-images.githubusercontent.com/8693840/33278616-24729168-d3ad-11e7-8694-7f5da53cf7c1.png)

Actual:
![actual](https://user-images.githubusercontent.com/8693840/33278806-bf996b8a-d3ad-11e7-8431-9256f0775bd2.png)

When changed to
`private static class CustomMap<K, V> extends LinkedHashMap<K, V> {
    }`
everything works fine.

**Comment by cowtowncoder** [comment]
Looking at types involved, I am not quite sure it should work: type assignments do not match.
Use of type variables in

    class CustomMap<K, V> extends LinkedHashMap<K, V> { }

makes sense, because this allows variables to be bound by specialization via abstract type mapping.
But same is not the case when attempting to extend type in multiple dimensions (`Map` to `CustomMap` but also its value type parameter -- and in sort of "wrong" direction, from more specific down to less specific).

So I am not sure if this is something that could or should be changed. Earlier versions did not handle type specialization correctly which allowed some cases to work (by assuming type parameters align and match without verifying). But this was more accidental at least in this case.

**Comment by taravkov** [comment]
Sure enough, thank you for the explanation, sir!
