### ISSUE TITLE
BeanDeserializerModifier called twice - and call needlessly

### ISSUE THREAD

**Issue by deblockt** [FasterXML/jackson-databind#1860]
In my application we use a `BeanDeserializerModifier` to create custom Deserializer and update deserializer of each attributes for entities.

We saw to things : 
- `BeanDeserializerModifier` is called twice on first api call : 
    - the first call is done to check if jackson can deserialize type
    - second is done to create deserializer and deserialize json
- For each api call `BeanDeserializerModifier` is called one time to check if jackson can deserializer type. But the created deserializer is not used to deserialize json.

We found some issues:
   - one in `objectMapper`, map `_rootDeserializers``
   - one in `DeserializerCache`

There are some questions: 
   - Is it mandatory to create Deserializer to check if jackson can deserializer type?
   - Can there be only one cache ?
   - Why method `ObjectMapper.canDeserialize` don't use `_rootDeserializers` map?

This happend using Spring, because on each request Spring call `objectMapper.canDeserialize`.

**Comment by cowtowncoder** [comment]
First of all, method `canDeserialize()` is pretty useless, and will probably be dropped from 3.0.
The only thing it can really do is to try to create a deserializer and see if that succeeds. There is very little value add. So in that sense I would recommend against using it for anything; and if so, not having to worry about how it works.

Now, methods of `BeanDeserializerModifier` are callde each time deserializer blueprint (instance based solely on type, but not on property it is used for) is constructed. This is necessary to let modules modify deserializers. This must be done each and every time deserializer for type is constructed, but not afterwards since instance is cached for reuse.

There are reasons for the specific caching structure as well, but I am not sure how it is relevant for your questions.

Other than that I am not sure what your actual issues are. I find it quite odd, as well, that you make claims like "call needlessly" before knowing what the purpose of the call is. It seems unlikely you would be able to make judgment with your current knowledge.

**Comment by cowtowncoder** [comment]
Not clear what the actual issue is here. Closing.
