### ISSUE TITLE
Allowing JsonNode's xxxValue() functions to throw an exception

### ISSUE THREAD

**Issue by jojenki** [FasterXML/jackson-databind#187]
This should probably start out as a debate for those with a strong opinion. JsonNode has two types of functions for retrieving a value from the current node.
- asXxx(), which has a best-effort strategy for returning a value and falls back to a default when an appropriate conversion cannot be made.
- xxxValue(), which will only attempt to return a suitable value if the current node is appropriate, otherwise, a default will be returned. For example, calling intValue() on a TextNode, even if the value of that TextNode is something like "3", will return its default value of 0.

Should there be a way to override the behavior of xxxValue() so that it would instead throw an exception if the current node were not appropriate? What should the policy be when the coercion would cause data loss, i.e. a DecimalNode with a value of 1.5 has intValue() called on it?

**Comment by coolsuhas** [comment]
Yes, I agree with the description of the problem. We recently uncovered a bug in our system resulting from the default value being returned by intValue(), which is 0, because the JsonNode value was "3" and not 3. And this was after 5 months after upgrading from 1.x to 2.x libraries. Don't know how many such bugs are now lurking in our code due to the confusion over the usage of xxxValue() vs asXXX().

The javadocs for the two methods makes it sound as if, use xxxValue() if you have control over the supplied JSON being parsed. Otherwise, use asXXX() when not sure if receiving number in string or numeric form in the supplied JSON. To me, I would always go for asXXX() to avoid any future hassle. I can't seem to find a reason why I would really need xxxValue() when the forgiving asXXX() exists.

An exception from xxxValue() would have at least alerted us to an error rather than subduing an unwanted behavior.

**Comment by cowtowncoder** [comment]
I am all for documentation improvements. As to why, background is this: originally, only 'xxxValue()' methods existed, and they assumed matching type. Choice of default vs exception seems like an error in hindsight, but I do not remember what the reasoning was. Perhaps it was a compromise, as I know some users strongly dislike exceptions and would rather use "empty" value.

But since need for coercions (from String to number, boolean) is common, 'asXxx()' methods were added as complementary choices. We try to (not always successfully, but try) not change existing behavior or semantics, which is why existing methods behavior was not and has not been changed.

The only practical problem with allowing throwing of exceptions has actually been that it has been difficult (or impossible? I forget) to pass dynamic configuration information to `JsonNode` deserializers.
However -- even if this is still the case, it would be possible to at least define a `MapperFeature`, which could be passed when constructing deserializers.
So I could investigate this approach.

I appreciate all suggestions here, thank you for sending those. Keeping things stable and compatible while still improving behavior and adding features is a challenging balancing act. Thank you for your patience!

**Comment by coolsuhas** [comment]
Thanks for all the work that goes into this.
It might be better if xxxValue methods are deprecated in future versions, as it seems asXXX() methods serve the same purpose and then more (in terms of being forgiving with the types of values being converted).
But thanks for your response. I think I am gonna replace all usages of xxxValue() with asXXX() in our code base.

**Comment by cowtowncoder** [comment]
Yes, deprecation is an option. The only concern I have is if anyone actually wants stricter checks, but then again those can be implemented outside before calling accessors.

And it does make sense to upgrade to `asXxx()` methods I think. I use those exclusively as well.

**Comment by coolsuhas** [comment]
Thanks for the confirmation.

**Comment by cowtowncoder** [comment]
No progress here, but with the discussion on possible Jackson 3.0, it would perhaps be possible to tackle this for 3.0 in medium-term future (we are now working on 2.9, to be released around January 2017).

**Comment by cowtowncoder** [comment]
Since 3.x will change exceptions to be unchecked, this problem will be solved, see:

https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-4
