### ISSUE TITLE
Mapping infinite recursion

### ISSUE THREAD

**Issue by neXus1987** [FasterXML/jackson-databind#1873]
Hello,

i got following error with the Version 2.8.4:
org.glassfish.jersey.server.internal.process.MappableException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]->java.awt.Rectangle["bounds2D"]- 
and so on

Do you need further informations?

Thanks
Phil

**Comment by cowtowncoder** [comment]
Please send usage questions on mailing list:

https://groups.google.com/group/jackson-user/

This does not sound like a bug in jackson but rather that an AWT class having self-references.
There are couple of ways around that which may help; although it is not certain AWT types necessarily work very well with default handling (there is no explicit support).

**Comment by JorricksTU** [comment]
I am having the same problem.
@neXus1987 did you ever fix the problem?
And @cowtowncoder do you know where I can find a solution? I am having a hard time finding one.

**Comment by neXus1987** [comment]
now i use the version 2.9.3 and it seems to work, but i am not really sure if this was the solution:
	<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.3</version>
		</dependency>

I have also tried something with an object mapper and mixin a json ignore, but this is commented out:
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class ObjectMapperResolver implements ContextResolver<ObjectMapper> {

	private final ObjectMapper mapper;

	public static interface Rectangle2DJsonIgnore {
		@JsonIgnore
		String getBounds2D();
	}

	public ObjectMapperResolver() {
		// System.out.println("new ObjectMapperResolver()");
		mapper = new ObjectMapper();
		mapper.addMixIn(Rectangle2D.class, Rectangle2DJsonIgnore.class);
	}

	@Override
	public ObjectMapper getContext(Class<?> type) {
		// System.out.println("ObjectMapperResolver.getContext(...)");
		return mapper;
	}
}

**Comment by neXus1987** [comment]
And avoiding BufferedImage to serialize with	@JsonIgnore

**Comment by cowtowncoder** [comment]
@JorricksTU I think @neXus1987 suggested a solution that should work, as far as I can see. The trick is to force ignoral of property "bounds2D" which is a self-reference.

Alternatively if explicit support for a set of AWT types (at least for serialization) is desired, it would make sense to open a separate issue: there is a difference between type being specifically handled by Jackson (many JDK types are, but AWT ones not yet) and one working with some settings as "regular POJOs".

**Comment by tgm1024** [comment]
I've also encountered this Rectangle bounds2D recursion, but it only happens when a particular getter that merely _returns_ a `Rectangle` exists without a preceding `@JsonIgnore`.

No `Rectangle` member data exists, and it was my understanding that Jackson only concerned itself with _data_ members, not member methods.  Is this incorrect?

For example, without the `@JsonIgnore` in front of the getter:
```
public static class Metrics
{
    public Metrics() { }
        
    public Metrics(int x, int y, int width, int height)
    {
        this(null, x, y, width, height);
    }
        
    public Metrics(Rectangle bounds)
    {
        this(null, bounds.x, bounds.y, bounds.width, bounds.height);
    }
        
    public Metrics(String dateStamp, int x, int y, int width, int height)
    {
        this.dateStamp = dateStamp;
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
        
    @JsonIgnore    // <----(required)
    public Rectangle getBounds() { return new Rectangle(x, y, width, height); }
        
    // Must have public members...
    public String dateStamp;
    public int    x, y, width, height;
}
```
Is it part of the Jackson spec to concern itself with methods?

**Comment by yawkat** [comment]
@tgm1024 yes this is expected behavior. Jackson will serialize getters as well. In fact, getters are more common than using public fields in java.

**Comment by tgm1024** [comment]
> @tgm1024 yes this is expected behavior. Jackson will serialize getters as well. In fact, getters are more common than using public fields in java.

For JSON output?

Well that's certainly my fault for only familiarizing myself with POJO examples.  Thanks for the quick reply!

**Comment by cowtowncoder** [comment]
Good point @tgm1024 : our examples really should show cases of both public fields and getters being used, to not give a wrong idea of only one of those being used (and to show both may be used for the same POJO).

**Comment by tgm1024** [comment]
> Good point @tgm1024 : our examples really should show cases of both public fields and getters being used, to not give a wrong idea of only one of those being used (and to show both may be used for the same POJO).

Curiosity got the best of me on this, and I spent a few more minutes on it.

Part of confusion I had was in the notion of "serializing getters".  It's not serializing the _gettter_ per se, it's serializing the results of a getter, as a means of getting to an otherwise unreachable member.  This isn't an attempt to do a full object serialization complete with any methods, getter or otherwise.  We're still only talking about data here.

So of course,  when I renamed my `getBounds()` method to `asBounds()`, Jackson ignored it.  Jakson is semantically looking for the "get" method prefix.

**Comment by cowtowncoder** [comment]
Correct @tgm1024: Jackson has the concept of "properties", accessed (read, written / gotten, set) using one of accessors; accessors can be of different types.

So to read ("get") property `x` for serialization, Jackson will try to find the best accessor:

1. If there is an annotated field or signature-compatible (no arguments) non-static method ("getter"), use that
2. If there is a "visible" "getter" method, use that
3. If there is a visible field with name `x` use that.

... and so on. Similarly for "set" side (deserialization); although that is even more complex since Creator method (constructors, static factory methods) may also need to be used.

And for serialization (get), the process actually starts by looking at what is available (Fields, Methods) and Properties are then inferred from accessors, not vice versa.
Same is actually true for deserialization, although in theory one could try the other way (start with property name).

**Comment by tgm1024** [comment]
@cowtowncoder , I would have thought that it would be relatively straightforward to keep track of every member as visited, and when one circles around have it auto-removed by Jackson.  No?

You're required to descend into references of references anyway, so it seems like an option to "auto punt" the recurring members would be helpful.

An introspection list might be returned optionally so these could be programmatically discovered by the calling code, but that's less important.

**Comment by cowtowncoder** [comment]
@tgm1024 You are assuming that there was an explicit graph being maintained but this is not the case; each JsonSerializer only knows the specific Java value it is ask to serialize but delegates to child serializers in case of POJO properties, List elements and so on. So no serializer knows its parent path (or descendant path), there's just the implicit call stack.
If there was an explicit stack, one would then have to keep on checking parent stack with property/element values as well; this is not free (gets slower with deeper nesting); simple to implement but processing overhead.

So those two things would need to be added adding overhead (some memory but mostly processing) and only being necessary to do cycle checking/avoidance. Doable, but not super easy depending on how the ancestor stack was updated (does every serializer need to handle it? Or are all calls to child serializers now required to go through context? LIkely every serializer class needs to be changed)

**Comment by KiraLis39** [comment]
Проблема по-прежнему актуальна.
Получаю перегрузку по выводу json из Rectangle или Rectangle2D
