### ISSUE TITLE
FEATURE: Unwrapping of null value objects

### ISSUE THREAD

**Issue by pmihalcin** [FasterXML/jackson-databind#1887]
Hi,
I'd like to ask you if it is possible to enable unwrapping on null values here: https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/impl/UnwrappingBeanPropertyWriter.java#L89

The motivation:
I use Jackson to (de)serialize entities and value objects in Spring Data REST based project.

Let's say I have value object:
```
@Data
public class Description {
    @Column(name = "DESCRIPTION")
    private final String description;
}
```
and entity:
```
@Entity
public class Product extends AbstractEntity<Long> {

    @JsonUnwrapped
    private final Description description; 

    public Product(Description description) {
        this.description = description;
    }

    protected Product() {
        this.description = new Description (null);
    }
}
```
and custom `Description` serializer:
```
static class DescriptionSerializer extends StdSerializer<Description> {
    DescriptionSerializer() {
        super(Description.class);
    }

    @Override
    public void serialize(Description value, JsonGenerator jgen, SerializerProvider provider) throws IOException {
        if (value != null) {
            jgen.writeString(value.getDescription());
        } else {
            jgen.writeNull();
        }
    }
}
```

When I create `Product product = new Product(null);`
it returns `{}`, but I would like to have it as `{"description":null}` as it is done by `BeanPropertyWriter` for builtin Java object types.

The reason I am asking for this is to have API consistent for client such as e.g. React based frontend

**Comment by cowtowncoder** [comment]
There is no way to do that at this point, nor easy way to implement it. Jackson tries to stay away from structural transformations, and unwrapping is one of few things where exception is made.
But trying to change from JSON Object to `null` is another transformation, and there simply isn't enough information on Java object level to do that.

However, on your use case... would it not make sense to instead use `@JsonValue` to serialize `Description` as `String`? And if it's `null`, that gets serialized as JSON `null`?
You can have reverse by using `@JsonCreator` (in delegating mode), with single-String-arg constructor (or annotated factory method).

**Comment by pmihalcin** [comment]
I tried `@JsonValue` and it only works for me when the `Description` value is actually `null`. When it is not `null`, then `NestedEntitySerializer` I depend on kicks in instead of `@JsonValue` https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/json/PersistentEntityJackson2Module.java#L323

Is there a way how to tell Jackson to prefer `@JsonValue` based serializer to the `NestedEntitySerializer`?

As a side question, is there a way how to view the hierarchy of serializers which are applicable during runtime?

**Comment by michael-simons** [comment]
I see @pmihalcin that you reached out at many places. I could read through your code and I would give the same answer as @cowtowncoder .

**Comment by cowtowncoder** [comment]
@pmihalcin If you specify override for property, that will get used over `@JsonValue` indicated one. There is no way to change that precedence.

As to hierarchy, it depends on what you mean by that, but I suspect answer boils down to "no".
So, there is no defined mapping of all types to all serializers, as custom serializers are attached with callbacks (that is, modules are asked if they have serializer for given `JavaType`).
If you mean processing of annotations, that is not well documented either, but general principle is that the most specific definition has highest precedence. So, specific definition on property (via `@JsonSerialize(using=...)`) has highest precedence. This is followed by annotation on type (Class) itself (complicated by the fact that both property and type can further change actual type to use for locating serializer -- `@JsonSerialize(as=<supertype>)`).
If neither applies, registered serializer for type is searched for; custom serializer from modules would be located first. If this fails, databind-provided standard serializers are searched; first "primary" types (String, numbers, wrappers, `Collection`, `Map` and son), and failing that, tag on types (`Iterable`).
If nothing found, yet, assumption is we have `POJO` (... except some problem types are excluded, like JDKs Proxy types...). If so, annotation introspection kicks in: it will find `@JsonValue`, if specified, and try to find serializer for that type instead.
If not, logical properties are located and `BeanSerializer` will be created.

Some other changes may still be applied by property annotations, however: but these will only take effect at a later stage -- initial search is only by type. For property annotations we further need `BeanProperty` for which serializer is needed. This is handled by `ContextualSerializer` interface that many/most serializers implement: it can then inspect property annotations.
This is used -- for example -- to allow "as-array" serialization of POJOs, on per-property basis.

I hope above gives some idea of complexity of processing. I hope to some day write a book about this (amongst other things).
And maybe I could find time to document this in an article or wiki page during 3.0 development.
Some parts will (need to) change, regarding POJO property introspection, since handling of Creators (constructor / factory method) needs to be integrated in better way.

**Comment by pmihalcin** [comment]
Thanks a lot for the explanation. It'd be great to read the book and blog post as well!
