### ISSUE TITLE
Another two gadgets to exploit default typing issue in jackson-databind

### ISSUE THREAD

**Issue by OneSourceCat** [FasterXML/jackson-databind#1899]
Hi, there.
Recently, I found that there are two new gadgets can be used to exploit jackson which can cause RCE vulnerability.
I had sent the report to `info@fasterxml.com`.

Cheers!

**Comment by cowtowncoder** [comment]
I am not sure I saw that email. Which address was it from (or what was the title)?

**Comment by OneSourceCat** [comment]
The title is `[Critical] Jackson Deserialization RCE via a new Gadget`.
There are two emails about two different gadget.

**Comment by cowtowncoder** [comment]
Ok somehow I do not see this via that email address (with that title or any other combination).
Would it be possible re-send it?

**Comment by codelion** [comment]
@OneSourceCat Should the latest published version of `jackson-databind` be considered vulnerable, until the issue is resolved?

**Comment by cowtowncoder** [comment]
@codelion before assuming anything, make sure to also read:

https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062

to know under what special conditions vulnerabilities exist. For most Jackson users these are not applicable.

**Comment by OneSourceCat** [comment]
@cowtowncoder I've already resent the report. My email address is chongrui123[at]gmail.com.

**Comment by cowtowncoder** [comment]
@OneSourceCat  Ah. Gmail decided to put them in SPAM for some weird reason. :-o

**Comment by cplvic** [comment]
will this fix be added to the 2.8 branch

**Comment by cowtowncoder** [comment]
Yes, it is in `2.8` branch. Fix will be in `2.8.11.1` if such is released at some point; no full releases are planned for `2.8` at this point.
Fix was included in `2.9.4` release.

**Comment by cplvic** [comment]
thanks!

**Comment by cowtowncoder** [comment]
Micro-patch `2.8.11.1` was just released, and this fix is in it, along with #1872 and #1931.

**Comment by arunnc** [comment]
OWASP dependency check is still reporting this as vulnerable after updating to 2.8.11.1

**Comment by codelion** [comment]
@arunnc that’s a problem with OWASP dependency check, you can report it to them.

**Comment by arunnc** [comment]
Hi Asankhaya

Issue is NVD database is not updated with the micro patch 2.8.11.1 version
and fix details.

Would you know how to get this corrected?

On 14-Feb-2018 9:46 PM, "Asankhaya Sharma" <notifications@github.com> wrote:

@arunnc <https://github.com/arunnc> that’s a problem with OWASP dependency
check, you can report it to them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FasterXML/jackson-databind/issues/1899#issuecomment-365658459>,
or mute the thread

**Comment by codelion** [comment]
@arunnc In general, we cannot rely on NVD for the accuracy of vulnerable and fix versions. Shameless plug but you can try using https://www.sourceclear.com/ instead.

**Comment by hinnerup** [comment]
@codelion At https://www.sourceclear.com/vulnerability-database/security/remote-code-execution-rce-/java/sid-5732/summary CVE is referenced as fixed in 2.7.9.3. However, I find it difficult to read that from the commit/code comments related to 2.7.9.3. Could you elaborate on how you've come to the conclusion that 2.7.9.3 is safe (and includes a fix for CVE-2018-5968) ?

**Comment by codelion** [comment]
@newbishme can you help answer @hinnerup ’s question and verify the fix info for the artifact.

**Comment by ScrapCodes** [comment]
https://github.com/advisories/GHSA-w3f4-3q6j-rh82 seems to indicate the version 2.6.7.3 is affected, is it that the advisories data is out of date. What are the steps to update it?

**Comment by cowtowncoder** [comment]
@ScrapCodes I don't know how github advisories work, what data source they use. If anyone is interested, can point maintainers to https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6.7.x which points that `2.6.7.3` contains the fix.
