### ISSUE TITLE
Trivial: setHandlerInstantiator should return ObjectMapper

### ISSUE THREAD

**Issue by koscejev** [FasterXML/jackson-databind#1910]
`ObjectMapper.setHandlerInstantiator()` should return `ObjectMapper`, not `Object`. Looks like a typo, should be trivial to fix. ;)

**Comment by cowtowncoder** [comment]
@koscejev Alas, it is not an easy fix since that will break binary compatibility. :-(
(because it changes method signature, and although it is source compatible -- of course -- it is not binary compatible).
This means it can not be done in a patch, at least, and typically may be problematic for minor version too (although just for users who use the method).

But I'll fix this for 3.0: it will use Builder-style construction.

Thank you reporting the issue, there are couple of these -- mostly legacy settings, done before API tried to go with more fluent route.

**Comment by koscejev** [comment]
What do you mean by binary compatibility in this case? I'm not sure I understand the repercussions.

Narrowing return type from `Object` to `ObjectMapper` would not affect usages of this method. This would only affect overrides that, for some reason, return something other than `ObjectMapper`. It's up to you, of course, but to me it would seem that this would be OK.

**Comment by cowtowncoder** [comment]
@koscejev It means that any code that has been compiled to call the method with existing signature would fail miserably trying to load and link against new version. Result being something like "Method setHandlerInstantiator does not exist" error from JVM. Linker does not check whether coercion would be legal, but exact signature as-is: this allows return type co-variance, for example. In this case, for example, both existing (`Object` returning) and fixed (`ObjectMapper` returning) methods could exist at same time.

This cause particularly nasty backwards incompatibility between Jackson 1.1 and 1.2, for another method in `ObjectMapper` (although going from `void` to `ObjectMapper`). So this is not a theoretical concern but actual: it has bitten us before, and is the main reason why there are a few methods in `ObjectMapper` (and couple if `JsonNode`, subtypes) with essentially wrong return type.

Change would not problematic for source compliancy; and I am not worried about overrides, where I agree it should not matter. It is strictly about effects of signature change for dependencies between app code, `jackson-databind`.
Most likely problem case is that of Jackson being transitive dependency by a framework: so although app code may be recompiled against new version, intermediate library/framework is not.

I agree that it is a silly typo and unfortunately went in that way. But will be fixed for 3.0.

**Comment by koscejev** [comment]
Thanks for the explanation.
