### ISSUE TITLE
Abstract class included as part of known type ids for error message when using JsonSubTypes

### ISSUE THREAD

**Issue by Incara** [FasterXML/jackson-databind#1919]
I have the below class definition:

```
public class SomeClass {

    private SomeType type;

    @JsonTypeInfo(
            visible = true,
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
            property = "type")
    @JsonSubTypes({
            @JsonSubTypes.Type(value = SubType1.class, name = "subType1"),
            @JsonSubTypes.Type(value = SubType2.class, name = "subType2"),
            @JsonSubTypes.Type(value = SubType3.class, name = "subType3")
    })
    private final SuperType superType; //SuperType is abstract

    //getters/setters
}

```
When attempting to deserialize, if I specify the wrong property, I receive the correct error stating:

`Could not resolve type id 'string' into a subtype of [simple type, class SomeClass]: known type ids = [SuperType, subType1, subType2, subType3]`

However, I want to know why my SuperType considered a known type id? Is there anyway to exclude it since it is an abstract class?

**Comment by cowtowncoder** [comment]
@Incara At this point I think it gets included by default, since there are cases where base type is concrete and usable. It is even possible there might be actual value deserializer (at least in theory).
So I am not 100% sure if it'd be possible to remove it -- but at this point it will be included and there is nothing you can do to remove it from being considered valid (although attempt itself would fail unless there's static factory method producing some subtype).

**Comment by Incara** [comment]
Yes, it will always fail unfortunately. I appreciate the quick response.

**Comment by cowtowncoder** [comment]
Actually, let's keep this open for now. I can see why this is sub-optimal... but most likely can only be tackled in 3.0.
