### ISSUE TITLE
JsonInclude.ALWAYS not honored by ObjectMapper.convertValue(...)

### ISSUE THREAD

**Issue by kaspersorensen** [FasterXML/jackson-databind#1933]
A JSON property of type `Map` with annotation `@JsonInclude(JsonInclude.Include.ALWAYS)` gets populated wrongly (missing entries with null values) when using `ObjectMapper.convertValue` from a `Map` to the type containing the `JsonProperty`.

Here is a full reproduction scenario where `Pojo` is the type containing the `JsonProperty`:

```
import java.util.LinkedHashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Example {

    private static class Pojo {
        @JsonProperty("name1")
        String name1;

        @JsonProperty("name2")
        String name2;

        @JsonProperty("other")
        @JsonInclude(JsonInclude.Include.ALWAYS)
        Map<String, Object> otherInfo;
    }

    public static void main(String[] args) throws Exception {
        final Pojo pojo1 = new Pojo();
        pojo1.name1 = "hello";
        pojo1.name2 = null;
        pojo1.otherInfo = new LinkedHashMap<>();
        pojo1.otherInfo.put("foo", "bar");
        pojo1.otherInfo.put("baz", null);
        
        System.out.println("pojo1:\t" + pojo1.otherInfo);

        final ObjectMapper mapper = new ObjectMapper();
        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

        final String str = mapper.writeValueAsString(pojo1);
        final Map<?, ?> map = mapper.readValue(str, Map.class);
        System.out.println("map:\t" + map);
        
        final Pojo pojo2 = mapper.convertValue(map, Pojo.class);
        
        System.out.println("pojo2:\t" + pojo2.otherInfo);
    }
}
```

Expected output:
```
pojo1:	{foo=bar, baz=null}
map:	{name1=hello, other={foo=bar, baz=null}}
pojo2:	{foo=bar, baz=null}
```

Actual output:
```
pojo1:	{foo=bar, baz=null}
map:	{name1=hello, other={foo=bar, baz=null}}
pojo2:	{foo=bar}\
```

I am using Jackson databind version 2.9.4.

**Comment by cowtowncoder** [comment]
It seems to me that this is working as expected. Call to

    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

will set both `value` (of property) and `contents` serialization to `NON_NULL`.
Since `convertValue()` should be logically equivalent to sequence of `writeValue()` and `readValue()`, and since value is `Map` (and NOT POJO), `null`-valued `Map` entries are not included on write-part, and thereby not available on read.

If you do want to keep `null`-valued Map contents you need to set defaults using `setDefaultPropertyInclusion` that takes `JsonInclude.Value`

http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/ObjectMapper.html#setDefaultPropertyInclusion-com.fasterxml.jackson.annotation.JsonInclude.Value-

like:

    mapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(Include.NON_NULL,
        Include.ALWAYS);

**Comment by kaspersorensen** [comment]
But it seems that the reading into a Map does respect nulls:
```
        final Map<?, ?> map = mapper.readValue(str, Map.class);
        System.out.println("map:\t" + map);
```
yields:
```
map:	{name1=hello, other={foo=bar, baz=null}}
```
But the null entry is removed by `convertValue` as it then becomes:
```
pojo2:	{foo=bar}
```

**Comment by cowtowncoder** [comment]
`readValue()` does not consider inclusion in any way: it only applies to writing of JSON.
Conversion is the sequence of write-then-read; but by time read is done, output does not contain excluded values any more.
In this case another relevant part is the setting for `Map` property, which overrides default serialization settings. Behavior of `Map` is different from POJOs as well.

**Comment by kaspersorensen** [comment]
OK it seems that your suggested change works well for my scenario:
```
mapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(Include.NON_NULL,
    Include.ALWAYS);
```

So I'm fine with closing this issue. It just seemed counter-intuitive to me, would be nice to have an annotation specifically for `Map` objects maybe. So that this different behavior can be controlled on the Pojo member level.

**Comment by cowtowncoder** [comment]
It is not a work-around but expected behavior.

Ine additional note, your earlier setting was equivalent to:

    mapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(Include.NON_NULL,
        Include.NON_NULL);

which indicates that all `null` property values are to be excluded (first) as well as all content values (values of Map entries). If you do not want latter, it has to be changed.

Also note that `@JsonInclude` actually accepts two properties as well:

    @JsonInclude(value = Include.NON_NULL, contents = Include.ALWAYS)

but if one (or both) are omitted, that value defaults to global inclusion base (one set with `setDefaultPropertyInclusion`).
