### ISSUE TITLE
Doubt about serialization of java.util.regex.Pattern

### ISSUE THREAD

**Issue by cromoteca** [FasterXML/jackson-databind#1959]
Hi,

`StringLikeSerializer` and `FromStringDeserializer` deal with `Pattern`s as `String`s, but the `java.util.regex.Pattern` class has two serializable fields: `String pattern` and `int flags`. I'm using those flags so I need to implement a custom serializer.

Do you think that the current behavior can be changed in Jackson? I could try to provide a patch, but I don't know if this can be more useful or harmful, for obvious backwards compatibility reasons.

I'm using version 2.9.4.

**Comment by cowtowncoder** [comment]
Good questions. You are right in that my main concern would be backwards compatibility, and realistically answer comes down to whether there is a serialization as `String` that would retain all the information (pattern and flags), and be backwards compatible. At least with respect to changes for 2.9 in patch: for 3.0 we could consider bigger change(s).

Actually... for 2.9 we could consider use of `@JsonFormat(shape=Shape.OBJECT)`, defining of which could serialize Patterns as JSON Objects, default being `Shape.STRING`. Since it does not change API wrt methods (and there's no current use of format shape for Patterns), this would be acceptable change, if you'd like it.

There are some examples of this, I think, although it gets bit complicated. I think `BooleanSerializer` might do something similar.
Deserializer could and should then just accept `String` as well as JSON Object representation.

**Comment by cowtowncoder** [comment]
So: as per earlier comment; accepting JSON Object or maybe JSON Array alternative as input (and via `shape`, as output too) would be fine.
Will close for now but may be re-opened if anyone wants to take a stab at PR.
