### ISSUE TITLE
how to make Integer 0 not a default and in output JSON when using NON_DEFAULT

### ISSUE THREAD

**Issue by test88d** [FasterXML/jackson-databind#1962]
I am upgrading from 2.8.1 to 2.8.9. I found the JSON string omitted integer 0 in the output. I have below in my code. I like all the other features in Include.NON_DEFAULT except take Integer as default too. Is there a way I can override any method to make integer 0 not a default value? or any other suggestions?

 objectMapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);

**Comment by cowtowncoder** [comment]
There is no way to customize that; but perhaps setting of `NON_EMPTY` might work better for you?
`NON_DEFAULT` is bit problematic as global default since its interpretation differs a bit with that of using it on classes or properties.

In 2.9 there is `@JsonInclude` option of `Include.CUSTOM`, as well, which allows specifying `valueFilter`, if you want to fully customize the logic.

**Comment by test88d** [comment]
I can upgrade to 2.9. Do you have any sample code how to use valueFilter and Include.Custom

**Comment by cowtowncoder** [comment]
Test for this feature is in `src/test/java/com/fasterxml/jackson/databind/ser/filter/JsonIncludeCustomTest.java` so that is probably the best (and only) documentation at this point.

**Comment by test88d** [comment]
I don't own domain class. Is there a way I can globally customize it by checking data type Integer?

**Comment by cowtowncoder** [comment]
That should be possible, I think, via config overrides, specifying `JsonInclude.Value` for type `Integer.class`. See `ObjectMapper.configOverrides(Class<?>)`.
