### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by krichter722** [FasterXML/jackson-databind#1965]
Please add or link build instructions to `README.md`. I wanted to get started with the development version in order to investigate an eventual bug and could not figure out how to obtain the `parent` of a lot of module `jackson-base`. The `.travis.yml` don't allow to figure out easily how to build either.

Please note that this is not a support request. I'd like to see this issue fixed for everyone instead of just me, so there's no need to explain how to build here. i'm aware that there're development snapshots available.

**Comment by cowtowncoder** [comment]
Building should really just work with `mvn clean install`. I am not sure why snapshot builds of parent types do not work -- help in figuring out travis settings (to push snapshots automatically) would be helpful as well. I have tried to enable automatic build but it has been proven bit difficult to troubleshoot since I am essentially cut'n pasting code someone else, once upon a time, contributed. :)

I can (and will) add some notes to README, but fundamentally I don't think developers should have to build all dependencies.
Another thing that might help would be adding an xml comment or two in `pom.xml` of databind -- while redundant, it could cover basic parent hierarchy.

**Comment by krichter722** [comment]
> I can (and will) add some notes to README

Nice.

> I don't think developers should have to build all dependencies.

On the CI service it needs to do it anyway, so developers will see the build result on a blank system there.

> Building should really just work with mvn clean install.

Then you should simply create an aggregator project (a POM with packaging type `pom` without parent that defines the build order in its `modules` section), see http://rostislav-matl.blogspot.de/2011/12/maven-aggregator-vs-parent.html for a detailed explanation. The aggregator can also manage project versions on different branches very efficiently as git submodules and allow the checkout on the CI and the build with two commands. I'd go so far that there's no other way to acchieve a reliable `mvn clean install` build, but I might be wrong - doesn't matter because an aggregator is clearly the cleanest approach.

**Comment by cowtowncoder** [comment]
I am not quite sure I follow wrt need for new aggregator project. Intent is that Travis settings for existing Jackson components will trigger snapshot build & deploy on commit. That would then work for CI dependencies too.

**Comment by krichter722** [comment]
> I am not quite sure I follow wrt need for new aggregator project.

Please explain what you don't understand.

I was a bit surprised that Jackson doesn't have an aggregator project, yet, given the size and maturity, so I added a lot of explanations which you might already be familiar with.

They were aiming at supporting you in realizing your statement ~"The build should be as simple as `mvn install`" which currently isn't the case for checked out projects (even if there was a list describing the order to projects (probably `jackson-bom`, `jackson-modules-base`, etc.) that'd still mean that it's more complex than `mvn install`) as well as for the Travis CI script (which uses the hard to understand `git clone -b travis `git config --get remote.origin.url` target/travis` instead of an aggregator).

> Intent is that Travis settings for existing Jackson components will trigger snapshot build & deploy on commit. That would then work for CI dependencies too.

You should keep Travis scripts for each subproject/-module since they already contain the snapshot deployment logic (I have no experience with that and the link http://blog.xeiam.com/2013/05/configure-travis-ci-to-deploy-snapshots.html is dead, so I assume it already works). Then you create a commit for every commit in a submodule (this is more or less the set of repositories in https://github.com/FasterXML) in the aggragator (form described above). This causes the need to commit twice, but that's the only reasonable approach given the fact that the submodules already are git repositories.

**Comment by cowtowncoder** [comment]
My comment on `mvn install` simply meant that for anyone wanting to build a snapshot version locally should be able to do so, and find existing set of artifacts for dependant projects already in Sonatype snapshot repositories.
I did not mean that publishing of Jackson components needs to occur from a single place: setup for releasing versions works adequately.

As to sub-modules: since terminology can be confusing (b/w maven and git), one limitation is that I do not (and will not) use git submodules. I know some developers swear by them: I don't.
Maven submodules/projects are used by some repos; originally I wished to avoid them as well, but due to sheer number some aggregation has been useful from release perspective. Further combination is possible as well (one thought would be to consider combining `jackson-core` and `jackson-databind` -- `jackson-annotations` will follow slightly different versioning scheme), but it is probably orthogonal for here.

So. To me the question is simply: what is missing from getting necessary parent pom dependencies deployed to central snapshot repository?

**Comment by krichter722** [comment]
> My comment on mvn install simply meant that for anyone wanting to build a snapshot version locally should be able to do so, and find existing set of artifacts for dependant projects already in Sonatype snapshot repositories.

I get your point. I might have exagurated with the need of an aggregator. However, if you want that something works, you need to test it. A standard checkout is currently not tested and as fate willed does not work:

```
sudo docker run -i -t maven:slim /bin/bash
> apt-get update && apt-get install --yes git
> git clone https://github.com/FasterXML/jackson-databind.git && cd jackson-databind
> mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.fasterxml.jackson.core:jackson-databind:3.0.0-SNAPSHOT: Could not find artifact com.fasterxml.jackson:jackson-base:pom:3.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.fasterxml.jackson.core:jackson-databind:3.0.0-SNAPSHOT (/jackson-databind/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.fasterxml.jackson.core:jackson-databind:3.0.0-SNAPSHOT: Could not find artifact com.fasterxml.jackson:jackson-base:pom:3.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

Maybe it's sufficient to review `before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"` since that seems to be hiding this issue from being detected in Travis. Moving it to `after_success` might work afaik, however I never configured deployment on Travis.

**Comment by cowtowncoder** [comment]
Actually what was not working was not deployment of snapshots -- which does work -- but something more fundamental: definition of snapshot repository itself was in parent pom.
That would be nice for avoiding duplication... except that, well, when parent is snapshot, it requires knowledge of repository to fetch itself and, well, that obviously can't work.

So what I have added is direct definition of snapshot repository in core projects.
Same should be done for others too over time.
