### ISSUE TITLE
Try to find some optimizations on startup?

### ISSUE THREAD

**Issue by dsyer** [FasterXML/jackson-databind#1970]
I've done quite a bit of work on JVM startup benchmarks (mainly with Spring Boot): https://github.com/dsyer/spring-boot-startup-bench. Jackson is not a huge cost on startup and won't have any impact on a large monolithic application. But it is not negligible, and I have started removing it from apps that need to start up quickly (under a second, say, where I can get back 100ms by not using Jackson). Spring Boot already initializes Jackson in a background thread because we spotted it as a bottleneck quite a while ago, but this doesn't help if you don't have the CPU available, and it has an impact on the main thread even if you do.

[Clarification: the 100ms above is the improvement I can get by replacing Jackson with another JSON mapper - i.e. I don't need to necessarily lose any features.]

I don't know what Jackson does when it initializes, but it does seem to load a lot of classes, and that will most likely be one part of the cost. Is it possible that some features that may never be used at runtime are primed aggressively but needlessly, and maybe a more lazy approach would help? Or maybe there is more than just the loaded classes, and some more internal caching would help?

**Comment by cowtowncoder** [comment]
@dsyer Never say never, but I don't think there are any easy pickings for lazy initialization.
As to caching, one area that could perhaps benefit from more/better caching is handling of class introspection: JDK/JVM is not very efficient at decoding generic type and/or annotation information for classes, field s and methods, and although there is caching for repeated access it is not always clear which kinds of access is covered. This is much worse on, say, Android, but adds up on regular JavaSE too.

One thing that could help would be some profiling on reasonable-sized class hierarchy; my guess is that introspection of class annotations for property values could result in unexpected number of calls. Similarly for traversal of class hierarchies; and perhaps even type resolution (`TypeFactory` calls to resolve possible generic types; information that requires a lot of work... especially if given subtype of `Type` other than `Class`).

Anyway, I am pretty sure introspection for Java classes (class hierarchy, declared members, annotations attached to classes/members) is the major source. It is also quite elaborate process and caching can be... challenging (and resulting bugs difficult to track down).

For what it is worth, I think work if any should be focused for 3.x (`master`), for couple of reasons:

1. Bigger changes are possible and now is time to make them
2. 2.x branch is effectively in bug-fix mode, so chance of getting less-safe refactorings in is not very high -- no more minor versions are likely, but even if it was decided 2.10 is to be done, big focus would be on making upgrade to 3.x easier while keeping things as stable as possible for existing 2.x using code.

**Comment by cowtowncoder** [comment]
What I mean is that when creating initial set of (de)serializers, there may be multiple calls for full introspection of class information (with or without field/method/constructor introspection), checking/merging of mix-in annotations, type resolution and so on. My suspicion is due to types of properties overlapping (in simplest examples, say, it's likely there's more than just one property of type `String` even with just one or two POJO types).
So I am not as worried about classpath (Jackson does not really do any auto-magic there as I really want to stay out of that business :) ), but about heavy-lifting of figuring out everything declared for types being processed.

However, if there is no introspection involved yet, none of this applies, as you say.
So I was just speculating from part that I know takes a while (mostly as pointed out by Android developers, as platforms also makes actual Reflection calls significantly slower)

I can see how JVM might easily spent 100 ms for just loading classes it needs, although most classes should only really be loaded once first read/write occurs. Lookups are dynamic, and before any serializer/deserializer is needed, nothing much should happen.

So I guess I would be interested in knowing what gets loaded. However, unless I am missing something obvious, this should be much less work than what is involved when (de)serializers are actually needed.

**Comment by stolsvik** [comment]
This was interesting: What if I only use Jackson with specific classes (i.e. serialize this object, deserialize this JSON into this specific class), do I still get an initialization penalty? If so, why?

**Comment by cowtowncoder** [comment]
@stolsvik There are 2 main parts:

1. General JVM startup overhead for loading necessary classes (happens dynamically when specific class is actively needed), HotSpot, JIT-compiling. Nothing Jackson or other libraries can do about this, somewhat related to size of actively used codebase
2. Introspection Jackson does to construct serializers, deserializers, for types you need. Done dynamically, depends on amount of types you deal with.

So Jackson only introspects things it needs, lazily (but aggressively caching).
But amount of introspection for classes, their members, super-classes/interfaces, annotations on any and all of these, is non-trivial. And JDK implementation and/or bytecode format are not necessarily well optimized to make these operations cheap (partly since they tend not be on critical path; partly since annotations were introduced on JDK 1.5 and had to be retrofitted, not included in original 1.0 designs)

Does this answer your question?

**Comment by hc-codersatlas** [comment]
Can an annotation processor not assist with this? Do some of it at compile time? Could be optional and speeds things up if available.

**Comment by dsyer** [comment]
I can see how an annotation processor might be able to help with the serialization and deserialization (ie runtime concerns), but we already have afterburner and blackbird for that. (Not that it wouldn’t be interesting to have something better and in particular something that works with native images.) But this issue was specifically about the startup cost and I don’t think there have been any concrete suggestions for improving that - comments above suggest there isn’t much that can be done because it’s mainly about just loading classes.

**Comment by cowtowncoder** [comment]
@hc-codersatlas I don't think there is anything that could be done at compilation time, the way things are set up. One could re-implement the whole databind to do something else, but I am not aware of any low-hanging fruits with this: it seems like a big architectural design difference to me. Including (but not limited) to questions like where exactly would pre-processed information be held? I personally strongly dislike source code generation, but creating external configuration files adds another level of complexity -- now requiring additional layer of modeling. This would have some value, to be honest (externalizing representation of POJO), but it is very big undertaking, and possibly with somewhat low effort/result ratio.

@dsyer Right; wrt Reflection use (which is popular topic these days wrt Graal and other non-reflective platforms), there are 2 sort of distinct parts -- (1) introspection to find "what kind of POJO we have" (including annotation access), and then (2) reflection to assign fields, call setters, getters, constructors.
And for startup costs, (1) is what mostly matters.

I am open to concrete ideas and have actually occasionally tried some -- and a few things were actually even included in 2.10 and 2.11 (see more below) -- but the success rate has been low.
Main challenges are (in no particular order)

1. My perf testing is all on regular JDK, not Android so I cannot quite optimize for latter
2. Most of JDK cost with reflection seem to be (but see (3)) for one-off reading of class metadata, esp. for generic types; it is very difficult to avoid this in any way -- at best can possibly defer
3. I don't necessarily trust profiler output (just the regular JDK hprof) to give very accurate picture of where time is even spent

Having said, I have managed to reduce startup overhead a bit for 2 specific types of content:

* Tree mode (mapper.readTree() -> JsonNode) -- startup overhead with Jackson 2.10 and later is much lower than with 2.9 (... at least in `jmh` "wasteful" tests, where new ObjectMapper is created)
* "Untyped" content: Lists, Maps, Numbers (that is, binding as `java.lang.Object` or `Map`) -- similarly much lower overhead, although bit higher than that of JsonNode

Optimizations mostly try to avoid some of reflection for cases where these types are involved.
Not much progress with POJOs, despite attempting deferring of some processing -- none of which is included, yet (played on an experimental branch). I may continue attempts to defer some of processing, still, mostly because there are certain bogus error cases that could be avoided (cases where POJO detection finds a potential problem, but one that is never actually triggered).

**Comment by hc-codersatlas** [comment]
Looking at something like https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule.java#L123 I'd think it can be optimized. Each time we call 1 of these methods to add a serializer / deserializer there's at least 3 IFs that aren't needed - it's not going to be null etc.

Would be good if there are optimized methods for modules that require this initialization (I assume most).

**Comment by cowtowncoder** [comment]
@hc-codersatlas perhaps, but I find it quite unlikely that those kinds of small optimizations would make much measurable difference; null checks, for example, are about simplest bytecode operations there are.

**Comment by dsyer** [comment]
Null checks would not have much impact I agree. But there are a ton of classes that have to be loaded in that example that might never be used (e.g. none of the keys are data times, or we never see a `MonthDay` or a `ZoneOffset` in a value etc.). I imagine that kind of pattern could be responsible for most of the perceived delay on start up if you add them all up over the whole library.

**Comment by cowtowncoder** [comment]
@dsyer Based on profiling I have done, I doubt that basic (de)serializer registration plays significant role either -- but I am always open for changes to improve things in measurable way. So if someone was to provide a PR and show its effects with a test, would be happy to merge changes.

Sometimes code clean up is useful in itself if it reduces code to maintain, cleans up logic, regardless of 
performance benefits.

But for what it is worth, my view is that the biggest time spent is for all introspection for Java class information for types, annotations.

**Comment by geoand** [comment]
First of all I'd like to thank @cowtowncoder for the detailed answers in this thread, they are most enlightening.

> But for what it is worth, my view is that the biggest time spent is for all introspection for Java class information for types, annotations.

From what I understand, this does **not** happen when one does `new ObjectMapper()` though, correct? In the case of framework startup, creating instances of `ObjectMapper` is a non trivial contributor to the total startup time.

**Comment by cowtowncoder** [comment]
@geoand You are 100% correct: there is some initialization and set up but none of Reflecation access occurs during construction -- neither in `ObjectMapper` construction nor when using `JsonMapper.builder()` style construction.

But given that I do not think construction of `ObjectMapper` should be significant contributor: it really should be more first `readValue()`s and/or `writeValue()`s.

So if overhead is observed at that point I'd be interested in learning why and how.

**Comment by geoand** [comment]
> So if overhead is observed at that point I'd be interested in learning why and how.

Absolutely. If we observer this, we'll reach out :)
