### ISSUE TITLE
Polymorphic Deserialization of Collections Not Serializing Class Id as Property

### ISSUE THREAD

**Issue by geekbeast** [FasterXML/jackson-databind#2078]
I am seeing weird issues with polymorphic deserialization of nested types. The main bad behavior I'm seeing is that type field (i.e ```@class```) is not getting serialized for collections when serialized in certain ways. I wrote several test cases for my own debugging that I included below. It seems like Jackson should have sufficient information in all cases, but passing a collection of the abstract class doesn't ever seem result in serialized type info. 

Test on 2.9.2 and 2.9.4

On 2.9.2:
`testListWithoutOptional` fails

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.openlattice.shuttle.transforms.TestCase$AbstractExample]: missing type id property '@class'
 at [Source: (String)"[{"a":"another"},{"b":1}]"; line: 1, column: 16] (through reference chain: java.util.ArrayList[0])`

`testWrappedListWithOptional` fails

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.openlattice.shuttle.transforms.TestCase$AbstractExample]: missing type id property '@class' (for POJO property 'examples')
 at [Source: (String)"{"examples":[{"a":"another"},{"b":1}]}"; line: 1, column: 28] (through reference chain: com.openlattice.shuttle.transforms.TestCase$ExampleOptionalList["examples"]->java.util.ArrayList[0])`

On 2.9.4: 
`testWrappedListWithOptional` fails

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.openlattice.shuttle.transforms.TestCase$AbstractExample]: missing type id property '@class'
 at [Source: (String)"[{"a":"another"},{"b":1}]"; line: 1, column: 16] (through reference chain: java.util.ArrayList[0])`

Code is available here: https://gist.github.com/geekbeast/b69e59eb21030e7be28ac79fa572c1f2

**Comment by cowtowncoder** [comment]
@MustafaHaddara as a general rule, it is best to avoid using generic types as root values, since the problem is 99% likely Java's Type Erasure: to include polymorphic type information, declaration of `List` (etc) must be available, and if only passing `List` as root value it is only known as `List<?>`: and since `java.lang.Object` is not considered polymorphic type (unless Default Typing is enabled with settings to make it one), no type information is included.
Worse, when deserializing you usually do pass generic type (as `JavaType` or `TypeReference`).

Difference to individual values is that type information is available for value itself: value classes are not generic (no type parameters).

I don't know if this is the same as the original example, but handling for this usage has not changed during 2.9.x as far as I know.

As to solution for second case either consider using a wrapper POJO like:

```java
public class ListContainer {
   public List<Vehicle> vehicles;
}
```

or create a throw-away non-generic container type:

```java
public class VehicleList extends ArrayList<Vehicle> { }
```

which then embeds type information via sub-typing (not generic any more).

Or finally force use of specific type during serialization:

```java
mapper.writerFor(new TypeReference<List<Vehicle>> () { })
    .writeValueAsString(list);
```

which passes full type declaration to make polymorphic nature of elements clear.
