### ISSUE TITLE
Comments are not allowed in Nested JSONs

### ISSUE THREAD

**Issue by abhi4151** [FasterXML/jackson-databind#2127]
Using Feature.Allow_Comments ignore the comments in the immediate json schema using below code:

```
public static ProcessingReport validateJson(String jsonSchemaNode, String jsonText)
			throws ProcessingException {
		JsonFactory jsonFactory = new JsonFactory();
		jsonFactory.enable(JsonParser.Feature.ALLOW_COMMENTS);
		jsonFactory.enable(JsonParser.Feature.ALLOW_YAML_COMMENTS);
		ObjectMapper mapper = new ObjectMapper(jsonFactory)
				.configure(JsonParser.Feature.ALLOW_YAML_COMMENTS, true)
				.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
		JsonNode jsonSchema = null;
		final JsonSchemaFactory factory = JsonSchemaFactory.byDefault();
		try {
			jsonSchema = mapper.readTree(jsonSchemaNode);
			return factory.getJsonSchema(jsonSchema).validate(mapper.readTree(jsonText));
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
```
But if Json file refers another schema file. The comments are not ignored in the imported json schema file.

```
{
	/*Hello, 
	I'm ABhishekt*/
	//This is a comment
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "SubmitProcess",
	"description": "Sample COmmand",
	"type": "object",	
	"allOf": [{ "$ref": "resource:/JsonSchema/Schema.json#"}]
}
```
So if there's any comment in the imported Schema.json. It doesn't allow comments in that file.

Please confirm if this could be an enhancement.

It gives an error:

```
--- BEGIN MESSAGES ---
fatal: content at URI "resource:/JsonSchema/Schema.json#" is not valid JSON
    level: "fatal"
    uri: "resource:/JsonSchema/Schema.json#"
    parsingMessage: "Unexpected character ('/' (code 47)): was expecting double-quote to start field name"
    info: "other messages follow (if any)"
---  END MESSAGES  ---
```

**Comment by cowtowncoder** [comment]
Where does `JsonSchemaFactory` come from? That would be component handling reads of imported schemas, and needs a mapper/parser to do that, and so needs to be configured to allow comments as well. I don't see configured mapper or `JsonFactory` being passed anywhere in sample code.

**Comment by cowtowncoder** [comment]
@abhi4151 yes, `readTree()` handles input and no comments are included. They will not come from tree. But `readTree()` just reads JSON, it does no JSON Schema handling and as such does not import anything.
So `JsonSchemaFactory` here must be piece fetching referenced schema json and parsing it.
But since you are not giving it configured `JsonFactory` or mapper, it obviously has to use something it has or creates.

What annoys me is that you failed to indicate anything about `JsonSchemaFactory` here: it is not part of `jackson-databind` (this package), and I don't think it's part of any standard Jackson component (`jackson-module-jsonSchema` does have a class with same name but that does not `byDefault()` method).
So you are asking me to debug your problem without giving necessary information.

**Comment by abhi4151** [comment]
@cowtowncoder My bad, I didn't get your ask in your previous comment.

`JSONSchemaFactory` comes with  com.github.fge.jsonschema.main.JsonSchemaFactory;

The Github Repository is:
https://github.com/java-json-tools/json-schema-validator

I'm using 2.2.6 version. Please let me know if I can provide any other information .

**Comment by cowtowncoder** [comment]
@abhi4151 Ok. I think you'll need to ask maintainers or on mailing lists of that project. I do not see anything to work on on Jackson side; there should be a way to configure their factory. If there isn't a way, maybe file a feature request or even PR if you can figure out what to add.
