### ISSUE TITLE
StdDateFormat implements clone() incorrectly.

### ISSUE THREAD

**Issue by joaoe** [FasterXML/jackson-databind#2170]
I noticed that `StdDateFormat()` implements the `clone()` method
https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java#L242

The semantics for cloning is really not trivial and that's a relic from the early Java days that people should not be relying on, e.g., what about transient state or do a shallow or deep copy ? 

Anyway, the state of the art recommentation strongly advise against that method, orr else you HAVE to call `super.clone()`, e.g.
http://cwe.mitre.org/data/definitions/580.html
The problem is that if someone extends `StdDateFormat` and then call `clone()`, that will return not the new extended class but `StdDateFormat`.

To use `clone()` you have to call `super.clone()`, e.g.
```
class MyClass extends Blah implements Cloneable {
  @Override
  public Object clone() {
    MyClass copy = (MyClass)super.clone();
    //copy.<fields> = <values>;
    return copy;
  }
}
```
`Object.clone()` checks if the `MyClass` implements `Cloneable` and if so, then returns a new clean instance of `MyClass` which you can cast and fill with the data.

`StdDateFormat` extends from `DateFormat` and if you notice, that one actually implements `clone()` correctly.

Cheers.

**Comment by cowtowncoder** [comment]
If `StdDateFormat` was intended for use by anything other than Jackson, yes, semantics would be surprising.

But it is not. It is not meant to be -- and should never be -- used outside of Jackson. The reason `clone()` is implemented that way is because Jackson itself does expect `clone()` from `DateFormat` -- and this is to allow use of custom `DateFormat` implementation -- but `StdDateFormat` can avoid otherwise expected construction of a new instance because semantics for this use are different.

So: while I understand that this violates general contract of `Object.clone()`, that is done on purpose here, not accidentally.
