### ISSUE TITLE
Deserialization issue with `@JsonIgnore` and `@JsonProperty` with 2.9.6+ :  Unrecognized field, not marked as ignorable

### ISSUE THREAD

**Issue by ant8e** [FasterXML/jackson-databind#2182]
Found this issue while bumping to 2.9.7
here is a small reproduction 
```java

    public static class TestClass {
        @JsonIgnore
        private String id;

        public TestClass() {

        }

        @JsonProperty("id")
        public String getAlternateId() {
            return null;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }
```

fail this test (with 2.9.6 and 2.9.7)

```java
Assert.assertNotNull( new ObjectMapper().readValue("{ \"id\": \"test\"}", TestClass.class));


com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class com.xxxx.yyyy.JacksonJsonIgnoreTest$TestClass), not marked as ignorable (0 known properties: ])
 at [Source: (String)"{ "id": "test"}"; line: 1, column: 10] (through reference chain: com.xxxx.yyyy.JacksonJsonIgnoreTest$TestClass["id"])
```

**Comment by cowtowncoder** [comment]
Hmmh. That is bit tricky, due to renaming involved. As a work-around I would suggest adding one more `@JsonProperty` on either `setId()`.

Actually come to think of that... what is the intent with `@JsonIgnore` on field? It should not have any effect here, as getter/setter has preference over fields anyway (plus private field is not discovered for serialization anyway).

**Comment by ant8e** [comment]
> Actually come to think of that... what is the intent with @JsonIgnore on field? It should not have any effect here, as getter/setter has preference over fields anyway (plus private field is not discovered for serialization anyway).

Yes I think that's my point: @JsonIgnore should do nothing here and yet since 2.9.6 the behaviour has changed and the field is ignored. As for the intent, I can only speculate that the original developer thought it was necessary in order to use @JsonProperty to rename the field.

**Comment by cowtowncoder** [comment]
No, `@JsonIgnore` can certainly be used in lower priority accessors too, and meaning is such that:

1. If only one of `@JsonIgnore` or `@JsonProperty` found, it is applied to the property as whole (as if added to all accessors)
2. If more than one found, accessors are "split", and apply to only specifically annotated ones.

But what I meant is that you likely should remove it, or, if preferred, add explicit `@JsonProperty` on `setId()`. Problem here is that of ambiguity: Jackson is trying to figure out expected semantics from set of annotations on multiple accessors, including renaming. I am not sure myself what intended end result should be, and if it was working before that was accidental more than intentional. Unit tests do not typically cover cases that would be considered undefined. It is of course unfortunate that actual behavior was what developer wanted, as opposed to failure of some kind.

**Comment by ant8e** [comment]
Thanks for the information.
I will update our code to remove any ambiguous usage of @JsonIgnore


Le mar. 20 nov. 2018 à 22:14, Tatu Saloranta <notifications@github.com> a
écrit :

**Comment by cowtowncoder** [comment]
Since I am not confident I know how to improve behavior, will close -- may be re-opened or re-filed with a proposal of how renaming could be handled (at logical level).
