### ISSUE TITLE
@JsonTypeInfo on nested property class is ignored?

### ISSUE THREAD

**Issue by vghero** [FasterXML/jackson-databind#2209]
I'm using jackson 2.9.6 and just encountered a strange behavior, when serializing subclasses in a nested property. It seems that the type info is not serialized. Take this example:

```
    public static void main(String[] args) throws JsonProcessingException {

        ObjectMapper mapper = new ObjectMapper();
        // mapper.enableDefaultTyping();

        Wrapper<B> wrapper = new Wrapper<>();
        wrapper.type = new B();
        wrapper.type.a = "testa";
        wrapper.type.b = "testb";

        System.out.println(mapper.writeValueAsString(wrapper));
    }

    public static class Wrapper<T> {
        public T type;
    }

    public static class B extends A {
        public String b;
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    @JsonSubTypes({ @Type(value = B.class, name = "b") })
    public static abstract class A {
        public String a;
    }
```

So executing this, returns:

```
{"type":{"a":"testa","b":"testb"}}
```

What I'm missing is the `@class` in there. If I only serialize `B` directly it works. It seems just not to work when it is nested inside another class that has declared that field as `Object` or a generic type. E.g. it also works if I directly make `T` a `B` in `Wrapper`. Also enabling `enableDefaultTyping()` seems to work, although it uses the classname instead of the alias.
Is this a known limitation?

I'm not in control of `Wrapper` and would like to avoid making changes to the `ObjectMapper` instance globally, since this might be used by other parts of the system.

Is there another way of handling this besides using e.g. mixins, registering them for specific types 
only in the `ObjectMapper` instance?

**Comment by cowtowncoder** [comment]
The main problem here is that you are using generic type for the root value: this will cause all kinds of problems. Problem is that during serialization, type can only be seen as `Wrapper<?>`, and thus static "base type" (one used as base for type id handling, including detection of annotations, directly or via mix-ins).

There are ways to work around this:

1. Use non-generic root value which can refer to generic types just fine (Type Erasure does NOT affect method, field, or super-type declarations!)
2. Make root type non-generic by sub-classing (class MyBWrapper extends Wrapper<B> { ... )
3. Create `ObjectWriter` with full type information (`ObjectMapper.writerFor(type)`), to force information on actual fully generic type.

So, wrt 1, if you have

```java
public class Request {
   public Wrapper<B> value;
}
```

things would work better as generic type information will be available via `Request`, to fields/methods and so on.

But when passing value of type `Wrapper`, generic type parameters are not available at run time, and Jackson can not resolve them but has to assume it just `Wrapper<?>`, which for all practical purposes is same as `Wrapper<Object>`. And since `Object` does not have annotations things won't work well (you could enable default typing, yes, but that's... bit heavy hammer and may have its own issues).

**Comment by vghero** [comment]
Ok, understood. Thanks for the detailed explanation and the provided "workarounds"!
