### ISSUE TITLE
Use interfaces instead of abstract classes for `Module`, `AbstractTypeResolver`

### ISSUE THREAD

**Issue by grv87** [FasterXML/jackson-databind#2214]
Current API is based on abstract classes.
For example, these:
* `com.fasterxml.jackson.databind.Module`
* `com.fasterxml.jackson.databind.AbstractTypeResolver`

are abstract classes and not interfaces.
And (in 3.0 dev version):

* `com.fasterxml.jackson.databind.cfg.MapperBuilder.addModule` accepts `Module`
* `com.fasterxml.jackson.databind.Module.SetupContext.addAbstractTypeResolver` accepts `AbstractTypeResolver`

As a writer of custom module for Jackson, I would like to create implementation as simple as possible.
For example, I want to implement custom abstract type resolver and register it as a module.
Currently I cannot do this with single class, since I can't inherit from several classes.
I have to create two classes and instantiate both. This increases labor for both the developer and the runtime.
I propose to add interfaces use them in API. This would make API more convenient and extendable, and remove unnecessary complexity when it is not needed.

Could this be done in 3.0?

**Comment by cowtowncoder** [comment]
With Java 8 (baseline for 3.0) it would certainly be easier to do that so I can consider this.
I'll have to check and see if there were additional reasons beyond just making it much easier to evolve API pre-Java8 (since adding new methods to interfaces was practically impossible considering backwards-compatibility), but I do not recall such limitations.

**Comment by cowtowncoder** [comment]
Looking back at this, I don't think that change is worth it just to make it possible to have "chameleon" types (that implement multiple APIs).
