### ISSUE TITLE
SerializerProvider has no FilterProvider but retrieves a BeanSerializer that has a non null _propertyFilterId

### ISSUE THREAD

**Issue by postsa** [FasterXML/jackson-databind#2293]
Using version 2.9.7
We've registered `SecurityEntityFilteringFeature` and `JacksonFeature`.
```
    register(SecurityEntityFilteringFeature.class);
    register(JacksonFeature.class);
```

**tl;dr**
`SerializerProvider` has no `FilterProvider` but retrieves a `BeanSerializer` from the cache that has a non null `_propertyFilterId`, resulting in https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/StdSerializer.java#L370

**I think the issue is here:**
https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializer.java#L145.

When the `DefaultSerializerProvider` looks up a `Serializer` https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/DefaultSerializerProvider.java#L231 it finds a previously used `BeanSerializer` that has a non null `_propertyFilterId`. My guess is this `BeanSerializer` was used in a previously successful filtered serialization by a `SerializerProvider` with non null `FilterProvider`  However, this time around, the `SerializationConfig` for this `SerializerProvider` does not have a `FilterProvider` so the call fails. 

Correct me if I'm wrong, but It seems like it should be impossible for a `SerializerProvider` with a null `FilterProvider` to find a `BeanSerializer` with a `_propertyFilterId` since this serialization will never succeed.

I'm also curious why a non null filter provider is necessary when a filter might not be necessary, https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/StdSerializer.java#L368 and https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/BeanSerializerBase.java#L850.

Would it also be possible to create an IllegalStateException or something here https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializer.java#L145. If the provider doesn't have a `FilterProvider` I'm not sure why it would continue execution.

**Comment by cowtowncoder** [comment]
I think I need bit more context. What does `register` do? I would also need a reproduction from usage end -- I can not comment on what happens internally without knowing how things are configured. There are reasons certain things are initialized certain way and it is often easier to point out usage that triggers problem, rather than trying to start from point of exception and trying to deal with that in isolation.

**Comment by postsa** [comment]
Sure no problem. We are all enterprisey so it's going to take me a little bit to create a project that I can share that recreates the problem. I am working on that now. In the mean time here are a few screenshots of our heap that might illustrate the problem a little better.
<img width="1027" alt="Screen Shot 2019-04-04 at 7 25 50 PM" src="https://user-images.githubusercontent.com/3301020/55598355-7de81b00-570f-11e9-9c58-8c95500e7711.png">
You can see in the above screenshot that BeanSerializer#12 is for type `Cart` and has a non null `_propertyFilterId` and BeanSerializer#21 is also for `Cart` and has a null `_propertyFilterId`. We also only have one FilterProvider on the heap, referenced by SerializationConfig#8. 
<img width="997" alt="Screen Shot 2019-04-04 at 7 29 44 PM" src="https://user-images.githubusercontent.com/3301020/55598476-239b8a00-5710-11e9-8799-39343397a658.png">. And to really compound the problem we have 15 ObjectMappers 
<img width="1003" alt="Screen Shot 2019-04-04 at 7 33 43 PM" src="https://user-images.githubusercontent.com/3301020/55598571-9b69b480-5710-11e9-945c-929c3e77376f.png">. My understanding is that if any of the object mappers but the one with SerializationConfig#8 tries to serialize the Cart and gets BeanSerializer#12 instead of BeanSerializer#21 I will get the exception `"Cannot resolve PropertyFilter with id '"+filterId+"'; no FilterProvider configured"`.  Basically we want to sometimes serialize an object with a filter and sometimes serialize without it. However the way the BeanSerializers are setup its unsafe for us to ever construct an ObjectMapper without a FilterProvider because BeanSerializer#21 exists in the cache and on the off chance it gets retrieved when we are trying to serialize the cart object without filtering we will get an exception.

**Comment by postsa** [comment]
It was confusing of me to bring up the register out of context but I believe that's the reason we have an `AnnotationIntrospector` other than https://github.com/FasterXML/jackson-databind/blob/36121159ff5f8fe9616cac558d64210834fc859d/src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java#L243. When you register both of those features you get https://github.com/jersey/jersey/blob/master/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/FilteringJacksonJaxbJsonProvider.java#L97 which finds `_filterProviderIds` for classes that aren't annotated with `@JsonFilter` which is why we have a `BeanSerializer` with a `_propertyFilterId` and one without. FasterXMLs annotation introspector didn't find a `_propertyFilterId` but Jersey's did.

**Comment by cowtowncoder** [comment]
Ok, my main challenge is just that it is easier to start from high-level and see how things are configured.
`SerializerProvider`, for example is something that no code outside Jackson core components should try to directly modify or instantiate: it is strictly read-only access, during individual serialization (one `writeValue()`). So its state is fully managed by databind itself. But sometimes developers do try to create their own instances and end up in trouble. This is just an example -- I don't think this is done here but is kind of thing that would end up with problem like this.

Similarly, lifecycle of `BeanSerializer` is strictly controlled by `jackson-databind` and no code outside should attempt to create instances by construction or sub-classing.

But couple of thing that can also lead to inconsistent state include:

1. When delegating calls from custom serializers to standard Jackson serializers (perfectly acceptable usage), initialization calls to `resolve()` (for `ResolvableSerializer`) and `createContextual()` (for `ContextualSerializer`) are not relayed to standard ones. This leaves standard serializes in incomplete state
2. Not creating new serializer instance from `createContextual()` (of any `ContextualSerializer`) -- serializers MUST be stateless, so if differently configured instance is needed, a new instance must be constructed (as one being called one is usually cached and shared)

So. Looking at very low level symptoms is not something that is likely to find what is causing the problem. It can suggest that a serializer has inconsistent state (which seems to be the case), but not so much why things ended up there.
This is why I am interested in knowing specifically how things are being registered.

Oh, and I could add third speculative root cause

3. Attempting to re-configure `ObjectMapper` during usage -- this will not work reliably, although unfortunately may seem to work for a while. :)

  (usage pattern for Jackson 2.x `ObjectMapper` is "configure completely first, then use" -- 3.0 will make mappers fully immutable and prevent unsafe usage, but 2.x can not be retrofitted that way)

**Comment by postsa** [comment]
Here's an example project that illustrates the problem. It's a little bit contrived. https://github.com/postsa/JacksonJerseyBugExample. If you call the [model1 endpoint ](https://github.com/postsa/JacksonJerseyBugExample/blob/master/src/main/java/com/spost/jjbug/V1Resource.java#L18)  before the [model2 endpoint ](https://github.com/postsa/JacksonJerseyBugExample/blob/master/src/main/java/com/spost/jjbug/V1Resource.java#L24) the model1 call filters the sensitive field but the model2 endpoint throws 'Cannot resolve PropertyFilter with id 'com.spost.jjbug.ResponseModel'; no FilterProvider configured' if you call them in the opposite order, you don't see the bug but you also don't get any of the filtering.

**Comment by cowtowncoder** [comment]
Again, while I appreciate reproductions I would need something that does use Jersey or Spring, as I have no control over how they create or use `ObjectMapper`.

But I wonder if this could be related to caching of JAX-RS provider (if Jersey uses that -- I notice use of Jackson enabled using Jersey-specific method which I suspect might not use pluggable JAX-RS provider).

Now: `SerializerProvider` is and MUST be used just for a single call. That is why it seems odd there would be any reuse -- if using `ObjectMapper` or `ObjectReader` there should be none; a new provider is created every time.

**Comment by postsa** [comment]
I appreciate the response. 

All Jersey is doing is using this [class](https://github.com/eclipse-ee4j/jersey/blob/eafb9bdcb82dfa3fd76dd957d307b99d4a22c87f/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/FilteringJacksonJaxbJsonProvider.java#L72) to set the `_propertyFilterId` on the `BeanSerializer` for fields and methods annotated with their `DenyAll` and `RolesAllowed` annotations. 

The reason I opened the issue here instead of with Jersey is because I don't understand the purpose of your shared cache of `BeanSerializers` and I think object mappers would be safer to use without it. 

What is the purpose of having two different object mappers share a cache of `BeanSerializers` if we cannot assume that the `BeanSerializers` in the shared cache can be used by different object mappers without throwing an exception? 

It seems like that if `BeanSerializers` must be cached for use among object mappers they should be shared only among object mappers with the same serialization or de-serialization configurations. I hope that I have given you enough information in this thread to support that point.

Here are some other examples of what I believe to be this issue being kicked around between Jackson and Jersey with no resolution.
* https://github.com/FasterXML/jackson-databind/issues/1645
* https://groups.google.com/forum/#!topic/jackson-user/tfYndVoRh0c
* https://github.com/jersey/jersey/issues/3574
* https://github.com/jersey/jersey/issues/3732

Thanks for your time.

**Comment by cowtowncoder** [comment]
Ok. One thing that seems suspicious on Jersey's implementation is this:

```java
    @Override
    protected JsonEndpointConfig _configForWriting(final ObjectMapper mapper, final Annotation[] annotations,
                                                   final Class<?> defaultView) {
        final AnnotationIntrospector customIntrospector = mapper.getSerializationConfig().getAnnotationIntrospector();
        // Set the custom (user) introspector to be the primary one.
        final ObjectMapper filteringMapper = mapper.setAnnotationIntrospector(AnnotationIntrospector.pair(customIntrospector, ...)
```

because it assumes that `ObjectMapper` passed is private and not yet used -- this is not true.
It is likely globally shared and one absolutely must not try to change configuration after first use.
What may be happening, then, is that serializer is found and cached using mapper instance before filter addition is attempted.
I am not sure if this causes the issue but issues would be related to sequence of usage.

Another possibility, is that overriding of `findFilterId()` leads to requirement of having filter provider for every serialization, anywhere -- this is what databind requires. It is not optional.
Checks in code that you mentioned earlier are not commented well but indicate the same thing: if filter id is defined for a serializer, filter will be used -- unlike views which may or may not be applied, filters are always applied and required. Such requirement is not very well documented by `AnnotationIntrospector` unfortunately, which may have lead to Jersey implementors assuming that there is no harm in declaring that an endpoint has filter id specified.

Beyond this at this point I am not sure I can help much further without specific Jackson-only reproduction of the problem: reproduction may be based directly on Jackson JAX-RS provider, but override as implemented by Jersey (and linked to) is not valid usage.

**Comment by postsa** [comment]
I think we have arrived at the heart of the matter.
```
Another possibility, is that overriding of findFilterId() leads to requirement of having filter provider for every serialization, anywhere -- this is what databind requires
```
This is what I have found to be the case. The fix that I have been working on in our codebase is to replace our object mapper instantiation with some sort of an `ObjectMapper` provider class that *always* guarantees a `FilterProvider` on an `ObjectMapper` and to force all of our code to use the provider instead of plain `ObjectMapper`. Unfortunately, this is a long process but probably a pattern we should have used from the beginning when integrating with an open source library.

If you don't mind, I will open an issue with Jersey and share your response here with them. Being forced to create a filter provider for "every serialization, anywhere" is quite the side effect and I'm not sure they realize they are causing it.

If you don't mind explaining, I would still like to understand some of the reasoning behind this
```
What is the purpose of having two different ObjectMappers share a cache of BeanSerializers if we cannot assume that the BeanSerializers in the shared cache can be used by different ObjectMappers without throwing an exception?
```
Are `BeanSerializers` so expensive to construct that it is worth the risk?

Thanks again.

**Comment by postsa** [comment]
Opened https://github.com/eclipse-ee4j/jersey/issues/4130 against Jersey

**Comment by cowtowncoder** [comment]
@postsa Different `ObjectMapper`s do not share caches so I am not sure what this reference is to. Scope of caching is mapper, no static global singletons used.

**Comment by postsa** [comment]
I don't think this bug would be possible otherwise. Isn't that what this is?
https://github.com/FasterXML/jackson-databind/blob/d2c083a6220f2875c97c29f4823d9818972511dc/src/main/java/com/fasterxml/jackson/databind/ser/SerializerCache.java#L43

**Comment by cowtowncoder** [comment]
@postsa Yes, there is a `SerializerCache`, one for each `ObjectMapper`. No two mappers share one `SerializerCache`. So I am missing something here.

Maybe you are referring to two invocations of `writeValue()` on same `ObjectMapper`? If so, those operations would share same cache.

**Comment by postsa** [comment]
Ok, ran it through the debugger again. It is the same object mapper but it has a different serializationConfig. So sharing BeanSerializer's across serializationConfigs is causing the issue.

**Comment by cowtowncoder** [comment]
@postsa Ok instances of `SerializationConfig` should not be shared, generally, but since instances are immutable it should not be dangerous in itself. I'd have to check whether 2.x uses a shared copy when mappers are `copy()`ed.

But serializer cache should not be referenced by `SerializationConfig`: it is passed via `SerializerProvider` isn't it?

**Comment by postsa** [comment]
Yes the cache is passed via the Provider but the FilterProvider is passed via the SerializationConfig. What must be happening is that one object mapper is being reused by the same Provider with a different config on different calls.

But it sounds like your design intention was:
> Now: SerializerProvider is and MUST be used just for a single call. That is why it seems odd there would be any reuse -- if using ObjectMapper or ObjectReader there should be none; a new provider is created every time.

So somehow that is getting violated.

**Comment by cowtowncoder** [comment]
Perhaps this is not well documented, but `FilterProvider` instances should be stateless. You can assign default one on `ObjectMapper`, although it is preferable to create new `ObjectWriter`s with whatever `Provider` you want. But whichever you use, provider must be thread-safe (it is used concurrently) and should be immutable (if it does lazy-loading or caching that is fine as long as access is properly synchronized).
If this is true then one can use same provider on different mappers as well.

So I do not see this as a problem either, unless provider implementation is mutable.

**Comment by cowtowncoder** [comment]
Not sure what if anything to do here, closing. May be re-filed with explanation on the current situation (and link to this issue).
