### ISSUE TITLE
JsonValue returning UUID and constructor of UUID fail to deserialize

### ISSUE THREAD

**Issue by dcapwell** [FasterXML/jackson-databind#2308]
I have a interface `ID` which has a default method 

```
@JsonValue
UUID getId();
```

Implementations all have a constructor such as the following (generated by lombok)

```
public class RealID implement ID {
  @java.beans.ConstructorProperties({"id"})
  @lombok.Generated
  public RealID(UUID id) { ... }
}
```

In 2.8.11.3 this was able to deserialize from string such as `"7ac79a21-b391-4342-99fd-e2e312ed837f"`.  I upgraded to 2.9.8 and found this was no longer working, and would throw the following exception

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.example.RealID` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('7ac79a21-b391-4342-99fd-e2e312ed837f')
 at [Source: (String)""7ac79a21-b391-4342-99fd-e2e312ed837f""; line: 1, column: 1]
```

I tried 2.9.6 and 2.9.0 and see that this is the same behavior in those versions as well.

I tested older versions and see that this test started working in 2.7.5 and stopped working in 2.9.0

Thanks for your time!

**Comment by cowtowncoder** [comment]
The problem is that what you declare with `@ConstructorProperties` is structure:

```json
{
   "id" : UUID-AS-STRING
}
```

but what I guess you are trying to map is JSON String (based on having `@JsonValue`).

I think what changed was that before 2.8 `@ConstructorProperties` was only recognized if "jackson-datatype-jdk7" was included. Not sure how or why later versions might have worked.

But what is needed, if so, is to make sure constructor is recognized as "delegating" and not "properties-based". With Jackson Annotations this occurs with

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)

but removing `@ConstructorProperties` would also work.

**Comment by dcapwell** [comment]
> but removing @ConstructorProperties would also work.

Why is that? The docs for the mapper feature says that it should be treated as JsonCreator, now if I change the class to have a JsonCreator which takes a UUID then deserialization works just fine.

Why should replacing the annotation work when the docs claim they should be the same?

**Comment by cowtowncoder** [comment]
Because you are using annotation wrong, essentially.

`@ConstructorProperties` suggests that construct parameters are to be mapped to named properties: but what you seem to want, instead, is to map JSON String value into one String-parameter. If so, no name is associated. Documentation is correct in that `@ConstructorProperties` implied `@JsonCreator`, but unfortunately specific case of single-argument constructors is fundamentally ambiguous: so, say

```java
public class Value {
    @JsonCreator
    public Value(String value) {  ... }
```

could theoretically map from either

```json
"something"
```

or

```json
{
   "value" : "something"
}
```

There is a way to disambiguate this with

    @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)

but in case of `@ConstructorProperties` no such mechanism exists. But since it does provide explicit names, it is taken to always mean `Mode.PROPERTIES`.

Note, too, that behavior of `@ConstructorProperties` has not changed: but it was formerly only detected if `jackson-datatype-jdk7` module was registered (before version... 2.7 I think). But with later versions this functionality was embedded directly in `jackson-databind`.

Finally there is another configuration setting, added in 2.9

    MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES

disabling of which would prevent use of `@ConstructorProperties`. Perhaps you want to disable that.

But I would go with explicit route of `@JsonCreator(mode = Mode.DELEGATING)` personally.

**Comment by dcapwell** [comment]
Thank you so much for the details!

**Comment by dcapwell** [comment]
I tried out disabling `MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES` but I get the following exception

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `RealID` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('4c118e7b-7ffd-3525-839e-23fed1bd95ee')
```

Which makes sense since the constructor is

```
public RealID(java.util.UUID);
```

**Comment by dcapwell** [comment]
Since Lombok is creating the constructor, I can add the following as you say

```
@RequiredArgsConstructor(onConstructor_={@JsonCreator(mode = Mode.DELEGATING)})
```

**Comment by cowtowncoder** [comment]
Ah. Yes, auto-detection of delegation would only work for a small number of simple types (`String`, `int`/`long`/`boolean`), but `java.util.UUID` would not be found without marker.

So adding that via Lombok would make sense here.
