### ISSUE TITLE
`SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN` not taken into account when serializing `BigDecimal` as String

### ISSUE THREAD

**Issue by membersound** [FasterXML/jackson-databind#2323]
The following test should convert a `BigDecimal` number to `"3.033"` string in json. But in fact it only converts it to double.

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.assertEquals;

public class JacksonTest {
	public class MyDto {
		private BigDecimal number;

		public BigDecimal getNumber() {
			return number;
		}

		public void setNumber(BigDecimal number) {
			this.number = number;
		}
	}

	@Test
	public void testBigDecimalSerialization() throws Exception {
		ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN);
		MyDto dto = new MyDto();
		dto.number = new BigDecimal("3.033");
		String json = mapper.writeValueAsString(dto);

		assertEquals("{\"number\":\"3.033\"}", json);
	}
}

```

Result:
```
org.junit.ComparisonFailure: 
Expected :{"number":"3.033"}
Actual   :{"number":3.033}
```

jackson-databind-2.9.8

**Comment by cowtowncoder** [comment]
You may be misunderstanding function of `SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN`: it does not convert `BigDecimal` into JSON String, but simple enforces representation as "plain", not using scientific notation.

To force serialization of (all) numbers as JSON Strings, you can use `JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS`

**Comment by sddakoty** [comment]
Ok sorry, but that would force *any* numbers being returned as strings? Couldn't I enable this feature for BigDecimals only?

**Comment by cowtowncoder** [comment]
@sddakoty That would force all numbers as Strings on output.

Another method that should work would be use of `@JsonFormat`:

```java
public class POJO {
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    public BigDecimal value;
}
```

and you can actually define it for all values of a type, see "config overrides" on:

https://medium.com/@cowtowncoder/jackson-2-8-features-5fc692887944

for details. Hope this helps!

**Comment by sddakoty** [comment]
Could you give an example how I apply this `JsonFormat` for all `BigDecimals` in my applicaiton, without having to apply the annotation each time? Would it be as follows?

```
mapper.configOverride(BigDecimal.class).setFormat(JsonFormat.Value.forShape(JsonFormat.Shape.STRING));
```

**Comment by cowtowncoder** [comment]
@sddakoty Yes I think that should be it, wrt String output. However looking at code (`NumberSerializer.java`), format with `Shape.STRING` uses `ToStringSerializer`, which simply calls `value.toString()`. 

So it may actually be that this would not work if you want to avoid scientific notation.

I'll reopen this issue, reword it, to suggest that combination should be taken into account (so that you would combine the feature AND format to get what you want).
But in the meantime you will have to create a simple custom serializer I think, which looks like `ToStringSerializer` except using `toPlainString()`.

**Comment by sddakoty** [comment]
Got ok. So atm the only solution would be as follows, eg:
```
public class BigDecimalSerializer extends JsonSerializer<BigDecimal> {
        @Override
    public void serialize(BigDecimal value, JsonGenerator gen, SerializerProvider provider) throws IOException, JsonProcessingException {
        if (value != null) {
            gen.writeString(value.toPlainString());
        }
    }    
}
```

Indeed it would be great I one could configure this effect directly through some serialization feature.

**Comment by cowtowncoder** [comment]
@sddakoty Almost, but you can actually remove that if check there: serialize() method is never called with `null` value (null handling is separate and caller must handle it).

And yes I hope I find time to implement this in near future.

**Comment by cowtowncoder** [comment]
Actually, I think it already works; fixed with #2230, to be included in 2.10 (and is included in `2.10.0.pr1` already).

**Comment by membersound** [comment]
So what is the correct settings and configuration now with the fix, if I'd just want `BigDecimal` being written as plain string, and none of the other digits?

**Comment by cowtowncoder** [comment]
@membersound Usage question belong to user mailing list. This issue is specifically ensuring that setting `SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN` works not only when written as JSON number, but also when written as JSON String (i.e. within double-quotes).
So for plain serialization, just enable `SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN`.
