### ISSUE TITLE
JsonNode.withArray should return an ArrayNode

### ISSUE THREAD

**Issue by victornoel** [FasterXML/jackson-databind#2338]
I'm not sure why, but `JsonNode.withArray` returns a `JsonNode`.

This makes no real sense since its sole purpose is to retrieve an `ArrayNode` (and this is reflected in the returned value of `ObjectNode.withArray`).
Maybe I am missing something though…

I suppose this would be a non-breaking change in terms of API since `ArrayNode` is a subclass of `JsonNode`.

**Comment by victornoel** [comment]
If it breaks compatibility, please consider adding a new method until a new major version can be released, this is hell to use :)

**Comment by cowtowncoder** [comment]
No, this would be completely binary-breaking change unfortunately -- it's not source-compatible either, although in practice that should not be a problem.
The reason is that as return type is part of signature, included in bytecode, any existing code that uses method would not load due to linker error; method signature having changed so code compiled against old version would fail to load. Recompilation solve this but that would not necessarily happen for transitive dependencies.

Now, I agree that this is not useful in its current state. One possibility would be to try to use work around like

`<A extends JsonNode> withArray() { .... }`

which I think results in same signature (since generics are sort of hidden) and might improve usage.

Jackson 3.0 can change signature itself. I am not super happy with forward-reference of type (from base type to subtype) but there's probably no way to get past that any way.

**Comment by cowtowncoder** [comment]
I'll make signature in 2.10 be:

```java
public <T extends JsonNode> T withArray(String propertyName) { }
```

which should be slightly more convenient. And then for 3.0 will fix the signature.

**Comment by victornoel** [comment]
@cowtowncoder great solution, please consider doing the same for #2339 :)

**Comment by cowtowncoder** [comment]
WIll do, thanks!
