### ISSUE TITLE
Suboptimal return type for `ObjectNode.set()`

### ISSUE THREAD

**Issue by victornoel** [FasterXML/jackson-databind#2339]
As it has been reported multiple time, `ObjectNode.set` (and possibly other methods that exist for chaining)  is returning the wrong type.

As in #2338, please consider introducing a workaround for 2.10 (I think the fix for 3.0 is already present).

Thanks

**Comment by cowtowncoder** [comment]
Note: also changed `without()` methods that had similar problems. Observed that `ArrayNode.set()` is inconsistent with `ObjectNode.set()` (for historical reasons, I presume). Merging to `master` (3.0) found out that all these problems had been fixed for `3.0` (so `ArrayNode` now has `replace()`/`set()` similar to `ObjectNode`).

Thank you for suggestions here, and I hope these are useful: co-variant helps in some cases but not in all

**Comment by victornoel** [comment]
yep, now that I'm thinking about it, I realize it won't help with chaining I fear :/
@cowtowncoder do you have an ETA for 3.0 btw? :)

**Comment by cowtowncoder** [comment]
@victornoel Unfortunately no ETA for 3.0 -- currently focusing on getting 2.10.0.pr1 out during June. Once 2.10.0 final goes out, focus can move back to 3.0 (well, probably plenty of bugfixing right after 2.10.0, but maybe couple of weeks afterwards). Challenge is that since major API upgrade is a good opportunity to fix issues that are difficult or impossible to do otherwise, many things pile up.
I don't think it can be out before something Sep/Oct 2019, although perhaps first pre-release could.

On plus side some work has been retrofitted in 2.10 (and some could be) which may help finalizing of 3.0.
