### ISSUE TITLE
Custom deserializer provide parent object.

### ISSUE THREAD

**Issue by cpdyj** [FasterXML/jackson-databind#2340]
In fact I use kotlin. Thank you.

```json
{"a": {"va": "sth", "vb": "sth"}}
```
```kotlin
class A @JsonCreator constructor(
    val a: B
)

@Deserializer(using=...) // In fact shouldn't! Otherwise the deserialization may fall in infinite-recursive (in some context).
class B @JsonCreator constructor(
    val va:String,
    val vb:String
)
```

The problem is in `deserialize(p: JsonParser?, ctxt: DeserializationContext?): InputMessageContent` . 
When I use `p.readValueAsTree` , it will return A instead of B.  
But if I call `p.nextToken()` before, the problem will be resolved.   
Is it a bug? Otherwise how to get B gracefully?

Previous discussion: [Google group](https://groups.google.com/d/topic/jackson-user/9_duBjglFlE/discussion)
Thank you.

PS: I use the lastest verison: 2.9.9

**Comment by cowtowncoder** [comment]
Would it be possible to provide a plain Java reproduction? Since there are 2 areas where the problem might occur -- core Jackson components (jackson-core or jackson-databind), or Kotlin module -- it is necessary to first isolate that.. Further, core components can not have any dependency to Kotlin runtimes, so investigation needs to either start from Kotlin module side, or from databind side (with no Kotlin). I am fine doing latter, although if you prefer, you can alternatively move this issue to Kotlin (there is new "transfer issue" functionality in Github). If you need help with latter let me know (not sure how access rights work wrt issues).

**Comment by cpdyj** [comment]
Looks I am not add jackson-kotlin-module to my project. I will retry with plain Java language.
And because in kotlin, subclass will include parent class's annotations. Jackson annotation will not work good as Java.

**Comment by cowtowncoder** [comment]
@cpdyj Jackson will handle annotation inheritance on its own, does not rely on JDK runtime. So that works just fine on just Java too.

**Comment by cpdyj** [comment]
@cowtowncoder
Oh, if I add @Deserializer annotation on parent class. Then call `treeToValue` with Subclass in custom deserializer. Deserializer will fall in infinite-recursive.
Is it by designed?

**Comment by cowtowncoder** [comment]
@cpdyj I can't say without seeing full code (unit test).

**Comment by cpdyj** [comment]
Thank you. When I register Kotlin Module to ObjectMapper. The problem is solved. Even I don' t know that's why.

**Comment by cowtowncoder** [comment]
@cpdyj Ok that is interesting. But yes, if you are dealing with Kotlin objects (as opposed to plain java). you should use Kotlin module; there are a few things that need additional support to work correctly.
