### ISSUE TITLE
ArrayNode should implement RandomAccess and List

### ISSUE THREAD

**Issue by victornoel** [FasterXML/jackson-databind#2342]
It would make sense that `ArrayNode` implement `RandomAccess` and `List` to ease its use with other libraries and classes that relies on those abstractions.

**Comment by cowtowncoder** [comment]
I am -1 for `List` (same way as `ObjectNode` is not and IMO should not be `Map`) and decision to encapsulate container was deliberate. Part of this is philosophical (`ArrayNode` really isn't just a basic List or Collection and should not be treated as such) and part practical (implementing `List` is a sizable undertaking).

And since `RandomAccess` is a tag interface there's probably no real benefit.

I am open to other means of improving interoperatibility, esp. via Java 8 Streams.

**Comment by victornoel** [comment]
@cowtowncoder ah indeed, I see your point. I suppose that if I want to use an `ArrayNode` as a `List`, it would be better to write an adapter relying on the already existing methods that are similar to `List`'s.

I'm not a user of streams (I believe they are not a very good OO solution to the collection domain), I prefer to use object-oriented libraries such as eclipse-collection. I usually wrap something based on the JRE libraries (hence my need for implementing `List`) with an adapter coming from eclipse-collection and then use their abstractions to work with collections.

**Comment by cowtowncoder** [comment]
FWTW I think that besides Streams, Iterable/Iterator integration (better one) would make sense for 3.0.
2.x botched this part as I recall, preventing use of more convenient for loops (for example); `Iterator` is less convenient to use.
