### ISSUE TITLE
Getter affects property serialization in a weird way

### ISSUE THREAD

**Issue by myskov** [FasterXML/jackson-databind#2345]
I faced some weird behaviour in serialization. Let's assume we have the following code:

```java
public class Main {
    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();
        TestClass testClass = new TestClass(1L);

        try {
            String s = mapper.writeValueAsString(testClass);
            System.out.println(s);
        } catch (Exception e) {}
    }
}

class TestClass {
    @JsonProperty("property") private Long prop = null;

    public TestClass(Long prop) {
        this.prop = prop;
    }

    public Long getProperty() {
        return 30L;
    }
}
```

The result is 
```json
{"property":30}
```

And it's correct, jackson detects that the getter and the property are the same entity. But if we will change JsonProperty value to "Property" (the only difference is that the first letter is capitalized), the result is different:

```json
{"property":30,"Property":1}
```

And now it is weird. I checked some combinations, here they are:

|getter variant | jsonproperty variant| result
|----|---|-----|
|getProperty|property | {"property":30}
|getProperty|Property|{"property":30,"Property":1}
|getPRoperty |pRoperty | {"property":30,"pRoperty":1}
|getPrOperty| prOperty| {"prOperty":30}|

So the result depends on what character is in uppercase. This is clearly wrong from my point of view, because this is not obvious.
I tested the latest version (2.9.9)

**Comment by cowtowncoder** [comment]
No, this is as expected.

First of all, json handling by default (and Java's handling of property names) is case-sensitive.

Second, Jackson has to figure out combination of accessors (field, getter, setter, constructor argument) that form a logical property: this requires that names from accessor (like "property" from "getProperty") match exactly. Field named "Property" implied property with name of "Property". That is not same as "property".

So... you do need to either follow Java's Bean naming convention or use annotations to indicate how accessors match.

But this is just part of the puzzle: it defines how getter/setter/field are combined.

If you want property expressed using different name in JSON, that is easy enough to handle. Once names match you can add annotation in appropriate place: in this case you'd move it next to getter or setter:

```java
@JsonProperty("Property")
public Long getProperty() { ... }
```

Further, if you just want to use "upper camel-case" (like SomeOtherProperty instead of someOtherProperty), you can specify `PropertyNamingStrategy` either:

* With `@JsonNaming` annotation on POJO
* Configuring default strategy with `ObjectMapper.setPropertyNamingStrategy()`

f.ex see: https://dzone.com/articles/jackson-property-custom-naming-strategy

so what you want I think is `UPPER_CAMEL_CASE`
