### ISSUE TITLE
JsonSerializable not using custom serializer of wrapped type

### ISSUE THREAD

**Issue by btruhand** [FasterXML/jackson-databind#2373]
I had a custom serializer for Double type to handle NaN data stored to be serialized as null. The thing is, the data is of type JsonNode in Java because that was the easiest thing I figured to use when having JSON whose content you don't necessarily care about.

What I then realized is that my custom Double serializer was not being used and after debugging I noticed that https://github.com/FasterXML/jackson-databind/blob/c75e810252098ac38c343c51860cabc92f295b50/src/main/java/com/fasterxml/jackson/databind/node/DoubleNode.java#L102 does not use any custom serializer. `_value` is of type double but as I understand I can do this

```java
module.addSerializer(double.class, new MySerializer());
```

to register a serializer to a primitive type. I was wondering if it is desirable to chaneg the `JsonSerializable` classes (at least for those wrapping primitive types directly) to try and get a custom serializer if available and go with the current behaviour if there is none

Jackson databind version I am using is `2.9.8`

**Comment by cowtowncoder** [comment]
When using `JsonNode`, serialization will not try to use handles for apparent content type: `TextNode` will not try to find serializer for `String`, nor `DoubleNode` for `Double`. This is by design, and not a bug. If you want to override handling, you will need to override whole `JsonNode` handling.
(it is also not sufficient to try to specify override for child nodes: default `JsonNodeSerializer` will not delegate to custom serializers -- but you can replace that first-level serializer).

So behavior is as expected: `JsonNode` is not a POJO type as far as `jackson-databind` is concerned.
