### ISSUE TITLE
when serialize Date(value: 1900-01-02 00:00:00 )，I add @JsonFormat for field，the result is not correct

### ISSUE THREAD

**Issue by lqw187927** [FasterXML/jackson-databind#2380]
```java
public class Main {
    public static void main(String []args) throws JsonProcessingException, ParseException {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = format.parse("1900-01-02 00:00:00");
        ObjectMapper mapper = new ObjectMapper();
        Obj obj = new Obj();
        obj.setDate(date);
       String ss = mapper.writeValueAsString(obj);
       System.out.println(ss);
    }
}
```

```java
class Obj {
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}
```

if `@JsonFormat` is not added，the result is correct，but when add `@JsonFormat` ，the result is not correct。
I run above code，the result is ：ss = {"date":"1900-01-01 23:54:17"}

**Comment by cowtowncoder** [comment]
Is not correct in what way?

**Comment by lqw187927** [comment]
> Is not correct in what way?

when the value of date is 1900-01-02 00:00:00, and the Date field is decorated with @JsonFormat,  the serialized result is not correct。you can see above code。

**Comment by cowtowncoder** [comment]
Above code does not say much: you are not including timezones, and value "1900-01-02 00:00:00" has no real meaning without timezone. Unfortunately `java.util.Date` has internal timestamp (numeric value of milliseconds since January 1st, 1970, UTC) but no timezone information, so if you simply print it out, string you get varies depending on your local timezone settings.
To include timezone information, you must use `java.util.Calendar`, or better yet either Joda or Java 8 date time values.

Serializing date/time values without timezone is not a good idea because underlying time value is then unspecified and (in Java at least) depends on local timezone settings. That is, date/time value being serialized will be deserialized likely as something else unless both sides somehow agree on which timezone to use.

To preserve timezone you should add zone indicator (I think that is `Z`?) in format strings.

**Comment by lqw187927** [comment]
> Above code does not say much: you are not including timezones, and value "1900-01-02 00:00:00" has no real meaning without timezone. Unfortunately java.util.Date has internal timestamp (numeric value of milliseconds since January 1st, 1970, UTC) but no timezone information, so if you simply print it out, string you get varies depending on your local timezone settings.
> To include timezone information, you must use java.util.Calendar, or better yet either Joda or Java 8 date time values.
> Serializing date/time values without timezone is not a good idea because underlying time value is then unspecified and (in Java at least) depends on local timezone settings. That is, date/time value being serialized will be deserialized likely as something else unless both sides somehow agree on which timezone to use.
> To preserve timezone you should add zone indicator (I think that is Z?) in format strings.

thank you vary much， you reply resolve my question perfectly
