### ISSUE TITLE
jackson version problem

### ISSUE THREAD

**Issue by chengbinghan** [FasterXML/jackson-databind#2396]
hi
   Thanks for jackson-x lib , it can reduce our workload。
    Now we use jackson-X lib ,detail is:

   jackson-core-2.9.8.jar
   jackson-annotations-2.9.0.jar
   jackson-databind-2.9.8.jar

   Now, for some reason ,we must use  jackson-databind which version is 2.9.9.1 ， can we only 
 change the  jackson-databind to 2.9.9.1 version, the jackson-core and jackson annotations is 2.9.8 version still ?

thanks

**Comment by cowtowncoder** [comment]
Ok, I should update FAQ, but here's summary:

* Versions with 3 digits are full major releases, with all components (although `jackson-annotations` never changes in patches and only 2 digits matter). So you use that as base
* Sometimes at or close to end of life for a branch, so-called micro-patches -- ones with 4 digits -- are released. These are independent releases used in cases where critical fixes are needed but overhead of full release is not warranted (and/or branch is not considered open any more).

So in this particular case, use:

* `2.9.9` (latest full release) for everything, except
    * `2.9.9.1` for `jackson-databind`
    * For annotations you have 2 choices: `2.9.0` or `2.9.9` -- they are identical (as are intermediate versions), but it depends on preferences (some people prefer using "same for everything", i.e. 2.9.9, others "2.9.0" as there are no further changes)

But I would also suggest you to have a look at `jackson-bom`: it is pom-only set of default versions for Jackson components (bom == Bill of Materials):

    https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom

since there is `2.9.9` but also later `2.9.9.20190727` which has version `2.9.9.2` (latest micro-patch) for `jackson-databind`.
