### ISSUE TITLE
type info is not useful when use hashmap double curly brace initialization 

### ISSUE THREAD

**Issue by GTxx** [FasterXML/jackson-databind#2441]
We use jackson for cache, and config jackson to output type info for deserializing data.
One problem we meet is if we use double curly brace initialization for map, then jackson would output  anonymous type to serialized data like **Person$1**, in such case, deserialization would fail because jackson don't know what **Person$1** type is and of cause can't construct it.

Can jackson add some mechanism to handle such case to output the actual useful type? 

Below is the code to reproduce this issue, and jackson version is 2.9.9:
```java
public class Person {
    private Map<String, String> attr;
    private String name;
    // omit getter setter

    static public void main(String[] args) throws JsonProcessingException {
      Person person = new Person();

      person.setName("alan");
      person.setAttr(new HashMap<String, String>() {{
        put("age", "10");
      }});

      ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);
      System.out.println(objectMapper.writeValueAsString(person));
      // the serialized string is ["Person$1",{"1":"2"}]
    }
  }
```

**Comment by cowtowncoder** [comment]
Unfortunately this use case can not be supported because you are using a non-static anonymous inner class -- there is no way to deserialize it, no matter what. Anonymous inner class with generated name comes from your construct:

```
new HashMap<String, String>() {{
        put("age", "10");
}});
```

which generates a new class, sub-class of `HashMap`, with reference to surrounding `Person` passed as invisible first argument to constructor.

To solve the issue, just construct `HashMap` explicitly, add elements, and do not use anonymous sub-class.
