### ISSUE TITLE
`ArrayNode.addAll()` adds raw `null` values which cause NPE on `deepCopy()` and `toString()`

### ISSUE THREAD

**Issue by heshamMassoud** [FasterXML/jackson-databind#2442]
Version: **`2.9.9`** 

When I create an `ArrayNode` and use `ArrayNode#addAll` to add elements containing a raw `null` element as follows:

```java
final List<ObjectNode> nodes = Arrays.asList(null, JsonNodeFactory.instance.objectNode());
final ArrayNode arrayNode = JsonNodeFactory.instance.arrayNode();
arrayNode.addAll(nodes);
```
Calling `ArrayNode#deepCopy` and `ArrayNode#toString` on such `arrayNode` will throw `NullPointerException`s.

However, if we add the nodes using `ArrayNode#add` as follows:

```java
final ArrayNode arrayNode = JsonNodeFactory.instance.arrayNode();
arrayNode.add((JsonNode) null);
arrayNode.add(JsonNodeFactory.instance.objectNode());
```
Calling `ArrayNode#deepCopy` and `ArrayNode#toString` on such `arrayNode` will **NOT** throw any `NullPointerException`s.

This is because `ArrayNode#add` converts any raw `null` to a `NullNode` object: 
https://github.com/FasterXML/jackson-databind/blob/f75b304c069ed8b2aef9c6afec5a49f304ef8205/src/main/java/com/fasterxml/jackson/databind/node/ArrayNode.java#L306-L313

But `ArrayNode#addAll` does not. But It should, otherwise how does one deepCopy an arrayNode that contains `null` raw elements?

**Comment by cowtowncoder** [comment]
First of all: thank you for reporting the issue! Yes, that looks like a problem, although surprisingly one that has not been reported before. I agree that raw `null` is not to be added; and to me it seems there are 2 possibilities: either automatically "upgrade" `null` as is done in a few other places, or throw an exception to indicate invalid value.

It seems reasonable to expect former, so that `null`s would be automatically coerced, given that this happens elsewhere.

I'll think about this bit more, and will get fixed for `2.10` to be included in 2.10.0.

**Comment by heshamMassoud** [comment]
Hi @cowtowncoder, thanks for the quick reply. I also agree with you about the former being the more suitable solution to be consistent with the rest of the methods. 

I attempted to provide a fix for it here: https://github.com/FasterXML/jackson-databind/pull/2443

**Comment by heshamMassoud** [comment]
any expected date when 2.10.0 will be released?

**Comment by cowtowncoder** [comment]
@heshamMassoud Hoping to release before end of September, ideally within 2 weeks.
