### ISSUE TITLE
Didn't find class "java.nio.file.Path" below Android api 26

### ISSUE THREAD

**Issue by KevynBct** [FasterXML/jackson-databind#2466]
Hello, 

With the version 2.10.0.pr3, I've got an error on simulators (and certainly real devices) with an API below 26 :

`
09-19 17:16:36.077 26359-26359/XX.XXXXX.XXXXX E/AndroidRuntime: FATAL EXCEPTION: main
    Process: XX.XXXXX.XXXXX, PID: 26359
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
        at com.fasterxml.jackson.databind.ext.Java7HandlersImpl.getDeserializerForJavaNioFilePath(Java7HandlersImpl.java:20)
`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Path" on path: DexPathList[[zip file "/data/app/XX.XXXXX.XXXXX-1/base.apk", zip file "/data/app/XX.XXXXX.XXXXX-1/split_config.fr.apk", zip file "/data/app/XX.XXXXX.XXXXX-1/split_config.xxxhdpi.apk"],nativeLibraryDirectories=[/data/app/XX.XXXXX.XXXXX-1/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)`

**Comment by cowtowncoder** [comment]
I think this is not Kotlin-specifc, so moving to `jackson-databind`.

Thank you for reporting the problem! This sounds like regresssion? Code in question was refactored and it is possible that handling of not finding JDK 7 class got broken: intent is for missing class to be handled gracefully, to allow running on platforms like Android that have JavaSE 6 (or close) level compatibility.

Do you know (or can test) if `2.10.0.pr2` suffers from same issue? I am guessing it wouldn't (there would be a log statement indicating missing type or something, but no exception)

**Comment by cowtowncoder** [comment]
Hmmh. Ok, I suspect this is because of my assuming that simply loading a class that depends on another class would trigger failure (on lines 23-24 of `Java7Handlers`), and that failure would be caught.

But based on symptoms, I guess loading works ok (alas!) and the problem comes from trying to call a method that actually refers to the class that is missing.

In hindsight this makes sense -- I think I will need to shuffle things around, and cause early failure, instead of deferred one.
The main challenge here is simply that I have no good way to test it.
