### ISSUE TITLE
make more use of generics in APIs (3.0 release)

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#2470]
This is just one example - but this could possibly be changed to something like `public final SerializerAndMapResult addSerializer<T>(Class<?> type, JsonSerializer<T> serializer)`

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/impl/PropertySerializerMap.java#L125

I was looking at https://github.com/FasterXML/jackson-module-scala/issues/431 and having to introduce a lot more casts in the code to get things to compile.

**Comment by cowtowncoder** [comment]
Or, possibly just changing `<Object>` to `<?>` as there are some challenges to keeping type casts working, and fundamentally this particular constraint won't help too much I feel, based on experience.
I have been relaxing some of these constraints since handling at lower level has to use "untyped" approach anyway (to get/put `Object`s). I know there is some benefit at user level, for preventing certain simple mistakes, but internally it adds need for workarounds with not much benefit.
