### ISSUE TITLE
Deserialization of Untrusted Data CWE ID 502

### ISSUE THREAD

**Issue by shyamalendukar** [FasterXML/jackson-databind#2497]
Veracode scan identified this flaw "Deserialization of Untrusted Data CWE ID 502" in jackson databind. The line of code which it marks vulnerable is

return new ObjectMapper().readValue(jsonResponse, new TypeReference<Collection<String>>() {
});

We are using 2.8.8 jackson databind version.

Can anyone let us know if this issue is fixed in some later version of jackson.

**Comment by cowtowncoder** [comment]
That seems like a bullshit warning. I can not think of any reason for that to be unsafe.
So I think it would be up to vendor of said tool to explain exactly why they think a perfectly normal deserialization call has some unexplained security problems.

I really really despise security tool vendors who have seemingly zero responsibility for false alerts that cause unnecessary concern and waster work hours. "Whops, our bad -- better safe than sorry".

Also: next time it'd be good to do more digging into alleged problem: in this case code sample fortunately is so simple that it sort of clears the issue.

Having said all of that I would recommend upgrade to either 2.9 (2.9.10 is the latest stable patch, and likely last full patch), or, 2.10.0 (first 2.10 release). There are many fixes there.

**Comment by cowtowncoder** [comment]
One minor addition: CWE just defines general type of issue. What would be needed, usually, is specific CVE ("instance" of security problem) of that type. Tool in question should provide that.
Simple search turned out only case(s) of C# (I think) issue of NewtonSoft's json library:

* https://community.veracode.com/s/question/0D52T00004i0Wgq/fix-deserialization-of-untrusted-data-cwe-id-502

**Comment by cowtowncoder** [comment]
Would need more information on this: may be opened if such provided.
