### ISSUE TITLE
Serializing ObjectNode doesn't respect SORT_PROPERTIES_ALPHABETICALLY or ORDER_MAP_ENTRIES_BY_KEYS

### ISSUE THREAD

**Issue by imgx64** [FasterXML/jackson-databind#2507]
When serializing `ObjectNode` with `SORT_PROPERTIES_ALPHABETICALLY` and `ORDER_MAP_ENTRIES_BY_KEYS`, the output JSON is still not ordered.

To reproduce, this code:
```java
ObjectMapper stableObjectMapper = new ObjectMapper() //
		.enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY) //
		.enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);

ObjectNode jsonObj = JsonNodeFactory.instance.objectNode() //
		.put("b", "second") //
		.put("a", "first");

System.out.println(stableObjectMapper.writeValueAsString(jsonObj));
```

Prints `{"b":"second","a":"first"}`. I expect it to print `{"a":"first","b":"second"}`

I simply want an ObjectMapper that always outputs a "canonical" JSON representation, no matter the source.

### Version
```xml
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.10.0</version>
</dependency>
```

**Comment by cowtowncoder** [comment]
Correct: "property" only refers to Bean properties and `JsonNode` representations are not Beans.
So this works as expected.

But I am hoping to build a good way to configure handling of `JsonNode` serialization/deserialization under:

https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-3

so that similar feature could be used. But as things are, `JsonNode` is designed to be used for exact mapping of content, with no transformations or changes. This means that sorting and filtering are not, for example, applied.

Unfortunately for this case there is no good way to implement sorting, externally, except by constructing new instance and adding properties in exact order (underlying storage uses `LinkedHashMap` and does retain ordering).
