### ISSUE TITLE
Serialization of constant value creates two entries

### ISSUE THREAD

**Issue by jwedel** [FasterXML/jackson-databind#2552]
Serialization of one constant value creates two entries with different keys.

# Steps to reproduce:
Given the following class (including test to reproduce issue): 

```
@DisplayName( "Test constant value serialization" )
class ConstantTest {
   @Data
   class TestPojo {
      @JsonProperty("content-spec")
      private String CONTENT_SPEC = "This wont be changed";
   }

   @Test
   @DisplayName( "should contain content spec" )
   @SneakyThrows
   void shouldContainContentSpec() {
      TestPojo value = new TestPojo();
      String payload = new ObjectMapper().writeValueAsString( value );

      assertThat( payload ).isEqualTo( "{\"content-spec\":\"This wont be changed\"}" );
   }
}
```

# Actual Behaviour

Results in the following output:
```
{
  "content_SPEC": "This wont be changed",
  "content-spec": "This wont be changed"
}
```

Note the two key/value pairs and that the word "SPEC" is uppercased while "content" is not.

# Expected Behaviour

```
{
  "content-spec": "This wont be changed"
}
```

# Additional hints:
- It works as expected when renaming the field to `contentSpec`.
- When removing the `@JsonProperty` annotation, only the `content_SPEC` key is left.
- Version 2.9.9.3

**Comment by cowtowncoder** [comment]
So, not sure where `@Data` comes from, but it is not something Jackson itself understands or handles, so what would be needed here is either post-processed actual class definition (assuming this is with plain Java). Framework (Lombok?) that handles this annotation probably adds something like getter/setters, and details of how those look like determine how things work, and whether Jackson handles that as expected (from its definition of handling -- which may not work with Lombok/auto-values/etc).

**Comment by jwedel** [comment]
Yes, `@Data` comes from Lombok, it adds getters, setters and constructor.

**Comment by jwedel** [comment]
What is the suggested way to serialize a constant anyway?

**Comment by cowtowncoder** [comment]
@jwedel I don't know if there is anything special about constants, but they are often represented as Java enums. It may also make sense to use `@JsonValue` / `@JsonCreator` combo to  -- for example -- serialize objects as simple JSON String, instead of JSON Object.

But as to Lombok the key is that Jackson does not see definition as defined above; it will see end result of Lombok's augmentation with a few other things; fields, methods, possibly annotations added. So source of that would be useful in knowing why annotation that you are (correctly) using did not match with other accessors (field, getter/setter) that were added.

**Comment by jwedel** [comment]
I was asking about constants because usually constants are `public static final` which won’t get serialized even with an annotation.

**Comment by jwedel** [comment]
You can just add Lombok to a project to check but when I am back at work, I will send the generated I file. Lombok generates Byte code, not java sources.

**Comment by cowtowncoder** [comment]
Correct, static members are not serializer or deserialized as they are not part of instances but class definitions.

**Comment by jwedel** [comment]
@cowtowncoder 
This is the decompiled generated class file:
```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.bosch.bci.ppm.ppmp;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Generated;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Test constant value serialization")
class ConstantTest {
   ConstantTest() {
   }

   @Test
   @DisplayName("should contain content spec")
   void shouldContainContentSpec() {
      try {
         ConstantTest.TestPojo value = new ConstantTest.TestPojo();
         String payload = (new ObjectMapper()).writeValueAsString(value);
         Assertions.assertThat(payload).isEqualTo("{\"content-spec\":\"This wont be changed\"}");
      } catch (Throwable var3) {
         throw var3;
      }
   }

   class TestPojo {
      @JsonProperty("content-spec")
      private String CONTENT_SPEC = "This wont be changed";

      @Generated
      public TestPojo() {
      }

      @Generated
      public String getCONTENT_SPEC() {
         return this.CONTENT_SPEC;
      }

      @Generated
      public void setCONTENT_SPEC(String CONTENT_SPEC) {
         this.CONTENT_SPEC = CONTENT_SPEC;
      }

      @Generated
      public boolean equals(Object o) {
         if (o == this) {
            return true;
         } else if (!(o instanceof ConstantTest.TestPojo)) {
            return false;
         } else {
            ConstantTest.TestPojo other = (ConstantTest.TestPojo)o;
            if (!other.canEqual(this)) {
               return false;
            } else {
               Object this$CONTENT_SPEC = this.getCONTENT_SPEC();
               Object other$CONTENT_SPEC = other.getCONTENT_SPEC();
               if (this$CONTENT_SPEC == null) {
                  if (other$CONTENT_SPEC != null) {
                     return false;
                  }
               } else if (!this$CONTENT_SPEC.equals(other$CONTENT_SPEC)) {
                  return false;
               }

               return true;
            }
         }
      }

      @Generated
      protected boolean canEqual(Object other) {
         return other instanceof ConstantTest.TestPojo;
      }

      @Generated
      public int hashCode() {
         int PRIME = true;
         int resultx = 1;
         Object $CONTENT_SPEC = this.getCONTENT_SPEC();
         int result = resultx * 59 + ($CONTENT_SPEC == null ? 43 : $CONTENT_SPEC.hashCode());
         return result;
      }

      @Generated
      public String toString() {
         return "ConstantTest.TestPojo(CONTENT_SPEC=" + this.getCONTENT_SPEC() + ")";
      }
   }
}
```
The issue here might be the non-conform getter `getCONENT_SPEC`.

> Correct, static members are not serializer or deserialized as they are not part of instances but class definitions.

So how would you design a class that holds a class-specific constant (aka static) that will never change (aka final) that should be serialized? `@JsonValue` and  `@JsonCreator` seems to be a bit to much such a simple thing. I don't want to write a method to return a constant value.

**Comment by cowtowncoder** [comment]
On "class-specific" constant: I don't think I understand what you are trying to achieve here, so I can't really help with it.

But behavior in this case is actually relatively straight-forward. Jackson sees 3 significant accessors:

```
@JsonProperty("content-spec")
      private String CONTENT_SPEC 

      public String getCONTENT_SPEC() { }
      public void setCONTENT_SPEC(String CONTENT_SPEC) { }
```

which infer existence of 2 properties:

1. field `CONTENT_SPEC` is detected only because of annotation (otherwise `private` visibility would not be enough); its "implicit" name is `CONTENT_SPEC`, but explicit annotation renames it as `content-spec`
2. getter/setter with implicit name of `content_SPEC` (as per Bean naming convention -- although this is somewhat unusual case)

and since there is nothing to connect (1) and (2) (neither implicit nor explicit names match), they are considered separate properties.

This is unusual case as more commonly Bean style naming would use something more like

```
private String contentSpec;

public String getContentSpec() { }
public void setContentSpec(String s) { }
```

in which case implicit names for all would be `contentSpec` and thereby connected to represent just one logical property.

To connect field and getter/setter, one more `@JsonProperty` (on either getter OR setter, doesn't matter) could be used to avoid duplication.
Or, conversely, prevent addition of `@JsonProperty` on field (or even add `@JsonIgnore`) would prevent its inferring existence of second property.

Given this I think system works as designed, although not ideally from viewpoint of this specific use case.

**Comment by jwedel** [comment]
@cowtowncoder 
It's a bit weird, that the word "CONTENT" is lower-cased but, OK. So, based on your valuable input, here is the fixed version with lombok (for anyone who is interested):

```
@DisplayName( "Test constant value serialization" )
class ConstantTest {
   @Data
   @Getter()
   class TestPojo {
      @JsonProperty( "content-spec" )
      @Getter( AccessLevel.NONE )
      @Setter( AccessLevel.NONE )
      private String CONTENT_SPEC = "This wont be changed";
   }

   @Test
   @DisplayName( "should contain content spec" )
   @SneakyThrows
   void shouldContainContentSpec() {
      TestPojo value = new TestPojo();
      String payload = new ObjectMapper().writeValueAsString( value );

      assertThat( payload ).isEqualTo( "{\"content-spec\":\"This wont be changed\"}" );
   }
}
```

This test actually succeeds. What did I do:
- I disabled getter/setter generation for the constant value.  Obviously, it doesn't make sense to annotate the class with `@Data` but usually, you have more fields that also requires to have getter/setter.

Now, there is no getter for `CONTENT_SPEC` and jackson will only pickup the annotation and will correctly serialize it.

**Comment by cowtowncoder** [comment]
Thank you for fully documenting the work-around needed in this case; other users will probably find this useful as well!

Some more information just in case it might be useful...

Lower-casing or not of "CONTENT" is actually one aspect that is configurable: default one Jackson uses deviates from standard Bean naming convention I think. Setting to change is:

    MapperFeature.USE_STD_BEAN_NAMING

which defaults to `false` for backwards-compatibility reasons. When enabled, inferred name would remain `CONTENT_SPEC` (because there is more than one capital letter starting name part), whereas legacy default setting would lower-case the continuous upper-case letter segment, to come up with `content_SPEC` (underscore ending the segment).
It is actually possible to further re-configure aspects of casing with `PropertyNamingStrategy`, but that is more geared towards different style in JSON, not on POJO method naming.
