### ISSUE TITLE
Conflicting setter definitions for  property of Scala class

### ISSUE THREAD

**Issue by kgignatyev** [FasterXML/jackson-databind#256]
I wrongly filed this for scala module, but the databind is the cause
https://github.com/FasterXML/jackson-module-scala/issues/88

temporary fix is to add this after line 210 of com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder
            if( nextSetter.getName().endsWith("$eq")){
                continue;//by some reasons scala generated $eq methods are among setters
            }

this issue popped up when I started migration of project to Scala 2.10.2 from 2.9.3 and updated jackson version to 2.2.2

**Comment by Sergey80** [comment]
2.5.1 I can see same issue (can not update for latest). So what is workaround ?

**Comment by cowtowncoder** [comment]
@Sergey80 You can always update to the latest patch version, so at least you can try 2.5.3. This may or may not solve the problem but at least would rule out solution.

But I can not work on this issue without having some code that does not use or rely on Scala, even if the underlying problem was on `jackson-databind` side. I will instead reopen report on Scala side assuming problem, whatever it is, still exists.

For issues on databind side we would need a java-only reproduction showing the underlying problem, fixing of which would either solve Scala problem, or at least allow Scala module to fix it.

**Comment by Sergey80** [comment]
In my case it is about:
 ```
  class RefData ... {
  @JsonProperty("SettlementDate")
  @BeanProperty
  var settlementDate:String = null
```
jackson & ackson-module-scala-2.10 is v. 2.5.1
(and I can not use another newer version for that project I work on)

So I got error java.lang.ExceptionInInitializerError:
``
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "SettlementDate": RefData#setSettlementDate(1 params) vs RefData#settlementDate_$eq(1 params)

at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242)
```

So I wonder what could be the workaround.

**Comment by Sergey80** [comment]
Just update so my workaround is:
``
 @JsonProperty("Settlement")
  @BeanProperty
  var s: String = _  // instead of settlement
``

I more interested in workaround than in fix. since I can not upgrade the lib in that project anyway.

**Comment by parsnips** [comment]
@cowtowncoder @Sergey80 I just ran into this issue with the `BeanProperty` and literally it was the word "settlement" in a property name (scala class) in both cases (jackson-databind version 2.6.7). 

eg
```scala
@BeanProperty var settlementEmail = ""
```

and 

```scala
@BeanProperty var settlementAccount = ""
```

Once changing the names of these to something else, the problem went away.
