### ISSUE TITLE
BeanProperty always null in createContextual for ContextualSerializer

### ISSUE THREAD

**Issue by sonOfRa** [FasterXML/jackson-databind#2585]
When using a contextual Serializer on a field that is marked with @JsonValue, the BeanProperty passed to createContextual seems to always be null, leading to an NPE in my code. The context in this case is an annotation on the field that tells the serialization how many digits of a BigDecimal to serialize, so simply creating a non-contextual instance in this case leads to incorrect behaviour.

I created a small repository that demos the problem here: https://github.com/sonOfRa/jackson-serialize. The code can be run with ``mvn test``, which will result in a JsonMappingException, caused by a NullpointerException because the bean property is null.

In a previous version, we simply had a single serializer instance for each possible value of @Precision that occurred in our code, but this seemed like a smell to us so we implemented the contextual serializer. Are contextual serializers just not meant to be used in conjunction with @JsonValue?

**Comment by cowtowncoder** [comment]
Thank you for reporting this issue.

Hmmh. I'd have to look into details to know for sure if `BeanProperty` is available at the point it would be needed. Ideally it should be available, I think, but the problem comes from the fact that it is sort of "unwrapping" operation and Jackson often has no mechanism for bridging that gap.
But then again it might be easy/easier to fix...

**Comment by cowtowncoder** [comment]
@sonOfRa Ah. This may be misunderstanding on what exactly would be Property (as Jackson defines it); it is not field that `@JsonValue` attaches to, but something that refers to value. So, if we had:

```
public class Wrapper {
    public Amount wrappedAmount;
}

public class Amount {
    @JsonValue
    BigDecimal value;
}
```

serializer would see `wrappedAmount` field (and info from getter/setter, if any) as `property`.
Annotations would then need to be in that field, and not on `value`

So in test case, when directly serializing `Amount`, there is no property that refers to it (since it is so-called "root value", not indirect value referenced via property), and `null` is passed.

I can see how this is unfortunate in this case, but unfortunately this quite fundamental definition and can not be changed (as other existing code may well be making use of annotations on `wrappedAmount`.

**Comment by cowtowncoder** [comment]
(note: I am open to improvement ideas, to find ways to improve handling -- but this particular aspect can not be changed I think, hence closing as "wont-fix")
