### ISSUE TITLE
Question: Alternatives for @JsonIgnoreProperties(value = "items" , allowGetters = true)

### ISSUE THREAD

**Issue by Andrew3431** [FasterXML/jackson-databind#2594]
Hi, I need to avoid deserialization of an object (`Set<Item> items = new HashSet<Item> ()`) without using `@JsonIgnore` or `@JsonIgnoreProperties`

I tried the following, but it always returns empty.
```java
 @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    public Set<Item> getItems() {
        return items;
    }
```
Am I doing something wrong or is there another alternative available ?

**Comment by cowtowncoder** [comment]
Going forward please use mailing list for usage questions:

https://groups.google.com/forum/#!forum/jackson-user

or Gitter chat:

https://gitter.im/FasterXML/jackson-databind

Having said that, I don't quite understand the question. What exactly is the expected behavior?
With what input? Annotation as shown above would skip value for possible `items` property, although more commonly annotation would be placed on setter or field, as those accessor have precedence (in case there is `@JsonProperty` on both getter and setter, for example).

**Comment by Andrew3431** [comment]
```java
@Setter
private Set<String> items = new HashSet<String> (); 

 @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    public Set<Item> getItems() {
        return items;
    }
```
I was using above annotation to avoid deserialization of the variable "items".  But value is not getting set for `items` property in unit test cases. Is there any way to turn off the Access.READ_ONLY setting (or allow deserialization) for tests ??

**Comment by cowtowncoder** [comment]
If you do need to block it just for tests you could use a mix-in annotation to override `@JsonProperty` with different settings (even just `@JsonProperty` without anything else).
