### ISSUE TITLE
Triggering of Squid:S2055 on StdDeserializer

### ISSUE THREAD

**Issue by GedMarc** [FasterXML/jackson-databind#2607]
Looks like a new lint rule is in effect : 

java:S2055

When a Serializable object has a non-serializable ancestor in its inheritance chain, object deserialization (re-instantiating the object from file) starts at the first non-serializable class, and proceeds down the chain, adding the properties of each subsequent child class, until the final object has been instantiated.

In order to create the non-serializable ancestor, its no-argument constructor is called. Therefore the non-serializable ancestor of a Serializable class must have a no-arg constructor. Otherwise the class is Serializable but not deserializable.

```
public class StringToPhoneDTODeserializer extends StdDeserializer<PhoneNumberDTO> {

public StringToPhoneDTODeserializer() {
this(PhoneNumberDTO.class);
 }

public StringToPhoneDTODeserializer(Class<?> vc) {
  super(vc);
}
```

Is it worth making Std/De/Serializers serializable? What is the purpose of them being serializable, as currently they will not be serializable at all

**Comment by cowtowncoder** [comment]
The only reason for (de)serializers to be serializable is to make `ObjectMapper` itself fully serializable, in case of custom modules register such (de)serializers (standard (de)serializers are in some cases also in serialization; but not all). This for 2.x; 3.0 actually does away with the requirement in much better way.

Now: is there specific ask for changes in `jackson-databind`, or is this just about reason for Serializable implementation? Fine either way, just want to make sure I know if some changes are desired (note: removal of serializability for Std[De]Serializer is not something I'd do for 2.x since that could be break usage).

**Comment by GedMarc** [comment]
No No, not at all :) 

Didn't know this lol - disabling the literal code smell will do quite fine I promise you!

**Comment by cowtowncoder** [comment]
Ok good. Sorry, today I seem to have trouble with reading comprehension, so I ... want to take things slowly and ask questions even where I think I know what's going on (like here). :-D
Question wrt serializers/deserializers makes sense: the reason I wanted to get rid of serializability (and changed Mapper builder style a bit as a consequence) was that it's pretty invasive and messy with sub-classing.
