### ISSUE TITLE
Same custom serializer/deserializer working with JSON, but failing with XML

### ISSUE THREAD

**Issue by ArtDan** [FasterXML/jackson-databind#2623]
Jackson Version: 2.10.2

The attached unit test represents a stripped down example of my actual problem.
[JacksonCustomSerializationTest.java.zip](https://github.com/FasterXML/jackson-databind/files/4197212/JacksonCustomSerializationTest.java.zip)

I use a custom serializer/deserializer that also generates an array. The generated JSON is as expected. The generated XML looks fine (although the array seems structured unusual).

When using XML, in deserializer `jsonParser.getCodec().readTree(jsonParser)` seems to not to get all the array elements.
However it does when generating JSON, i.e. switching from XmlMapper to ObjectMapper.

### serializeAsXML()
Running test `serializeAsXML()` will produce this output:

*Generated: XML:*
```xml
<MyDataType>
	<valueList>
		<order>0</order>
		<value>And then a step to the right</value>
	</valueList>
	<valueList>
		<order>1</order>
		<value>It's just a jump to the left</value>
	</valueList>
	<valueList>
		<order>2</order>
		<value>With your hands on your hips</value>
	</valueList>
</MyDataType>
```

And `jsonParser.getCodec().readTree(jsonParser)` parses the input to this tree

*Deserialize: Incoming data:*
```json
{
    "valueList": {
        "order": "2",
        "value": "With your hands on your hips"
    }
}
```
First two array elements do not show up. ValueList is not even parsed as an array.

### serializeAsJSON()
However, running `serializeAsJSON()` which uses the same serializer/deserializer, but an ObjectMapper instead of a XmlMapper, is working as expected!

Here `jsonParser.getCodec().readTree(jsonParser)` parses the input to this tree with all the array's items:
*Deserialize: Incoming data: *
```json
{
    "valueList": [
        {
            "order": 0,
            "value": "And then a step to the right"
        },
        {
            "order": 1,
            "value": "It's just a jump to the left"
        },
        {
            "order": 2,
            "value": "With your hands on your hips"
        }
    ]
}
```

ValueList is an array and contains all the three items.

### Questions
Could this be a bug, because
* Shouldn't serialization/deserialization work independent of the used format?
* Is `readTree()` failing, because the XML misses a grouping element? So it rather should be `MyDataType/valueList/item/*` instead of `MyDataType/valueList/*`?
 However, this would have the consequence, that the serializer would need to generate different output, depending on the used format.

**Comment by cowtowncoder** [comment]
Serialization/deserialization can not really be identical since JSON and XML have incompatible logical content model. Best Jackson can do is try to make them as similar as possible, wrt POJOs and as many container types as possible.

But one thing you may not have known is this: tree model (`JsonNode`, `readTree()`) is explicit NOT supported for XML module. It may work for some cases, but will specifically not work for case of repeating elements: for that you will need a POJO with container types annotated to indicate how such sequence would map. This is because XML fundamentally has no concept of Objects or Arrays, but just elements and attributes with optional textual content.

Similarly use of custom (de)serializers is not recommended with XML: it is possible, and supported to a degree that you can do that, but you really need to know more details on how backend works -- especially on reader (parser) side, but also in some cases on writer (generator)... for example how to write attributes (as oppose to elements).

So the question of whether something works the same on json or xml depends on specific case. Ideally it should, but due to different logical content model, this is not and can not in general be guaranteed.

If you have specific issue to cover I may be able to help, given above notes on Tree Model not being very useful. Also important to know why you consider custom serializer being necessary: XML module is all about databinding and minimizing need for custom handlers.

**Comment by ArtDan** [comment]
Thanks for your swift reply!

So it seems that I'm misusing the framework...

I naively thought that if I generate JSON in the right way, for the XML also a suitable representation of an array would be used -- certainly there is more than one way to do that in XML.

I chose custom (de)serializers because my objects have some maps inside holding data technically separate for faster access, but logically belonging together.
So the wish was to store multiple entries of different maps together in one array element.

But OK, then I suppose I need to re-think. Maybe I really create some interims objects provided by a computed property that could be serialized/deserialized without a custom implementation.

Thanks for the answer, even though my issue was more a question than a bug report in the end.

**Comment by cowtowncoder** [comment]
Your expectation is not unreasonable, and it is unfortunate that it is so difficult to unify handling -- JSON/XML is possibly the trickiest combination of formats (with possible competition with CSV).

If you do want to proceed with custom handling that is possible, but in case of XML requires some more attention to details -- and possibly some additional calls. This may mean different (de)serializers for formats, or differing handling (you can detect format via parser/generator, I think, or simply check that you have XML-specific subtype). Not very clean but certainly doable.

So... if you do want to proceed, I am happy to try to help, ideally over mailing list (jackson-user) or gitter chat (https://gitter.im/FasterXML/jackson-databind)

**Comment by ArtDan** [comment]
;-)
CSV is not a even a real format ... not a robust one ... at least that's what I tell our customers all the time ... most times in vain, however.

Thank you for your offer to help. But in meantime I did create a computed property on the class that returns a interims object having the desired structure and so can be serialized with annotations only. This way the needed array type serializes correctly in both formats.

So I'm happy for the moment, but I will gladly return to ask you in the future.
