### ISSUE TITLE
LocalDate conversion fails with default ObjectMapper configuration

### ISSUE THREAD

**Issue by stefanscheid** [FasterXML/jackson-databind#2628]
To make ObjectMapper work with LocalDate, it is necessary to configure it manually:
```
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
```
because deprecated JSR310 Module is used otherwise which has no converters for LocalDate.
Standard behaviour should be adapted.

**Comment by cowtowncoder** [comment]
You are describing existing intended behavior: Java 8 datatypes are not included since Jackson 2.x does not require Java 8. This is intentional.

For Jackson 3.x Java 8 date/time types might actually still be kept separate even if other Java 8 functionality like parameter names, Optional types, due to sheer size of date/time support.

So, am I reading this correctly as to requesting of inclusion of these types for Jackson 3.0? (it will not be done for 2.x unless baseline were to be increased to Java 8).
