### ISSUE TITLE
Provide a way to override StringCollectionDeserializer

### ISSUE THREAD

**Issue by dmoagx** [FasterXML/jackson-databind#2638]
I'm currently working with an API provider which has a specific bug: Instead of empty JSON arrays it will return a JSON array with a single null element, which causes issues down the line for our code.

Since the Java model classes will be autogenerated I don't really want to touch those and my idea was to modify the collection deserializer like so:

```java
ObjectMapper mapper = ...;

mapper.registerModule(new SimpleModule() {
	@Override
	public void setupModule(SetupContext context) {
		context.addBeanDeserializerModifier(new BeanDeserializerModifier() {
			@Override
			public JsonDeserializer<?> modifyCollectionDeserializer(DeserializationConfig config, CollectionType type, BeanDescription beanDesc, JsonDeserializer<?> deserializer) {
				if(deserializer instanceof CollectionDeserializer) {
					return new ErrorCollectionDeserializer((CollectionDeserializer) deserializer);
				}
				return deserializer;
			}
		});
	}
});
```

```java
public class ErrorCollectionDeserializer extends CollectionDeserializer {
	public ErrorCollectionDeserializer(CollectionDeserializer src) {
		super(src);
	}

	@Override
	public Collection<Object> deserialize(JsonParser p, DeserializationContext ctxt, Collection<Object> result) throws IOException {
		Collection<Object> res = super.deserialize(p, ctxt, result);
		if(res.size() == 1) {
			boolean hasNull = false;
			for(Object o : res) {
				if(o == null) {
					hasNull = true;
				}
			}
			if(hasNull) {
				res.clear();
			}
		}
		return res;
	}
}
```

This works fine, until something like `List<String>` is encountered. 

Jackson will then use `StringCollectionDeserializer` and since that class is final I cannot extend it like the `CollectionDeserializer` shown above.

I can't use the `deserializeUsingCustom` extension point either, because that one assumes that one input token will always result in one object which is not true in my case.

Also it doesn't seem like a wrapper class would be possible, since `JsonDeserializer<T>` is a class hierarchy and there is no way to get the original `JavaType collectionType` used when creating the `StringCollectionDeserializer` which would be required to create a new object extending `ContainerDeserializerBase<Collection<String>>`.

I tried adding a custom deserializer, but when doing this I don't even have access to the `inst` variable that `StringCollectionDeserializer` (or `CollectionDeserializer`) would normally receive when being created from `BasicDeserializerFactory`:

```java
// in setupModule(SetupContext context)
CollectionType scType = context.getTypeFactory().constructCollectionType(List.class, String.class);
SimpleDeserializers dsr = new SimpleDeserializers() {
	@Override
	public JsonDeserializer<?> findCollectionDeserializer(CollectionType type, DeserializationConfig config, BeanDescription beanDesc, TypeDeserializer elementTypeDeserializer, JsonDeserializer<?> elementDeserializer) throws JsonMappingException {
		if(scType.equals(type)) {
			return new StringCollectionDeserializer(type, elementDeserializer, ???);
		}
		return super.findCollectionDeserializer(type, config, beanDesc, elementTypeDeserializer, elementDeserializer);
	}
};
context.addDeserializers(dsr);
```

Therefore my question is: Can `StringCollectionDeserializer` be changed to not be `final`?

**Comment by cowtowncoder** [comment]
I'd prefer not to change that class to non-final, as it is not designed to be extensible, and in general its existence/use over more general collection deserializers should really be an implementation detail.

However: approach using `findCollectionDeserializer()` should work: what `inst` parameter is missing?
Similarly, use of `BeanDeserializerModifier` seems like a good alternative; if fact, probably that would be my main choice.

Now, instead of sub-classing (which is problematic in a few ways, including higher likelihood of things breaking over time when new features are added), what I would suggest is to create custom deserializer to use delegation, not sub-classing: keep reference to "original" deserializer, call its `deserialize()` method(s), and then just modify result as appropriate.

The only (?) complications I should mention are that there are 2 calls that you'd need to delegate to (`resolve()`, `createContextual()`): for this, I suggest you base custom deserialize on `DelegatingDeserializer` which implements some of this; it should also be more robust wrt new Jackson versinos.

**Comment by dmoagx** [comment]
Thanks for your reply.

> what inst parameter is missing?

I was talking about this line: https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L1211

>  it should also be more robust wrt new Jackson versinos.

OK, my assumption was that since `JsonDeserializer` is a class hierarchy and not an interface hierarchy a subclass would be more robust, since it's 99,99% the same code as the original class, while for a wrapper/delegating class it was difficult for me to see which parts were implementation details and which parts may belong of the public contract and are used elsewhere.

But I didn't know about `DelegatingDeserializer`, either.

**Comment by cowtowncoder** [comment]
Ah, `ValueInstantiator`. Right, that is generally not necessary for fully custom implementations, although often lack of certain info is due to historical reasons (pluggable `ValueInstantiator`s added after factory interfaces were created, not retrofitted).

I sometimes struggle with documentation: specifically how to document classes that are meant as extension points (like `Std[De]Serializer`, `StdDelegating[De]Serializer`) vs those that are considered implementations.
But the general rule for container type (de)serializers is that they are not designed extensible, as most of the time what matters are content (element) types.

String collection (de)serializer is bit of an outlier, however, as I can see how it would more commonly be something users might want to extend. Especially for `null` / empty String handling.

But I hope you can use delegation model here as it seems like it would fit the way things are now. If there are specific challenges please let me know (adding comment on this issue is fine even if it's closed) and we can work through them. I am not completely against allowing sub-classing, but want to make sure it is the way to go considering that changes would need to go to next minor version and there's always some delay there.
