### ISSUE TITLE
Occurred an error when deserialize from Redis.

### ISSUE THREAD

**Issue by jxin19** [FasterXML/jackson-databind#2646]
- Java 10
- Spring 5
- Jackson 2.10

I can't figure out the deserialization error in the parallel stream API.
didn't occur any error on the test code or without parallel stream API.

Class
```
@Data
public class Example implements Serializable {
    private Long pk;
    private String profileImage;
    private String id;
    @JsonDeserialize(using = ActivityTypeDeserializer.class)
    private ActivityType type;
    private Date actionDate;
}
```

Redis Data
```
[
	"com.example.domain.Example",
	{
		"pk": 12345,
		"profileImage": "https://imageUrl",
		"id": "exampleId",
		"type": "LIKE",
		"actionDate": [
			"java.util.Date",
			1582768824000
		]
	}
]
```

Config
```
@Bean
    public RedisTemplate<String, Example> activityTemplate() {
        Jackson2JsonRedisSerializer serializer = new Jackson2JsonRedisSerializer(Example.class);

        PolymorphicTypeValidator polymorphicTypeValidator = BasicPolymorphicTypeValidator
                .builder()
                .allowIfBaseType(List.class)
                .allowIfSubType(Example.class)
                .allowIfSubType(Date.class)
                .build();

        ObjectMapper mapper = JsonMapper.builder()
                .visibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY)
                .activateDefaultTyping(polymorphicTypeValidator, ObjectMapper.DefaultTyping.NON_FINAL)
                .build();
        serializer.setObjectMapper(mapper);

        RedisTemplate<String, Example> template = new RedisTemplate<>();
        template.setEnableDefaultSerializer(false);
        template.setEnableTransactionSupport(true);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(serializer);
        template.setConnectionFactory(connectionFactory());

        return template;
    }
```

Stacktrace Error
```
Could not read JSON: Could not resolve type id 'com.example.domain.Example' as a subtype of `com.example.domain.Example`: Not a subtype
 at [Source: (byte[])"["com.example.domain.Example",{"pk":12345,"profileImage":"https://imageUrl","id":"exampleId","type":"LIKE","actionDate":["java.util.Date",1582768824000]}]"; line: 1, column: 47]
```

**Comment by cowtowncoder** [comment]
That looks like a weird exception message indeed...

First things first: you mention using Jackson 2.10, but which exact patch? If you are using an earlier one, I would suggest trying 2.10.3 and see if that makes difference.

Test code above is useful (thank you for including it), but unfortunately does not quite allow me to reproduce the issue due to couple of things:

1. `ActivityTypeDeserializer` is missing 
2. I don't have access to Redis-specific types.

Ideally it should be possible to isolate handling to only depend on Jackson types (also removing Lombok use, I assume `@Data` is for Lombok?), and I could figure out why subtype compatibility check is failing.

Also: good job on `PolymorphicTypeValidator` -- that is a good idea wrt safety concerns.

**Comment by jxin19** [comment]
@cowtowncoder thank you for your quick reply.
My Jackson version is `2.10.3`.

`ActivityTypeDeserializer` has no problem. it's just a custom JSON deserializer.

Solved then remove `@Data` Lombok annotation.
