### ISSUE TITLE
AnnotationIntrospector doesn't override JsonAlias

### ISSUE THREAD

**Issue by RyanSusana** [FasterXML/jackson-databind#2697]
Hello all!

Thank you for the awesome work.
While using Jackson within my own framework, I came across some potentially weird behaviour.

Use Case: I want to  dynamically add  Json Aliases to fields marked with a certain annotation(that I don't control)

I would expect that overriding like this should do the trick, but it doesn't. If I add the JsonAlias annotation myself, it works.
```java
@Override
    public List<PropertyName> findPropertyAliases(Annotated ann) {
        if (isId(ann)) {
            return List.of(new PropertyName("_id"), new PropertyName("id"));
        }
        return super.findPropertyAliases(ann);
    }
    
    

    private boolean isId(Annotated annotated) {

        return annotated.hasAnnotation(Id.class)
                || annotated.hasAnnotation(javax.persistence.Id.class)
                || annotated.hasAnnotation(Identifier.class)
                || annotated.getName().equals("id");

    }
```

**Comment by cowtowncoder** [comment]
That does sound odd since simple override should work as expected.

But some questions:

* Which class do you extend (`JacksonAnnotationIntrospector`?)
* How do you register custom annotation introspector? (replacing default one, or insert/append'ig)

I can write a simple unit test but first want to eliminate some obvious possibilities like introspector not actually being registered (happens more often you'd think :) )

**Comment by RyanSusana** [comment]
Hi @cowtowncoder 

Right now I override the MongoAnnotationIntrospector of mongo-jack, which overrides NopAnnotationIntrospector.

I insertAnnotationIntrospector in with a new module like  so:
```java
import com.fasterxml.jackson.databind.ObjectMapper;
import org.mongojack.internal.MongoJackModule;

public class CustomJacksonModule extends MongoJackModule {

    public static ObjectMapper configure(ObjectMapper objectMapper) {
        objectMapper.registerModule(new CustomJacksonModule());
        return objectMapper;
    }

    @Override
    public void setupModule(SetupContext context) {
        context.insertAnnotationIntrospector(new CustomAnnotationIntrospector(context.getTypeFactory()));
    }
}
```

The ```java return List.of(new PropertyName("_id"), new PropertyName("id"));```

Gets apparently gets called while debugging, but it doesn't override still

**Comment by cowtowncoder** [comment]
@RyanSusana that is weird. Thank you for investigating this part. Code looks legit. About the only thing better than this would be unit test based on pieces above -- I'll add this to my todo list to hopefully check out soon (depending on other tasks).
Or, if you have time and interest, you can create one and attach too: just needs to have no additional dependencies so can reduce to minimal reproduction (just check for `id` named property for example, pass in "_id").

One other thing: make sure to test with latest Jackson version (2.10.3) if not using that -- there is at least one fix (#2378 in 2.10.0) since addition of `@JsonAlias`).

**Comment by RyanSusana** [comment]
Hi @cowtowncoder 
After performing a simple unit test (removing the MongoJack dependency), I can confirm that the error comes  from within that dependency.

```java
public class JacksonTest {

    @Test
    void theTest() throws IOException {
        // Without MongoJack
        final var mapper = CustomJacksonModule.configure(new ObjectMapper());

        String test = "{\"_id\":\"arbitrary data\"}";

        final var testPojo = mapper.readValue(test, TestPojo.class);
        assertEquals("arbitrary data", testPojo.theId);
    }

    public static class TestPojo {
        @Identifier
        private String theId = "test";

    }
} 
```
Thanks for the help mate! Cheers  😄

**Comment by cowtowncoder** [comment]
@ryangardner Excellent code spelunking!
