### ISSUE TITLE
InvalidDefinitionException: Conflicting setter definitions for property when deserializing (if not String)

### ISSUE THREAD

**Issue by megonik** [FasterXML/jackson-databind#2741]
Hi,

I am using jackson-databind:2.11.0, and is experiencing interesting behaviour. Let's say we have 2 overloaded set methods, and one of them has String argument.
```java
public class A {
	private Integer i;

	public Integer getI() {
		return i;
	}

	public void setI(String s) {
		this.i = Integer.parseInt(s);
	}
	
	public void setI(Integer i) {
		this.i = i;
	}

	@Override
	public String toString() {
		return "A [i=" + i + "]";
	}
}

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Main {
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	public static void main(String[] args) throws JsonProcessingException {	
		A a1 = new A();
		a1.setI(1);
		
		String serStr1 = MAPPER.writeValueAsString(a1);
		System.out.println(serStr1);
		
		A a2 = MAPPER.readValue(serStr1, A.class);
		
		System.out.print(a2);
	}
}
```
This works fine. But if we change A, so that setS will accept Boolean instead of String, i.e.:
```java
public class A {
	private Integer i;

	public Integer getI() {
		return i;
	}

	public void setI(Boolean b) {
		this.i = b.booleanValue() ? 1 : 0;
	}
	
	public void setI(Integer i) {
		this.i = i;
	}

	@Override
	public String toString() {
		return "A [i=" + i + "]";
	}
}
```
it fails with 

> InvalidDefinitionException: Conflicting setter definitions for property "s": A#setI(1 params) vs A#setI(1 params)

I know that I can fix it by adding annotations to overloaded methods:

```java
public class A {
	private Integer i;

	public Integer getI() {
		return i;
	}

	@JsonIgnore
	public void setI(Boolean b) {
		this.i = b.booleanValue() ? 1 : 0;
	}
	
	@JsonProperty
	public void setI(Integer i) {
		this.i = i;
	}

	@Override
	public String toString() {
		return "A [i=" + i + "]";
	}
}
```
but shouldn't it work from the first place without any annotations, like in example at the beginning with String? I.e., JSON string after serialization clearly shows that the type of i property is numeric, so it should use setI(Integer i), but instead it got confused what set method to use when choosing between setI(Boolean b) and setI(Integer i). I understand that it won't always work if, for example, we have 2 overloaded setters which accept Integer and Long, but in these cases we can annotate, and in cases if the setter can be inferred from the JSON type it would be nice to have this working. Thanks.

**Comment by cowtowncoder** [comment]
I am bit surprised that the first example works; I would expect an exception be thrown as well since that is similarly ambiguous. There are cases where it is possible to determine which of overlapping setters to use (if one has argument type that is a subtype of argument of there other one, more specific one is used, f.ex; if one is annotated for inclusion, that is used), but here they seem to have same visibility and no annotations.

But handling goes like this: Jackson will determine statically (based on just value class, not input) which deserializer to use for a given property and will not try to do dynamic dispatching based on inputs -- you will either have to specify one (and just one) to use, or use a more general type like either `java.lang.Object` (which can then be `String` or `Boolean` or `Integer`) or `JsonNode` (which can represent any value).
Part of the challenge is that type of property can be literally any type, and in nested set up JSON String does not necessarily become Java String; it might be bound to `java.net.URL` or `LocalDateTime` (and similarly for JSON numbers). So there is no reliable way to even figure out which of alternate getters to call, even if waiting to see what kind of input value is coming (in specific case, like here, we know that deserializers for `String` and `Boolean` are actually non-overlapping but there is no general rule guaranteeing that).

So this requirement for a single setter method is a design choice that is unlikely to be changed at this point.

But one note on selecting "right" setter: it is enough to use either `@JsonProperty` or `@JsonIgnore`: both are not needed. Problem only arises if there is nothing indicating preferred choice of two seemingly equivalent possibilities.

**Comment by megonik** [comment]
Thanks for your quick reply and good explanation. My point was that in some cases JSON type information can help to select only 1 possible setter, and in other cases `InvalidDefinitionException` can be thrown. In my example JSON data type is `Number`, there is no constructor `Boolean(Number)`, and if we can check constructors of these 2 setter arguments, we can eliminate setI(Boolean b). Classes of setter arguments can use static factory method(s) (as mentioned by you `LocalDateTime` class: `LocalDateTime.parse` and variants of `LocalDateTime.of`, or `Integer.valueOf`, `Integer.decode`). Because of this checking of constructors is not enough and this can be solved by going through every method of the class of the parameter, and filtering them by return type (which sould be the same as parameter type), and number of arguments, and then check types of the arguments. If after filtering there will be only 1 suitable setter - we can use it. It will require more code to run, but will add setter method inference, can be triggered only if we encounter overloaded method, and possibly can be turned on as feature on `ObjectMapper`. These are just my thoughts, I didn't look into how library works, and I understand that this can be a lot more complex to do. I just made a quick experiment: in main method I changed `a1.setI(1)` to `a1.setI(5)`, removed `@JsonIgnore` annotation in `A` class and got the following output: `{"i":5}, A [i=5]`. Then I moved `@JsonProperty` annotation to `setI(Boolean b)`, and got `{"i":5}, A [i=1]`. I understand, that any number >=1 can be treated as `true`, and `true` is usually represented as 1, but it seems odd, as there is no `Boolean(Number)` constructor or static factory method in Java.

**Comment by cowtowncoder** [comment]
Ok, not sure I got all of above (will take a while to re-read with thought), but one quick note: coercion of `Boolean` from integral numbers dates back to early days, where some client systems (for example, ones written in Perl) could not actually express booleans natively.
I wish this was made configurable originally.
There are also a small number of other legacy coercions, but with 2.12 I am trying to come up with a more generic configuration system to allow enabling/disabling such coercions to handle both very strict (only allow use of strictly mapping scalars) and very loose (use all conceivable coercions) as well as things in-between.

But as to above: going back to very specific case of:

```java
	public void setI(String s) {
		this.i = Integer.parseInt(s);
	}
	
	public void setI(Integer i) {
		this.i = i;
	}
```

I unfortunately do not see logic that I could see being feasible to implement.
It is always possible I might be missing something, happy to be proved wrong. 
But I will try to explain the problem.

While it is easy enough to support type X that has multiple non-overlapping creators, like so;

```
public class MyType {
   @JsonCreator(mode = Mode.DELEGATING) // optional if public constructor
   MyType(int arg) { .... }

   @JsonCreator(mode = Mode.DELEGATING) // optional if public constructor
   MyType(String arg) { .... }
}
```

(and this in fact already works)
same is not true for setters; there is no layer to do similar dispatching. Adding one would require major rewrite of the whole databinding system, likely adding measurable performance overhead. To support use case that while useful (I am not saying it would not be nice), is not one of most commonly requested ones.

**Comment by megonik** [comment]
Ok, got it. Thanks for your good explanation. I am closing this suggestion.
