### ISSUE TITLE
Type ID is missing during serialization, if wrapped in collection

### ISSUE THREAD

**Issue by el-dot** [FasterXML/jackson-databind#2742]
Type ID is lost during conversion, if object with type info is wrapped in collection.
```java
public static void main(String[] args) {
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME) @JsonTypeName("test_type_name")
    class Test {
        public String key= "value";
    }
    System.out.println(new ObjectMapper().writeValueAsString(new Test(), Object.class));
    System.out.println(new ObjectMapper().writeValueAsString(singletonList(new Test()), Object.class));
}
```

Prints out: 
```
{@type=test_type_name, key=value}
[{key=value}]
```

However in case of list I expected the same value, but wrapped in array like this: 
```
{@type=test_type_name, key=value}
[{@type=test_type_name, key=value}]
```

Checked Jackson versions:
* 2.10.1
* 2.11.0

**Comment by el-dot** [comment]
Thank you for clarification the problem.

However I posted simplified use case. In "real" code I'm gathering different objects from system into raw `List<Object>` and narrowing generic type of this list is not the case; working-around type erasure won't work either. At the moment I'm doing some preconversion like below before adding objects to it, but it is not clean nor optimal.
```
objectMapper.convertValue(object, new TypeReference<Map<String, Object>>() {});
```

**Comment by cowtowncoder** [comment]
Unfortunately base type of `List` elements must be what defines Type Id to use, if any.
One other possibility that is probably not applicable here is "Default Typing", which could possible work here (since it allows you to effectively apply [certain types of] `@JsonTypeInfo` on categories of types -- but it requires use of class name, not logical type name.

But last technique which might work -- but I have not tested it myself -- would be to add mix-in `@JsonTypeInfo` annotation on `java.lang.Object`. I think that _should_ actually work, and then make all `Object` declared properties (and element types) use Type Id.

**Comment by alienisty** [comment]
Type erasure should not be a problem, so much so that you determine the element serializer by using the emlement's class.

From my analysis, the problem seems to be in PropertySerializerMap.findAndAddSecondarySerializer(), where provider.findContentValueSerializer() returns a BeanSerializer rather than the appropriate TypeWrappedSerializer, which is used when the instance is serialized as a field or in isolation.

**Comment by cowtowncoder** [comment]
@alienisty Just because Type Erasure could be resolved during serialization does not help if it would prevent deserialization: Jackson tries to ensure possibility of round-tripping and as such has to consider both sides.
Specifically, runtime type is not typically a good candidate for "base type" handling, and in particular so for elements of containers (Collections, Maps). So there must be more information available during serialization: runtime type only gives us `List<?>` which is not enough.

Your change is unfortunately not the correct way: typed value serializer is only to be used for the root values of serialization and in particular never for elements of containers. It may do what you want but it does not do what should be done.

**Comment by cowtowncoder** [comment]
Works as designed, should have closed earlier -- behavior will not be changed; I have included usual workarounds.

**Comment by alienisty** [comment]
I think that you are missing the ponit that elements of a List<?> can provide the missing information, so much so that the framework is currently using the element's type to find its serializer, it's only not considering polymorphism in that case.
I agree with you that List<?> is not enough when it's empty, and that doesn't even matter, you'll just output "[]", which is also correct.
My change may not be correct, which is fine because I don't know the internals of the framework very well, but I would say that an implementation to fix this issue would be possible.

**Comment by cowtowncoder** [comment]
You are obviously free to argue that serialization should not be limited to what deserialization can do but Jackson does consider it for specific case of polymorphic handling (or rather, existence and use of type information to include in that case). There is no such limit on actual value serialization (it would be very difficult to try to guarantee it anyway).
Further, the type to use must be statically detectable for elements of structured types: whether container has elements or not is irrelevant for base type determination (type used as the base type of polymorphic subtyping).

This is a design choice and not a flaw to fix: it is pretty fundamental design limitation/guarantee.
Behavior wrt requiring type information for generic root values (like `List` being directly serialized) is the expected behavior at this point and will not be changed.
