### ISSUE TITLE
Java7Handlers(6175): Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added

### ISSUE THREAD

**Issue by ber4444** [FasterXML/jackson-databind#2744]
This issue is observed in Wiremock 2.26.3 which depends on Jackson 2.10.2, and in Wiremock master which depends on Jackson 2.11.0. 

When I add `coreLibraryDesugaringEnabled` on android (https://developer.android.com/studio/preview/features#j8-desugar), getting the error that you see in the issue title.

**Comment by cowtowncoder** [comment]
That message would be seen on system that does not have those couple of JDK7 types, but it is warning and should not prevent usage in any way (since types that do not exist within JDK need no support).

Now, I am not familiar with (de)sugaring, but reading:

https://jakewharton.com/d8-library-desugaring/

suggests that it would mean rewiring class references in bytecode, so that references to types not directly included would be "rerouted" to replacements. But I assume this can not work for reflection-usage (at least not statically). Hence it would not handle such dynamic usage.

Odd thing, however, is this: with Jackson 2.10 and above, `Java7HandlersImpl` actually has direct reference to types; and it is only link from `Java7Handlers` to `Java7HandlersImpl` that uses reflection.

So maybe the thing needed by tooling is to point to `Java7HandlersImpl` as something that must also be processed, even if it is not reachable by static references from other Jackson types (i.e. nothing from `ObjectMapper` references it even indirectly, except by Reflection).
That sounds like something that could resolve the issue?
And in fact, it is possible some Android tooling (build, package) might simply not be including `Java7HandlersImpl` in package, and if so that class missing could itself give the warning message I suppose.

**Comment by ber4444** [comment]
`Java7HandlersImpl` is actually included, and the error is happening in Wiremock-based tests which don't have any kind of proguarding applied that would strip things out.

**Comment by cowtowncoder** [comment]
Ok so that is not what would be causing it. Which is unfortunate as there would have been a fix.
My problem is that I do not have a way to unfortunately reproduce this easily, which also means that I can not try out various changes as I can not validate their working.

**Comment by ber4444** [comment]
Some more details on this are here: https://issuetracker.google.com/issues/158452385

**Comment by cowtowncoder** [comment]
Thank you @ber4444. So, quoting from that ticket

```
The java.nio.file package was added in OpenJDK 7 https://devdocs.io/openjdk/java/nio/file/package-summary

It was not included in Android until API 26 https://developer.android.com/reference/java/nio/file/package-summary

As of the version used by AGP 4.0.0, L8 still doesn't desugar classes in the java.nio.file package.

java.nio.file.Path and friends are commonly used in libraries targetting OpenJDK 7+.

This means that there is still code that works on OpenJDK 7 can still not be used on Android API 25 even with JDK lib desugaring enabled.
```

it sounds like this is not something Jackson can help a lot with?
