### ISSUE TITLE
ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT does not convert empty JSON array to null value

### ISSUE THREAD

**Issue by athlan** [FasterXML/jackson-databind#2752]
Hello,

I am struggling with `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` Object Mapper setting that says:

> Feature that can be enabled to allow empty JSON Array value (that is, [ ]) to be bound to POJOs as null.

However empty JSON array  `[]` is neither set to null into JSON-array-to-JAVA-collection mapping nor JSON-array-to-JAVA-array. Here's example test case tested on Jackson 2.11.0:

```
import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.util.List;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;

public class JacksonTest {

    public static class SampleData {
        List<String> field;
        String[] field2;

        public List<String> getField() {
            return field;
        }

        public void setField(List<String> field) {
            this.field = field;
        }

        public String[] getField2() {
            return field2;
        }

        public void setField2(String[] field2) {
            this.field2 = field2;
        }
    }

    @Test
    void testEmptyArrayAsNull() throws IOException {
        String payload = "{\"field\": [], \"field2\": []}";

        ObjectMapper objectMapper = createObjectMapper();
        SampleData dane = objectMapper.readValue(payload, SampleData.class);

        assertThat(dane.getField2()).isNull();
        assertThat(dane.getField()).isNull();
    }

    private ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
        return mapper;
    }
}
```

`field` (mapped as collection) is empty collection instead of null
`field2` (mapped as array) is empty java array instead of null.

Seems like bug for me.

**Comment by cowtowncoder** [comment]
Just to make clear: in Jackson documentation, "POJO" means roughly same as "Bean"; Java type that is handled as a set of property/value pairs. This does not include `Collection`s, `Map`s or arrays (or scalar types). So while naming of `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT ` is too vague (it really should say POJO), it is not currently intended to coerce `[ ]` into `null` for container types.

But more generally I don't think I want to add coercions from JSON Array in cases where such input can be interpreted normally; that is, it is not intended to change empty List/array into Java `null` value.
I may need to update Javadocs to clarify this behavior.

**Comment by athlan** [comment]
Thank you for replying @cowtowncoder .

> But more generally I don't think I want to add coercions from JSON Array in cases where such input can be interpreted normally

I think when option exists it's user choice how to treat collections. Of course, in Java it's better to have empty collection instead of `null`, but when this option exists I'd say that's user decision. For example I had super specific use case where I'd like to adhere behavior of Jackson to other Codec Transport (proprietary one) and I wanted to use this option fully aware knowing what are the downsides of `null` collections.

Well, if you say
> it is not intended to change empty List/array into Java null value.

Then, Is there any other use case for `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` option? JSON-arrays are mapped into Collections or Arrays.

If not, deprecate it or support that.

**Comment by cowtowncoder** [comment]
@athlan I thought use case was clear from document and my comment, but I think this is a bigger misunderstanding than I originally thought. What was intended and implemented is for "coercion" -- implicit conversion from incompatible type -- from (empty) JSON Array into non-array/non-collection type such as POJO or `Map` or even Scalar, as `null`.
This was to support some specific platform (PHP I think) that encodes `null`s as `[ ]`.
Without setting you would get basic "can not deserialize MyValue from JsonToken.START_ARRAY" exception.
New `CoercionConfig` (see #2113) will make this bit more clear as well as configurable.

As to converting empty Collection/array into `null`, which I think is what you want: only the reverse -- converting `null`s into "empty", or skipping setting, or throwing Exception -- is possible currently. Functionality for doing that was added because avoiding `null`s has been consistently brought up as a use case users want.
Inverse functionality -- making `null` out of "empty" value -- has been sometimes requested too, I think, but so far no support has been added.
I am always open to possibility of new functionality, features, but in this case it is not a matter of extending something that already is (mechanisms mentioned above are quite specific, partly since `null` value handling is quite separate from general `JsonDeserializer` deserialization flow for historical reasons...).

I will leave this issue open as it could serve as RFE for adding functionality (although if so, editing title would make sense); alternative would be to file a new specific issue.
