### ISSUE TITLE
Fix #1395 changes behaviour for boxed primitive subtypes

### ISSUE THREAD

**Issue by obroomhall** [FasterXML/jackson-databind#2753]
This fix breaks a use case in which a field should to be serialised as a boxed primitive. If I modify the test given by @antantantan slightly to include some additional annotations, including a `@JsonSubTypes.Type` annotation, the test fails to box the serialised value.

The problem is solved by reverting this commit, I have tested on 2.8.4 and 2.11.0 with the reverted commit and can confirm my test case passes. Would it be possible to solve my issue, without reverting the current fix?

```java
package com.fasterxml.jackson.databind.jsontype;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder;
import org.junit.Ignore;
import java.util.*;

// [databind#1395]: prevent attempts at including type info for primitives
public class DefaultTypingWithPrimitivesTest extends BaseMapTest
{
    static class Data {

        private long key;

        @JsonCreator
        private Data(@JsonProperty("key") Long key) {
            this.key = key;
        }

        @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
        @JsonSubTypes.Type(value = Long.class)
        public long key() {
            return key;
        }
    }

    @Ignore
    public void testDefaultTypingWithLong() throws Exception
    {
        Data data = new Data(1L);
        Map<String, Object> mapData = new HashMap<String, Object>();
        mapData.put("longInMap", 2L);
        mapData.put("longAsField", data);

        // Configure Jackson to preserve types
        ObjectMapper mapper = new ObjectMapper();
        StdTypeResolverBuilder resolver = new StdTypeResolverBuilder();
        resolver.init(JsonTypeInfo.Id.CLASS, null);
        resolver.inclusion(JsonTypeInfo.As.PROPERTY);
        resolver.typeProperty("__t");
        mapper.setDefaultTyping(resolver);
        mapper.enable(SerializationFeature.INDENT_OUTPUT);

        // Serialize
        String json = mapper.writeValueAsString(mapData);

        // Deserialize
        Map<?,?> result = mapper.readValue(json, Map.class);
        assertNotNull(result);
        assertEquals(2, result.size());
    }
}
```

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (VALUE_NUMBER_INT), expected START_ARRAY: need JSON Array to contain As.WRAPPER_ARRAY type information for class java.lang.Long
 at [Source: (String)"{
  "__t" : "java.util.HashMap",
  "longInMap" : [ "java.lang.Long", 2 ],
  "longAsField" : {
    "__t" : "com.fasterxml.jackson.databind.jsontype.DefaultTypingWithPrimitivesTest$Data",
    "key" : 1
  }
}"; line: 6, column: 13] (through reference chain: java.util.HashMap["longAsField"]->com.fasterxml.jackson.databind.jsontype.DefaultTypingWithPrimitivesTest$Data["key"])
```

_Originally posted by @obroomhall in https://github.com/FasterXML/jackson-databind/issues/1395#issuecomment-641279477_

**Comment by cowtowncoder** [comment]
One quick note: fix that has been on for this since 2.8.4 is unlikely to be reverted (it has become de facto default behavior), so another solution would likely be needed.

**Comment by cowtowncoder** [comment]
Hmmh. I must say I do not understand notation here: `long` is NOT a valid base type for anything, being primitive; so it needs to be `Long`. Changing that declaration makes test pass.
It would possibly make sense to try indicate this erroneous definition (subtypes that are not actual subtypes at all), but not sure how easy that would be.

In addition, it is typically bad idea to try to use inclusion mechanism of `As.PROPERTY` with default typing: recommend one is `As.WRAPPER_ARRAY` because As.PROPERTY only works with types that are serialized as JSON Objects (and as a result, WRAPPER_ARRAY is used wherever PROPERTY is not possible to use).

So, I would consider examples as is unsupported: if `key` is declared as `Long` things work as expected.

But... I will see if I can nonetheless find a way to make it behave as it did: problem being that serializer does not include type information yet deserializer expects it.

**Comment by cowtowncoder** [comment]
I think that since the check is quite clearly identified in `StdTypeResolverBuilder`, it would make sense to extract the check (whether type information should be included/expected on primitive types) into separate, overridable method. That way sub-classing and override can be used to achieve previous behavior, regardless of whether that makes sense for general case (to me it does not as primitive types can not be sub-classed anyway).

**Comment by cowtowncoder** [comment]
So, couple more notes on test itself: looks like typing is enabled using 2 different mechanism: `@JsonTypeInfo` AND Default Typing. While supported, there can be edge cases wrt applicability, and some of configuration is different, regarding `TypeResolverBuilder` used.

In specific case of `long`, field, part of solution is to use 

```java
@JsonTypeResolver(MyTypeResolverBuilder.class)
```

annotation. With 2.11.1 and later, you would implement custom subtype like so:

```java
public class MyTypeResolverBuilder extends StdTypeResolverBuilder {
        @Override
        protected boolean allowPrimitiveTypes(MapperConfig<?> config,
                JavaType baseType) {
            return true;
        }
}
```

to allow Type Id for primitive types, for serialization, deserialization.

However, I'll still remind that original confusion was due to serialization seeing type `long`, and deserialization `Long`: this due to discrepancy with accessor (getter) and mutator (constructor parameter).

Anyway: it will be possible to make even this case work, once 2.11.1 is released (although technically it is already possible to sub-class... but changes needed would be much more sizable).
