### ISSUE TITLE
Support multiple names in `JsonSubType.Type`

### ISSUE THREAD

**Issue by swayamraina** [FasterXML/jackson-databind#2761]
This issue is linked to https://github.com/FasterXML/jackson-annotations/issues/171

**Comment by swayamraina** [comment]
link to PR : https://github.com/FasterXML/jackson-databind/pull/2762

**Comment by cowtowncoder** [comment]
PR looks good; added note on #2762 wrt CLA.

**Comment by cowtowncoder** [comment]
@swayamraina I finally got this all merged: thank you very much for this contribution! It will be included in 2.12.0 release.

**Comment by swayamraina** [comment]
@cowtowncoder should I also raise an issue to remove the singular version of this field to be removed in `3.0.0`?

**Comment by cowtowncoder** [comment]
I thought about that, and it would otherwise make sense but I am planning to keep 2.x and 3.x annotations compatible -- so that unlike all other components, you can actually use either one.
That is, 2.x annotations will work with 3.x and vice versa: so there is no major version difference for annotations. This is based on my experiences with 1.x -> 2.x upgrade where the only recurring issue users have is that with auto-completion they sometimes gets Jackson 1.x annotations which will not work with 2.x.

So at this point I think this sub-optimality can live on. Thank you for suggesting it though, it is good to follow up properly with clean up, keeping codebase as tidy as possible.

**Comment by swayamraina** [comment]
sure, this also makes sense.
