### ISSUE TITLE
SnakeCase not working expectly while second letter is upper case

### ISSUE THREAD

**Issue by Anricx** [FasterXML/jackson-databind#2769]
hi, I have a entity 
```java
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Foo extends BaseRequest {

    private String carnum;

    private Short qType;

}

QueryMonthPriceRequest request = QueryMonthPriceRequest.builder()
                .pid(apiHeader.getApiParkUuid())
                .carnum("123")
                .qType(MonthQueryType.CreateOrder)
                .build();

System.out.println(new ObjectMapper().writeValueAsString(request));
```
but the out put property `qType` go to `qtype` not `q_type`;
```json
{"carnum":"123","qtype":1}
```
expect result
```json
{"carnum":"123","q_type":1}
```

so this is lombok's fault or can fastxml fix it?

**Comment by cowtowncoder** [comment]
@Anricx I think this depends on exactly what kinds of getters/setters Lombok generates as field name is not necessarily used at all (although it is possible to configure Jackson to only detect fields, not getters, too). But I think the problem is almost certainly since name like `qType` can not be reliably brought back and forth: getter probably becomes

     getQType()

(although I guess `getqType()` might be generated too -- but that might not be Bean Naming compatible)

from which name becomes either `QType` or `qtype`; but there is no way it could be determined to be `qType` if `getQType` is the base)

There is one setting in Jackson that is relevant here: `MapperFeature.USE_STD_BEAN_NAMING` (disabled due to backwards compatibility).

You may try add explicit `@JsonProperty` on field to rename it (to `q_type`, directly, by default naming strategy does not modify explicitly annotated names).
