### ISSUE TITLE
Custom JsonSerializer not working with JsonValue

### ISSUE THREAD

**Issue by gordon00** [FasterXML/jackson-databind#2774]
Context :
First I needed to serialize/deserialize Java enum to the following json : 
`{
  id: "NAME",
  label: "LABEL"
}`

The "id" was only mapped on the Java enum name. It was quite easy.
Then I needed for some special cases only to map the "id" on a custom property in the java enum.
So I decided to use @JsonValue and @JsonCreator in our specific enums and then adapt my custom serializer/deserializer.

And it worked perfectly until I migrate from version 2.8.11 to version 2.11.0.
So in my opinion it might be a regression.

To make your life easy, I created a sample project to reproduce things : 
[https://github.com/gordon00/jackson-enum-serializer](url)

There are three commits :

1. The working version in 2.8.11
2. The non working version in 2.11.0 (the only change is the version in the pom)
3. The non working version after moving findJsonValueMethod() which is deprecated to findJsonValueAccessor

**Comment by cowtowncoder** [comment]
This is quite advanced use of Jackson internals, which unfortunately means that result is likely to be bit less stable than if using public API.

Having said that, I think I understand what is being attempted, and would suggest rewriting handling so that instead of using `SimpleModule` -- and specifically, `SimpleDeserializers` and `SimpleSerializers` for registering custom (de)serializers -- you would instead register custom versions of `Deserializers` / `Serializers` to get access to fully resolved `BeanDescription` when constructing (de)serializers, as well as exact type.
This should be more reliable than trying to access this information from `createContextual()`.

For `Deserializers` you can extend `Deserializers.Base`, define:

```
    public JsonDeserializer<?> findEnumDeserializer(Class<?> type,
            DeserializationConfig config, BeanDescription beanDesc)
        throws JsonMappingException  { ... }
```

and similar for `Serializers.Base`:

```
    // No separate method for Enums, used for POJOs, Enums
    public JsonSerializer<?> findSerializer(SerializationConfig config,
            JavaType type, BeanDescription beanDesc); { }
```

This will work around one problem with current implementation, too; (de)serializers need to be stateless, thread-safe.

But as to the underlying problem here: it is due to call to `introspectClassAnnotations()`.
As name suggests it is guaranteed (intended) to only introspect annotations on class, but NOT on members (methods, fields). And since `@JsonValue` and `@JsonCreator` are on members, former is not found.
You can change that to use full `introspect(JavaType)`, and that will now find accessor, but hit access problem (since test uses non-public inner class); that can be fixed by a call, so you'd get something like:

```
    // need JavaType, not Class<?> so here need to do:
    JavaType type = serializers.constructType(value.getClass());
    annotatedMember = serializers.getConfig().introspect(type).findJsonValueAccessor();
    annotatedMember.fixAccess(true);
```

and with that, test passes.

Unfortunately I think code in this case happened to work with 2.8 although it really should not have (for some reason, members were also resolved: possibly by caching, or by lazy resolution), so there isn't something I would want to change (members were not supposed to be accessible).

I would still recommend rewrite to get access to `BeanDescriptions` through `Serializers` / `Deserializers`, too, but above is the minimal fix.

**Comment by gordon00** [comment]
Thank you very much for your detailed reply !

Indeed, the enum class is not a public inner class but it was not intented. However I've noted the use of annotatedMember.fixAccess(true) which may helpful next time I try to make exotic uses of your api.

I will try to follow your advice about Deserializers.Base.

Seeya

**Comment by cowtowncoder** [comment]
@gordon00 good luck!
