### ISSUE TITLE
`JsonNode` does not retain duplicate Object entries

### ISSUE THREAD

**Issue by Judekeyser** [FasterXML/jackson-databind#2809]
Hello,

Bug short description: JsonTree is currently destructive when reading duplicate keys from Json input.

According to Json format and specification, it is allowed (although not recommended) to have multiple entries for the same key. For example, the JSON
`{
   "prop": 1,
   "prop": 2
}`
is technically correct. I'm already aware how to handle the case with a custom Map implementation, and the workaround I have works just fine! 

Nevertheless, the duplicate information completely disappears within the JsonNode structure. More precisely, when performing a `readTree`, there seems to be no information inside the tree to recover the duplicate values. The current behavior of `get` is somehow unfair too, as it always concerns the last entry, although from specification: fields are unordered. Thus this behavior is completely arbitrary.

Without altering the behavior of `get` (thus, still returning "the last" key) for keeping backward compatibility, it would be nice to enrich the JsonTree object with an additional `getAllDuplicatedValues(String prop)` that would return all the duplicates found for a given key `prop`.

This way, the object JsonTree looks closer to the real valid json taken in input, and clients (developers) need not force the `readValue` where a `readTree` is actually sufficient, but currently destructive.

**Comment by cowtowncoder** [comment]
As far as I recall, JSON does not say that duplicates are fine, but rather that behavior is undefined/unspecified, and implementations are free to keep first, keep last, fail, or anything along those lines.

I don't really like the idea of overhead or complexity of keeping track of what is commonly considered invalid usage (many users consider it a flaw that Jackson does not by default throw exception for duplicates -- there are features to do that however).

But I'll keep this open to think about it: 2.12 has special handling for XML to allow XML-backed `JsonNode` to auto-convert duplicate values into array of values.

**Comment by Judekeyser** [comment]
Well, specification is rather clean concerning the duplicate entries (pdf attached to JSON spec page http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf):

> The JSON syntax does not impose any restrictions on the strings used as names, does not require that name strings be unique, and does not assign any significance to the ordering of name/value pairs. These are all semantic considerations that may be defined by JSON processors or in specifications defining specific uses of JSON for data interchange.

In other words: the choice of representing objects via LinkedHashMap is arbitrary in two ways: keeping things ordered and forgetting about duplicates. Although I also agree that one choice should have been done and LinkedHashMap suits most needs, I'm convinced this is a too strong choice for the Json Tree, which should be as fair as possible with respect to documentation.

Also, this the Javascript Object Notation Data Interchange Format (https://tools.ietf.org/html/rfc8259#section-4) says:

> The names within an object SHOULD be unique.

and in this context, parser behavior is unpredictable. On the other hand, the SHOULD here is not a MUST (https://tools.ietf.org/html/bcp14), which means:

> This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

Shouldn't it be the responsibility of the client of the library to choose whether he wants to work with duplicate, rather than the responsibility of the lib itself?

**Comment by cowtowncoder** [comment]
The spec you point to is not really canonical; at this point there is the original incomplete specification as well as 2 RFCs:

* https://tools.ietf.org/html/rfc4627 which is somewhat incomplete, not saying much on duplicate names
* https://tools.ietf.org/html/rfc7159 which says (in https://tools.ietf.org/html/rfc7159#section-4)

" An object whose names are all unique is interoperable in the sense
   that all software implementations receiving that object will agree on
   the name-value mappings.  When the names within an object are not
   unique, the behavior of software that receives such an object is
   unpredictable.  Many implementations report the last name/value pair
   only.  Other implementations report an error or fail to parse the
   object, and some implementations report all of the name/value pairs,
   including duplicates."

which is what I use as the basis (this was discussed to death during "json specification next gen" mailing list years ago -- without much consensus).

With that, I think we fundamentally disagree here, so I will say this: I do not see anything that convinces me that additional complexity of handling duplicates (regarding API and implementation, backwards compatibility) is worth my time to change the behavior.
I also personally feel that use of duplicates in JSON Objects is wrong, from philosophic perspective, even if JSON specification from the start has been ambiguous about it.

But since `JsonNode` is that one possible representation of JSON, you are free to implement alternative (could even be a `TreeNode` implementation, if that makes sense).
Jackson does not really strongly depend on it, although it is the default tree model exposed.

I will leave this open if anyone wants to comment.

**Comment by cowtowncoder** [comment]
No plans to address, closing.
