### ISSUE TITLE
Block one more gadget type (org.arrahtec:profiler-core, CVE-xxxx-xxx) 

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2827]
Another gadget type(s) reported regarding class(es) of `org.arrahtec:profiler-core` library.
See https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062 for description of the general problem.

Mitre id: [to be allocated]
Reporter(s): ChenZhaojun (Security Team of Alibaba Cloud)

Fix is included in:

* 2.9.10.6 (usable via `jackson-bom` version `2.9.10.20200824`)
* Not considered valid CVE for Jackson 2.10.0 and later (see https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba)

**Comment by bad-boy1** [comment]
will this issue be fixed in  the new  version，like 2.10.6 and 2.11.3，though it is mentioned that CVE not include 2.10.0 and later. In order to prevent some users not complying the new security mechanism and  still using enableDefaultTyping，as also some users use activateDefaultTyping set org.arrah.framework.rdbms.UpdatableJdbcRowsetImpl as a trusted class

**Comment by cowtowncoder** [comment]
@bad-boy1 Blocks are added in later versions too (SubTypeValidator is still applied).

But problem itself is not considered applicable, not only because user explicitly has to enable a feature but because methods to do so are marked as deprecated with noted safe alternatives.
Actually these issues should probably never have been accepted as legit CVEs since they require changing of default configuration -- something that I think would rule them out.

As to users enabling unsafe behavior: that is on them. One could always write a custom handler to open up security holes.
