### ISSUE TITLE
activateDefaultTyping with JsonTypeInfo.As.PROPERTY introduces an extra wrapper

### ISSUE THREAD

**Issue by DanielYWoo** [FasterXML/jackson-databind#2838]
When we enable default typing by using @class property like this:
```
mapper.activateDefaultTyping(new DefaultBaseTypeLimitingValidator(), ObjectMapper.DefaultTyping.EVERYTHING, JsonTypeInfo.As.PROPERTY);
```
To write an ArrayList, the BeanPropertyWriter uses AsPropertyTypeSerializer with a CollectionSerializer. As a result, the output of an ArrayList is not a raw json array, it's an array wrapper.
e.g. 
```
MyBean myBean = new MyBean();
myBean.setMyList(populateSomeArrayListOfEmployees());
mapper.writeValueAsString(list);
```

The expected output is
```
{
     "@class": "com.test.MyBean",
     "myList": [
             { "@class":"com.test.Employee", ...},
             { "@class":"com.test.Employee", ...}
     ]
}
```

But the actual output is
```
{
     "@class": "com.test.MyBean",
     "myList": [
         "java.util.ArrayList", // we should not have the extra array wrapper here
         [
             { "@class":"com.test.Employee", ...},
             { "@class":"com.test.Employee", ...}
         ]
     ]
}
```
Hence we cannot deserialize the json back due to the extra wrapper.

We should check if the value is a Collection class in BeanPropertyWriter.serializeAsField(...), and avoid using the AsPropertyTypeSerializer for any collection value.
original code:
```
        if (_typeSerializer == null) {
            ser.serialize(value, gen, prov);
        } else {
            ser.serializeWithType(value, gen, prov, _typeSerializer);
        }
```
Change to
```
        if (_typeSerializer == null || value instanceof Collection) {
            ser.serialize(value, gen, prov);
        } else {
            ser.serializeWithType(value, gen, prov, _typeSerializer);
        }
```

**Comment by cowtowncoder** [comment]
Type information is included because you explicitly told you want it:

    DefaultTyping.EVERYTHING

and this is a setting you rarely if ever want to use -- it say "yes, add type info EVERYWHERE regardless of type". As such, information should be there.

Further, `_typeSerializer` is only to be constructed if type information is needed. Code really should not have special magic types for which it would not use it: if type id is not needed, `Type[De]Serializer` should not be constructed for (de)serializer in question. So the question is not that of code requiring work-arounds but you defining correctly kinds of types for which information is needed. `DefaultTyping` has some pre-set choices, although you can also implement custom implementations where you can specify exact logic you want -- this is where you could prevent it from being added for `List`s or `Collection`s.

I would also suggest that maybe you don't even want to use default typing at all: you can enable type information for elements of a `List` by adding `@JsonTypeInfo` on property in question (or if it's a base type  you control, in class definition of the value type).

**Comment by DanielYWoo** [comment]
The background is, I need to serialize some existing classes which does not have @JsonTypeInfo annotation, and when deserialize I don't know the expected types so need "@class" property when serialize. I don't like defaultTyping but it seems to be the only option I can try. 

The problem here is, if we use the EVERYTHING option, Jackson is not working as required for collections, it will not add @class property to an ArrayList. In my previous example, I want EVERYTHING has an inclusive "@class" by specifying JsonTypeInfo.As.PROPERTY. But only the Employees are serialized with an inclusive @class property as specified, the list is serialized with a wrapper of array without "@class".
```
{
     "@class": "com.test.MyBean",
     "myList": [
         "java.util.ArrayList", // we should not have the extra array wrapper here
         [
             { "@class":"com.test.Employee", ...},
             { "@class":"com.test.Employee", ...}
         ]
     ]
}
```

I don't know how to add a "@class" property to "myList" in this example, could you show me the JSON string generated?

Actually, since in JSON spec, string/number/array are built-in primitives and maybe they should be treated specially, for array, maybe we can also serialize it to JSON array without any wrapper or type property.

**Comment by cowtowncoder** [comment]
@DanielYWoo ok, you may be misunderstanding what you see there -- for Collections, it is not possible use PROPERTIES style as they are written as JSON Arrays, and arrays have no properties. Because of this "WRAPPER_ARRAY" style is used instead to include Type Id as required by `EVERYTHING`.
(earlier I assumed you did NOT want type id for Lists, which is why I asked).

In fact, I would strongly recommend NOT trying to use `PROPERTIES` style for this reason (as well as efficiency), `WRAPPER_ARRAY` is generally better choice.

If you do use `PROPERTIES`, however, deserializer needs to be aware of this difference. Jackson databind does know what to expect and should match reading.

At this point it is more useful to know what you are trying to achieve, and less what you think is going wrong. I can explain how things will work, based on evidence, but without understanding the goal it is not very efficient.

To summarize:

1. For list, that inclusion is the way Jackson implements it and this will not change: only values that are serialized JSON Objects can use `PROPERTIES` (or `EXISTING_PROPERTIES`, `EXTERNAL_PROPERTIES`) -- Collections, arrays and Scalars will instead revert to `WRAPPER_ARRAY` (but could also be configured by user to use `WRAPPER_OBJECT` as alternative)
2. It is possible to instead use `WRAPPER_ARRAY` (or `WRAPPER_OBJECT`), applicable to all types, being more consistent
3. It is also possible to prevent inclusion of Type Id if specifying custom `TypeResolverBuilder`, but most of the time setting `DefaultTyping.NON_CONCRETE_AND_ARRAYS` or `DefaultTyping.NON_FINAL` makes more sense (includes Type Id where necessary, but not for everything)
4. Jackson-databind itself will know how to read what it writes, but with DefaultTyping it will dictate representation used (that is, it is not possible to always force specific style of inclusion).

**Comment by DanielYWoo** [comment]
You made me crystal clear now, many thanks. Do you want a PR for javadoc on this? So other people will be aware of the PROPERTIES limitation.

**Comment by cowtowncoder** [comment]
@DanielYWoo yes, I would appreciate PR for this!
