### ISSUE TITLE
On upgrade of jackson from 2.6 to 2.7 ser-de for enum has changed when using annotation pair of jackson and jaxb annotation introspectors.

### ISSUE THREAD

**Issue by abhi-rao** [FasterXML/jackson-databind#2848]
**Describe the bug**
Due to the introduction of JsonProperty in 2.7, the behaviour of annotationInspector while using jackson as primary and jaxb as secondary changes.
 
**Version information**
Which Jackson version(s) was this for?
`2.7.0`
**To Reproduce**
Run the following snippet with versions `2.6.0` and `2.7.0`.

Following is the annotation introspector configuration used to 
```java
 public static void main(String[] args) throws JsonProcessingException {
    // Jackson as primary, jaxb as secondary.
    AnnotationIntrospectorPair annotationIntrospectorPair = new AnnotationIntrospectorPair(
            new JacksonAnnotationIntrospector(),
            new JaxbAnnotationIntrospector(TypeFactory.defaultInstance())
    );
    ObjectMapper objectMapper = new ObjectMapper()
            .setAnnotationIntrospector(annotationIntrospectorPair);

    Map<String, TestEnumWithXmlEnumValue> testData = Collections.singletonMap("key", TestEnumWithXmlEnumValue.TEST);
    String value = objectMapper.writeValueAsString(testData);
    System.out.println(value);
  }


  public enum TestEnumWithXmlEnumValue {
    @XmlEnumValue("test")
    TEST
  }

```
When run with `2.6.0` the output is `{"key":"TEST"}`, while on upgrade to `2.7.0` it changes to `{"key":"test"}`
**Expected behavior**
Expected behaviour was that behaviour would remain unchanged.

**Additional context**
If the change was expected, to restore the behaviour would overriding JacksonAnnotationIntrospector's findEnumValues to rely on name of enum be the right approach, for the reasons of maintaining backward compatibility?

**Comment by cowtowncoder** [comment]
Couple of notes.

First, always use the latest patch version of minor version -- in this case test should use `2.7.9`, not `2.7.0`; there are literally dozens of fixes.

Second 2.7 branch is quite old and no new full release has been made since 2017, nor are there plans to release new minor versions for 2.7 (or 2.8 or 2.9 -- 2.10 is still technically open).
So any changes would be needed for one of active branches: currently 2.11 (or upcoming 2.12, esp. for behavioral changes)

Given this, it'd be good to test with a newer version, ideally 2.11.2 and see if the problem still occurs.

**Comment by Hillrunner2008** [comment]
@abhi-rao - This was a bug fix by all appearances. I randomly stumbled into this recently and found the issue was that the AnnotationIntrospectorPair class has a method ```findEnumValues``` that now correctly processes the "secondary" annotation processors annotations instead of simply taking the primary and ignoring the seondary. 

Although of course its a change in behavior, it is also clearly better that it now respects the secondary annotation processor.

**Comment by cowtowncoder** [comment]
@Hillrunner2008 Thank you for additional notes here -- this makes sense.

**Comment by cowtowncoder** [comment]
I concur with @Hillrunner2008, not sure why new behavior would be considered wrong: it now picks up annotation as it should have (i.e. it's a bug fix).

**Comment by abhi-rao** [comment]
@cowtowncoder Thanks the confirmation it helped as initially I didn't find this as a bug fix in the release notes, hence the issue.
