### ISSUE TITLE
is convertValue serializing from scratch a java object?

### ISSUE THREAD

**Issue by Ben-Mark** [FasterXML/jackson-databind#2849]
Hi, 
A performance question:
when I invoke a convertValue(javaPOJO, JsonNode.class)  am I reserializing the entire javaPOJO which was already serialized in prior stages of the code?
or is jackson reusing that prior serialization and optimizing this step?

Thanks in advance,
Ben Mark

**Comment by cowtowncoder** [comment]
Jackson will only produce event stream (stored as `TokenBuffer`) -- a sequence of `JsonToken`s -- and reading that token stream. So it is avoiding encoding/decoding part of serialization/deserialization.
It would actually be interesting to see relative performance: my gut feeling is that encoding/decoding would account for somewhere between 50% and 70% of time (assuming no I/O) for typical cases.

But if you are thinking of code like:

```
POJO value = ....'
byte[] encoded = mapper.writeValueAsBytes(value);
POJO2 converted = mapper.convertValue(value, POJO2.class);
```

then no, there is no state being saved from "writeValueAsBytes". In such cases you could further optimize things by "serializing" things as `TokenBuffer`, something like this (haven't tested but should work in some form)

```
TokenBuffer tb = new TokenBuffer();
mapper.writeValue(tb, value); // TokenBuffer implements JsonGenerator
byte[] encoded = mapper.writeValueAsBytes(tb);
POJO2 converted = mapper.readValue(tb.traverse(), POJO2.class); // traverse() creates JsonParser
```

**Comment by Ben-Mark** [comment]
Actually I'm only asking this question where I/O is occurring
For example:

- A json esponse just came in to the server
- serializing / deserializing by just specifying the endpoint's signature with a corrsponding java object (dto) 
- with that dto I'm invoking convertValue  again for some abstract inner logic 

in the 3rd step of convertingValue, did it reuse the in-memory serialization/deserialization of that same object, or are we doing it again ?


thanks for the reply,
@cowtowncoder

**Comment by cowtowncoder** [comment]
@Ben-Mark I am not sure I fully understand your question, but:

1. Jackson does NOT retain any information after `readValue()` or `writeValue()` call ends -- holding a reference to content would easily lead to memory leaks. Any caching would have to be outside of `ObjectMapper`
2. `convertValue()` does not do either full serialization or deserialization since no JSON (or other format) representation is created or used. Intermediate representation is a sequence of tokens.

Put another way: when you handle a request:

1. Jackson has to decode ("parse") JSON content into a token stream (JsonParser does this)
2. To create POJOs, `ObjectMapper` will read token stream and contructor Objects

and when serialization response, reverse

1. `ObjectMapper` will use a `JsonGenerator` to generate sequence of tokens
2. `JsonGenerator` encodes tokens into JSON (or whatever backend format mapper is configured with)

What `convertValue()` does:

1. Create `TokenBuffer` for holding sequence of tokens
2. ObjectMapper serializes input value using `TokenBuffer` as generator (it implements `JsonGenerator`); this fills buffer with tokens
3. ObjectMapper "reads" tokens from `TokenBuffer` to deserialize target value

which does not involve encoding or decoding underlying format (JSON).

I hope this helps.
