### ISSUE TITLE
JsonInclude.Include.ALWAYS for Map.entry no longer works since version 2.10.2

### ISSUE THREAD

**Issue by ArunParthiban-ST** [FasterXML/jackson-databind#2863]
**Describe the bug**
null value not included despite setting inclusion property to always

**Version information**
2.10.2

**To Reproduce**

The following test passes in 2.10.1, but fails since 2.10.2 onwards
```
def 'object mapper includes null java entries'() {
        given:
        ObjectMapper objectMapper = DefaultConfigDataBuilder.newDefaultObjectMapper()
            .setSerializationInclusion(JsonInclude.Include.NON_NULL)
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .setTimeZone(TimeZone.getTimeZone("UTC"))
            .configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);

        objectMapper
            .configOverride(Object.class)
            .setInclude(JsonInclude.Value.construct(JsonInclude.Include.ALWAYS, null));

        objectMapper
            .configOverride(Map.Entry.class)
            .setInclude(JsonInclude.Value.construct(JsonInclude.Include.ALWAYS, null));

        HashMap<String, String> foo = new HashMap<>()
        foo.put("key", null)

        expect:
        objectMapper.writeValueAsString(foo) == '{"key":null}'
    }

```

In version 2.10.2 onwards, objectMapper returns an empty json 
```        
objectMapper.writeValueAsString(foo) == '{}'
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this: I hope to have a look at it tomorrow. Nothing in 2.10.2 release seems relevant (just one fix) but we'll see.

**Comment by cowtowncoder** [comment]
Looking at this example bit more, I realized that this is actually not correct -- `Map.Entry` settings are NOT considered when serializing `Map`s and contents: it would only be relevant for something that directly implements `Map.Entry`.
I am not sure why behavior was different before 2.10.2, but looking at it I think behavior test shows is correct since:

1. Default inclusion criteria for values is defined as `NON_NULL` (setSerializationInclusion)
2. Overrides are not relevant here since they only apply directly matching types (so although `Object` is ultimate base type, inheritance hierarchy is not traversed when applying config overrides; and `Map.Entry` is not relevant even if `Map` internally happens to use it.

Further, to control inclusion of contents of `Map`s (and other structured types), it is the second argument of `JsonInclude.Value` that matters, not first.

There are a few different ways to achieve inclusion criteria you want; possibly:

    mapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(Include.NON_NULL, Include.ALWAYS);

which would not include `null` value POJO properties but would include all Map entry values, including `null`s.

You can also add configOverride for `Map.class` similarly: that would affect serialization of all Maps.
