### ISSUE TITLE
How to deserialize json when key is like 'bBT' ?

### ISSUE THREAD

**Issue by furaul** [FasterXML/jackson-databind#2899]
**Describe the bug**
com.fasterxml.jackson.databind.ObjectMapper#readValue(java.lang.String, java.lang.Class<T>)
failed to deserialize json when the key is like ‘bBT’。

**Version information**
Which Jackson version(s) was this for?
<groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.11.3</version>

**To Reproduce**
If you have a way to reproduce this with:
My java class is defined as
`
public class TestV implements Serializable {

    private String bBT;

    public String getBBT() {
        return this.bBT;
    }

    public void setBBT(String bBT) {
        this.bBT = bBT;
    }

}
`

And my deserialize method is like
`
String json= "{\"bBT\":\"aaa\"}";
TestV testV = new ObjectMapper().parseObject(json, TestV.class);
`
An exception is throwed that the property in testV is bbt, not bBT。

**Expected behavior**
The bBT in testV is 'aaa'.

**Additional context**
Nothing.

**Comment by cowtowncoder** [comment]
Yes, your use of casing is not Bean-compatible; you will need to add `@JsonProperty("bBT")` next to `setBBT` method (or `getBBT`).

**Comment by furaul** [comment]
> Yes, your use of casing is not Bean-compatible; you will need to add `@JsonProperty("bBT")` next to `setBBT` method (or `getBBT`).

Thanks for your reply, but I have got a lot of properties like 'bBT' in classes. 
It seems that I need to do a lot of work to add ‘@JsonProperty’. 
Is there any global config in Jackson to be compatible to properties like 'bBT'?

**Comment by cowtowncoder** [comment]
@furaul Jackson will infer property name of either "bbt" (default) or "BBT" (MapperFeature.USE_STD_BEAN_NAMING) from `getBBT()`. It would never match `bBT` since there is no rule that would produce such a name.

There is no global configuration setting that would change this, but you can probably implement your own `PropertyNamingStrategy` that would allow you to override specific cases? It is more often used to convert from different conventions (like "snake_case" or "kebab-case" names :) ), but should work here too I think.

**Comment by furaul** [comment]
@cowtowncoder Thank you very much, I will try to implement your own PropertyNamingStrategy。
