### ISSUE TITLE
`@JsonValue` not considered when evaluating inclusion

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#2909]
I have an object (a `links` holder) that is essentially a container around a `java.util.Map`. The map is annotated with `@JsonValue`, and this behaves as expected (the map is dumped as a JSON object inline).

However, I only want this included when the map is non-empty, so I annotated the `getLinks()` method with `@JsonInclude(NON_EMPTY)`. However, it appears that the inclusion filter is applied before the value substitution, so it is always included even as `{}`.

I'm using Jackson 2.11.2 (managed via Spring Boot).

```java
@Data
class Wrapper {
  @JsonValue
  Map<String, String> values;
}

@Data
class TopLevel {
  @JsonInclude(NON_EMPTY)
  Wrapper nested;
}
```

**Comment by cowtowncoder** [comment]
Actually, while the basic idea is to indeed implement `isEmpty()`, details get rather tricky (due to existing workarounds).
I think I can solve this but it's not a good starter problem for anyone else.

**Comment by chrylis** [comment]
Thanks! Should I plan to bump to 2.12.0 when it's out to see the new output?

**Comment by cowtowncoder** [comment]
I am planning to release one more rc, 2.12.0-rc2 within 1 week.

**Comment by mbenz89** [comment]
Seems not to work on my side. I'm using 2.12.3 and the @JsonValue annotated getter is still serialized to "null"/default-value if I set JsonInclude to `NON_NULL`/'NON_DEFAULTS` in the ObjectMapper properties or view annotating the relevant value field.

My POJO looks like this:

```
class Container {
@JsonValue @JsonInclude(Include.NON_NULL)
 public getValue(){
 // compute value
 }
}
```

Any ideas @cowtowncoder ?

**Comment by cowtowncoder** [comment]
@mbenz89 This is a bit different combination than issue here and is not supported. Technical reason is because `getValue()` is not an accessor in POJO sense (but provides alternate surrogate/delegate representation to serialize); inclusion would be determined by annotation either on returned type (class annotations) or on property that refers to this value type.
If you want, you can file a new issue to request (RFE) for this combination to work; I don't know if that would be easy to implement or not.

**Comment by mbenz89** [comment]
@cowtowncoder I see. Thanks a lot for the elaboration!
