### ISSUE TITLE
JsonTypeInfo lost in List, but not Array

### ISSUE THREAD

**Issue by efenderbosch** [FasterXML/jackson-databind#2946]
**Describe the bug**
If several "Foo" objects are serialized as an array, the JsonTypeInfo/JsonTypeName information is preserved. If serialized as a List, that information is lost.

**Version information**
2.11.3

**To Reproduce**
```java
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.List;

public class Test {

    @org.junit.jupiter.api.Test
    public void test() throws JsonProcessingException {
        Foo[] asArray = new Foo[]{new Bar("bar"), new Baz("baz")};
        List<Foo> asList = new ArrayList<>();
        asList.add(new Bar("bar"));
        asList.add(new Baz("baz"));
        ObjectMapper mapper = new ObjectMapper();
        String json1 = mapper.writeValueAsString(asArray);
        System.out.println(json1);
        String json2 = mapper.writeValueAsString(asList);
        System.out.println(json2);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
    interface Foo {
        String getId();
    }

    @JsonTypeName("Bar")
    class Bar implements Foo {
        private String id;

        public Bar(String id) {
            this.id = id;
        }

        @Override
        public String getId() {
            return id;
        }
    }

    @JsonTypeName("Baz")
    class Baz implements Foo {
        private String id;

        public Baz(String id) {
            this.id = id;
        }

        @Override
        public String getId() {
            return id;
        }
    }
}
```
output:
```
[{"type":"Bar","id":"bar"},{"type":"Baz","id":"baz"}]
[{"id":"bar"},{"id":"baz"}]
```
Note the first println shows the "type" pseudo-attribute, the second does not.

**Expected behavior**
I know I can resolve this by creating a TypeReference, but can't do that when serializing objects automatically for an API response.

**Comment by cowtowncoder** [comment]
Right, this is Java Type Erasure in action: array types are not generic and keep the type; generic types like `Collection`, `List` etc are generic, and runtime instances do not have this type.
What you pass as value has type of `List<?>`, about same as `List<Object>`. And since `java.lang.Object` does not have `@JsonTypeInfo`, it will not be considered needing polymorphic handling.

As a general recommendation I suggest users avoid using generic root-level values at all since those cause trouble.

But if they really want, there are 2 work-arounds:

1. Use helper class to specify parameterized subtype: `class FooList extends ArrayList<Foo>` -- if so, generic typing is available via subtype relationship
2. Force type to use on writing, something like

    mapper.writerFor(new TypeReference<List<Foo>>() { }).writeValueAsString(list);

Hope this helps -- there is nothing Jackson can do to avoid this issue.

**Comment by efenderbosch** [comment]
Thanks. I'm not sure why I have re-learn this every few years at each new job. Sorry.

Regardless, I was able to solve the (de)serialization with a little wrapper as you mentioned.

```kotlin
class ItemTransactions(val delegate: MutableList<ItemTransaction>) : MutableList<ItemTransaction> by delegate {
    @Suppress("unused")
    constructor() : this(mutableListOf<ItemTransaction>())

    companion object {
        val typeReference = object : TypeReference<ItemTransactions>() {}
        fun wrap(list: List<ItemTransaction>) = ItemTransactions(list.toMutableList())
    }
}
```

Seems line Valhalla is stalled and we'll never get reified generics or inline classes in Java.

**Comment by cowtowncoder** [comment]
@eduardische no problem. :)

I wish there was a good way to catch the problem & help users. It is a very common gotchas.
Thank you for sharing the work-around!
