### ISSUE TITLE
Serialization of transient fields with public getters (add MapperFeature.PROPAGATE_TRANSIENT_MARKER)

### ISSUE THREAD

**Issue by mletynski** [FasterXML/jackson-databind#296]
Currently when my field is transient (with a public getter) it is serialized. I can put @JsonIgnore annotation to tell jackson to not serialize it. But with this approach my object is coupled directly with jackson. Is it possible to add such functionality to "tell" Jackson globally to not serialize transient fields ? Via ObjectMapper#SerializationFeature/Visibility or something different.

**Comment by cowtowncoder** [comment]
Looked at this briefly, and was about to add a `MapperFeature`, but then remembered the underlying complication: removal of `transient` fields occurs too early in the processing (by `AnnotatedClass`).
It would need to occur at a later point. Will see how easy that would be.

**Comment by cowtowncoder** [comment]
Turned out easy enough to implement: the default behavior did not change, but if enabling: `MapperFeature.PROPAGATE_TRANSIENT_MARKER`, `transient` is handled same way as a `@JsonIgnore` on field would, leading to removal of the whole logical property unless there is an explicit `@JsonProperty` to counteract.

Default handling was not changed due to backwards-compatibility concerns, although for Jackson 3.x we could definitely consider changing of defaults.
