### ISSUE TITLE
Stream JSON serialization

### ISSUE THREAD

**Issue by nstdio** [FasterXML/jackson-databind#3010]
**Is your feature request related to a problem? Please describe.**
When one wants to send reasonably big object graph over the wire one forced (otherwise I have lack of knowledge) to materialize 
object to it's JSON representation. I'm referring to `ObjectMapper#writeValueAsString(Object)` and `ObjectMapper#writeValueAsBytes(Object)`, which returns , as methods name suggested, `String` and `byte[]` respectively.
On the other hand one have streaming methods with `OutputStream`, `DataOutput`, `Writer`, which seems logical, but the problem is that HTTP clients I'm aware of using `InputStream` to consume bytes to form the request body.

Using `ObjectMapper#valueToTree(Object)` is not an option either, because it boils down to the same `JsonGenerator`, which is writer in a essence.

**Describe the solution you'd like**
The `ObjectMapper` or some specific component should be able to stream serialized JSON representation through some form of `InputStream`.

Alternatively, we can have method which will supply portion serialized JSON when requested. It can be anything, user supplied byte array buffer or internally maintained buffer exposed through `Iterable<byte[] | ByteBuffer>`.

**Usage example**
```java
ObjectMapper mapper = ...;
Object body = ...

HttpClient httpClient = HttpClient.newHttpClient();
httpClient.send(newBuilder()
    .POST(BodyPublishers.ofInputStream(() -> mapper.stream(body)))
    .build());
```

**Additional context**
If I'm not following wrong path the `TokenBuffer` is the bridge between `JsonGenerator` and `JsonParser`. Is there a way to use it to achieve streaming behavior without introducing new feature, hence complexity?

I'll be happy to contribute if we find it appropriate and useful.

**P.S.** If this issue belongs to [Core](https://github.com/FasterXML/jackson-core), I will transfer it.

**Comment by cowtowncoder** [comment]
First, as to repo, this probably belongs to https://github.com/FasterXML/jackson-future-ideas/ as it seems like a very big undertaking (unless I completely misunderstand what is being asked).

But to be honest I am not sure I completely understand what kind of thing is being requested.
I do understand usage example itself, I think, just not mechanics of suggested solution.
I also wonder if this is not something that should be more tackled from HTTP client side.

So... On one hand, fully streaming serialization (via `OutputStream`, `Writer`) exists. Same for reading (`InputStream`).
But on the other hand, it is generally impossible (with a language like Java) to use a streaming output that could be also read in streaming manner, without buffering. To do that requires, to my knowledge, functionality like coroutines (https://en.wikipedia.org/wiki/Coroutine), since there is sort of impedance.
But such buffering would either require storing full intermediate content (which you would want to avoid), or some way to avoid fundamental problem with blocking i/o where abstractions have impedance (you cannot simply connect one `InputStream` and `OutputStream`).
This is why I am wondering if http client library would not be in better position to handle this impedance, as it is not really specific to json handling, but for all kinds of generated content.

Alternatively I guess one could consider extension of non-blocking (asynchronous) processing. Jackson does implement non-blocking parsing/decoding for JSON and Smile, actually, but not for generation at this point.
In theory, non-blocking output would be doable, although I have not figured out sensible way to do that by augmenting existing generator API (which seems trickier than parser-side).

even with non-blocking output, the question of connecting output and input may not be trivial from user side.

So... I guess I am hoping you have some more ideas to share on both how exactly functionality should work.

**Comment by nstdio** [comment]
@cowtowncoder Thanks for the reply. I'll move this issue to https://github.com/FasterXML/jackson-future-ideas/ and respond there.

**Comment by michael-simons** [comment]
Hello everyone,

I was made aware of that issue and I'd like drop my solution to this here, it's essentially copied it over from my blog post ["lets deadlock all the things](https://info.michael-simons.eu/2025/02/05/lets-deadlock-all-the-things/), with the Jackson bits added.

In essence `java.io.PipedInputStream` and `java.io.PipedOutputStream` do work quite well here for this approach, if care is taken to run them on separate threads. Virtual threads is a great way here, as we will block for IO. 

While this might solve JSON streaming at all, it avoids at least serializing potentially huge object trees into a string sitting on heap just to be chunked over the wire.

```java
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.Map;
import java.nio.charset.StandardCharsets;
import com.fasterxml.jackson.databind.ObjectMapper;
 
class S3 {
  public static void main(String... a) throws Exception {
    var uri = URI.create("http://randomapi.io");
    var body = "Hello";
    var mapper = new ObjectMapper();
 
    try (var client = HttpClient.newBuilder().build()) {
      var bodyPublisher = BodyPublishers.ofInputStream(() -> {
        var in = new PipedInputStream();
        var out = new PipedOutputStream();
        try {
          out.connect(in);
        } catch (IOException e) {
          throw new UncheckedIOException(e);
        }
        Thread.ofVirtual().start(() -> {
          try (out) {
                    mapper.writeValue(out, Map.of("your", "json"));
          } catch (IOException e) {
            throw new UncheckedIOException(e);
          }
        });
        return in;
      });
      var response = client
        .send(
          HttpRequest.newBuilder(uri).POST(bodyPublisher).build(),
          BodyHandlers.ofString()
        ).body();
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
```

I hope someone finds it useful.
Thanks Tatu and maintainers for Jackson and the work you putting in.
