### ISSUE TITLE
Add constructor to Mapper.Builder to allow new builders to be created based on existing builder instances

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3049]
**Is your feature request related to a problem? Please describe.**
jackson-module-scala has some 'mix-ins' that allow classes to be created that mixin code from different sources. It would be easier to do this with Mapper.Builder or more specifically the JsonMapper.Builder if they had a constructor that let you create a new builder from an existing one.

**Describe the solution you'd like**
Basically, the solution I'm looking for is included in the feature request.

**Usage example**

**Additional context**
Not the end of the world if you don't implement this. Just means we don't add a mixin for the Mapper.Builder and the Scala users just need to use the Java APIs to add things like Jackson mix-ins (a Jackson mix-in is a different concept to a Scala mix-in - just have the same name).

**Comment by cowtowncoder** [comment]
Sub-classing of `Mapper.Builder` in Jackson 3.x is designed only for use by data format modules, for format-specific `Mapper` subtypes. Sub-classing by anything else would seem like a bad idea since that would either lead to combinatorial explosion (since there are subtypes for each and every supported format, and now another dimension for module like Scala module).
I realize this 3.x approach to subclassing differs from ideas in 2.x where some other modules did use sub-classing (even Joda datatype at some point).

Or is this is for Jackson 2.x? If so, this may make more sense -- given that it is existing usage?

So I guess that is my first question: if for 2.x, we can discuss details; or if wrt 3.0, would probably need to find some other mechanism.

**Comment by pjfanning** [comment]
Jackson v3 would be ok for this.

**Comment by cowtowncoder** [comment]
Addition itself is doable (although existing copy constructor in base `MapperBuilder` is commented out as there was so far no actual need; `JsonMapper.Builder` would be trivial (has no additional state).
Same thing would be needed for dataformat modules too, but those are probably quite easy as well.

But I guess I would still want to understand use case: ok so yes, mix-ins are different; I assume they add methods (similar to what many scripting languages allow), and as such you might want to add them to all kinds of `ObjectMapper` (format-specific ones)?

How would usage look like?

**Comment by pjfanning** [comment]
addMixin (jackson mixin) is on ObjectMapper in jackson v2 and there is a Scala mix-in for ObjectMapper that adds a more Scala friendly addMixin to ObjectMapper

Jackson 3 does not allow this and only MapperBuilders expose the addMixin. So the aim would be to add a Scala mixin for MapperBuilder.

**Comment by cowtowncoder** [comment]
Ok. So these are mix-ins in Jackson sense. Yes, with 3.0 `ObjectMapper`s are fully immutable so mix-ins cannot be changed through mapper itself but only through Mapper.Builders.

Is the problem here about missing some more convenient mechanisms (to make use of something in Scala like more advanced type handling?), or something that would not work at all?

**Comment by pjfanning** [comment]
It's just a convenience. If there wasn't a convenience function in jackson-module-scala v2, I wouldn't be too worried about adding an equivalent in v3. In the end, Scala devs can use the Java method to add the jackson mix-ins. I'll close this because it's not worth the effort maintaining this support in jackson-module-scala v3.

**Comment by cowtowncoder** [comment]
Ok. We can still revisit this in whatever form, based on feedback from users or ideas.

Could possibly use Builder-style for Scala module itself, and that could probably offer more convenient methods and pass that on build (Module.setModule()). Actually now that I say this, I think that might be the pattern for convenience configuration?
