### ISSUE TITLE
Jackson fails to deserialize 1 field POJO

### ISSUE THREAD

**Issue by WojciechDolata** [FasterXML/jackson-databind#3085]
**Describe the bug**
When trying to deserialize JSON to POJO it fails when POJO has only one field.

**Version information**
2.11.4

**To Reproduce**
POJO: 
@AllArgsConstructor //lombok, if i add constructor manually it still fails
public class SubjectRequest {
    public final String name;
}

While trying to create this POJO via spring's @RequestBody it fails. When i add another parameter, ex public final String a;
jackson works correctly. (creates POJO with {name: 'text', a: null})

**Expected behavior**
Jackson should be able to deserialize 1 field POJO

**Error message**

Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `ad.school.planner.inner.subject.SubjectRequest` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `ad.school.planner.inner.subject.SubjectRequest` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 2, column: 5]]

**Comment by cowtowncoder** [comment]
This is a well-known issue due to ambiguity of the 1-arg constructor case: single-argument could match either:

1. Delegating case like `"string-value"` OR
2. Properties-based case like `{"name" : "value"}`

and if user does not specify mode with

    @JsonCreator(mode = JsonCreator.Mode.PROPERTIES) // or Mode.DELEGATING

Jackson will try to guess which one to use. In your case it likely guesses that DELEGATING mode is to be used and expects a `String`, not `Object` value.

I think Lombok has a way to get appropriate `@JsonCreator` (or `@ContructorProperties` which also implies properties-based approach).

Or... Jackson 2.12 does allow configuration to default to Properties, always. This is probably the best way:

https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0

**Comment by WojciechDolata** [comment]
Thanks a lot! Adding `@JsonCreator(mode = JsonCreator.Mode.PROPERTIES)` solved my issue.
