### ISSUE TITLE
ObjectMapper generates differences in values 

### ISSUE THREAD

**Issue by HirenPatelPh** [FasterXML/jackson-databind#3092]
**Describe the bug**
While iterating my values and putting into my pojo class values are correct as per expectations but when I used to convert values into string using objectMapper it converts my Long values into different values.

String writeValueAsString = objectMapper.writeValueAsString(initialConfig);

I have two long value _groupId_ and _headerId_ and I am creating id = groupId.concat(headerId) so when I print inside my java classes it print values correct but when I convert this list of object using objectMapper values have differences.

Here _groupId_ =9874886776394
[{id: 9874886776394308, _headerId_: 308,},…]  
0: {id: 9874886776394308, _headerId_: 308,…} =>correct
1: {id: 9874886776394900, _headerId_: 900,…} =>correct 
2: **{id: 9874886776394900, _headerId_: 901,…}** => should be 9874886776394901
3: **{id: 9874886776394904, _headerId_: 903}]**  => should be 9874886776394903

I have multiple pojo classes and all pojo classes have generated serialVersionUIDs. 
	private static final long serialVersionUID = -9191888917115709746L;
is there any solution that make serialization perfectly well.

**Version information**
2.9.4

**To Reproduce**
If you have a way to reproduce this with:
AS above 

**Expected behavior**
Serialized value should not differ . 

**Additional context**
Spring itself uses objectMapper for marshalling and unmarshalling so this issue is persist there as well when we send my response to UI or DB services.

**Comment by cowtowncoder** [comment]
Sigh. Ok, some initial suggestions:

1. Please use a recent version: 2.9.4 is very old -- the very least you really really should ALWAYS do is to check out the latest patch (2.9.10). But since no updates will be made for 2.9 would also need to test on 2.11 at least
2. Explaining bits and pieces of code is rarely enough to reproduce: we would absolutely need to see the POJO definitions, input being used. In this case, a self-contained unit test would work best.
3. If this comes via framework like Spring, there is a good chance something outside of Jackson might be causing issues: this is why stand-alone tests are almost always required (to rule out possibility of issue from outside).

**Comment by cowtowncoder** [comment]
Will close as the issue cannot be reproduced: may be reopened with a Jackson-only reproduction against a recent version (2.11.4 or 2.12.2 for example).
