### ISSUE TITLE
Java version used in mvn compile

### ISSUE THREAD

**Issue by OrenGitHub** [FasterXML/jackson-databind#3094]
Hi guys,
Just posting here a reference to a stack overflow question related to your project:
https://stackoverflow.com/questions/66867554/determine-the-actual-java-version-used-in-maven-build/66867638#66867638
It would be awesome if you can answer, thanks !

**Comment by GedMarc** [comment]
posted your fix, 

Please don't use github as a questionaire

**Comment by OrenGitHub** [comment]
@GedMarc thanks, sure.
Can you explain the diff I'm seeing between the data in my `*.class` files and the one in my `pom.xml`?

**Comment by OrenGitHub** [comment]
Problem solved on SO, thanks !

**Comment by cowtowncoder** [comment]
@OrenGitHub in future, please explain the problem here, even if briefly. I personally detest "Link to SO please answer"; that is bit disrespectful. It's fine to link to questions there for context and so on, but issues ought to have enough information to give a clear idea (and proper summary in title) on their own.

**Comment by OrenGitHub** [comment]
@cowtowncoder sure, sorry. no disrespect intended at all. some open source projects like SO as a portal, and that's why I wrote it there.

**Comment by cowtowncoder** [comment]
Np @OrenGitHub! Did not assume any disrespect was meant (you provided some context so I did not mean you only added link, just to be clear).
