### ISSUE TITLE
Non-annotated 1-property Java Record will always use "Properties-based" constructor instead of "Delegating"

### ISSUE THREAD

**Issue by dkubicki** [FasterXML/jackson-databind#3097]
_Given:_

**Version information**

version 2.11.3 which works properly
openjdk 15.0.2 

```
public record UserId(String raw){ }

jsonBody -> {"userId": "123456" }

ObjectMapper objectMapper = new ObjectMapper()
objectMapper.readValue(jsonBody, UserId.class)

noThrowsException()

```

**Version information**
version 2.12 which not works properly
openjdk 15.0.2 

```
public record UserId(String raw){ }

jsonBody -> {"userId":  "123456" }

ObjectMapper objectMapper = new ObjectMapper()
objectMapper.readValue(jsonBody, UserId.class)

throws `Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `user.model.UserId` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('123456')
```

**Version information**
version 2.12 which works properly
openjdk 15.0.2 

```
public record UserId(String raw) {
  @JsonCreator(mode = Mode.DELEGATING)
  public UserId {}
}

jsonBody -> {"userId": "123456" }

ObjectMapper objectMapper = new ObjectMapper()
objectMapper.readValue(jsonBody, UserId.class)

noThrowsException()
```

I am expecting Jackson to serialize String value to UserId record **without using extra annotations** as before. 
What can I do to have a pure approach? Maybe some global configuration on object mapper can be set?

**Comment by cowtowncoder** [comment]
Quick note: since there is no version 2.12, so just to make sure: is this against 2.12.2 (latest) or earlier? If earlier, first make sure to check with 2.12.2.

Second: behavior with 2.12 is as expected: by default, `Record` types are assumed to use Properties-style delegation. 1-argument case is unfortunately fully ambiguous and over past 10 years it has been a big source of pain for everybody.
You expect delegation, most other users seem to expect properties.
It is unfortunate that due to no explicit handling of Records before 2.12, behavior turns out to differ. This was not caught during 2.12 pre-release candidates: not one user reported this as problematic.
But as things are, defaults for Record will not be changed.

There is, however, a new feature to default to delegating which would work for general POJOs:

https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0

```
ObjectMapper mapper = JsonMapper.builder()
    .constructorDetector(ConstructorDetector.USE_DELEGATING)
    .build()
```

I am not 100% sure if Record deserializer considers this setting or not; handling path is different.

**Comment by dkubicki** [comment]
@cowtowncoder in my dependencies tree I have the 2.12.0 version

`|    |         |         |    +--- com.fasterxml.jackson.core:jackson-core:2.10.3 -> 2.12.0 (*)
|    |         |         |    +--- com.fasterxml.jackson.module:jackson-module-kotlin:2.10.3 -> 2.12.0
|    |         |         |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.0 (*)
|    |         |         |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.0 (*)
|    |         |         |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.0 (`

Additionally, I've made some mistake in the previous msg I have `jsonBody -> {"userId": {"raw": "123456"} }`. 
Thanks for the replay I gonna try your approach.

**Comment by cowtowncoder** [comment]
@dkubicki Ok. So the reasoning for this change is two-fold:

1. Before 2.12, there was no planned support for `Record` types: they happen to mostly work by forcing setting of private fields, but this may not work with newer JDKs
2. With 2.12 support was added and since conceptually `Record`s are collection of named properties, the default logic for all cases -- 1, 2 or how many properties -- is to use "Properties" style, expecting JSON Object, with matching name/value pairs. This differs from POJOs where logic for 1-argument case is much more complex and unpredictable

Although it would be possible to add a feature in `ConstructorDetector` to also allow overriding 1-argument Record case.
But as of now, adding the annotation is way to go.

**Comment by yihtserns** [comment]
Not sure if I'm misunderstanding something here, but how can this work?
```
public record UserId(String raw) {
  @JsonCreator(mode = Mode.DELEGATING)
  public UserId {}
}


new ObjectMapper().readValue("{ \"userId\": \"123456\" }", UserId.class)
```
...since the `userId` in the JSON object does not have the same name as the constructor's `raw` parameter?

Unless you mean:
```
new ObjectMapper().readValue("\"123456\"}", UserId.class)
```

**Comment by cowtowncoder** [comment]
@yihtserns Correct. Example given originally could not work for reasons you point out. I am not sure there was a typo: DELEGATING case must take 1 (and only 1) argument; and JSON value structure must be deserializable into that one nominal argument type.

**Comment by cowtowncoder** [comment]
Changed title a bit; considering closing this as I don't have plan to change behavior.
