### ISSUE TITLE
Custom `SimpleModule` not included in list returned by `ObjectMapper.getRegisteredModuleIds()` after registration

### ISSUE THREAD

**Issue by dkindler** [FasterXML/jackson-databind#3110]
**Describe the bug**
I'm trying to register a `SimpleModule` that simple uses some custom serializers and deserializers I need. Based on the output of `mapper.registeredModuleIds`, it doesn't appear that the module is being registered to the mapper.

**Version information**
2.12.2

**To Reproduce**
```
    val mod = SimpleModule()
        .addSerializer(DBDecimal::class.java, DBDecimalSerializer())
        .addDeserializer(DBDecimal::class.java, DBDecimalDeserializer())

    val mapper = jacksonObjectMapper()
        .setTimeZone(TimeZone.getTimeZone("UTC"))
        .registerModule(JavaTimeModule())
        .registerModule(mod)
        .registerModule(MoneyModule())
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false).also {
            println("!!!!!!!!!!!!!!!")
            println(it.registeredModuleIds)
        }
```

```
[com.fasterxml.jackson.module.kotlin.KotlinModule, com.fasterxml.jackson.datatype.jsr310.JavaTimeModule, org.zalando.jackson.datatype.money.MoneyModule]
```

**Expected behavior**
The SimpleModule is registered and appears in the output of `registeredModuleIds`

**Comment by cowtowncoder** [comment]
Hmmh. This is somewhat interesting.

First of all, I think that `SimpleModule` actually is registered, despite id not showing.
As to why id is not included, things get bit more complicated: this is a combination of two different things.

First, there is feature `MapperFeature.IGNORE_DUPLICATE_MODULE_REGISTRATIONS` (enabled by default) that is to prevent duplicate registration of a module. Since it is unlikely to be useful for `SimpleModule`, it is designed in a way so as not to apply to basic `SimpleModule` (but to apply to sub-classes).
This, in turn, is implemented by `SimpleModule` returning `null` from `getTypeId()` (unless sub-classed).
End result then is that no type id is included in list of registered module type ids returned by `getRegisteredModuleIds()`.

I will add a note on Javadoc of `getRegisteredModuleIds()` to mention this, but am not quite sure what else could be done -- there is the challenge of avoiding unintended prevention of registering multiple instances.
One minor improvement could be to make sure that if user specifies explicit `name` in constructor, that would be used as non-null "type id". I'll consider this issue to be about doing just that, but I am open to other ideas as well.

In your case you can sub-class `SimpleModule` if you want, and this should give it distinct type id that would get included.

**Comment by dkindler** [comment]
Thanks @cowtowncoder  -- Your suggestions did in fact work

**Comment by cowtowncoder** [comment]
Changed it so that if (and only if) code specifies explicit `name` for `SimpleModule`, that will be used as the module "type id", and consequently that id will be returned as expected.

**Comment by cowtowncoder** [comment]
Ended up rewriting some aspects and now ALL modules should actually be listed, including "anonymous" `SimpleModule`s. It should not lead to duplicate registrations either (added some basic tests to sanity check).
