### ISSUE TITLE
Deserializers registered via JavaType.withValueHandler are used for array elements but not object properties

### ISSUE THREAD

**Issue by pgoodwin** [FasterXML/jackson-databind#3112]
**Describe the bug**
If I attach a deserializer to a JavaType and then wrap that type in an array type, I can then successfully use that array type to deserialize a JSON array of objects as in the Kotlin code below:
```
val resultType = mapper.typeFactory.constructParametricType(
    Result::class.java,
    MultiValuePayload::class.java,
    String::class.java
).withValueHandler(
    ResultDeserializer(
        MultiValuePayload::class.java,
        String::class.java
    )
)
val resultArrayType = mapper.typeFactory.constructArrayType(resultType)
val reconstitutedArray = mapper.readValue<Array<Result<MultiValuePayload, String>>>(arrayAsJson, resultArrayType)
```
If I try to use the same type outside of the context of an array the deserialzer is not found and the operation fails. So the following code would not work:
```
val reconstitutedObject = mapper.readValue<Result<MultiValuePayload, String>>(resultAsJson, resultType)
```
Instead it throws an `InvalidDefinitionException` because it is using an `AbstractDeserializer` rather than the `ResultDeserializer` that I tried to register.

I am attempting to use this technique because the `KotlinModule` does not allow deserializers for multiple variations of parameterized types to be registered since type erasure removes the distinguishing information from the types being registered. This seems like a simpler issue to fix, however.

**Version information**
2.12.2

**To Reproduce**
The code above comes from a public repo that I have been experimenting in. It is located on the following branch:
https://github.com/pgoodwin/serialization-experiment/tree/inconsistant_value_handler_behavior

**Expected behavior**
The ObjectMapper should handle deserializers registered via `withValueHandler` in a consistent way. I would prefer, of course, that they be used at all times, rather than only when wrapped by an array. 

This inconsistent behavior reflects a deeper issue in the code which is that the deserializer resolution for array elements follows a different code path than the resolution for object properties. If the inconsistency I'm reporting is possible surely others are possible as well, possibly even more serious than this.

**Comment by cowtowncoder** [comment]
First, one quick note: please do not use `withValueHandler()` from custom code. Javadocs may need to be amended but this is not meant to be used by application or framework code outside of jackson-databind internals.
Ideally this method was not needed at all, but it has been in internal use since 1.0 due to difficulties in passing information in other ways and I have not yet figure out a way to remove it from Jackson 3.0.

Second: if you need to register handlers (serializer, deserializer) for generic types, you can not use "Simple" variants (`SimpleModule`, `SimpleSerializers`, `SimpleDeserializers`) but implement your own `Deserializers`/`Serializers` wherein you can use fully resolved type information (`JavaType`) from a callback.
This allows you to provide different (de)serializer.

As to `withValueHandler()`, behavior only needs to work for internal usage of databind: there is no intention of it working for anything outside. I will go ahead and try to indicate this better in Javadocs so that developers would not try to use it -- I understand that since it exists it may seem tempting to use it.

**Comment by pgoodwin** [comment]
I see. This makes sense. I think it's worth pointing out that this was the path of least resistance for getting this deserializer instance registered, which may be an indicator of an ease-of-use issue with the API.

**Comment by cowtowncoder** [comment]
@pgoodwin Makes sense; I was just surprised that someone had found this mechanism :)
(or maybe I just aware of its use)

There are some reasons why the ability of passing custom (de)serializers directly is not exposed so far (related to lack of contextualization), but if there is need for such ability, perhaps something could be added as an explicit feature via `ObjectReader`. Something like:

    MyValue v = objectMapper.readerFor(MyValue.class)
        .using(new MySpecialDeserializer())
       .readValue(source);

If so, it'd be worth filing an issue to request this (I could do that but I usually prefer users doing that to make sure there's always someone who asked for it, and not just something I thought someone somewhere might need :) ).
