### ISSUE TITLE
Support registering custom deserializers for parameterized types on Deserialzers objects

### ISSUE THREAD

**Issue by pgoodwin** [FasterXML/jackson-databind#3114]
**Is your feature request related to a problem? Please describe.**
I need to serialize/deserialize objects of a parameterized type that I do not control (so I can't annotate it). Since the type is parameterized and deserializers don't receive data about the values of those parameters, I want to register a different deserializer for each variation of the type I'm using. The code I'm writing is in Kotlin, so I'm using the `KotlinModule` which inherits from `SimpleModule` which stores its deserializers in a field of the concrete type `SimpleDeserializers`, all of which serves to make it nearly impossible to register deserializers based on `JavaType`s which can contain type parameter data rather than `Class`es which cannot.

**Describe the solution you'd like**
I would like `SimpleModule` to use the most abstract types possible for the fields that it allows to be customized. In particular it would help me if `setDeserializers` took `Deserializers` rather than `SimpleDeserializers`. In addition I would like there to be an implementation of `Deserializers` that is based on `JavaType` rather than `Class` so that there is a supported avenue (albeit not very discoverable or convenient) for developers to register their custom deserializers for parameterized types.

**Usage example**
I have implemented (by completely overriding the functionality of `SimpleDeserializers` in a new class) and used this feature on a branch in a toy project which can be found here: https://github.com/pgoodwin/serialization-experiment/tree/java-type-deserializers

**Additional context**
This is the third issue I've filed to suggest (hopefully) easy ways to support deserializing parameterized types. I think that this may become a more popular topic if more and more developers start using monads (such as Result) in their programming and want to pass them between processes via JSON. 

I hope my filing these multiple issues is more useful than annoying.

**Comment by cowtowncoder** [comment]
Term "Simple" in SimpleModule and SimpleDeserializers refers to support in a simple case -- and this precludes handling things like generic types. Maybe documentation needs to be improved in this case, but the intent is not to try to offer complex out-of-the-box logic but only simple 90/10 solution.
The specific reason for `SimpleModule` to refer to `SimpleDeserializers` is that otherwise it would not be possible to support convenience mechanisms (addSerializer / addDeserializer) -- `Deserializers` interface does not have mutators, nor does it impose class-based lookups.

If you wanted to offer a design for more advanced alternative(s) that could work; but I think the request on SimpleModule/Simple[De]Serializers is a non-starter. There is a reason why design is limited in this way: there is a lot of complexity if and when you need to handle generic types, many (most?) of which are structured or container types, and where few assumptions can be made on handling.
