### ISSUE TITLE
Two fields with different casing are not serialized properly

### ISSUE THREAD

**Issue by akefirad** [FasterXML/jackson-databind#3115]
**Describe the bug**
Two fields with different casing are not serialized properly.

**Version information**
2.11.3

**To Reproduce**
```java
@Data
public class Foo {
    String foobar;
    String fooBar;
}
```

If you try to serialize an instance of `Foo`, you get the following (the second field is gone!):
```json
{"foobar":"foobar"}
```
It seems Jackson ignores the casing altogether and overwrites one field with another. I'm not sure if it's a bug or feature. 

**Expected behavior**
I expect to see:
```
{"foobar":"something", "fooBar":"something"}
```

**Additional Context**
We're using Spring default ObjectMapper bean. Is there any specific configuration I need to check?

**Comment by cowtowncoder** [comment]
Since this seems to use some framework (Lombok?) based on `@Data`, what is first needed is to see what kind of class gets generated -- Jackson only sees actual runtime class, which includes getters and setters generated.
This will likely show the root cause or at least indicate what is going on.

Beyond this, what is missing here is actual code: class definitions alone are only a part of the picture: it is not possible to reliably build a test case from just this since `ObjectMapper` may be configured in different ways that affect serialization.

Finally, I would strongly recommend avoiding using fields with names that only differ by casing: it is prone to issues like this.

**Comment by akefirad** [comment]
OK, I'm pretty sure I checked the Lombok generated class, but apparently I was blind. You're right. It's a Lombok bug/feature. Sorry for the false alarm.

**Comment by cowtowncoder** [comment]
@akefirad no problem, thank you for checking & quick follow up!

I'll need to figure out how to better document this kind of challenge as it has become pretty common.
