### ISSUE TITLE
TypeReference not working as expected in generic context

### ISSUE THREAD

**Issue by CollinAlpert** [FasterXML/jackson-databind#3129]
**Describe the bug**
Using `TypeReference` in a generic context doesn't convert to the expected type correctly and results in a `ClassCastException`.

**Version information**
2.11.4

**To Reproduce**
```java
public class Main {

	private static final ObjectMapper objectMapper = new ObjectMapper();

	public static void main(String[] args) throws JsonProcessingException {
		String json = "{\"name\": \"Steve\"}";
		Person p = getResult(json);
	}

	private static <T> T getResult(String json) throws JsonProcessingException {
		return objectMapper.readValue(json, new TypeReference<T>() {});
	}

	private static class Person {
		public String name;
	}
}
```
This results in the following exception: `java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class Main$Person`

**Expected behavior**
The program exits without any issues.

**Comment by cowtowncoder** [comment]
You cannot use `TypeReference` with type variables: this will not and cannot work due to Java Type Erasure: no type information is passed and 

```
  new TypeReference<T>() { }
```

is roughly equivalent to saying

```
    new TypeReference<Object>() { }
```

which is why you get result mapped as `Map` (specifically `LinkedHashMap`) if you get JSON Object.

Unfortunately it is not easy to even catch this case in general case, and report it as an error (which would be ideal as usage makes no sense): type variables may be hidden deeper in structure.

**Comment by rcollette** [comment]
Oddly enough, I've been able to get this to work somehow with an HttpClient BodyHandler

https://stackoverflow.com/a/69211157/107683

**Comment by cowtowncoder** [comment]
@rcollette That is interesting indeed. Unless it results in same as `TypeReference<Object>` (which would make sense), mapping to `List`s, `Map`s and wrapper types using "natural" mapping.
