### ISSUE TITLE
extend @JsonFilter to filter lists/arrays

### ISSUE THREAD

**Issue by rpfong0** [FasterXML/jackson-databind#313]
As of version 2.2.3, @JsonFilter is not applicable to List or array types.  However, issue #307 is extending this filter to work for maps.  It would be very useful to enable this extension for lists and arrays.  A use-case and current workaround solution was discussed on the mailing list topic below.

see:  http://markmail.org/message/svf42uyo6t576mvn?q=filtering+whole+objects

**Comment by cowtowncoder** [comment]
Minor update: (1) from above has been implemented, and there is now `PropertyFilter.serializeAsElement(...)` method to call.

The bigger part, (2), of calling this method from array/`Collection` serializers still needs to be implemented to support filtering. This is not difficult to do, but requires changes to quite a few distinct serializers.

**Comment by cristianconstantin** [comment]
Any progress on this issue?

**Comment by cowtowncoder** [comment]
No, I have not worked on this issue. Pull Requests welcome.

**Comment by pdinc-oss** [comment]
> requires changes to quite a few distinct serializers.

Any hints where to start looking?

**Comment by pdinc-oss** [comment]
> > requires changes to quite a few distinct serializers.
> Any hints where to start looking?
Making progress, but not sure where to get/create the PropertyWriter.

**Comment by cowtowncoder** [comment]
@pdinc-oss Can you elaborate on the problem? (it has been a while since I worked in this area)

**Comment by pdinc-oss** [comment]
in IndexedListSerializer.serializeContents(List<?> value, JsonGenerator g, SerializerProvider provider):
 
                if (elem == null) {
                    provider.defaultSerializeNull(g);
                } else if (filter != null ) {
                    filter.serializeAsElement(elem, g, provider, /*PropertyWriter*/ null);
                } else {
                    Class<?> cc = elem.getClass();
                    JsonSerializer<Object> serializer = serializers.serializerFor(cc);
                    log.log(Level.INFO,"i:{0}, serializer={1}, elem={2}",new Object[] {i,serializer,elem});
                    if (serializer == null) {
                        // To fix [JACKSON-508]
                        if (_elementType.hasGenericTypes()) {
                            serializer = _findAndAddDynamic(serializers,
                                    provider.constructSpecializedType(_elementType, cc), provider);
                        } else {
                            serializer = _findAndAddDynamic(serializers, cc, provider);
                        }
                        serializers = _dynamicSerializers;
                        log.log(Level.INFO,"new serializer={0}",new Object[] {serializer});
                    }
                    serializer.serialize(elem, g, provider);
                }

my issue is I need to pass a writer to filter.serializeAsElement, but I do not understand enough of how/why PropertyWriters are instantiated.

I have been looking at the MapSerializer.serializeFilteredFields, but I have been unable to make heads or tails on the `prop = new MapProperty(_valueTypeSerializer, _property);`

**Comment by cowtowncoder** [comment]
Originally filtering was done for POJOs, so I thing `BeanSerializer` and/or `BeanSerializerBase` might be good places to loop -- `MapSerializer` was added later... although `MapSerializer` may have more similarities to what is needed here, as it also does not have "real" properties (from Jackson perspective).

**Comment by pdinc-oss** [comment]
> Originally filtering was done for POJOs, so I thing `BeanSerializer` and/or `BeanSerializerBase` might be good places to loop  

I did look there, but it seemed too specific. Need to account for list of list, etc. It also still did not help me understand "how" a new PropertyWriter should be instantiated.

> -- `MapSerializer` was added later... although `MapSerializer` may have more similarities to what is needed here

That was my rationale.

> , as it also does not have "real" properties (from Jackson perspective).

Is that good or bad?

**Comment by cowtowncoder** [comment]
On not having "real" properties: it's just that original filtering was based on assumption of filtering POJO properties, so some amount of working around is/was needed with `MapSerializer`. Something similar might be necessary with arrays/lists.

This also goes to one semantic question: for some other annotations (like `@JsonIgnoreProperties`) annotation on List/array-valued property actually applies to contents (POJOs within List/array), instead of container. So one thing I realized here is that ... it may be necessary to verify that such usage is not supported yet; we don't want to change behavior.

**Comment by pdinc-oss** [comment]
I am going for a minimal change set right now - as there is a specific blocking itch.

We have a filter which applies if the type has an annotation, then if that object has certain fields or field values applies another transformation.

Back to my question, is there a getting started set of docs, emails archives, something to explain the PropertyWriter concepts? I ask because I am not finding a good starting place with the `MapSerializer`.

**Comment by cowtowncoder** [comment]
I don't think there is any documentation outside source & comments, unfortunately, since these are more of internal extension points; `PropertyWriter` would be intended as of interest only from within filter, where it is the sink/target to call to output property value.

But on usage: just to make it easier for me to understand; would this be used for something like removing `null`s from being serialized for `List` values? Or something similar.

**Comment by cowtowncoder** [comment]
Been open 10 years, no plans to implement, not highly voted, closing. May be re-filed as new RFE (possibly linking to this issue) if there is strong demand or -- ideally -- suggestion for specific plan, or PR.
