### ISSUE TITLE
JsonTypeInfo not work on Map serialization

### ISSUE THREAD

**Issue by deblockt** [FasterXML/jackson-databind#3167]
When we use the annotation `JsonTypeInfo` it not work when the object is used on a Map.

``` java
package com.adeo.sales.customerorder.paymentscheduler.v2.domains.paymentexecution.service;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;


public class Main {
    public static void main(String[] args) throws JsonProcessingException {
        final var myClass = new MyClass();

        System.out.println(new ObjectMapper().writeValueAsString(Map.of("test", myClass)));
    }

    @JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type")
    @JsonSubTypes({
        @JsonSubTypes.Type(value = MyClass.class, name = "MyClass")
    })
    public static abstract class Test {
        public String testValue;
        protected Test(String value) {
            this.testValue = value;
        }
        public String getTestValue() {
            return this.testValue;
        }
    }

    public static class MyClass extends Test {
        public String myValue;
        public MyClass() {
            super("MyClassValue");
            this.myValue = "foo";
        }
    }
}

```

This sample give the result `{"test":{"testValue":"MyClassValue","myValue":"foo"}}` instead of `
{"test":{"type":"MyClass","testValue":"MyClassValue","myValue":"foo"}}`

tested with jackson 2.12.3

**Comment by cowtowncoder** [comment]
This does not (and can not work) due to your usage of generic type as root value (as opposed to something access via typed property of a POJO). I really should add this in some FAQ as it is a very common question.

The issue is that type of any `Map` instance, at runtime, can only be detected as `Map<?,?>` -- with the sole exception of non-generic subtypes that by extension indicate actual type binding.

Type definition during serialization MUST indicate typing for containers (`Map`s, `Collection`s -- arrays actually are fully typed and not problematic) since base type of all elements must be same.

With that, there are couple of work-arounds (your usage as-is cannot be supported unfortunately):

1. Use a throw-away helper type: `public class MyClassMap extends HashMap<String, MyClass> { }` -- if you do that, type information will be added appropriate
2. Add wrapper POJO around your map: since `Map` field is declared with full generic type, it will be appropriately detected.
3. Use `ObjectWriter` and construct or reconfigure it with generic type: `TypeReference` or `JavaType` works: something like

     ObjectWriter w = mapper.writerFor(new TypeReference<Map<String, MyClass>>() { })
          .writeValueAsString(map);

I hope this helps.

**Comment by chrylis** [comment]
This is highly surprising; I found this after getting bitten by the same problem. While I understand the difficulties with _deserialization_, if I simply write this code:

```
Object o = new ClassWithTypeInfo();
om.writeValueAsString(o);
```

I get the `@type` property written. The _apparent logic_ for ObjectMapper is to inspect the value as it's traversed and to then recursively handle it according to whatever it sees. This is how, for example, collection-valued map entries appear, and if I put some other type that gets specific handling (say, `Instant`) into the map, the custom serialization also applies to it. It is both highly surprising that the mapper "notices" certain serialization instructions but not others, and it's unclear to me why it "can't work", since the mapper does in fact do runtime-type dispatch on other dimensions of serialization customization.

**Comment by yawkat** [comment]
@chrylis The "weird" case here is the root serialization. If you were to wrap the object in a class like:

```java
    public static class Wrapper {
        final Object o;

        public Wrapper(Object o) {
            this.o = o;
        }

        public Object getO() {
            return o;
        }
    }
```

You will see the same behavior reported by the OP, without the type serializer.

The root value serializer uses a different code path than those of `Object` fields.

**Comment by chrylis** [comment]
Perhaps it is. Nevertheless, it's highly unintuitive that _serializing_ should do so, especially because these are both true:

- If the runtime type has `@JsonSerializer`, then that serializer is used regardless of the declared type.
- If the runtime type has `@JsonTypeInfo`, then type info is ignored if the declared type is more general.

The expected rule seems to be that if one serialization customization is applied in circumstance X, then serialization customizations _generally_ should be applied in that circumstance.
