### ISSUE TITLE
Clarification on split behavior with `@JsonIgnore`

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#3207]
I am using 2.12.0 and just ran into some behavior that was surprising to me; I'm not sure whether it's (1) intentional, (2) unintentional but unavoidable, or (3) a bug.

I had a base interface that applied `@JsonIgnore` to an abstract getter:

```
interface HasProp {
  @JsonIgnore
  String getProp();
}
```

Later on, I had an implementation class where I _do_ want `prop` deserialized on incoming requests. I wrote my class like this, using Lombok:

```
@Getter
@Setter
class WithProp implements HasProp {
  @JsonIgnore(false)
  String prop;
}
```

I expected this to override the interface's instruction and make the property "visible" again, but it didn't. I believe that the reason for this is that Lombok doesn't copy field annotations onto the accessors, but I expected Jackson to either (1) override the ignore entirely or (2) split the configuration and enable the setter while still ignoring the getter (which would have been fine). Instead, the entire property was still ignored. What is the reason that the annotation on the implementing class didn't trigger at least a split?

**Comment by cowtowncoder** [comment]
Ok, I think I can explain some of the confusion here.

So... adding `@JsonIgnore(false)` would mask any `@JsonIgnore` that would exist either in target class (when using mix-ins) or super class (which only works for methods). It does not have effect on annotations in other accessors such as getters. This when not considering Lombok; Lombok might choose to add annotations to other accessors.

But instead of trying to mask annotations this way, you could try adding explicit `@JsonProperty` instead: if there are conflicting ignore/inclusion markers, we have an actual "split" case.

**Comment by cowtowncoder** [comment]
I don't think there is anything to change here; I can clarify if there are further questions but will close the issue itself (will see updates for followups)
