### ISSUE TITLE
Add ability to use a custom AnnotationIntrospector to an ObjectWriter

### ISSUE THREAD

**Issue by geoand** [FasterXML/jackson-databind#3294]
**Is your feature request related to a problem? Please describe.**
Use custom `AnnotationIntrospector` when deriving an `ObjectWriter` from an `ObjectMapper`.

**Describe the solution you'd like**
I would like to see a new method like:

```java
    public ObjectWriter writer(AnnotationIntrospector introspector) {
        return _newWriter(getSerializationConfig().with(introspector));
    }
```

added to `ObjectMapper`.

**Usage example**
The code above should hopefully explain what I want to see.

**Additional context**
I don't know enough about Jackson internals to know if this has any deep implications I am not seeing by looking at the API surface.

If however this proposal is acceptable, I can open a Pull Request.

The reason I would like to see this feature is that I would like to provide even deeper Jackson integration for [RESTEasy Reactive](https://quarkus.io/guides/resteasy-reactive)

**Comment by cowtowncoder** [comment]
Hi @geoand! Unfortunately this is not possible to do/offer: not because it would not be possible to create differently configured `ObjectWriter`s but because `AnnotationIntrospector` configuration must be set before any read/write use.
This because information acquired via introspectors is used for creating various handlers (serializers, deserializers etc) that are then cached on per-`ObjectMapper` basis. These handlers are accessed by `ObjectWriter` as well.
So even if you could change the introspector in use, it would usually not change observed behavior as introspection may have already occurred for types in question.

So. To use different `AnnotationIntrospector`, you essentially need a new `ObjectMapper`. This is a fundamental design constraint.

**Comment by geoand** [comment]
Understood, thanks a lot for the explanation!
