### ISSUE TITLE
`DecimalNode` type not retained during JDK serialization, deserialization

### ISSUE THREAD

**Issue by victornoel** [FasterXML/jackson-databind#3296]
**Describe the bug**

When a `DecimalNode` is cloned via serialization (serialized then deserialized), the clone is not equal to the original.

I know there are a lot of issues related to `BigDecimal` in jackson, but I don't think I have seen one about this. Don't hesitate to close it if there are other planned/tracked issues that covers this :)

**Version information**

2.12.1

**To Reproduce**

```java
    @Test
    public void should_properly_deserialize_decimal_node() {
        var node = new ObjectMapper().getNodeFactory().numberNode(BigDecimal.ONE);
        Assert.assertTrue(node instanceof DecimalNode);
        var clone = clone(node);
        Assert.assertTrue(clone.equals(node));
        Assert.assertTrue(node.equals(clone));
    }

    @SuppressWarnings("unchecked")
    private <T> T clone(T original) {
        try(var baos = new ByteArrayOutputStream(); var oos = new ObjectOutputStream(baos)) {
            oos.writeObject(original);
            try (var bais = new ByteArrayInputStream(baos.toByteArray()); var ois = new ObjectInputStream(bais)) {
                return (T) ois.readObject();
            }
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }
    }
```

**Comment by cowtowncoder** [comment]
Hmmh. Ok, what is happening is that `BigDecimal.ONE`, `1`, gets serialized as JSON value `1` on serialization.
And gets deserialized as `IntNode` because, well it is an integral JSON number.

This is due to my deciding to use a compact & light-weight format for serialization: JSON.
But that does not necessarily retain exact type as shown here.

I think I'll consider it a flaw but one that probably will not be fixed: effort to create alternate parallel encoding schema that would retain type seems rather expensive for benefits. In general intent with `JsonNode` really is to handle it as JSON representation.
