### ISSUE TITLE
ObjectMapper initialization problem

### ISSUE THREAD

**Issue by juliuszhang** [FasterXML/jackson-databind#3317]
```java
public class Holder{
   private static volatile ObjectMapper mapper;

    public static ObjectMapper getMapperInstance() {
      if (mapper == null) {
            synchronized (Holder.class) {
                if (mapper == null) {
                    mapper = new ObjectMapper();
                    mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
                    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
                    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
                    mapper.setLocale(Locale.CHINA);
                    mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
                }
            }
        return mapper;
    }
}
```

i wrote such code in my project,the FAIL_ON_UNKNOWN_PROPERTIES feature sometimes not works,I know the way of initialization will cause such problems in multithreading enviroment, Although I think this problem will be recoverd when the ObjectMapper fully initialized. but it did't recover，looks like FAIL_ON_UNKNOWN_PROPERTIES is always true.i really want to know why.
Thanks a lots！！！

**Comment by yawkat** [comment]
It is hard to guess at the exact cause of this issue, but publishing the ObjectMapper that way is definitely a bad idea. Fully initialize it first, then write it to the field.

**Comment by cowtowncoder** [comment]
This is incorrect way to synchronize anything; you are not syncing when checking if `mapper` is `null`, so as @yawkat suggested you could well see a partially initialized instance.

So I would first fix that problem: there are ways to achieve lazy construction by using class loader: basically, your `Holder` object can simply eagerly construct and configure `ObjectMapper` on its constructor, and then caller can access mapper normally without synchronization.

There are no known issues with Jackson itself in this regard and usage pattern is clear: you MUST fully configure instance before using it.

Or, if you want to dynamically change `DeserializationFeature`s, use `ObjectReader`:

```
ObjectReader r = mapper.readerFor(MyClass.class)
    .without(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
MyClass value = r.readValue(source);
```

since `ObjectReader` instances are thread-safe and can be constructed with different settings.
