### ISSUE TITLE
`@JsonSetter(nulls=...)` not working for serialization?

### ISSUE THREAD

**Issue by andreas-trvlk** [FasterXML/jackson-databind#3333]
So, I have been utilizing ObjectMapper in my Spring Boot project. I would like to achieve a result when all null string should be converted into empty string in a serialization. I have tried:
1. using configOverride
```
objectMapper.configOverride(String.class).setSetterInfo(JsonSetter.Value.forValueNulls(Nulls.AS_EMPTY));
```
2. Using `@JsonSetter` directly to the field.
```
@JsonSetter(nulls=Nulls.AS_EMPTY)
```
None of them are working. I even tried to used other `Nulls` value, eg. `Nulls.SKIP`, but it is still not working.

FYI, I use Jackson module v2.11.2. I think this module it is defined automatically by Spring.

Did I miss something?

**Comment by andreas-trvlk** [comment]
I think this should be only working for deserialization? In my case, I want to convert a object into another object like Map or Json.

**Comment by cowtowncoder** [comment]
Correct: it works on deserialization -- setters are not involved in serialization at all (with minor exception that annotations from setters are merged along with those from getters, fields).

Right now there isn't functionality for general conversions on serialization, although it should be possible to use `Converter`s via:

```
@JsonSerialize(converter = MyConverter.class)
public String getValue() { ... }
```

... with one notable exception. `null` value writes (or filtering) do not actually go through value `JsonSerializer` at all.
Originally this was to simplify serializer implementations (meaning they never have to deal with `null`s for value itself) but over time this become a problem since there isn't much in way of customizing handling on writer side.

So: with respect to the original question you are right: `@JsonSetter` is not applied to serialization. 
I will close this issue; you may file a new one for requesting or suggesting functionality that could help, but `@JsonSetter` as is would not really fit the bill from semantic perspective (wrt Setters not being applicable).

**Comment by cowtowncoder** [comment]
One other note: of functionality that exists, `@JsonFilter` might work (see f.ex https://www.baeldung.com/jackson-serialize-field-custom-criteria). I am not 100% sure, however, if `null`s do get passed. If they do, however, filtering object can do any write so it could definitely translate `null`s into some other output.
