### ISSUE TITLE
Limit the length of serialized json strings

### ISSUE THREAD

**Issue by asasas234** [FasterXML/jackson-databind#3351]
When serializing an object as a json string, how to limit the length of the result, the result can be an incomplete json string, I don't want to serialize the whole object first and then go to truncate it with a subString

**Comment by yawkat** [comment]
You can provide a custom OutputStream that limits the length.

**Comment by cowtowncoder** [comment]
I would second @yawkat's recommendation at this point.

I do think we should have some processing limits, going forward, including possible limit on total output length. But that would be much bigger undertaking; and would likely be using exceptions to indicate "too big to output" instead of quietly truncating.
