### ISSUE TITLE
Polymorphic typing does not work for root-level Record values (type erasure)

### ISSUE THREAD

**Issue by toonborgers** [FasterXML/jackson-databind#3356]
**Describe the bug**
When configuring an object mapper with following configuration
```
    private final ObjectMapper objectMapper = new ObjectMapper().activateDefaultTyping(
            BasicPolymorphicTypeValidator.builder().allowIfBaseType(Object.class).build(),
            NON_FINAL);
```

The serialization of records does not work as expected. Instead of creating an array with the type information, we just get the plain json. If we then try do deserialize we get an error like follwing:
`com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected START_ARRAY: need JSON Array to contain As.WRAPPER_ARRAY type information for class java.lang.Object
 at [Source: (String)"{"value":"9d15f17b-6596-434e-877f-4ecf1528bba9"}"; line: 1, column: 1]`

**Version information**
2.13.0

**To Reproduce**
```
class RecordTest {
    private final ObjectMapper objectMapper = new ObjectMapper().activateDefaultTyping(
            BasicPolymorphicTypeValidator.builder().allowIfBaseType(Object.class).build(),
            NON_FINAL);

    @Test
    void testRecords() throws Exception {
        var json = objectMapper.writeValueAsString(new MyRecord("My value"));
        System.out.println(json); // Prints {"value":"My value"} , expected: ["MyRecord",{"value":"My value"}]

        var deserialized = objectMapper.readValue(json, Object.class); // Throws exception because the type information is unknown
        System.out.println(deserialized);
    }
}

record MyRecord(String value) {
}
```

**Additional context**
Passing the explicit class to the `readValue` call does work, but it shouldn't be needed

**Comment by cowtowncoder** [comment]
Hmmmh. I think you are hitting the dreaded "JAva Type Erasure" issue here: when serializing so-called "root value" (main level object NOT referenced via properties), the base type considered is the runtime type -- in this case a record type, and record types are `final`. Hence, no type info.

But when you read it you are asking for different base type, essentially, `Object`. Which is not final.

One work-around would be to use a wrapper POJO, in which type of `Record` value field is `Object` -- this would work as expected, since then "base type" is defined by field/method signature and serialization value type by actual instance type.

Ideally we should also have something like `ObjectWriter.withBaseType()` which would allow forcing "base type" (type only considered for polymorphic type id handling but NOT value itself) to something different than "value type" (what the value being serialized actually is, i.e. subtype here).

So I don't have a really good solution here, for case of root value polymorphism. I would recommend using a wrapper.
One benefit there being that you could enable polymorphism for ONLY that field, not as general:

```java
public class Wrapper {
     @JsonTypeInfo(....) // instead of "default typing")
     public Object value; // Records and whatever
}
```

**Comment by cowtowncoder** [comment]
Cannot make work as suggested: Type Id not written since Record type is `final` on serialization and take as base type (unless `ObjectWriter.forType(Object.class)` used to change that); but on deserialization target type of `Object` is NOT `final`; so Type Id is expected.

Closing as won't fix.
