### ISSUE TITLE
`@JsonIgnore` does not if together with `@JsonProperty` or `@JsonFormat`

### ISSUE THREAD

**Issue by lizongbo** [FasterXML/jackson-databind#3357]
**Describe the bug**
JsonIgnore is not work when with JsonProperty or JsonFormat。
code:

        @JsonIgnore
        @JsonProperty("create_time")
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
        Date createTime;

**Version information**
2.13.1

**To Reproduce**
test case:

    @Test
    void testJsonIgnore() throws JsonProcessingException {
        TestIgnorebean tb = new TestIgnorebean();
        tb.setCreateTime(new Date());
        tb.setAge(10);
        tb.setNickName("lizongbo");
        ObjectMapper mapper = new ObjectMapper();
        JsonInclude.Value full = JsonInclude.Value.construct(Include.ALWAYS, Include.ALWAYS);
        mapper.setDefaultPropertyInclusion(full);
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
        mapper.enable(Feature.WRITE_BIGDECIMAL_AS_PLAIN);
        mapper.setTimeZone(TimeZone.getDefault());
        System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(tb));
        System.out.println("jackson vesion " + JsonIgnore.class.getPackage().getImplementationVersion());
    }

    static class TestIgnorebean {
        @JsonIgnore
        @JsonProperty("nick_name")
        String nickName;
        @JsonIgnore
        @JsonProperty("create_time")
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
        Date createTime;
        int age;

        public String getNickName() {
            return nickName;
        }

        public void setNickName(String nickName) {
            this.nickName = nickName;
        }

        public Date getCreateTime() {
            return createTime;
        }

        public void setCreateTime(Date createTime) {
            this.createTime = createTime;
        }

        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            this.age = age;
        }

    }

result:

```
{
  "nickName" : "lizongbo",
  "createTime" : 1640089093927,
  "age" : 10
}
```

jackson vesion 2.13.1

//  JsonIgnore, JsonFormat and JsonProperty all not work  correct.

**Expected behavior**
need:

```
{
  "age" : 10
}
```

jackson vesion 2.13.1

**Comment by cowtowncoder** [comment]
Hmmh. I am not sure if this is working properly or not: combination of `@JsonIgnore` (to ignore) and `@JsonProperty` (to explicitly include) is undefined. You should NOT add `@JsonProperty` for anything being ignored since that is specifically meant to mean "DO INCLUDE". This is not true for `@JsonFormat` which should not have any effect if `@JsonIgnore` exists.

I can see why it might be expected that `@JsonIgnore` has precedence: I hope to have time to investigate this to make sure I understand what is going on.

**Comment by cowtowncoder** [comment]
Hmmmh. Interesting. At first I was unable to reproduce this, with simpler test like:

```java
    static class IgnoreAndProperty3357 {
        public int toInclude = 2;

        @JsonIgnore
        @JsonProperty
        @JsonFormat
        public int toIgnore = 3;
```

in which `@JsonIgnore` takes effect over `@JsonProperty`.

But if I make field non-public, leave annotations, add a public getter, then the problem is reproduced.

On short term I would recommend removing unhelpful `@JsonProperty` -- it really should NOT be there -- or moving annotations to getter (or even setter method). Any of these should make behavior ignore property in question.

I will however add a failing test for this problem since I do think that ideally even this combination should result in ignoral of the property.
