### ISSUE TITLE
Missing JsonNode field deserialized to null instead of NullNode

### ISSUE THREAD

**Issue by the8tre** [FasterXML/jackson-databind#3389]
**Describe the bug**
There's a behavior change between `2.12.6` and `2.13.0`.
Until then a missing `JsonNode` field was deserialized as a `NullNode` and it now is deserialized to Java `null`.

**Version information**
Behavior change occurs since `2.13.0`

**To Reproduce**
```java
    public static class MyObject {
        public JsonNode jsonNode;
        @JsonCreator
        public MyObject(@JsonProperty("jsonNode") JsonNode jsonNode) {
            this.jsonNode = jsonNode;
        }
    }
    
    @Test
    void nullNodeTest() throws JsonMappingException, JsonProcessingException {
        String json = "{}";
        ObjectMapper mapper = new ObjectMapper();
        MyObject object = mapper.readValue(json, MyObject.class);
        assertNotNull(object.jsonNode);
        assertInstanceOf(NullNode.class, object.jsonNode);
    }
```
With `2.12.6`this test passes successfully.
Since `2.13.0`it fails as `jsonNode` is deserialized to `null`.

**Expected behavior**
After I've read a lot of issues related to `null` and `NullNode` and I can't tell for sure what should be the expected behavior.
But for sure that change can break some code relying on that.

**Additional context**
The change  introduced in `2.13.0` to fix https://github.com/FasterXML/jackson-databind/issues/3214 seems to be somewhat linked to this behavior change.

**Comment by wix-andriusb** [comment]
@cowtowncoder Is this the new expected behavior?
Or can we expected this to be reverted?

**Comment by cowtowncoder** [comment]
Correct: as per #3214 this works as intended and is the new expected behavior.

If coercion from `null` to `NullNode` is preferred, it should be possible to add "null conversion" logic (either with `@JsonSetter`, or `ObjectMapper`s configuration) using `Nulls.AS_EMPTY` for `JsonNode`.
But distinction between "absent" and "explicit 'null' token" required this change.

I am not sure if this is tested and would be interested in seeing if it does work or not yet (there is need for deseralizers to help). Tests for POJOs, enums etc can be found from:

    src/test/java/com/fasterxml/jackson/databind/deser/filter/

(like `NullConversionsPojoTest.java`)

and this also shows how to configure null conversions (via annotations or for ObjectMapper).
