### ISSUE TITLE
Convert JSON string to JsonNode without numbers converting into scientific notation

### ISSUE THREAD

**Issue by harsha-sira** [FasterXML/jackson-databind#3396]
**Describe the bug**

I want to convert json string into JsonNode without values converting into  scientific notation.
I have used `USE_BIG_DECIMAL_FOR_FLOATS` and  `WRITE_BIGDECIMAL_AS_PLAIN`  , which works for most cases but failed  when using smaller number like in below example. 

I know there are a lot of issues related to BigDecimal in jackson, but I don't think I have seen one about this. Don't hesitate to close it if there are other planned/tracked issues that covers this :)

**Version information**

2.13.1

**To Reproduce**

```java
  @Test
  public void test() throws IOException {
    ObjectMapper mapper = new ObjectMapper()
        .enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS)
        .setNodeFactory(JsonNodeFactory.withExactBigDecimals(true))
        .enable(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN);

    String content = "{\"min\":0.0000000000056 }";
    JsonNode node = mapper.readTree(content);

    Assert.assertEquals("0.0000000000056", node.get("min").toString());

  }
```

**Expected behavior**

Above unit test is failing

```
org.junit.ComparisonFailure: 
Expected :0.0000000000056
Actual   :5.6E-12
```

**Comment by yawkat** [comment]
`toString` isn't affected by the mapper you use to create the node. You have to also use that mapper for the serialization, i.e. do `mapper.writeValueAsString(node.get("min"))`

**Comment by cowtowncoder** [comment]
I think I agree with @yawkat: settings will work as follows:

* `USE_BIG_DECIMAL_FOR_FLOATS` means that when reading JSON into `Number` or `Object` or `JsonNode`, all floating-point numbers become `BigDecimal`s. Has no effect on notation since `BigDecimal` instance has no such property -- there are methods like "toPlainString()" that need to be used if converting
* `WRITE_BIGDECIMAL_AS_PLAIN` changes _serialization_ -- but `JsonNode.toString()` can not access any of mappers configuration settings. So you would need to use `writeValue()` or something.

But really, you can get `BigDecimal` value out of `JsonNode` (getDecimalValue() or something) and THEN call `BigDecimal.toPlainString()` will do the trick.

**Comment by harsha-sira** [comment]
Fair enough. Using `mapper.writeValueAsString(node.get("min"))` works fine. 

Hence, Closing the issue.
