### ISSUE TITLE
Version 2.13.2 uses `Method.getParameterCount()` which is not supported on Android before API 26

### ISSUE THREAD

**Issue by finiasz** [FasterXML/jackson-databind#3412]
After updating from jackson 2.13.1 to jackson 2.13.2 I noticed my app no longer worked on Android API 21.

After digging into the code I found the issue at line 187 of `AnnotatedMethodCollector.java`:
- version 2.13.1 used `m.getParameterTypes().length`
- version 2.13.2 uses `m.getParameterCount()`

However, the [getParameterCount()](https://developer.android.com/reference/java/lang/reflect/Method#getParameterCount()) method requires API 26 on Android.

For now, I'm sticking to version 2.13.1 😄

**Comment by cowtowncoder** [comment]
Oh crap. :-(

This was not intentional  -- but teaches me to not cherry pick changes into patch. PR #3293 should have gone in 2.14(.0).

I wonder if it was worth reverting this for 2.13.3, keeping for 2.14?
I mean, for 2.13.2, damage is done (alas). But still there is likely to be 2.13.3 which would at least allow latest 2.13.x to be usable on Android API 21.

**Comment by finiasz** [comment]
I'm not sure my point of view is relevant (I'm a bit biased as I mostly use Jackson on Android), but maintaining a 2.13.x branch (with security patches), that is compatible with older Android versions would be perfect for me.

And if branch 2.14 breaks support for Android API <26, that's not a problem. We'll upgrade to this branch once we drop support for these Android versions in our app.

**Comment by cowtowncoder** [comment]
@finiasz I made changes to revert #3293 from 2.13, so things should work in 2.13.3.

I pushed `2.13.3-SNAPSHOT` to Sonatype snapshot repository so if there's any chance you could verify functioning, that'd be great -- there are quite a few places where `getParameterCount()` is called, but not all of them are related to `Method`.
But I hope I did not miss something.

**Comment by finiasz** [comment]
Many thanks for your time @cowtowncoder, I'll check this tomorrow as it's getting late here in France :)

**Comment by cowtowncoder** [comment]
Perfect, thank you @finiasz!

**Comment by finiasz** [comment]
I was able to run some tests today and did not run into any issue when using the code from the latest commit in branch 2.13. So my understanding is that you caught all the problematic calls to `getParameterCount()`.

However, keep in mind that I only use a small portion of the features of jackson, with simple serialization and deserialization of POJOs, so my tests should not be considered as "exhaustive"!

**Comment by cowtowncoder** [comment]
@finiasz Understood. Thank you for doing that level of verification; I did try to change relevant places outside of just one you reported. But it can definitely be the case that something else was still there... I hope others can help if and when they hit this issue.

**Comment by jonathan-caryl** [comment]
I came to report this same issue, we just bumped from 2.12.1 up to 2.13.2 and ran in to this issue on older Android APIs. Is there a release date for 2.13.3 ?

**Comment by cowtowncoder** [comment]
No release date, the usual OSS style "when it's ready" means in Jackson's case that there should be enough fixes, or, sometimes, enough time has passed. Former can be seen on:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13.3

and latter varies a bit; for first patch maybe 1 month since .0, later on from 2 to 4 months.

At this point there are not many fixes so 2.13.3 would probably be released at earliest in May, maybe June.

Having said that, I think this particular fix is actually contained in micro releases 2.13.2.1 and 2.13.2.2 which were released to address unrelated security issue (#2816).
So you should be able to use one of those (they are essentially identical except for some Gradle users); these micro-patches are listed on:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13

**Comment by jonathan-caryl** [comment]
Thanks @cowtowncoder

**Comment by geekbeast** [comment]
Thanks @cowtowncoder also came here to report and was so happy to see there's already a fix in the micro-releases. Will report back if it works.

**Comment by cowtowncoder** [comment]
2.13.3 now released, upgrade recommended for Android users.

**Comment by vitalyster** [comment]
This is broken again in 2.14, or it was intended to drop Android support?

**Comment by cowtowncoder** [comment]
@vitalyster Not intentional. I do wish that at least one Android developer had tested one of multiple release candidates so this was uncovered early enough to decide on which path to take.
