### ISSUE TITLE
How can i include jsonInclude at property level 

### ISSUE THREAD

**Issue by DineshSarvey** [FasterXML/jackson-databind#3436]
I am having json schema and json upon which I am running jsonschema2pojo to generate pojo class.
In jsonschema2pojo I have included InclusionLevel as NON_EMPTY.
What do i need to add in json schema or json so that I can override the InclusionLevel from jsonschema2pojo and apply InclusionLevel as ALWAYS on each property in the json.
Or is there a way to handle this in any other way.
PS: I do not want to change InclusionLevel in jsonschema2pojo as it would effect existing pojo classes.

**Comment by cowtowncoder** [comment]
Please use mailing list for usage question: issue tracker is not a Q&A forum.

* https://groups.google.com/g/jackson-user

Also: this seems to be about an external tool not Jackson so you may have better luck with forum of `jsonschema2pojo` package. But since it is related to Jackson, jackson-user is fine too.
