### ISSUE TITLE
Deserialization allows additional content (is non-greedy)

### ISSUE THREAD

**Issue by hktegner** [FasterXML/jackson-databind#3471]
**Describe the bug**
If the first curly bracket is missing from the JSON, deserialization throws a JsonMappingException rather than a JsonParseException.  My example is from import functionality where we don't expect/want any additional content
in the JSON body of the request. I would have expected this to be true for 99.99% of all cases of JSON deserialization
and parsing.

**Version information**
jackson-databind 2.10.5.1

**To Reproduce**
Missing initial curly bracket of JSON that should deserialize into a simple Java bean with the three properties in the JSON.
(I'm not listing that object here for brevity, but it uses annotations to aid deserialization.)
```
String json = "" +
  "  'mappings': [ { 'code: 'codeValue', field': 'fieldValue', 'driver': 'driverValue'} ] " +
  "}
try {
  ObjectMapper mapper = new ObjectMapper();
  mapper.readValue(json, JsonImportMappings.class);
} catch (JsonMappingException e) {
  // ends up here
} catch (JsonParseException e) {
  // I expected it to end up here
}
```

**Expected behavior**
I expected parsing to throw JsonParseException, because to my eyes this is invalid JSON. Perhaps it isn't? Perhaps the JSON standard
allows for additional content.

**Additional context**
I'd like to return a response with a useful error message like "The JSON has syntax errors", rather than "The JSON syntax is correct, but content is not."

If I do a `ObjectMapper.readTree()` instead, I do end up with a JsonNode just reflecting the literal string "mappings". The other content is ignored.

**Comment by cowtowncoder** [comment]
Interesting. The issue is that the first token IS a valid JSON String, so at high level it can be deserialized as a `String`, for example. In case content is considered a Stream of white-space separated values, that would be initially valid part; but the next token -- `:` -- would not be.
If the definition is stricter, like the original JSON spec, where only JSON Object and JSON Array values are legal at root level, this would be invalid JSON.

But since Jackson does allow all JSON Values (including Numbers, Booleans, Strings) as root values (in addition to Objects and Arrays), as well as root-level streams, the behavior is what you see: you cannot map JSON String into POJO.

Now, one thing that would sometimes help is enabling:

    DeserializationFeature.FAIL_ON_TRAILING_TOKENS

and I think it would actually fail `ObjectMapper.readTree()` call. So perhaps that would be helpful.

However, I am not sure if there is a way to change Jackson handling to consider input invalid, at least without more work.
So while I see a potential issue here I am not sure what could be done without bigger rewrite.
One possibility would be to make it possible to disable "root value sequences" and/or only accept root-level Object and Array values. But all streaming parsers would need to consider start applying that limitation and while doable that is a whole lot of work, for possibly limited gain.

**Comment by hktegner** [comment]
Thanks for the tip @cowtowncoder. I will definitely try this out. What I ended up doing which is horrendously inefficient was to use a different stricter JSON parser to validate the syntax, and then a second pass to serialize it to the POJO.
