### ISSUE TITLE
Using ParameterNamesModule with lombok @Builder

### ISSUE THREAD

**Issue by emiatej9** [FasterXML/jackson-databind#3477]
I'm using a class annotated with `@Builder` of lombok as the `valueType` of `readValue(String content, Class<T> valueType)` in `ObjectMppaer`.

Applying `@Builder` annotation to the class creates all-arg-constructor in compile time, so I think the `ParameterNamesModule` can exploit constructor arguments to find settable properties.

Is it safe to use `ParameterNamesModule` with lombok `@Builder` instead of using `@JsonDeserialize(builder = ...)`?

**Comment by cowtowncoder** [comment]
Issue tracker is not the place to ask usage questions, mailing list is:

https://groups.google.com/g/jackson-user

but you may also want to reach out to Lombok lists since it's about Lombok annotation and handling.
`ParameterNamesModule` is only relevant for Jackson's usage; I suspect that if using `@Builder` it won't be needed.
