### ISSUE TITLE
Add optional explicit `JsonSubTypes` repeated names check

### ISSUE THREAD

**Issue by ancane** [FasterXML/jackson-databind#3500]
Hi) Got a project at hand, using tons of JsonSubTypes with logical short names defined for the brevity of serialized data. Usually, it's pretty hard to manually check there are no repeated name/names aliases defined when adding a new subtype. I would like to explicitly state and validate there are no repeated subtype names defined. Please, consider related PR for this matter and suggest the best way to do this if PR is not good enough. I will also PR the annotations repo with the flag to enable the check.(https://github.com/FasterXML/jackson-annotations/issues/204) 
Also please advise, how to add this to the 2.12 branch if that's at all possible. Cheers!

**Comment by cowtowncoder** [comment]
Ok, sorry for the slow follow up. I hope to look into this in near future. PR is a good way to go!

**Comment by cowtowncoder** [comment]
Hi @ancane! Ok, this took way longer than I hope for but now I am finally looking at this. I think this makes sense: I do have one request wrt annotation property naming, but otherwise it makes sense.

But aside from that change (I'll add a comment in annotations PR), I need one other thing, CLA. It's here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and only needs to be sent once (works for all future contributions too); so if you had sent it earlier (I don't think so but I could have missed) that'd be fine.
The usual way is to print the doc, fill & sign, scan/photo, email to `info` at fasterxml dot com.
Once I get that I can merge these PRs and it'll all make it into upcoming 2.14 release.

Thank you again for the contribution!

**Comment by ancane** [comment]
@cowtowncoder Think I've done the code. Next will sort out the CLA. Ta!

**Comment by ancane** [comment]
Sent a photo of the signed agreement to info mail as requested.

**Comment by cowtowncoder** [comment]
Thanks! CLA received, I will proceed with merging.

**Comment by cowtowncoder** [comment]
Merged the annotation patch, looking into #3501 here next.

**Comment by cowtowncoder** [comment]
Merged for inclusion in 2.14.0: thank you again, @ancane !

**Comment by ancane** [comment]
Cool! Thanks ever so much @cowtowncoder, it was my pleasure.

**Comment by cowtowncoder** [comment]
Thank you @ancane and apologies for slow handling. But happy to get it done!
