### ISSUE TITLE
Chnage LRUMap to just evict one entry when maxEntries reached

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3530]
Current implementation clears full map when maxEntries reached. jackson-dataformat-csv has its own separate LRUMap[1] and it only evicts the eldest entry when you add a new entry after the maxEntries is reached. Would it be possible to have jackson-databind LRUMap use similar logic? The change would require LRUMap to subclass LinkedHashMap.

[1] https://github.com/FasterXML/jackson-dataformats-text/blob/2.14/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/impl/LRUMap.java

**Comment by pjfanning** [comment]
Closing as this rehashes https://github.com/FasterXML/jackson-databind/issues/2502 and https://github.com/FasterXML/jackson-module-scala/issues/428. Making the change in the issue description would incolve dropping the ConcurrentHashMap that currently backs LRUMap.

**Comment by cowtowncoder** [comment]
Makes sense. And just to be clear: the reason `LRUMap` just cleared it all was because incremental updates were not available using backing map choice (originally `LinkedHashMap` was used, but there were concurrency problems as both reads and writes need synchronization and only writes were sync'ed... long story). Clear-all was not a feature we want, just the limitation of the approach.

**Comment by cowtowncoder** [comment]
Hooray! Big thanks to @pjfanning for contributing the implementation and @ben-manes for helping with suggestions.
