### ISSUE TITLE
Json object deserialization stopped working between version 2.10.5 and 2.13.3.

### ISSUE THREAD

**Issue by spacetom** [FasterXML/jackson-databind#3551]
**Describe the bug**
Before migrating to version 2.13.3 object deserialization worked fine. Afterwards it fails with message 
> _com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `example.PersonId` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (13)
 at [Source: (String)"{"id": 13, "testVal": "abc"}"; line: 1, column: 8] (through reference chain: example.PersonDto["id"])_

**Version information**
Works under 2.10.5.
Fails under 2.13.3.

**To Reproduce**
Sample project provided with both versions defined in pom.xml.
Activate 2.10.5. Should work.
Activate 2.13.3. Should fail.

**Expected behavior**
Object PersonDto deserialized correctly.

**Additional information**
The issue is somehow similar to the one under https://github.com/FasterXML/jackson-databind/issues/3374. The initial version of the sample project is taken from there.

[jackson-example.zip](https://github.com/FasterXML/jackson-databind/files/9199820/jackson-example.zip)

**Comment by spacetom** [comment]
Unit test with reproducable test case is in project packed into jackson-example.zip attached to first message.

**Comment by cowtowncoder** [comment]
Ok. So, the problem with the test is that it uses Lombok. What I'd need is the resulting POJOs after Lombok's processing, to see exact class definitions. This because this is what Jackson sees, not the original source definitions (Lombok augments byte code with generated methods and possible annotations).

It is also very likely that there is a Lombok setting that allows working around the issue, so you may want to search for something reported against Lombok.

But on Jackson side I'd need to see the post-processed classes.

**Comment by spacetom** [comment]
[jackson-example-no-lombok.zip](https://github.com/FasterXML/jackson-databind/files/9242882/jackson-example-no-lombok.zip)
In the attache zipped project I removed lombok completely (no dependency). All Lombok's annotations are inlined and the issue still persists.

**Comment by cowtowncoder** [comment]
Ok, the issue is this: the JSON being read has simple integer number, `13` for `id` of type `PersonId`.

But definition of `PersonId` has only one explicit creator method -- constructor -- which expects JSON Object; this is due to named parameters from this:

```
    @ConstructorProperties({"id"})
    public PersonId(Long id) {
```

since there is also:

```
    public static PersonId valueOf(Long value) {

```

you could add `@JsonCreator` into that method like so:

```
    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PersonId valueOf(Long value) {
```

or, if you prefer, change annotation on constructor similarly.

in case of `Mode.DELEGATING` the incoming structure will match that one (and only one) constructor/factory method argument.

As to why 2.10 appeared to work: I suspect this is likely due to bug in which non-annotated `valueOf()` had precedence over annotation Constructor.

But regardless behavior in 2.13 is more correct giving precedence to explicitly annotated Creator over implicit one.

**Comment by spacetom** [comment]
I know that adding annotation (@JsonCreator) would fix the situation but that is what I wanted to avoid. Not to have Jackson dependencies on modules which do not require it. There are like hundreds of classes to change in project I work in. Having reasonable order for creators like e.g. one of them might be: public constructor with @ConstructorProperties over public static constructor, would be imo much better solution. If one wants to use static constructor then one would use annotation. Otherwise I am forced to depend on Jackson even if it is not needed directly.

**Comment by cowtowncoder** [comment]
I think I explained this inadequately: the precedence is like you say -- explicit `@ConstructorProperties` DOES have priority. That is being used. But it is wrong for your use case: what you want is what `valueOf()` does.

Since  `@ConstructorProperties` associates names with parameters, it then implies that "properties" style delegation is expected: incoming JSON must have Object value with properties matching parameter names.
But what you want here is "delegating" style where the whole JSON value must map to the one (and only one) argument.
But unlike `@JsonCreator` where you can decide which `mode` to use (if you don't, it tries to use heuristics to select...), `@ConstructorProperties` always uses "properties" mode.

And so why it "worked" in 2.10 was due to a bug in handling which lead code use `valueOf()`.

**Comment by spacetom** [comment]
Thank you for clarification. I will read referenced docs and reconsider approach to this problem.
