### ISSUE TITLE
SettingPropertyNamingStrategy on ObjectMapper doesn't work.

### ISSUE THREAD

**Issue by TanushNadimpalli** [FasterXML/jackson-databind#3556]
**Describe the bug**
SettingPropertyNamingStrategy on ObjectMapper doesn't work.

**Version information**
Which Jackson version(s) was this for?
Version: 2.13.3

**To Reproduce**

```java
ObjectMapper snakeMapper = new ObjectMapper();
snakeMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
String JSON = "{\"displayName\": 1001}";
HashMap<String, Integer> map = snakeMapper.readValue(JSON, HashMap.class);
```

Printing the keySet of the hash map returns ```[displayName]```

**Expected behavior**
It should return ```[display_name]```

**Comment by cowtowncoder** [comment]
Works as intended: property naming strategies only affect POJO serialization, not non-POJO types such as:

* `Map`s
* `JsonNode`s (specifically `ObjectNode`)

There is probably room for better documentation to make this clear.

In addition it would be possible to add separate functionality for renaming keys of `Map`s, but if so that would require bit different API: current `PropertyNamingStrategy` depends on POJO metadata.
