### ISSUE TITLE
Is there a way , we can permanently address the vulnerabilities in the databind library

### ISSUE THREAD

**Issue by hari819** [FasterXML/jackson-databind#3630]
hello Team,

every week we run the vulnerability scanner and jackson-databind is in the list many times , atleast once per month,
Is there a way we can address the vulnerable code permanently,  I am sorry for asking , but just wanted to know if this is possible.

thanks,

[https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind](url)

**Comment by cowtowncoder** [comment]
@hari819 If there is a way I am not aware of it. I doubt this is achievable.

But if you are interested in why and how these vulnerability reports come about I suggest you to read through disclosures and understand what code is affected. It may help understand why there really is not a single fix: code affected is typically not obvious and problems are found by security researchers.
Due to Jackson's high popularity most researchers focus on it compared to, say, other less widely used (JSON) libraries, which means that even most obscure potential issues get reported and often get published as security disclosures.

However: we are collaborating with security researchers, including but not limited to AdaLogics, to try to find out issues pro-actively. It will not prevent them from being published but should over time reduce frequency quickly.

**Comment by yawkat** [comment]
My personal opinion: 

The recent CVEs in databind have been resource exhaustion bugs (e.g. the stack overflow in CVE-2020-36518). I don't mean to say they are not problematic, but their impact is limited, and similar bugs are likely present in other deserialization libraries that support the same features.

They are currently in the spotlight because open-source security is receiving a lot more attention (think log4shell), and jackson is basically the ideal candidate: There's no large dev team behind jackson, it is *very* popular, and basically its whole purpose is parsing untrusted input. Now there are quite a few security researchers fuzzing jackson to find these bugs. I'm not involved, but I assume jackson also qualifies for "critical importance" project under the [oss-fuzz reward program](https://google.github.io/oss-fuzz/getting-started/integration-rewards/).

The fact that *these* issues are what is being found – resource exhaustion only, limited to applications that use the affected features, etc. – is a *good* sign for jackson security: An issue like log4shell could not pass the scrutiny jackson is receiving, so we can be reasonably sure nothing similar exists in jackson.

**Comment by cowtowncoder** [comment]
@yawkat Well put! And yes, Jackson does qualify under oss-fuzz reward program and there is a bit of background work related to this, results of which often become CVEs. There will likely be more public reports, too, in due time.
