### ISSUE TITLE
Why micro-patch in open branch 2.13?

### ISSUE THREAD

**Issue by HugoVeillette** [FasterXML/jackson-databind#3648]
Hi there, 

I see we got micro patches on both version 2.12.X and  2.13.X, regarding security fix for  CVE-2022-42003 & CVE-2022-42004.
https://github.com/FasterXML/jackson-databind/issues/3590 

According to your Wiki, micro patches are for branches no longer open.
https://github.com/FasterXML/jackson/wiki/Jackson-Releases#open-branches 

Why not issue a minor for version 2.13.X? This breaks deps management in many scenarios. 
2.14 is still in RC.

Thank you.

**Comment by cowtowncoder** [comment]
@HugoVeillette because it takes 3-4 hours to do a full release: unpaid, "free" time I have limited amount of.
I do not want to waste half a day pushing a single version dependency change as there is a valid alternative.
While Wiki is mostly correct, I think in this case I need to reword it. Thank you for bringing this to my attention.

Situation would be different if I worked on OSS and had paid customers: if so I could justify this amount of work.
Maybe some day :)

On deps management breaking: I strongly suggest everyone start using `jackson-bom` to make handling of version dependencies simpler and safer; not just for micro-patches, but also for them.

**Comment by HugoVeillette** [comment]
@cowtowncoder I understand the defensive stance. It's a shame no one is sponsoring (financially) this project.

Putting this aside, I'm  interested to know if there was still an open branch (2.14  being not officially released yet), and if we would see more minor releases on 2.13 in the future, including the changes done on the micro-patch.

Looking forward to read clarifications on the Wiki. 

Thanks.

**Comment by cowtowncoder** [comment]
I thought I was clear on this above, but apparently not.

So, yes, 2.13 is open, and yes, eventually there will be 2.13.5 release once there are enough changes.
As you can see from release page:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13.5

there are 2 known changes which is not really enough to warrant a full release.
