### ISSUE TITLE
Version 2.14.0 uses Method.getParameterCount() which is not supported on Android before API 26

### ISSUE THREAD

**Issue by jonnycaley** [FasterXML/jackson-databind#3658]
**Describe the bug**

This [previous issue](https://github.com/FasterXML/jackson-databind/issues/3412) was re-introduced with the usage of `getParameterCount` in `src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerBase.java` as seen in the [release changes](https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.13.4...jackson-databind-2.14.0).

**Version information**
Which Jackson version(s) was this for?

2.14.0

**To Reproduce**

Run the following code on a device running Android 24:

```
ObjectMapper().writeValueAsString(mapOf<String, Any>())
```

**Expected behavior**
Exception `java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-oj.jar)` is not thrown

**Additional context**

Crashes on Android device running API 24

**Comment by cowtowncoder** [comment]
I wish we had CI tests for Android compatibility testing. Also wish I had remembered that this had already been an issue quite recently (see #3412).

But at this point I am tempted to say that the baseline Android SDK Jackson works with is 26; and for earlier SDKs one needs to use 2.13 or earlier.

**Comment by cowtowncoder** [comment]
I am now adding Android SDK compatibility verification (via #3659) and it looks like 2.13 is compatible with Android SDK 24, except for use of `Class.getTypeName()` (26-only). Will file an issue and fix that.
But beyond that I think that verified minimum working baseline will be such that:

* Jackson 2.13 should work with ASDK 24 and above (may work with earlier but as per AnimalSniffer this is the safe baseline)
* Jackson 2.14 should work with ASDK 26 and above

**Comment by cowtowncoder** [comment]
Will mark this as closed given that it is basically "works as planned" in that the idea was (but that I had forgotten) to start using specific method in 2.14.

We now finally have actual checking for Android SDK compatibility for databind so that we shouldn't accidentally break compatibility going forward. But we also need to add notes on what the actual compatibility is, on README -- I will file another issue. Similarly for `jackson-core`.

**Comment by jonnycaley** [comment]
Thanks for the updates 🚀

**Comment by cowtowncoder** [comment]
You are welcome @jonnycaley !

**Comment by adhirajsinghchauhan** [comment]
Would it be possible to add some kind of a build-time warning/error? Normally one doesn't expect a minor release to intentionally (also permanently it seems: https://github.com/FasterXML/jackson-databind/issues/3702#issuecomment-1358396811) break backwards compatibility, if you're going by [semver](https://semver.org).

Sometimes devs are lazy and don't boot up an old device to check if things still work after a minor dep update, so seeing a message at build-time would be preferable to finding out _after_ releasing to prod.

**Comment by yawkat** [comment]
I don't think it's possible

**Comment by cowtowncoder** [comment]
Wrt SemVer: although in perfect world major versions would be used to indicate compatibility changes, in practice this is not a workable for Jackson, given that a new major version behaves more like a fork (new package names, new Maven coordinates). So incremental changes to baseline requirements (minimum JDK has changes from Java 6 to Java 8 during Jackson 2.x, as another example) need to be made in minor versions.

I am not sure how build time warning could work; especially since it specifically affects a subset of developers (Android devleopers).
I am open to suggestions, as usual, just not sure how to go about this.
