### ISSUE TITLE
`ObjectMapper` default heap consumption increased significantly from 2.13.x to 2.14.0

### ISSUE THREAD

**Issue by mhalbritter** [FasterXML/jackson-databind#3665]
Hello,

I'm currently looking at heap consumption when using native image with a Spring Boot 3 application. Spring Boot 3.0 SNAPSHOT uses Jackson 2.14.0-rc3. I noticed that with the upgrade from 2.13.4.2 to 2.14.0 the application uses more heap memory, which i tracked down to [this PR](https://github.com/FasterXML/jackson-databind/pull/3531). It changed the cache implementation from `ConcurrentHashMap` to `PrivateMaxEntriesMap`, which in turn preallocates a lot of `AtomicReference` (they appear to be all empty).

I created a [reproducer here](https://github.com/mhalbritter/graalvm-jackson) - it creates an empty objectmapper and then dumps the heap. It has more information and screenshots in the README.

When using Jackson 2.13.4.2 it uses 567 B for the LRUmap, with Jackson 2.14.0 it uses 507320 B for the LRU map. The bad thing is that most of these caches are per `ObjectMapper` - create more of them and it uses even more heap.

As we're trying to optimize the memory consumption of native image applications, this is quite a bummer and we hope you can help us out here.

Thanks!

**Comment by mhalbritter** [comment]
You can see the problem (but not as exaggerated) on a regular JVM. I created 100 ObjectMapper and heapdumped.

This is 2.13.4.2:

![image](https://user-images.githubusercontent.com/98899556/201927453-f1cfd8d5-40db-45bd-a6fb-5e3f2a170c4d.png)

This is 2.14.0:

![image](https://user-images.githubusercontent.com/98899556/201927509-f30a5d11-09cb-41e7-9809-852a770e4062.png)

**Comment by GedMarc** [comment]
From my understanding, ObjectMapper's should be singleton's as much as possible,
and the ObjectReader and ObjectWriters are the thread-safe objects that can be built from it - 

So this would be a bad implementation of using the ObjectMapper

**Comment by mhalbritter** [comment]
I created 100 ObjectMappers to show the extent of this problem. As you'll see in https://github.com/mhalbritter/graalvm-jackson, it is even observable with only 1 ObjectMapper. 2.14.0 uses ~880x more heap for an empty ObjectMapper compared to 2.13.4.2.

**Comment by GedMarc** [comment]
Hmmm - @cowtowncoder  this one needs your eyes

**Comment by sdeleuze** [comment]
I agree with @mhalbritter, it looks like the heap allocation regression in 2.14 is pretty huge and I hope that something could be refined on Jackson side.

@cowtowncoder Looking forward to your feedback, we still have the opportunity to update Jackson before Spring Boot 3 GA is released (expected next week).

**Comment by cowtowncoder** [comment]
Uh. I did have some concerns about apparent complexity of the improved cache choice, relative to benefits. The baseline for cache should be solid from what I recall, but @pjfanning worked on it most closely.

This is unfortunate of course. But just to make sure: that's about 0.5 MB per `ObjectMapper`, without any use? (basic data structures).

**Comment by cowtowncoder** [comment]
Ok, looks like there are just 4 cache instances by default (plus one optional):

1. `JacksonAnnotationIntrospector` uses it to keep track of annotations that have (or not) `JacksonAnnotationsInside`. This definitely does not need super-nice cache
2. `TypeFactory` caches types; this is relatively heavily used during construction of (de)serializers
3. `SerializerCache` probably the most important cache since many serializers are dynamically accessed
4. `DeserializerCache` somewhat important but deserializers mostly statically accessed beyond root instances
5. (optional) `RootNameLookup` -- mostly used with XML, sometimes JSON

Initial sizes of all these seem to be between 16 and 65, nothing drastic unless I am missing something.

It would be good to get more numbers, if possible, on sizes of individual `LRUMap` instances.
Unfortunately it doesn't look like initial sizes can be reduced a lot (or put another way, reducing would not have humongous effect).
It'd also be good to just have an estimate of a single `LRUMap` with specific initial size as baseline to consider what exactly to do. The whole `PrivateMaxEntriesMap` implementation seems very much overpowered for Jackson's use case... and it'd be good to see if some parts could be removed.

**Comment by ben-manes** [comment]
Sorry, I haven’t looked at that caching logic for about 7 years (or 12 when written). At the time the emphasis was concurrency for server-class usages, when a concurrent lru algorithm was a novel, hard problem. I’m sure those AtomicReferences could be replaced by aAtomicReferenceArray to slim it down. It is striped lanes to reduce thread contention, but you could greatly simplify that by knowing what is actually needed here, e.g. a single array is probably fine.

I later [rewrote](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/StripedBuffer.java) this to dynamically stripe light weight, mpsc [ring buffers](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedBuffer.java). That is more memory conscious by being slimmer and demand based.

**Comment by ben-manes** [comment]
@bclozel may be interested as he similarly [rewrote](https://github.com/spring-projects/spring-framework/blob/c470262c8ea733fd0846a50232599715ec2d2b83/spring-core/src/main/java/org/springframework/util/ConcurrentLruCache.java) that original code for use by Spring. There are versions floating around in groovy, mssql jdbc, etc. it should be simple to streamline to be more tuned towards the project needs.

**Comment by cowtowncoder** [comment]
That sounds useful @ben-manes thank you for sharing. I wonder how easy it'd be to measure -- of course it's not rocket science to just count fields and do it manually but there are probably tools to automate using introspection to at least give static minimums or such.

**Comment by ben-manes** [comment]
I used openjdk’s [object layout](https://github.com/openjdk/jol) on the current code to verify padding rules for protecting against false sharing. And for a rough footprint estimate, [jamm](https://github.com/jbellis/jamm) is good enough for seeing if things line up to expectations. All are just best guesses due to jvm internal complexity, [JEP-8249196](https://openjdk.org/jeps/8249196).

**Comment by mhalbritter** [comment]
They are all the same size, because the `AtomicReference[][] readBuffers` field, which consumes most of the heap, is sized this way:

```java
static final int NCPU = Runtime.getRuntime().availableProcessors(); // 9 on my machine
static final int NUMBER_OF_READ_BUFFERS = ceilingNextPowerOfTwo(NCPU); // 16 on my machine
static final int READ_BUFFER_THRESHOLD = 32;
static final int READ_BUFFER_DRAIN_THRESHOLD = 2 * READ_BUFFER_THRESHOLD; // 64
static final int READ_BUFFER_SIZE = 2 * READ_BUFFER_DRAIN_THRESHOLD; // 128

readBuffers = new AtomicReference[NUMBER_OF_READ_BUFFERS][READ_BUFFER_SIZE];
```

which will make this is a `AtomicReference[16][128]` array on my machine (this depends on the number of CPU cores). This is not influenced by `initialCapacity` or `maximumCapacity` as far as i can see.

**Comment by ben-manes** [comment]
Yes, concurrency is unrelated to a maximum cache size. At that time a synchronized lru was standard and perfectly fine in most cases due to single core machines still being common. Those who used this concurrent cache (ConcurrentLinkedHashMap) were servers that had clear needs (4-1024 cores). This led to porting into Guava (CacheBuilder) where we defaulted to 4 for Google’s needs, with a setting to adjust manually (concurrencyLevel). For a more general, modern cache (Caffeine) it now dynamically adjusts the size by need so that low concurrency has a low footprint while high concurrency benefits by trading some extra space. However CLHM is simpler to fork and embed, so decisions that aged poorly are copied over.

For Jackson a modest size is enough, thanks to lossy buffers and modest needs, so slimming this down should be simple and effective. Or if you prefer the advanced solution, copying that code and making the minor replacement edits.

**Comment by pjfanning** [comment]
The jackson-databind use case is to add an entry to the LRU map and not to replace it.

The use of PrivateMaxEntriesMap (a renamed fork of https://github.com/ben-manes/concurrentlinkedhashmap) is to be able to cap the entry size of the map and to evict the LRU instances when the entry size limit is reached.

We could certainly try to reduce the `AtomicReference[][] readBuffers` size to maybe max out as NUMBER_OF_READ_BUFFERS=4 and READ_BUFFER_THRESHOLD=4. We should set up some load test scenarios to see if those numbers are ok. Throwing unexpected exceptions is the main worry but also, we would like not to have poor performance in any usage scenarios. We could tweak these new numbers to see if they have a major impact.

**Comment by bclozel** [comment]
I've locally switched `AtomicReference[]` to `AtomicReferenceArray` and I'm seeing a nice improvement on heap consumption. In theory this shouldn't change things much for runtime performance but I'm seeing a degradation (but still in the error margin).

Right now Spring's implementation is not the dominator here, but we might still revisit the read buffer sizes or how its implementation works.

**Comment by cowtowncoder** [comment]
@pjfanning (I reworded your desc a bit) -- +1 for capping size of those arrays so that no matter how many cores it would not increase linearly. 

@bclozel Use of `AtomicReferenceArray` sounds good as well.

Ultimately I think memory usage per cache should be significant lower than initial implementation. Load testing would be nice, but it is worth noting we didn't perf test new implementation vs old implementation either...

**Comment by ben-manes** [comment]
> In theory this shouldn't change things much for runtime performance but I'm seeing a degradation

This is due to cpu cache line sharing which causes coherency bottlenecks as a distinct fields within a block are invalidated together. As the thread distribution is not perfect some shared producers will select the same lane. In a perfect world each slot would be fully padded so that once an index is acquired the two producers do not impact each other. That of course is very wasteful (64-byte blocks). The use of object references was a middle ground for partial padding. In these [guava benchmarks](https://github.com/ben-manes/guava/commit/0f286172945f7f23d1c2b8f297f9816e918c6bc3#r11588011) from one of my attempts to revisit using ring buffers (uses CLQ as quick-and-dirty first pass), the read throughput ranged from 240M (64b) / 256M (256b) / 285M (1kb) ops/s. While the 45M spread sounds scary, in practice the cache reads won't be a bottleneck if it can support ~60M ops/s due to real application work so further gains won't impact system performance.

> We should set up some load test scenarios to see if those numbers are ok.

Please see this [jmh benchmark](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/GetPutBenchmark.java) as a reference.

**Comment by pjfanning** [comment]
`16*128*4` (4 bytes per Java object pointer) means that the `AtomicReference[16][128] readBuffers` should use 8192 bytes (8 Kb). This seems a long way short of the totals being quoted for each ObjectMapper.

**Comment by ben-manes** [comment]
@pjfanning you forgot to account for the `AtomicReference` instances themselves. That ranges from 16-32 bytes depending on the jvm optimizations (compressed references, compressed class pointers, byte alignment). In that case you might expect to see it as `16 * 128 (4 + 32) = 73,728` or ~300kb if each mapper uses 4 caches. Using Java Object Layout,

```console
# Running 64-bit HotSpot VM.
# Using compressed oop with 3-bit shift.
# Using compressed klass with 3-bit shift.
# WARNING | Compressed references base/shifts are guessed by the experiment!
# WARNING | Therefore, computed addresses are just guesses, and ARE NOT RELIABLE.
# WARNING | Make sure to attach Serviceability Agent to get the reliable addresses.
# Objects are 8 bytes aligned.
# Field sizes by type: 4, 1, 1, 2, 2, 4, 4, 8, 8 [bytes]
# Array element sizes: 4, 1, 1, 2, 2, 4, 4, 8, 8 [bytes]

***** Hotspot Layout Simulation (JDK 15, 64-bit model, compressed class pointers, 16-byte aligned)
java.util.concurrent.atomic.AtomicReference object internals:
OFF  SZ               TYPE DESCRIPTION               VALUE
  0   8                    (object header: mark)     N/A
  8   4                    (object header: class)    N/A
 12   4                    (alignment/padding gap)
 16   8   java.lang.Object AtomicReference.value     N/A
 24   8                    (object alignment gap)
Instance size: 32 bytes
Space losses: 4 bytes internal + 8 bytes external = 12 bytes total
```

**Comment by cowtowncoder** [comment]
300 kB sounds in the ballpark that was observed.

`AtomicReferenceArray` could improve things, but also seems like limiting actual size of 2-dimensional array (which @pjfanning suggested I think) would make sense.

I wonder how much we could cut things here -- to me some added overhead is fine; `ObjectMapper` instances will accumulate other baggage when actually used (for cached Serializers, Deserializers in particular).
But getting from ~300kB to less than 100kB would seem like a worthwhile goal to me.

**Comment by yawkat** [comment]
i dont think it has to be a 2-dimensional array either, could save some space by flattening it.

**Comment by cowtowncoder** [comment]
@yawkat Going to `AtomicReferenceArray` would remove one dimension, although I guess it'd be possible to flatten both into single instance. Not sure if that'd be bad wrt false sharing or other caching aspects but that'd probably eliminate quite a bit of usage.

**Comment by ben-manes** [comment]
To be fair, since Jackson's caches are likely tiny a Clock (aka Second Chance) policy would be adequate if you wanted a much simpler rewrite. That was my original [stop-gap](https://github.com/ben-manes/concurrentlinkedhashmap/blob/master/src/test/java/com/googlecode/concurrentlinkedhashmap/caches/ProductionMap.java) when starting to explore a general approach. It is simply a FIFO with a mark bit that is set on a read and reset during an O(n) eviction scan. That has similar hit rates to an LRU with lock-free reads, but writes block on a shared lock and large caches have GC-like pauses due to scanning. For a small cache like I imagine these to be, anything simple (even just FIFO or random) is likely good enough. I think it would be perfectly fine to write a very simple, fast, low overhead cache that is specific to your needs.

**Comment by cowtowncoder** [comment]
I have bit ambivalent feelings about this. On one hand, yes, use case specific would be good. On the other hand, using something (as close to) off-the-shelf (as possible) is great.
So in that sense, incremental changes for 2.14.x at least, to address unexpectedly sizable memory usage increase, would probably be best.
For 2.15 could do something bigger. Assuming we have someone with time and interest.

**Comment by pjfanning** [comment]
Spring Boot 3 and anyone else waiting on this should consider using jackson-databind 2.13.4.2 instead of jackson-databind 2.14.0. All the security fixes are in jackson-databind 2.13.4.2.

I'd prefer not to rush a jackson-databind 2.14.1 release.

**Comment by sdeleuze** [comment]
We can't, we rely on feature only available in Jackson 2.14.

**Comment by cowtowncoder** [comment]
I would really hope to address this soon and will work with anyone who has bandwidth.
One thing that'd be great would be to have some way to easily verify memory usage so sharing techniques here would be helpful.
If and when this usage could be brought down by factor of 3x or more, I'd be happy to push 2.14.1 containing whatever fixes are available (currently just couple).

**Comment by pjfanning** [comment]
@sdeleuze spring-boot only switched to rc version of v2.14.0 less than 1 month ago in a set of PRs that have no decriptions and no code changes other than changing the jackson version - eg https://github.com/spring-projects/spring-boot/issues/32771

I would appreciate if you could give us more details of why the change to v2.14.0 was done.

**Comment by cowtowncoder** [comment]
One possibility I should maybe consider is actually just rolling back the use of new cache for 2.14.1 altogether. And going forward, for 2.15.0, offer pluggable cache option but not necessarily changing the default.

**Comment by pjfanning** [comment]
@cowtowncoder another workaround other than reverting LRUMap changes or #3670 is for users of jackson v2.14.0 who absolutely need a fix and need it now is for them to try https://github.com/pjfanning/jackson-caffeine-cache

**Comment by sdeleuze** [comment]
@pjfanning You will fine more details on https://github.com/spring-projects/spring-framework/issues/29343.

@cowtowncoder I think I would be also in favor of reverting the cache changes in 2.14 and take the time to refine the right implementation. We will be happy to provide help a d feedback from the Spring team. Those cache changes were initially planned for Jackson 3.0 after all, and I have the feeling the right solution that allows reasonable memory consumption and good performances is not so obvious to find and may take a few cycles.

**Comment by mhalbritter** [comment]
@cowtowncoder i used [visualvm](https://visualvm.github.io/).

**Comment by ben-manes** [comment]
Since the Spring code changes are small and unreleased, and the negative impact is a little bit of memory waste (kilobytes unless misused), it seems to me that @cowtowncoder and @pjfanning should fix this at the pace they are comfortable with. If that is too slow then reverting Spring’s changes doesn’t appear too bad from looking at that usage. If just moving fast is the decision then both of @pjfanning pr approaches lgtm. Otherwise please let me know how/ when I can be of help.

**Comment by bclozel** [comment]
@pjfanning @ben-manes Thanks for the suggestion.

I don't see how reverting the changes would solve the problem for our user base. We can only enforce a baseline and people will upgrade themselves if we don't.
Indeed, Spring Framework recently upgraded (quite late in the milestone cycle) because we believed that using the latest features would bring significant improvements to our users.
Spring Framework 6.0 being a major version, this is a rare opportunity to raise the baseline for libraries support and we want to avoid putting maintenance pressure on other popular projects like Jackson.We trust the Jackson team will make the right call and we're here to help.

We don't want to rush the team in one direction or another but simply offer our help when it comes to testing native apps and Spring-specific scenarios to evaluate possible changes.

**Comment by yawkat** [comment]
To get some better data on this issue, I created #3675, which uses [jol](https://github.com/openjdk/jol) to measure the estimated footprint of the ObjectMapper. Using this data, the size of the ObjectMapper on my machine (LRUMap is core-count-dependent) is roughly 450K, compared to just 25K on 2.13. With only the array optimizations (flattening + Atomic\*Array), which should have no performance impact, it goes down to 113K. With the parameter tuning @pjfanning did in #3670 (with the reservations described in that PR), it goes down to 29K, almost at the 2.13 level.

If @pjfanning can confirm that the parameter changes in #3670 don't hurt performance too badly, I think these changes are sufficient to fix memory footprint for 2.14.1, and we can avoid a revert.

**Comment by pjfanning** [comment]
Sure @yawkat - your changes in #3675 seem good - I'll try to set up jmh benchmarks over the next few days.

**Comment by cowtowncoder** [comment]
Ok at this point I am optimistic about being able to optimize `LRUMap` implementation to have much lower memory footprint, so there's no need to revert change. Better cache pluggability/configuration would still be nice but that would require API change and go in at earliest in 2.15.

I wonder if use of `jol` for main `ObjectMapper` would help us guard against significant unintended memory usage increase for some changes -- just constructing an instance, testing direct size. And for bonus points do the same after one simple serialization, deserialization.
The idea being that limit for maximum size (on CI?) would be kept relatively tight and increased along with additional fields, but making it easier to notice increases that are higher than expected (including surprises where none were expected etc).

**Comment by yawkat** [comment]
@cowtowncoder I tried to add exactly such a test (though the limit is fairly lax), but ran into these issues with JOL on CI: https://github.com/FasterXML/jackson-databind/pull/3675#issuecomment-1321052910

**Comment by cowtowncoder** [comment]
Fixed for 2.14.1.

**Comment by sdeleuze** [comment]
Awesome, thanks a lot for this quick update! Looking forward to leverage Jackson `2.14.1` asap available. If the release could happen by tomorrow (Nov 22), that would I think allow us to ship Spring Boot 3 GA with the memory fix.

**Comment by mhalbritter** [comment]
Nice, thanks a lot!

**Comment by cowtowncoder** [comment]
I'll see if I could find time today to release a patch version; cannot promise it but will try my best.

**Comment by cowtowncoder** [comment]
Ta-dah! I did it. 2.14.1 release mostly done, last couple of artifacts on their way to Maven Central (Scala module may take bit longer). Please LMK if you find issues.

**Comment by cowtowncoder** [comment]
@yawkat `MapperFootprintTest` seems to be running for CI too and arbitrarily failing. I think I'll increase limit a bit for now, to at least reduce incidence rate.

**Comment by yawkat** [comment]
@cowtowncoder ugh, or just disable it for now. ive given up on making the results resilient to gc, there is too much going on, weird caches with soft references and such. maybe it will be less flaky with epsilon gc, but that's not available on java 8 so i didn't try it for the ci
