### ISSUE TITLE
Timestamp in classes inside version 2.14 showing 02/01/1980

### ISSUE THREAD

**Issue by elizalde1981** [FasterXML/jackson-databind#3680]
Any idea why the classes inside version 2.14 are showing 02/01/1980??

![image](https://user-images.githubusercontent.com/6456386/203209201-63971d77-b145-4561-b916-6136eeb799a3.png)

**Comment by cowtowncoder** [comment]
I don't know. It could perhaps be related to  "Reproducible Builds" changes since use of constant timestamp for classes would remove one source of non-meaningful differences in jars. This was done for Jackson 2.14.

Is there a specific problem here or just general curiosity?

**Comment by cowtowncoder** [comment]
Yes, I think this is related to Reproducible Builds, but something seems wrong: only META-INF entries have expected timestamp. Classes do not...

**Comment by elizalde1981** [comment]
> I don't know. It could perhaps be related to "Reproducible Builds" changes since use of constant timestamp for classes would remove one source of non-meaningful differences in jars. This was done for Jackson 2.14. (see https://maven.apache.org/guides/mini/guide-reproducible-builds.html )
> 
> Is there a specific problem here or just general curiosity?

Just general curiosity

**Comment by cowtowncoder** [comment]
@hboutemy See ^^^ -- I suspect that for purposes of RB this works, but it is awkward that class file timestamps are in distant past. Do you know what might be causing it, or, more importantly, how to fix it?

**Comment by cowtowncoder** [comment]
Looks like this might be same as

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2517

but I don't see a resolution there...

**Comment by cowtowncoder** [comment]
Thank you @hboutemy -- was about to suggest it might be bundle plugin as that'd be likely difference. I hope it is resolvable, although fundamentally value chosen only needs to be stable and not necessarily useful.

**Comment by hboutemy** [comment]
> Maybe we just need to add: ...

no, you don't need to add anything: as written to the doc you pointed to, it's done automatically by bnd-maven-plugin when outputTimestamp is defined. Notice that your build does not use bnd-maven-plugin

same is done by Maven Bundle Plugin, see https://github.com/apache/felix-dev/commit/957e5c9838aa67061888760286cb78251bee50bd

I suppose that creating a sample project using bnd-maven-plugin and improving bnd-maven-plugin to get the desired result looks like a good idea, because it will be easier for Bnd maintainer: once everything works as expected with bnd-maven-plugin, Felix's maven-bundle-plugin can mimic the same updates (notice: don't ask me why 2 plugins exist, I'm definitively not an OSGi expert...)

**Comment by cowtowncoder** [comment]
@hboutemy Ah. So it's "the other" OSGi bundle plug-in. That explains why configuration settings seemed different.

Unfortunately my knowledge of OSGi bundle building is very limited: the whole setup was a contribution.
So I don't think I will be able to build a PoC on my own, in a way that reproduces other aspects of current build -- another big issue being that there is no way currently to verify correctness of the resulting jar (ideally CI would check these by loading resulting bundle into OSGi container, including dependencies).

But maybe someone else with more knowledge can help.
On plus side the current behavior is still acceptable, and use of "wrong" timestamps is more of an annoyance than issue.
... unless someone finds there is an issue with some other tooling that expected sensible timestamps. We'll see.

**Comment by cowtowncoder** [comment]
@hboutemy Just to make sure I understand state of things: it sounds like neither Felix `maven-bundle-plugin` nor `biz.aQute.bnd:bnd-maven-plugin` automatically handle things the way we'd want, wrt specified timestamp.
But both could perhaps be improved to do so. Is my understanding correct?

**Comment by hboutemy** [comment]
@cowtowncoder thanks for sharing the migration article: I'm learning very interesting things about these 2 plugins, I'm starting to understand the story behind

which leads to an answer on "it sounds like neither Felix maven-bundle-plugin nor biz.aQute.bnd:bnd-maven-plugin automatically handle things the way we'd want, wrt specified timestamp.
But both could perhaps be improved to do so. Is my understanding correct?"

good news: not exactly, the situation is better: the `bnd-maven-plugin` as used in the migration documentation will bring the updated timestamp in the jar file (because it uses `bnd-maven-plugin:bnd-process` goal only to generate manifests, and lets `jar:jar` do the jar, and `jar:jar` respects the configured timestamp)

Felix `maven-bnd-plugin` does not respect the timestamp, because it delegates the jar creation to Bnd, which seems not to respect the timestamp from what we saw in your Jackson project. And I suppose `bnd-maven-plugin:jar` to do exactly the same

So the quick summary is: if you migrate Jackson to `bnd-maven-plugin` with packaging `jar` instead of `bundle` as described in the migration documentation, you should have the expected result: jars with updated timestamp

(I learned many things these days, thanks a lot)

**Comment by cowtowncoder** [comment]
@hboutemy Ah. Interesting! So at least there is a way forward. I'll need to figure out who could help with migration; mostly wrt verifying that resulting OSGi bundle works as well or better after change -- this also would need to be done for all dozen of repos or so. But the first one would no doubt be most work and should be able to use same procedure for others.

**Comment by hboutemy** [comment]
@cowtowncoder I worked on it: in fact, we can avoid the full `bnd-maven-plugin` migration for now and just apply the good idea from the migration documentation: use `maven-bundle-plugin` only for manifest creation, but let `maven-jar-plugin` create the jar (which will preserve configured output timestamp)

**Comment by cowtowncoder** [comment]
Excellent, thank you @hboutemy !
