### ISSUE TITLE
@JsonIdentityInfo - Always Serialize IDs as Fields

### ISSUE THREAD

**Issue by ecavinat** [FasterXML/jackson-databind#372]
Hi,

I searched a lot about how to serialize IDs in <code>@JsonIdentityInfo</code> annotated classes as JSON field with ID (like this pseudo-code <code><b>someField : { id : 1 } ... someField : { id : 1 } ... someField : { id : 1 }</b></code>) <b>for all cases</b> (not just the first object), and I can't do that. I realize that are two options: 
<ul>
<li>The default one (just the first object is serialized with a field with ID and others by IDs references, making incomplete JSON objects). Pseudo-code: <code><b>someField : { id : 1 } ... someField : 1 ... someField : 1</b></code></li>
<li>All objects are serialized just as ID (<code>@JsonIdentityReference(alwaysAsId = true)</code>). Pseudo-code: <code><b>someField : 1 ... someField : 1 ... someField : 1</li>
</ul>
I tried extend some Jackson's core classes (<code>BeanSerializer</code>, <code>BeanSerializerBase</code> and <code>WritableObjectId</code>), but it seems too dificult (have a lot of <code>final</code> classes and methods and much more classes to extend...). I resolved this problem using custom serializers (via <code>@JsonSerializer</code>) to control the cycle, but that wasn't a elegant way (I had a lot of work on these customizations...). 
Is this third option possible to implement?

Thanks (and sorry for my poor English...)

**Comment by reda-alaoui** [comment]
Hi,

I am stuck with the same issue.
I am not sure I understood the issue resolution.

I want to use ```IntSequenceGenerator``` with a generated property named ```@id```.
Sometimes we obtain the following:
```json
{
   a: {
     '@id': 1
   }
}
```
other times the following:
```json
{
   a: 1
}
```

We need to always retrieve the object with the first representation.

Is that possible?

**Comment by redben** [comment]
@reda-alaoui have a look at https://github.com/jsog/jsog-jackson

**Comment by reda-alaoui** [comment]
Ok great, thank you

**Comment by cen1** [comment]
I am not entirely sure why this issue is closed since there is no solution to the question (using yet another external library is not ok). The requested feature seems rather simple to me (not knowing the internal workins of Jackson):

We need to get form this:
```
"store": "f8aca5e4-c09f-4bf8-81e5-f6f0fad251a5"
```
to this:
```
"store": {
  "id":"f8aca5e4-c09f-4bf8-81e5-f6f0fad251a5"
}
```

The current generated JSON is breaking the entity model and is unexpected client-wise as far as I'm concerned. Is anything being worked in this direction or could we re-open this as a feature request?

**Comment by cowtowncoder** [comment]
@cen1 Jackson will serialize Object Ids as simple scalars, and not as Objects. This is the design choice, and htis is why this is closed. References are NOT OBJECTS, so why would you embed them in unnecessary wrapping? Or, if you want such complicated reference objects, feel free to implement them using whatever means you want. It is difficult enough to get all the other features working -- specifically, unwrapped properties and polymorphic handling -- and due to lack of separate metadata, or even good conventions, in JSON, I do not think there is a way to reliably use JSON Object wrapping for yet another thing.

Still, I am always open to PRs that suggest alternate way of doing things. I have just zero interest in pursuing this approach myself -- I think it is fragile, complicated way to go, and will not lead to robust and well-functioning system.

**Comment by sotty** [comment]
I also think it is a bit of an issue, mostly for compatibility with other tools that (de)serialize references using the { "@id" : "URI" } pattern. 
For example,  I am trying to serialize certain annotated classes into JSON-LD, then read them using Jena or OWL-API (in and out of Protege) to implement a 'semantic data model'. With IDs being treated as strings, not only I get a broken graph, but reasoners also complain about an inconsistency: OWLObjectProperties cannot have xsd:string for range
