### ISSUE TITLE
New DeserializationFeature IGNORE_UNKNOWN_PROPERTIES

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3721]
DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is enabled by default but when disabled, Jackson can waste a lot of processing time on the unknown properties.

Would it be possible to add DeserializationFeature.IGNORE_UNKNOWN_PROPERTIES (default=false)? This setting only matters if DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is false.

I know we can the annotation `@JsonIgnoreProperties(ignoreUnknown = true)` to classes but adding annotations to classes is not always feasible and in the case of Scala, the generated Java classes may not map 1:1 to the original Scala class.

**Comment by cowtowncoder** [comment]
Ok. I am not 100% sure I understand the distinction between proposed new feature and existing `FAIL_ON_UNKNOWN_PROPERTIES`... but maybe I do. So would this be equivalent to having `@JsonIgnoreProperties(ignoreUnknown = true)` in every class?
If so that might be simple enough to implement.

I am also not sure how existing handling when not failing on unknown properties would be doing more processing than bare minimum: I thought it'd skip value (whenever possible; `@JsonUnwrapped` handling requires some buffering since "unknown-ness" cannot be established.

**Comment by pjfanning** [comment]
@cowtowncoder the ignorable fields can lead to Jackson parsing BigIntegers (and probably BigDecimals). I can reproduce this in the Scala test case (https://github.com/FasterXML/jackson-module-scala/issues/609#issuecomment-1348773581).

The class that does the number parsing is TokenBuffer. This TokenBuffer comes into play when Jackson decides to not treat the deserialization as 'vanilla'. It uses TokenBuffer to 'copyCurrentStructure' and this leads to the code writing out the JSON and hitting this code.

```
            case BIG_INTEGER:
                writeNumber(p.getBigIntegerValue());
```

p.getBigIntegerValue() is super expensive when you have a number with 1000s of digits.

**Comment by cowtowncoder** [comment]
Right, I remember our back-and-forth from a month or two ago.

I should probably have framed my question differently: has it been verified that having a default "ignore unknown" will avoid buffering? And more interestingly, can we create a test case (maybe using a mock framework) to test behavior such that we can verify that specific calls are actually avoided where expected?
My main concern really is that of adding something that won't work the way envisioned (and to some degree confusion of having overlapping features -- for example, I'm pretty sure there is something like `IGNORE_UNKNOWN_PROPERTIES` for other dataformats; I think Protobuf and/or CSV have this).

**Comment by pjfanning** [comment]
I have a Java test case that shows the issue.
* https://github.com/pjfanning/jackson-number-parse-bench/blob/main/src/test/java/org/example/jackson/bench/BigIntegerJsonParseTest.java#L30
* When `ExtractFieldsNoDefaultConstructor` has the `@JsonIgnoreProperties(ignoreUnknown = true)` annotation, the damage is reduced
* When the annotation is not added, you can run the test in debug mode (in an IDE) and set a breakpoint in jackson-core NumberInput.parseBigInteger and you'll see the this method is made to parse a huge string with the DoS risks involved.

**Comment by cowtowncoder** [comment]
One other idea: this might fit well with `ConfigOverride` system. Or, perhaps, is already implemented... looking at `ConfigOverride.java` there is 

    protected JsonIgnoreProperties.Value _ignorals;

and so it should be possible set default value, for which "ignore unknown" could be set.

**Comment by pjfanning** [comment]
@cowtowncoder I'm not really familiar with ConfigOverride. Could you provide a code snippet of how someone could set up an JsonMapper that disabled FAIL_ON_UNKNOWN_PROPERTIES but then set it up so all unknown properties are ignored even when the bean is not 'vanilla' (eg a Java bean with no empty constructor and no setters - immutable Java bean, basically). 

One other option would be to flip the logic on its head so that ignoring unknown props is actually the default - many users would assume this to already be the case - so that only users who don't want to ignore unknown props need to jump through hoops.

**Comment by cowtowncoder** [comment]
I'll have to dig a bit -- unit tests are the best place.

As to changing the default; if we are talking about failing on unrecognized properties, that may be changed for 3.0 but cannot really be done for 2.x -- it's a major behavioral change.

But what I am still not quite sure about is where in code, and why is there such difference.
If it's just a sort of side effect of not having vanilla flag set I guess I can see it.
Otherwise, yeah, it seems like there should be a way to avoid buffering overhead.

Come to think of that, would it be easy to include a simple reproduction here, with plain Java, to show the case? I could debug through it locally and see that I also understand what is happening.

**Comment by cowtowncoder** [comment]
@pjfanning Finally dug deeper into Config Overrides functionality, and realized that while `com.fasterxml.jackson.databind.cfg.ConfigOverrides` has some defaults (besides per-Class settings), setting for `JsonIgnoreProperties.Value` (which contains settings `@JsonIgnoreProperties` has) only exists for per-class overrides.
So there is not yet something that can be used. But I'd be +1 for adding functionality in `ConfigOverrides` to allow defaulting of `JsonIgnoreProperties.Value`. It's not trivial to add, but there are examples for other default settings.
I'd prefer addition here to try to minimize number of `DeserializationFeature`s. And access seems to be only from:

    MapperConfigBase.getDefaultPropertyIgnorals()

More interestingly, maybe, this would also allow configuration where one could have default set of "always ignored" properties. I wish I had time to tackle this as it actually seems straight-forward.

**Comment by cowtowncoder** [comment]
Another thought, slightly related: it'd be great to actually add lazily-decoded numbers for `TokenBuffer`.
I haven't had time to think it through end-to-end, but the general idea has been around for years now.

So. Right now `TokenBuffer.Segment` has 2 elements per buffered token:

1. Type (`JsonToken`)
2. `Object` of value; `String`, `Number` etc.

In case of numbers, it is possible to actually store `String`; handling won't be optimal since `NumberType` is not retained. But this gives an idea... what if we had wrapper type `BufferedNumber` (or `LazyNumber`)? Defined by `jackson-core`, it would contain information needed -- like `NumberType` we know, and either already decoded value (if there is one) or source String (known to be lexically valid, just not decoded).
We'd need a new accessor (getBufferedNumber() or getLazyNumber()); and obviously `TokenBuffer` would need to take advantage of functionality when asking for content to buffer.

But beyond benefits of lazy execution for ignored properties (which we could reserve for `BigInteger` and floating-point types), it could also improve coercion support when buffering, since this would defer need to decide between, f.ex `double` and `BigDecimal` (for which there are couple of issues)

I'll create a separate issue for this idea.

**Comment by cowtowncoder** [comment]
I think this and #3640 are duplicates; should one be closed?

**Comment by pjfanning** [comment]
should use #3640
