### ISSUE TITLE
Mixin with @JsonProperry to override @JsonIgnore no longer works in 2.14

### ISSUE THREAD

**Issue by ddewaele** [FasterXML/jackson-databind#3812]
Given the following code

```
public class MixinSample {

    public static class CustomerMixin {
        @JsonProperty
        public String id;
    }

    public static void main(String[] args) throws Exception {
        Customer customer = new Customer();
        customer.setId("123");   // This POJO has a JsonIgnore on the id field
        customer.setName("Joe");

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.addMixIn(Customer.class, CustomerMixin.class);
        System.out.println("objectMapper = " + objectMapper.writeValueAsString(customer));

    }
}
```

With jackson-databind 2.13.x it outputs as expected (Mixin overrides the JsonIgnore id field):
```
{"id":"123","name":"Joe"}
```

With jackson-databind 2.14.x it doesn't seem to take into account the mixin :
```
{"name":"Joe"}
```

**Comment by cowtowncoder** [comment]
Incomplete reproduction, would need `Customer` definition too.

But assuming there's simple `@JsonIgnore` on property `id` (on `setId()` or `getId()`), the problem is that `@JsonProperty` does not exactly override `@JsonIgnore`: the two are in conflict.
To override ignoral, one has to add mix-in for

     @JsonIgnore(false)

and not add conflicting `@JsonProperty`. Adding override as above should have worked with 2.13 and earlier as well.
I think the fix via #3357 is what you are seeing here.

Older behavior (of `@JsonProperty` having precedence if both included) was unintended, as in case of ignore-and-property, ignoral should have (had) precedence.

New behavior is correct, at any rate.

**Comment by ddewaele** [comment]
Correct. Thx for the clarification. Closing Issue.

**Comment by cowtowncoder** [comment]
Forgot to say: thank you for filing this @ddewaele -- unfortunately it being a behavior change means that there are probably other developers who have used mix-ins the same way; and seemingly working as intended (I can see why that makes sense; it's just tricky to decide whether inclusion or exclusion ought to "win").
So at least they can find this issue.

**Comment by ddewaele** [comment]
Thx again for clarifying. We're doing a big Spring boot 2.x -> 3.x upgrade on a lot of projects and I did read in the Jackson 2.14 release notes initially but somehow missed this one.

Awesome work you people are doing in keeping this great library compatible too a large degree for such a long time !

**Comment by cowtowncoder** [comment]
@ddewaele Actually it is quite possible that that note was added after release -- so you couldn't have seen it then. I just added note here for sake of completness (was about to add something there if this was missing).
