### ISSUE TITLE
`TypeFactory` cache performance degradation with `constructSpecializedType()`

### ISSUE THREAD

**Issue by carterkozak** [FasterXML/jackson-databind#3876]
**Describe the bug**
TypeFactory cache interactions taking seconds in real-world scenarios under heavy load (e.g. Jersey ProviderBase, where 'constructSpecializedType' is used) where the operation itself takes microseconds.

TypeFactory.constructSpecializedType adds elements to the cache which contain PlaceholderForType type arguments. These type arguments all have the same hashCode (based on Object.class plus a hard-coded value for all placeholders) while overriding equals to perform reference equality. Each time that constructSpecializedType is called, more data is added to the cache with the same hash code, but equality never succeeds due to instances differing, not only reducing cache hit probability, but making it increasingly difficult to find the values we want due to following pointers on heavy cache collisions where the data structure degenerates into a linked list.
I've committed a change which bypasses the cache in cases where PlaceholderForType is used. I don't know if this is an ideal solution, but it improves the case where I've encountered this edge case.

**Version information**
Impacts versions prior to 2.14.0, but the issue becomes more pronounced in 2.14.0 due to #3531 which doesn't simply clear the map upon reaching max size. #3675 seems to make the issue even more pronounced in some environments due to heavy hash collisions.

**To Reproduce**
Reproducer can be found here: https://github.com/FasterXML/jackson-benchmarks/pull/5

PR here: https://github.com/FasterXML/jackson-databind/pull/3875

**Comment by cowtowncoder** [comment]
I regret merging of #3531; we have made a few highly speculative optimization attempts that may have been net negative (in the worst case). :-(

But as to solution, yes, my first instinct is that the change makes sense.

I'll see if we can get the fix merged tomorrow since I agree that this sounds like a gnarly issue.

And if we can prove this via 2.15.0-rc3, I am open to limited backport into 2.14(.3) if we are happy with safety aspects.
That may actually need to wait until 2.15.0 release if we want to get wider feedback (true .0 release tends to bring out more bug reports than all RCs combined).

**Comment by carterkozak** [comment]
Closing this as resolved by #3876
