### ISSUE TITLE
Varying behavior of `FAIL_ON_UNRESOLVED_OBJECT_IDS` when invoking `readValue()` using `mapper.configure()`and `mapper.readerFor().with()`

### ISSUE THREAD

**Issue by JooHyukKim** [FasterXML/jackson-databind#3886]
**Describe the bug**
Varying behavior on `DeserializationFeature .FAIL_ON_UNRESOLVED_OBJECT_IDS` is observed when invoking `readValue()` using `mapper.configure(jsonWithMissingId)`and `mapper.readerFor().with(jsonWithMissingId)`

**Version information**
2.15 (default branch)

**To Reproduce**

I have included this in #3880 

### Using `mapper.readerFor().with()`

```java
    public void testUnresolvableWithFeatureSymmetry() throws Exception
    {
        // specifically configured to "not" fail
        IdWrapper w = MAPPER.readerFor(IdWrapper.class)
            .without(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS)
            .readValue(a2q("{'node':123}"));
        assertNotNull(w);
        assertNull(w.node);

        // specifically configured to fail, but doesn't
        IdWrapper w2 = MAPPER.readerFor(IdWrapper.class)
            .with(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS)
            .readValue(a2q("{'node':123}"));
        assertNotNull(w2);
        assertNull(w2.node);
    }
```
### Using `mapper.configure()`

```java
    public void testUnresolvableConfigureFeatureSymmetry() throws Exception
    {
        // specifically configured to "not" fail
        IdWrapper w = MAPPER
            .configure(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS, false)
            .readValue(a2q("{'node':123}"), IdWrapper.class);
        assertNotNull(w);
        assertNull(w.node);

        // specifically configured to fail
        try {
            IdWrapper w2 = MAPPER
                .configure(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS, true)
                .readValue(a2q("{'node':123}"), IdWrapper.class);
            fail("should not pass");
        } catch (UnresolvedForwardReference e) {
            verifyException(e, "Unresolved forward reference", "Object id [123]");
        }
    }
```

**Expected behavior**

 Below code should fail with `UnresolvedForwardReference`

```java
        // specifically configured to fail, but doesn't
        IdWrapper w2 = MAPPER.readerFor(IdWrapper.class)
            .with(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS)
            .readValue(a2q("{'node':123}"));
```
**Additional context**

**Comment by cowtowncoder** [comment]
One quick note: one of use case is incorrect -- changing configuration of `ObjectMapper` after first use (read/wrote) is not supported and should not be attempted. Unfortunately Jackson 2.x API does allow calling, say, `ObjectMapper.configure()` after usage; 3.0 will remove methods so that no unsafe/unsupported usage is possible.
In practice some of reconfiguration cases may happen to work but tests should not try to do that: all configuration of `ObjectMapper` should occur before any use. For changed settings, either different mapper should be used or `ObjectReader`/`ObjectWriter` (for which reconfiguration is fully supported as new instances are constructed).

I don't think this is the reason for failing tests but that part needs to be removed or changed to use supported mechanism.

**Comment by cowtowncoder** [comment]
Yeah the general "configure-then-use" approach is touched upon in Javadoc of `ObjectMapper`, although it focuses on thread-safety. Adding notes on individual configuration methods is bit tricky because there are so many -- in theory all of them should refer to them needing to be called before any use of mapper. Although I guess maybe only adding something to `configure(Feature)` (and `enable()`/`disable()` -- still there are multiple overloads) is an option.
