### ISSUE TITLE
InternalNodeMapper needs to support setting JsonMapper

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#4017]
Relates to #4016 

The broken test in DeepJsonNodeSerTest is because of the `jsonNode` and the `toString` call. That call uses InternalNodeMapperwhich has its own hardcoded JsonMapper. That JsonMapper instance uses the default StreamWriteConstraints. The jsonNode has data that exceeds the max default depth allowed.

**Comment by cowtowncoder** [comment]
No, there is no need to change these settings -- this class is only ever to be used for `JsonNode.toString()` and as such is expected not to be configurable.

**Comment by ppawel** [comment]
@cowtowncoder I think you should also consider `InternalNodeMapper.bytesToNode` which is used when using Java serialization. This leads to unexpected/random issues with node typing because of the hardcoded nature of `InternalNodeMapper`.

**Comment by cowtowncoder** [comment]
@ppawel Consider in what way?

**Comment by ppawel** [comment]
> [@ppawel](https://github.com/ppawel) Consider in what way?

E.g. make parts of this serialization configurable - either the components used inside `InternalNodeMapper` or another way to influence how Jackson does JDK serialization.

Right now it causes unexpected results like if you have an `ObjectNode` which has a property with `DecimalNode`, you use JDK serialization on that, and you get back an `ObjectNode` with `DoubleNode` or `IntNode` (depending on the value of the number in that property). I understand that this is due to JSON string/bytes format not being able to preserve the types properly but this kind of "type switching" is not an expected behavior when you look from JDK serialization perspective.

In my case the impact is not huge because it just affected writing out the JSON-string in the end from `10.0` to `10` for example but I imagine there could be other potential differences when going through serialize/deserialize cycle.

I guess bottom line (or at least for me personally) would be, don't use JDK serialization with Jackson objects but rather (de)serialize it yourself and feed JDK the resulting String.

**Comment by cowtowncoder** [comment]
> .. [type switching]

Interesting point, yes, that is unfortunate indeed.

> I guess bottom line (or at least for me personally) would be, don't use JDK serialization with Jackson objects but rather (de)serialize it yourself and feed JDK the resulting String.

Definitely recommended for multiple reasons.

Unfortunately configurability would be hard to implement due to `JsonNode` instances having no references to any Jackson handler/config types so the only option would be `static` configuration -- and that is considered definite anti-pattern from Jackson perspective (all configuration should be bound to specific `ObjectMapper` or objects it has references to).

**Comment by ppawel** [comment]
Agreed, and understood. Thanks for quick response and also sorry for rising it in this 3-year-old closed issue...

**Comment by cowtowncoder** [comment]
@ppawel I appreciate your help in my understanding of the issues, regardless of route information takes :)
