### ISSUE TITLE
TokenBuffer support for setting streamWriteConstraints

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#4018]
The TokenBuffer will inherit the default StreamWriteConstraints. We'll need a way to allow users who want to support deeply nested data to have TokenBuffer run with a custom StreamWriteConstraints.

Relates to https://github.com/FasterXML/jackson-core/pull/1055

**Comment by cowtowncoder** [comment]
Possibly. If I remember correctly, there are methods in `SerializerProvider` to be used for constructing instances, instead of direct construction -- if so, there'd be access to underlying `JsonFactory` which should give access I think.
Ability to override this setting would be useful as well. Same holds true for `StreamReadConstraints` if not already handled.

**Comment by pjfanning** [comment]
The StreamReadConstaints come from the JsonParser instances that are passed to the TokenBuffer. The StreamWriteConstaints could come from the JsonGenerator instances.

**Comment by cowtowncoder** [comment]
@pjfanning Yes, definitely in cases where `JsonGenerator` is passed (or can be passed)

**Comment by cowtowncoder** [comment]
@pjfanning Is this still needed?

**Comment by pjfanning** [comment]
Maybe best to wait for a real world issue instead of trying to be proactive on this.

**Comment by cowtowncoder** [comment]
Ok, will close; easy enough to re-open if/when requested.
