### ISSUE TITLE
Deserialization of wildcard `super` generic type defaults to `Object`

### ISSUE THREAD

**Issue by FWest98** [FasterXML/jackson-databind#4030]
**Describe the bug**
When trying to deserialize a generic type for which the type parameter is of the form `? super Foo`, Jackson will return an `Object` instead of `Foo` (which I would expect, or at least desire to have happen)

**Version information**
2.15.2

**To Reproduce**
My usecase is that I have some property that in JSON is either an entity, or a textual reference that my code will later resolve to that entity. Since this pattern is quite generic in my models, I did not want to create unique types and deserializers for every such case. Hence, I wrote the following:

```java
public sealed class ReferenceOr<T> {
    public static final class Reference extends ReferenceOr <Object> {
        public String ref;

        public Reference(String ref) {
            this.ref = ref;
        }
    }
    public static final class Value <U> extends ReferenceOr <U> {
        public U instance;

        public Value(U instance) {
            this.instance = instance;
        }
    }
}

public class Foo {
    public ReferenceOr<? super Bar> bar;

    public static class Bar {
        public String name;
    }

    public static Foo create() {
        // Usage illustration to see how "Reference" does not need a type parameter here
        Foo foo = new Foo();
        foo.bar = new ReferenceOr.Value<>(new Bar());
        foo.bar = new ReferenceOr.Reference("some");
        return foo;
    }
}
```

After writing a contextual deserializer, I noticed that the property type I receive in `createContextual` is `ReferenceOr<Object>`, whereas I would have expected `ReferenceOr<Bar>` (or at least, hoped for). As a consequence, continuing to deserialise will have Jackson produce a `Map` as instance for the `Object`, thus producing a `ReferenceOr<Map>`, which is entirely incompatible with `? super Bar`.

After some tracing, this is eventually produced by https://github.com/FasterXML/jackson-databind/blob/2.16/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L1756 where only the first upper bound of the wildcard type is chosen. In this case, the `? super Bar` has an upper bound `Object` and lower bound `Bar`.

**Expected behavior**
I would hope that the `_fromWildcard` function would try to use the lowerbound type in case we have such a `? super Bar` case - that would solve my issue. In the comment in the TypeFactory code it is already written that the current behaviour might not be sufficient - it seems like it might not be indeed.

**Additional context**
In this particular instance, changing `? super Bar` to `Bar` fixes the problem, but makes my code harder to work with and the deserializer harder to implement, as I can no longer just produce any instance of `Reference`.

**Comment by pjfanning** [comment]
Please report Kotlin issues to https://github.com/FasterXML/jackson-module-kotlin

jackson-databind team normally only accept Java examples.

**Comment by FWest98** [comment]
This is not a Kotlin-specific issue - the notation `in T` is just how Kotlin writes the type `? super T`. The issue is really directly related to the TypeFactory in the databind library

**Comment by pjfanning** [comment]
Can you provide a Java example then?

**Comment by FWest98** [comment]
I rewrote the question to using Java

**Comment by FWest98** [comment]
I took some time and wrote some unit tests to reproduce the issue: https://github.com/FWest98/OS-Jackson-Databind/commit/8357805289c18feac19105a5efc51b2e342fffe2
and coded up an initial version for a proposed "fix": https://github.com/FWest98/OS-Jackson-Databind/commit/e06a18c595988d494eb4211321a359e2bcea0439

The example I used in the tests is shorter than the one above, but misses som of the context of the usecase. Please let me know what you think - I can imagine this will need some more thinking and elaboration, and possibly even some configuration for users to specify desired behaviour.

**Comment by yawkat** [comment]
> As a consequence, continuing to deserialise will have Jackson produce a Map as instance for the Object, thus producing a ReferenceOr<Map>, which is entirely incompatible with ? super Bar.

You're getting a ReferenceOr<Object> *containing* a Map, which is not the same as a ReferenceOr<Map> (at least statically, at runtime it's the same). The former is valid, the latter would not be.

Producing a `? super` type is always going to be problematic with deserialization. A contravariant collection makes it possible to add objects of the lower bound, but you can't get objects of that lower bound out of the collection, only Object. This makes the collection essentially useless for getting objects out. But this is exactly what you want to do with deserialization, so there is an inherent conflict in what deserialization is for and what contravariance is for.

In your example, if you deserialize a `Foo` with the `ReferenceOr<? super Bar>` field, and jackson used `ReferenceOr<Bar>` as the type for deserialization, then you would still have no way to actually get a `Bar` out of the field safely! You would need to cast the value yourself.

Even worse, someone could place another type `Baz` in the field like so: `new Foo().bar = new Value<Object>(new Baz())`. This is entirely compatible with generics. During *serialization*, jackson would then serialize the Baz type without complaint. Then, during *deserialization*, it would blow up because jackson expects a Bar type, but the data comes from a Baz type.

In my opinion, there is no ideal solution here, because `? super` is inherently weird to deserialize. But falling back to Object, as we do right now, is the safest approach, because it ensures serialized data can be deserialized again, even if possibly not to the type you want.

Additionally, there could be weird interactions with eg default typing if we were to change this, but I would have to look at it more.

**Comment by cowtowncoder** [comment]
Yeah.... not sure I'd feel confiident changing semantics of `TypeFactory` to resolve to upper bound.

However! If anyone wanted to provide a PR for functionality that allows configuring `TypeFactory` for alternate logic (either directly, or by newly added `MapperFeature`), I could merge such a contribution.

**Comment by cowtowncoder** [comment]
I am not sure there is a way to proceed here, for now; closing. May be re-opened/re-filed esp. if there's a PR proposing changes.
