### ISSUE TITLE
JsonTypeId is not serialized in Collection even if set hard coded

### ISSUE THREAD

**Issue by mistriel** [FasterXML/jackson-databind#4051]
Having two classes inherited from a common class that declares two subtype,
where each subtype is setting the type hard coded, when the children classes are in an Array, the type field is not exist

```java

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.assertj.core.api.Assertions;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

public class JacksonTypeIdTest {


    @Data
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true )
    @JsonSubTypes({
            @JsonSubTypes.Type(value = ChildA.class, name = "ChildA"),
            @JsonSubTypes.Type(value = ChildB.class, name = "ChildB")
    })
    @NoArgsConstructor
    public static abstract class ABSTRACT {

        @JsonTypeId
        protected String type ;
    }

    @Data
    public static  class ChildA extends ABSTRACT {
        public ChildA() {
            type = "ChildA";
        }

        private String aaa;

    }

    @Data
    public static  class ChildB extends ABSTRACT {
        public ChildB() {
            type = "ChildB";
        }
        private String bbb;
    }

    @Test
    public void test() throws JsonProcessingException {

        ChildA childA = new ChildA();
        childA.setAaa("aaa");

        ChildB childB = new ChildB();
        childB.setBbb("bbb");

        ObjectMapper objectMapper = new ObjectMapper();
        List<ABSTRACT> children = new ArrayList<>();
        children.add(childA);
        children.add(childB);

        Assertions.assertThat(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(children)).contains("type");

    }
}

```

The result of this test is:

```java
java.lang.AssertionError: 
Expecting:
  "[ {
  "aaa" : "aaa"
}, {
  "bbb" : "bbb"
} ]"
to contain:
  "type" 
```

### Version Information
version 2.13.4

### Expected behavior

type parameter `type` should appear if explicitly set.

### Additional context

In opposition to [Issue 303](https://github.com/FasterXML/jackson-databind/issues/303)  here the types should not be inferred as they are hard coded - so even if we get type erasure by the compiler, still here the value exist like any other parameter in the serialized classes

**Comment by cowtowncoder** [comment]
This is a FAQ: problem is due to Java Type Erasure -- root level values use runtime type where generic type signature is not retained. There are ways to work around this but there is no way to prevent the problem with usage pattern shown.
The problem is that Jackson only sees type of value as `List<?>` (about same as `List<Object>`) -- type declarations from sources are only used for compiling sources and runtime `Class` for `List` does not retain any.

And since `java.lang.Object` does not have `@JsonTypeInfo`, no type id is added: type inclusion is based on "base type" and not dynamically checked for every element separately.

Work arounds include:

* Sub-classing `List` as, say, `class AbstractList extends ArrayList<ABSTRACT> { }` -- in this case, type parameters are retained by sub-classing.
* Creating `ObjectWriter` with specific type to use instead of runtime type: 

    mapper.writerFor(new TypeReference<List<ABSTRACT>>() { }).writeValue(list);

**Comment by cowtowncoder** [comment]
@JooHyukKim Yes, that would be good. I am not good at getting documentation written but I would like to improve things.

Technically there is a tiny FAQ at:

https://github.com/FasterXML/jackson/wiki/FAQ

which you should now have access to edit (I sent an invite).
