### ISSUE TITLE
Exclude toString, hashCode, and equals from Jackson's analysis

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4073]
### Is your feature request related to a problem? Please describe.

In implementing `AnnotationIntrospector`, `toString`, `hashCode`, and `equals` are input to various parsing methods.
On the other hand, these functions basically have no effect on both serialization and deserialization.
In other words, they seem to be increasing the load on the parsing process for no good reason.

### Describe the solution you'd like

The method extraction process excludes these methods.

### Usage example

Initialization load and memory consumption are reduced.

**Comment by yawkat** [comment]
i think some people use toString for JsonValue

**Comment by k163377** [comment]
I may have been short in my explanation, but I don't believe that anything can be unconditionally excluded.
I think it is necessary to take into account that there should be no unintended consequences when annotations such as `JsonValue`, `JsonAnyGetter`, `JsonAnySetter`, etc., which are provided by `Jackson`, are added.

**Comment by cowtowncoder** [comment]
First of all: I assume that the removal would be for set of methods exposed via `AnnotatedClass`.

As @yawkat correct points out, `toString()` is quite frequently used with `@JsonValue`.
And I could see `hashCode()` being used in some cases similarly (but less commonly). So I don't think these can be unconditionally dropped.
Excluding `equals()` might be doable but... does that really lead to measurable performance improvements?
(it is commonly defined, but in grand scheme of things there are many more other potential setter methods that get resolved).

Note, too, that removal of non-qualified methods is done at point where we have no idea of which annotations might be relevant; since `AnnotationIntrospector`s are pluggable it is not safe to assume only Jackson-provided once are.
So the simple method for dropping methods by name would be "blind" to any annotations.
And conversely trying to detect meaningful annnotations during filtering would likely negate benefits of trying to filter out methods.

So I am not sure this is worth pursuing.

**Comment by k163377** [comment]
> does that really lead to measurable performance improvements?

Depending on the use case, for example, `kotlin-module` can be expected to be faster since it skips the costly reflection process.
Also, in cases where many `AnnotationIntrospector`s are connected, a speedup is expected.

This is especially true for performance improvement at first runtime.
For example, when using `Jackson` at each endpoint of a microservices architecture, it is important to reduce the load on the first run, since the overhead on the first run can be many times larger.

> And conversely trying to detect meaningful annnotations during filtering would likely negate benefits of trying to filter out methods.

It seems to me that this could be accomplished inexpensively and easily with the condition that "no annotations be assigned."

> AnnotationIntrospectors are pluggable it is not safe to assume only Jackson-provided once are.

This point is certainly true.
It looks like it has to be an option.

**Comment by cowtowncoder** [comment]
@k163377 I did not question whether removing reflection in general improves performance (and is good in that sense), but rather if excluding just one method (even if common) really would help. It seems like a tiny portion of all methods.

All in all I am not fully convinced, although remain open to excluding inclusion of `equals()` from processing.

So if anyone wants to propose a PR for removing it (plus, we could even have `MapperFeature` for changing behavior just in case), I'd be open to merging it.

**Comment by k163377** [comment]
> excluding just one method

I thought that `toString` and `hashCode` could also be excluded, provided that the annotation size is zero.

In any case, I will check if it is possible to implement this when I have time.

**Comment by cowtowncoder** [comment]
@k163377 I suspect annotation check might not be possible for couple of reasons:

1. Part that collects methods does not really do any annotation processing  -- although if it did, check for 0 annotations might work fine since `@Override` is source-only annotation
2. Mix-in annotations are merged at a later point

Mix-in part is the main challenge I think: they are used in some cases.

**Comment by yawkat** [comment]
if the goal is to avoid unnecessary reflection calls when there are no annotations, i dont see why this would need to be limited to eq/hc/ts. Any optimization that can exclude one of these methods for further analysis could be applied to other methods as well as long as they are not annotated and don't match the standard get/set naming conventions. Conversely, any edge cases that apply to normal methods also apply to eq/hc/ts.

I'm a bit skeptical that adding an analysis step to exclude methods (eq/hc/ts or more) from other analysis steps is going to improve performance, though. Could definitely benchmark this though.

**Comment by cowtowncoder** [comment]
@yawkat the problem is that most other methods/fields/constructors are potentially discoverable even without annotations, so cannot be discarded without more analysis (like you suggest, naming convention).
Conversely this small set would consist of methods for which no default handling could apply (... except if one specifies get/set prefix to be "", maybe they would, come to think of that).

I agree that I, too, am bit skeptical of benefits from doing this.

And there were some regressions when I did something similar to prune, handling of methods defined in `Object.class` -- our unit test suite does not really cover any of "clever use", except where there have been regressions.

**Comment by k163377** [comment]
> if the goal is to avoid unnecessary reflection calls when there are no annotations, i dont see why this would need to be limited to eq/hc/ts. Any optimization that can exclude one of these methods for further analysis could be applied to other methods as well as long as they are not annotated and don't match the standard get/set naming conventions. Conversely, any edge cases that apply to normal methods also apply to eq/hc/ts.

You are right.
They were excludable from all classes, so I assumed that anything other than those could not be excluded.

**Comment by k163377** [comment]
Unfortunately, I have confirmed that this change does not affect performance that much.

The following is a poc that assumes a Kotlin data class and excludes 5 functions.

```java
    /* in AnnotatedMethodCollector.java */
    private static boolean _isIncludableMemberMethod(Method m)
    {
        if (Modifier.isStatic(m.getModifiers())
                // Looks like generics can introduce hidden bridge and/or synthetic methods.
                // I don't think we want to consider those...
                || m.isSynthetic() || m.isBridge()) {
            return false;
        }
        // also, for now we have no use for methods with more than 2 arguments:
        // (2 argument methods for "any setter", fwtw)
        return m.getParameterCount() <= 2 && !(_isExcludableMethodName(m.getName()) && m.getAnnotations().length == 0);
    }

    private static boolean _isExcludableMethodName(String name) {
        return name.equals("hashCode")
                || name.equals("equals")
                || name.equals("toString")
                // Kotlin specific
                || name.equals("component1")
                || name.equals("copy");
    }
```

I ran the `JMH` single-shot benchmark several times against `Dto` defined as follows and compared the lowest values (the lower the score the better in single-shot mode).

```kotlin
import com.fasterxml.jackson.annotation.JsonValue

data class Foo(@JsonValue val v: Int)
data class Bar(@JsonValue val v: Int)
data class Baz(@JsonValue val v: Int)
data class Qux(@JsonValue val v: Int)
data class Quux(@JsonValue val v: Int)

data class Dto(
    val foo: Foo,
    val bar: Bar,
    val baz: Baz,
    val qux: Qux,
    val quux: Quux
)
```

As a result, both serialization and deserialization improved only a little more than 1%.
This issue is closed as it does not appear to be very effective.

---

Benchmarks and results are uploaded below.
[jackson-4073-benchmark.zip](https://github.com/FasterXML/jackson-databind/files/12565278/jackson-4073-benchmark.zip)

**Comment by cowtowncoder** [comment]
It should usually have zero effect on serialization and deserialization -- introspection should only ever occur the first time a serializer/deserializer is constructed, and cached afterwards.
So unless test is for a single `readValue()` or `writeValue()` (but running for multiple seconds), I would not expect to see any real change in performance.

The main benefit would be reduced startup time for initializations, for cases where a single read or write call is made; or service startup time is particularly important.
