### ISSUE TITLE
Problem with custom `TypeIdResolver`

### ISSUE THREAD

**Issue by StuAtGit** [FasterXML/jackson-databind#4100]
### Describe your Issue

Hello, I cannot understand the documentation around implementing custom `@JsonTypeIdResolver` enough to know if what I'm doing is a wrong, or I've found a bug.

I have a fairly straightforward scenario:

(1) Two very similar classes that are in use across multiple services
(2) I created a unified interface to allow services to accept either class under one interface
(3) I now want to support updates to the services to use the new interface to serialize / deserialize. It's fine if the service, after an update, requires an additional property to differentiate between types when serializing into an interface. No problems here.
(5) I want any updated service to be able to deserialize _directly into a concrete type_ from the old services, even if the JSON lacks type info. Note, they _only_ need to be able to handle deserializing into _concrete_ types lacking type info. This doesn't work. Not sure why Jackson doesn't support it, but that's another story. I tried patching over this default behavior of insisting on type ids for concrete types by using a custom `TypeIdResolver` .. but it doesn't work, and that's where my question lies.

Example:

```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "__object_type"
)
@JsonSubTypes(
    {
        @JsonSubTypes.Type(value = Concrete1.class, name = "CONCR1"),
        @JsonSubTypes.Type(value = Concrete2.class, name = "CONCR2")
    }
)
public interface MyInterface {...}
....
public class Concrete1 implements MyInterface {...}
...
public class Concerete2 implements MyInterface {...}
```

Using the bog-standard `@JsonTypeInfo` and `@JsonSubTypes` annotation doesn't work, because for some inscrutable reason, even when you're deserializing into a _concrete_ class like so:

```
var obj = objectMapper.readValue(serializedValue, Concrete1.class);
```

the deserializers demands that the JSON still has the `__object_type` property even though _it only exists on the interface, and I've explicitly told Jackson which exact, concrete class to use in the code_ . 

So that's strange, but moving on...

I tried to work around that with:

```
@JsonTypeResolver(CustomTypeResolver.class)
@JsonTypeIdResolver(CustomTypeIdResolver.class)
@JsonTypeInfo(
    use = JsonTypeInfo.Id.CUSTOM
)
```

However, the deserializer still insists on looking for some sort of property with type information, and, as a kicker, by putting breakpoints all over my overrides in `CustomTypeIdResolver`, I can see that only the `init` method is getting called. 

Based on the docs, I would assume that `JsonTypeInfo.Id.CUSTOM` would instruct the deserializer to identify the class to use via the `CustomTypeIdResolver` class .. but it appears  not to do so.

Feeding a serialized version of the pre-interface concrete class into the object reader I get:

```
Missing type id when trying to resolve subtype of [simple type, class ....Concrete1]: missing type id property ''
```

My TypeIdResolver looks like so:

```
public class CustomTypeIdResolver extends TypeIdResolverBase {
    private JavaType type;

    @Override
    public void init(JavaType bt) {
        this.type = bt;
    }

    @Override
    public String idFromValue(Object value) {
       //breakpoint never hit
        return value.getClass().getName();
    }

    @Override
    public String idFromValueAndType(Object value, Class<?> suggestedType) {
       //breakpoint never hit
        return null;
    }

    @Override
    public JsonTypeInfo.Id getMechanism() {
       //breakpoint never hit
        return JsonTypeInfo.Id.CUSTOM;
    }

    @Override
    public JavaType typeFromId(DatabindContext context, String id) throws IOException {
       //breakpoint never hit
        if (id.equals(Concrete1.class.getName())) {
            return context.constructType(Concrete1.class);
        }
        return context.constructType(Concrete2.class);
    }
}

```

My custom type (not typeId, type) resolver looks like so:

```
public class CustomTypeResolver extends StdTypeResolverBuilder {
    @Override
    public TypeDeserializer buildTypeDeserializer(DeserializationConfig config, JavaType baseType, Collection<NamedType> subtypes) {
        if (baseType.getRawClass().equals(Concrete1.class)) {
            return super.buildTypeDeserializer(config, config.constructType(Concrete1.class), Collections.emptyList());
        } else if (baseType.getRawClass().equals(Concrete2.class)) {
            return super.buildTypeDeserializer(config, config.constructType(Concrete2.class), Collections.emptyList());
        }
        return super.buildTypeDeserializer(config, baseType, subtypes);
    }
}
```

Why isn't `CustomTypeIdResolver` being used by the deserializer to resolve the type? Why does it even need one, when the `CustomTypeResolver` can handle resolving legacy data on it's own? Why does the deserializer continue to insist that a type id is required? Shouldn't it just call my custom implementations to derive the type from the payload?

Interestingly enough, the CustomTypeResolver does get called, and it does the correct thing, and creates a deserializer with the correct concrete class... and than that deserializer decides to ignore the concrete class it's given and throw the error about the missing type id property.

**Comment by cowtowncoder** [comment]
In general, if you want polymorphic handling, you need to prove type id. Jackson doesn't try to use complicated heuristics in figuring when it MIGHT be ok not to do that -- just because a type is concrete does not in itself guarantee anything.
So in that sense you may be trying to do something system is not designed to support.

More specifically, functionality is designed to support reading and writing type as indicate by so-called "base type": class on which `@JsonTypeInfo` is added. Not one of its subtypes (although that might work if you are lucky). Certainly not its supertype (which won't work since annotation not visible).
So in your case, target type is meant to be `MyInterface`. Not one of implementing types.

As to why `TypeIdResolver`: it does not get JSON payload, almost nothing in Jackson gets anything more than streaming `JsonParser`. And resolver must get Type Id to resolve, which is something something else (`TypeDeserializer`, as it happens) must extract.

So. Long story short: you trying to do something Jackson polymorphic handling is not designed to do -- it is not designed for type transformations. It operations on Type Ids added, with some minor edge cases (allowing `defaultImpl` for missing type id case, if specified).

**Comment by cowtowncoder** [comment]
A bit more...

Your `CustomTypeIdResolver` methods are not called because they are only called when:

1. Type id is needed for serialization (and you are deserializing)
2. Type id has already been extracted and needs to be resolved to Type -- your code doesn't get there since no Type Id is found

Your `CustomTypeResolver` on the other hand makes wrong assumption regarding base type -- it assumes that means "target type" (type requested to be deserialized). This is not what "base type" is in general sense (although I can see how it might make sense for specific case of concrete main-level value type); base type is the declared type for property; usually base class/interface with `@JsonTypeInfo`.
As a result, check for

```
    if (baseType.getRawClass().equals(Concrete1.class)) 
```

will never likely match.

But overall, I don't think what you are trying to do is achievable by Jackson's in-built polymorphic handling -- you need a custom deserializer that implements intended logic. It could use Jackson annotations if that makes sense, but doesn't have to.
