### ISSUE TITLE
JsonGetter is used during Deserialization

### ISSUE THREAD

**Issue by ModProg** [FasterXML/jackson-databind#4127]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When deserializing, a method annotated with `@JsonGetter` is used by, e.g. extending the value returned by getter.

### Version Information

2.15.2

### Reproduction

While this is Kotlin code (using https://github.com/FasterXML/jackson-module-kotlin) I noticed this first in Java, but writing the reproduction is more concise in Kotlin.

```kts
@file:Repository("https://jcenter.bintray.com")
@file:DependsOn("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.2")

import com.fasterxml.jackson.annotation.JsonGetter
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue

var mapper = jacksonObjectMapper()

data class MyValue(val a: List<Int>) {
    @JsonGetter
    fun getB(): List<Int> {
        return a
    }
}

var value: MyValue = mapper.readValue("{\"a\":[1], \"b\":[2]}")

println(value); // MyValue(a=[1, 2])
```

### Expected behavior

I would expect only `a` to set the field.

**Comment by cowtowncoder** [comment]
Yes, we need a Java reproduction for `jackson-databind`.

One quick note is that this may be use of "getter-as-setter" (`MapperFeature.USE_GETTERS_AS_SETTERS`) that may be used for `Collection` values if there is no setter found.
So I'd try disabling that first to see if that helps.

But fundamentally I think this is due to discrepancy between logical properties `a` and `b` (via Creator/getter).

**Comment by ModProg** [comment]
> One quick note is that this may be use of "getter-as-setter" (`MapperFeature.USE_GETTERS_AS_SETTERS`) that may be used for `Collection` values if there is no setter found.
> So I'd try disabling that first to see if that helps.

yes, that is the issue.

I didn't expect that to be on by default, but that is probably personal preference.

**Comment by cowtowncoder** [comment]
@ModProg No I hear you -- in hindsight this feature probably should NOT be enabled. The reason it is, is due to JAXB having that feature, and some users asking for it. I always thought it wrong to modify `Collection`s accessed via getters but... at any rate, this is the current default setting.

Note that this feature is disabled by default in Jackson 3.0 (... still under work).
