### ISSUE TITLE
Support java record deserialization on Android

### ISSUE THREAD

**Issue by eranl** [FasterXML/jackson-databind#4166]
### Is your feature request related to a problem? Please describe.

On a range of Android SDK versions <34, java records are supported through desugaring. Jackson's built-in support for records doesn't work on these platforms, since the classes have a non-standard super class, and record component-related reflection methods are missing.

Serialization of records works fine with `setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)`, but deserialization fails there.

### Describe the solution you'd like

I created a Jackson module that adds automatic support for Android-desugared record deserialization, by matching constructor signatures with field types. It has one minor limitation: it doesn't allow a deserialized record to have a custom constructor with a signature that's any permutation of the canonical one's.

Can I contribute this module? How?

**Comment by cowtowncoder** [comment]
This sounds like a cool module idea; use of Fields as a work-around isn't good approach.
I think module, instead of trying to make `jackson-databind` include it, makes sense.

As to how to contribute... my initial thinking is that if build could work on JavaSE platform, module could be included as part of `jackson-modules-base`. But if specific build is needed, maybe it should be stand-alone repo.
And if/when there would be more Android-specific modules we could have multi-Maven-project repo ("jackson-modules-android"?).

But much depends on details.

**Comment by eranl** [comment]
Just posted a PR.

>... use of Fields as a work-around isn't good approach. ...

I'm curious: what did you mean by this?

**Comment by cowtowncoder** [comment]
@eranl I mean that forcing direct access to non-public fields can become problematic, compared to using accessors.
I probably should have said "relying on being able to access underlying Fields is problematic".

**Comment by eranl** [comment]
I see. The code uses field metadata, but doesn't access fields for reading/writing data.

**Comment by cowtowncoder** [comment]
Implemented via https://github.com/FasterXML/jackson-modules-base/pull/230 -- closing
