### ISSUE TITLE
BeanDeserializerModifier::updateProperties doesn't work

### ISSUE THREAD

**Issue by herkrath** [FasterXML/jackson-databind#4358]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

At least changing the order doesn't work via `BeanDeserializerModifier::updateProperties`, maybe actions like add/remove too. Returning a different order has no effect.

This issue originates from https://github.com/FasterXML/jackson-databind/discussions/4351.

### Version Information

2.16.1

### Reproduction

Explanatory unit tests are part of my PR #4359.

### Expected behavior

The order defined via the result of `BeanDeserializerModifier::updateProperties` shall define the order of the deserialization (i.e. the invoking of the deserializers and setter methods).

**Comment by cowtowncoder** [comment]
Merged (failing) tests for this.

**Comment by cowtowncoder** [comment]
Oh. I should have read this in detail -- I assumed this was about serialization order.

No, there is no expectation that deserialization order would be sorted by anything other than the order in which input is read. Otherwise there would be additional buffering for (mostly) no good reason -- buffering will be needed for multi-parameter constructors, and sometimes polymorphic handling, but not otherwise: ideally content is bound ASAP when available, in whatever order it comes in.

Will close.
