### ISSUE TITLE
Remove `MapperFeature.SORT_CREATOR_PROPERTIES_BY_DECLARATION_ORDER` from 3.0; make logic default

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4589]
### Describe your Issue

#4580 added new `MapperFeature.SORT_CREATOR_PROPERTIES_BY_DECLARATION_ORDER` to prevent alphabetic sorting from affecting order of Creator properties for serialization (in case of `MapperFeature.    SORT_CREATOR_PROPERTIES_FIRST` enabled).
This is necessary due to logic of lexicographic (~= "alphabetic") sorting which, as of 2.18, will separately sort Creator properties lexicographically too, if `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` is enabled.

But such sorting makes little sense. Instead, for 3.0, let's leave only 2 settings:

* `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` for enabling lexicographic sorting, and
* `MapperFeature.SORT_CREATOR_PROPERTIES_FIRST` for determining how Creator properties are dealt with.

Former (`SORT_PROPERTIES_ALPHABETICALLY`) will ONLY have effect if latter (`SORT_CREATOR_PROPERTIES_FIRST`) is false. If `SORT_CREATOR_PROPERTIES_FIRST` is true, Creator properties are always sorted before any other properties, in declaration order.

NOTE: above is only for handling in absence of explicit ordering by `@JsonPropertyOrder`.

**Comment by cowtowncoder** [comment]
@pjfanning Above is meant to basically change defaults to sane(r): Record/Case/Data Creator props in declaration order first; then alphabetic (lexicographic) for the rest. And with just 2 `MapperFeature`s.
Can still be improved upon but seems like an ok first step.

**Comment by JooHyukKim** [comment]
Much cleaner now.

**Comment by cowtowncoder** [comment]
@JooHyukKim no problem, I'm very familiar with this part.

**Comment by cowtowncoder** [comment]
@pjfanning @JooHyukKim It looks like this change did not cause additional breaks for master/3.0 dependencies. It should basically bring default behavior of sorting closer to 2.x (still sorts non-Creator properties lexicographically; but leaves Creator properties in declaration order, preceding other properties [unless `@JsonPropertyOrder` used, or `@JsonProperty(index=...)`])

**Comment by ML-Marco** [comment]
Am I right in understanding that in Jackson 3 it is no longer possible to sort properties in the order in which they are listed in the class file, **if** a constructor with a **different** order is present?

I came across this because some XML schema validations failed. Even when both `SORT_PROPERTIES_ALPHABETICALLY` and `SORT_CREATOR_PROPERTIES_FIRST` are disabled, the properties are still sorted according to the order defined in the constructor.

**Comment by cowtowncoder** [comment]
Jackson has never been able to reliably sort properties in declaration order, as JDK does not guarantee providing such order (plus, Fields vs Methods precedence). It never attempted to either.
Such ordering may have happened due to way things are processed, but not by design.

But no, if `SORT_CREATOR_PROPERTIES_FIRST` is disabled, constructor property declaration order is not used explicitly.
Still, in that case, order is essentially undefined; no attempt is made to determine in-class declaration order, so... order is whatever it happens to be.
But this lack of guarantee has always been there.

**Comment by ML-Marco** [comment]
Ok, I understand that the order might not be defined by the JDK and thus is unreliable. Still, this test has ensured the correct order for the last 7 years across multiple different JDKs. So although undefined, it was stable.

I'll open a separate issue because properties are indeed sorted although above mentioned features were disabled.

https://github.com/FasterXML/jackson-databind/blob/ab8664d8cdd2b57051054478133e7aeda1f795e4/src/main/java/tools/jackson/databind/introspect/POJOPropertiesCollector.java#L1806-L1809

This snippet shows that the condition evaluates to true if `_creatorProperties` is not null (which is the case when the pojo has a constructor with arguments) and `sortAlpha` is false (which is the case when `SORT_PROPERTIES_ALPHABETICALLY` is disabled).

I already confirmed this by changing the order of parameters in the constructor. The order in the resulting xml also changed.

**Comment by cowtowncoder** [comment]
Separate issue much appreciated.
