### ISSUE TITLE
No way to explicitly disable wrapping in custom annotation processor

### ISSUE THREAD

**Issue by SimonCockx** [FasterXML/jackson-databind#4595]
When upgrading from Jackson 2.15.0 to 2.17.1, we noticed our custom annotation processor stopped working due to a change in behaviour in the way `PropertyName`s are merged. See #4364. I would like to know whether this is intended, and if it is, how I should migrate my code.

We have a custom XML annotation introspector which explicitly sets the wrapper name to `Property.NO_NAME` if our custom annotation is present and the type is a list:
```
    @Override
    public PropertyName findWrapperName(Annotated ann) {
        if (ann.hasAnnotation(RosettaAttribute.class) && hasCollectionType(ann)) {
            // Disable wrapping of lists.
            return PropertyName.NO_NAME;
        }
        return super.findWrapperName(ann);
    }
```
This used to work in Jackson 2.15.

Unfortunately, due to the change in #4364, `PropertyName.NO_NAME` is now merged with `PropertyName.DEFAULT` from the default Jackson XML annotation introspector, and the new behaviour prefers `PropertyName.DEFAULT` over `PropertyName.NO_NAME`. The previous behaviour would prefer `PropertyName.NO_NAME`.

I have not found a way to fix this. Is there a way to get rid of the default annotation processor?

_Originally posted by @SimonCockx in https://github.com/FasterXML/jackson-databind/issues/4364#issuecomment-2182307781_

**Comment by cowtowncoder** [comment]
Ok, first work-arounds possible...

Logic change is in `AnnotationIntrospectorPair`, which is used when more than one introspector is to be used. To avoid its use, and merging logic, you might be able to sub-class default AnnotationIntrospector (for plain JSON it'd be `JacksonAnnotationIntrospector`, but for XML `JacksonXmlAnnotationIntrospector`), instead of registering your own.

If you do need to combine dynamically multiple `AnnotationIntrospector`s, it'd be possible to sub-class `AnnotationIntrospectorPair` but that might get complicated.
Actual merging logic is defined in `PropertyName.merg(...)`

**Comment by cowtowncoder** [comment]
But so, on possible actual fix. I think `PropertyName.merge(...)` needs to consider 2 special instances (`NO_NAME` and `USE_DEFAULT`) and return as-is, if primary value is either one.

I could make this change, although bit hesitant to do in 2.17(.2), instead of 2.18. 

But one thing that I think I would need is a test case -- could you create a unit test to show the problem? It would need to go in `jackson-dataformat-xml`, but I can take care of that part.

In the meantime, I'll create a PR to show what might work.

**Comment by cowtowncoder** [comment]
Actually, I think only `NO_NAME` should have such special semantics.

**Comment by cowtowncoder** [comment]
Created #4596 (against 2.17) with proposed fix.

**Comment by SimonCockx** [comment]
Thanks for the quick resolution! Is there an ETA for the release by any chance?

> To avoid its use, and merging logic, you might be able to sub-class default AnnotationIntrospector (for plain JSON it'd be JacksonAnnotationIntrospector, but for XML JacksonXmlAnnotationIntrospector), instead of registering your own.

How do I register my custom subclass of the default introspector? While I really have dug into the code, I have not found a way to "replace" the default, rather than registering a new one.

> But one thing that I think I would need is a test case -- could you create a unit test to show the problem? It would need to go in jackson-dataformat-xml, but I can take care of that part.

Created a test here: https://github.com/FasterXML/jackson-dataformat-xml/pull/659

**Comment by cowtowncoder** [comment]
On Mon, Jun 24, 2024 at 1:37 AM SimonCockx ***@***.***> wrote:

> Thanks for the quick resolution! Is there an ETA for the release by any
> chance?
>
> To avoid its use, and merging logic, you might be able to sub-class
> default AnnotationIntrospector (for plain JSON it'd be
> JacksonAnnotationIntrospector, but for XML
> JacksonXmlAnnotationIntrospector), instead of registering your own.
>
> How do I register my custom subclass of the default introspector? While I
> really have dug into the code, I have not found a way to
>
"replace" the default, rather than registering a new one.
>

ObjectMapper (and sub-classes) has something like
"setAnnotationIntrospector()", and I think "XmlMapper.builder()" probably
"annotationIntrospector(introspector)"


> But one thing that I think I would need is a test case -- could you create
> a unit test to show the problem? It would need to go in
> jackson-dataformat-xml, but I can take care of that part.
>
> Created a test here: FasterXML/jackson-dataformat-xml#659
> <https://github.com/FasterXML/jackson-dataformat-xml/pull/659>
>

Thank you!

-+ Tatu +-
