### ISSUE TITLE
Support for default `@JsonView` for a class

### ISSUE THREAD

**Issue by markwoon** [FasterXML/jackson-databind#507]
I'd like to be able to specify a default view for all properties of a given class that doesn't already have a view defined on it.  This would remove the need to annotate every single property.

Something along the lines of:

```
@JsonDefaultView(A.class)
public class Foo {
}
```

**Comment by tadas-subonis** [comment]
Is this expected anytime soon? at the moment it is really tedious to go and label each of the properties with their respective JsonView.

**Comment by rgoldberg** [comment]
Can `@JsonView` have `TYPE` added to its `@Target.value` so that it can be applied to types instead of adding a whole new `@JsonDefaultView` annotation? Can you add an element named `ancestors` to `@JsonView` whose type is a new `CombinationStyle` enum with values `OVERRIDE` and `UNION`? `ancestors` should default to one of these, whichever is more consistent with current behavior. You could also add a `descendants` element, also of type `CombinationStyle`. You'd have to spec out if `descendants` takes precedence over `ancestors`, or vice versa (I prefer the former).

**Comment by cowtowncoder** [comment]
@tadas-subonis I don't think anyone is working on this at the moment, so it is not known if or when this would be implemented. I'll tag this for 2.9 to at least make it so it will be evaluated as simple implementation might not be too difficult.

@rgoldberg I am not quite sure what would be functionality for this addition. Instead of (or in addition to) explaining what to add, it would make sense to explain intended behavior with an example.
It would also make sense to create a new issue instead of add that to an existing one, as it does not seem to relate to this issue directly, just happens to related to same annotation (unless I am missing something).

**Comment by cowtowncoder** [comment]
Implemented for 2.9.0 so that `@JsonView` can now be used on classes, and doing so will use said views as defaults, possibly overridden by per-property annotation as before.

**Comment by markwoon** [comment]
I've been waiting so long for this!  :)

Is 2.9 coming soon, or still months away?

**Comment by cowtowncoder** [comment]
@markwoon was hoping to get rc1 out before end of the year, but that is not to be (leaving for vacation tomorrow). That said, should get rc1 out by end of january or so. So... somewhere in between the two.

**Comment by sdeleuze** [comment]
Interesting issue, FYI this kind of need is why we had to [configure ](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L694)`MapperFeature.DEFAULT_VIEW_INCLUSION` to `false` in Spring by default, otherwise `@JsonView` is not usable easily for most non-trivial web application use cases I have seen.

@cowtowncoder Since `MapperFeature.DEFAULT_VIEW_INCLUSION` only concern non-annotated fields/properties, I guess we can expect class level `@JsonView` working as expected even with `MapperFeature.DEFAULT_VIEW_INCLUSION` set to `false` right?

**Comment by cowtowncoder** [comment]
@sdeleuze Right, so default should only apply to non-annotated properties, but would then "override" setting of `false` in a sense. Or put another way: having setting as `false would NOT prevent class annotation from taking effect.

**Comment by yugander-krishan-singh** [comment]
@cowtowncoder  I am a  bit confused about class-level @JsonView annotation.
After going throught he above discussions thread I tried the class-level @JsonView annotations. 
First, I have disabled DEFAULT_VIEW_INCLUSION in Object mapper. Now I have a class level JsonView annotation(with default view class) on my Entity class which has both annotated and non-annotated fields.

Now when I serialize my entity class by passing the default view class I am not getting the non-annotated fields of the class in the output.  
But when I enable DEFAULT_VIEW_INCLUSION again the o/p is as expected. 
It seems the class-level @JsonView annotation has no effect on the o/p. 

Pls have a look at this [stackoverflow](https://stackoverflow.com/q/55371168/6407858) question which is not exactly same but similar.

**Comment by matiasah** [comment]
@cowtowncoder couldn't @JsonDefaultView be implemented so that you can make a class always use a particular view if no view is specified for serialization. It would be different than using @JsonView on class level.

**Comment by matiasah** [comment]
The way I'm currently dealing with "hiding all the views by default" is by doing the following.
```Java
objectMapper.setConfig(objectMapper.getSerializationConfig().withView(Object.class));
```
But it would be awesome to set this property per class

**Comment by cowtowncoder** [comment]
@matiasah If you have specific new feature in mind, please file a new issue; I don't usually open old issues. I am also not quite sure why exactly a new annotation would be needed (or perhaps new setting), so you could outline expected semantics, above and beyond current use of `@JsonView`.
