### ISSUE TITLE
Differentiate a null value from an absent one in JsonDeserializer

### ISSUE THREAD

**Issue by antonbobukh** [FasterXML/jackson-databind#578]
Hi,

I have a class representing a field update:

```java
public class OptionalUpdate<T> {

    private final Optional<T> value;

    private Present(Optional<T> value) {
        this.value = value;
    }

    public boolean isPresent() {
        return value != null;
    }

    public Optional<T> getValue() {
        return value;
    }

    public static <T> OptionalUpdate<T> unset() {
        return new OptionalUpdate<>(Optional.empty());
    }

    public static <T> OptionalUpdate<T> set(T value) {
        return new OptionalUpdate<>(Optional.of(value));
    }

    public static <T> OptionalUpdate<T> empty() {
        return new OptionalUpdate<>(null);
    }

}
```

and an entity update:

```java
public class UserUpdate {

    private final OptionalUpdate<String> nickname;

    @JsonCreator
    public UserUpdate(OptionalUpdate<String> nickname) {
        this.nickname = nickname;
    }

    public OptionalUpdate<String> getNickname() {
        return nickname;
    }
    
}
```

I would like to handle three types of updates:
 1. to set a nickname to "lolcontrol":
    ```{ "nickname": "lolcontrol" }```
 2. to unset a nickname:
    ```{ "nickname": null }```
 3. not to update a nickname:
    ```{ }```

How relevant is it to add a new method to ```JsonDeserializer``` that can be overridden in the custom deserializer?
```java
/**
 * Method called to determine value to be used for absent values.
 * Usually this is same as {@link #getNullValue} (which in turn
 * is usually simply Java null), but it can be overridden
 * for types.
 *<p>
 * Default implementation simple calls {@link #getNullValue} and
 * returns value.
 */
public T getAbsentValue() {
    return getNullValue();
}
```

**Comment by cowtowncoder** [comment]
This issue is complicated, and covers multiple aspects, so I will close it. For specific aspects, let's create new issues: for example, supplying default values is one aspect; and ability to do deep-merges another.
For those there may already exist issues; but if not, I don't think this issue is a good base.

**Comment by garretwilson** [comment]
This is indeed an interesting problem. @cowtowncoder maybe you can point me to where the discussion should take place.

This becomes a more important issue when patching a resource using [JSON Merge Patch](https://tools.ietf.org/html/rfc7396). If I want to update a `FooBar` resource on the server, I can send via HTTP `PATCH`:

```json
{
  "foo": 123
}
```

This would update `FooBar.foo` on the server to 123. But what would it do with the existing `FooBar.bar` value, which might already be set to `789`? If my Java DTO object assumes that `bar` here is `null` because it is absent, it would set `FooBar.bar` to `null` on the server. But in reality I want to recognize that `bar` wasn't specified at all, so that `FooBar.bar` should remain unchanged.

Where is the best place to discuss this issue further? Thanks.

**Comment by cowtowncoder** [comment]
@garretwilson This discussion predates Jackson 2.9, which introduced ability to do full merges, see #1399. Machinery behind feature itself might be of interest.
I recommend taking discussion to `jackson-dev` list initally:

https://groups.google.com/forum/#!forum/jackson-dev

although there are couple of options for more specific follow up, like issue here, or, for new functionality:

https://github.com/FasterXML/jackson3-dev/issues

**Comment by garretwilson** [comment]
I just send a message to the jackson-dev forum. @cowtowncoder if you could please check to make sure my message wasn't marked as spam and left waiting to be approved (I think that happened once in another forum). Thanks.

**Comment by garretwilson** [comment]
Oops, sorry @cowtowncoder , I think I was looking at the wrong place in my logs. 😊 This technique may work after all; I'm seeing the other fields left as `null`, which is what I wanted. (When my message comes through on jackson-dev I'll update that as well.) Cheers.

**Comment by cowtowncoder** [comment]
@garretwilson on mailing list: yes, there is moderation flag set so the first message needs to be approved. This adds delay but has kept mailing lists spam free well.

I hope my reply there makes sense: as to "merging", it's just term I use in Jackson context to refer to the case where deserialization is more complex than just creating values out of JSON; in effect it is necessary to get existing value (if any), and only if not, then construct new POJO value.
Whether that correlates to logical merging or not is separate, but from low-level perspective that is one way to view it.
I hope this makes more sense.

**Comment by thaDude** [comment]
Hello,

I have the same requirement as OP. @cowtowncoder's suggestion to "hook" onto the setters in order to flag explicitly set values using some instance variable works nicely for de-serialisation. 

However, I am looking for a way to make this symmetric and preserve the information when serialising, i.e in terms of OP's example:

```
# Explicit null
{ "nickname": null } --> POJO with o.nicknameSet == true --> { "nickname": null }

# Missing value
{  } --> POJO with o.nicknameSet == false --> { }
```

What if any would be an approach to accomplishing this? Basically, the inclusion of a field in serialisation would depend on the value of some instance variable.

Thank you!

**Comment by amr** [comment]
I was able to hack together a quick solution for this following these steps:

1. Implement or find a type that can represent the state of absence as something different from `null`, `java.util.Optional` doesn't work here. The `Option` type from a proper functional toolkit like Fuego, Vavr or FunctionalJava fits the bill perfectly, more on that below
2. Write a custom deserializer for the chosen type

The end result seems rather clean IMHO. The following test is an example of this in action:

```
public class MissingValueTest {
  private static final ObjectMapper objectMapper = new ObjectMapper();
  private static final String lastNameUndefined = "{\"firstName\":\"John\"}";
  private static final String lastNameDefinedAsNull = "{\"firstName\": \"John\", \"lastName\": null}";

  @BeforeAll
  static void beforeAll() {
    objectMapper.registerModule(new VavrModule());
  }

  @Test
  void testUndefined() throws IOException {
    var result = objectMapper.readValue(lastNameUndefined, ProfileUpdate.class);
    assertThat(result.firstName.isDefined()).isTrue();
    assertThat(result.firstName.get()).isEqualTo("John");
    assertThat(result.lastName.isDefined()).isFalse();
  }

  @Test
  void testDefined() throws IOException {
    var result = objectMapper.readValue(lastNameDefinedAsNull, ProfileUpdate.class);
    assertThat(result.lastName.isDefined()).isTrue();
    assertThat(result.lastName.get()).isNull();
  }

  @Data
  public static class ProfileUpdate {
    private Option<String> firstName = Option.none();
    private Option<String> lastName = Option.none();
  }
}
```

The reason `Option` works is because in the functional world, a proper `Option<T>` can be of `Some(T)` or `None`, and it's perfectly valid to have `Some(null)` which denotes the presence of the value `null`. There are articles written comparing this to `java.util.Optional` behavior so no need to get into that here, but suffice to say that they do that very intentionally.

I would share code but all I have for now is a hackish demo. Thought I'd put these thoughts here in case it helps someone.
