### ISSUE TITLE
Jackson Binding Visibility Not Working 

### ISSUE THREAD

**Issue by luissantos** [FasterXML/jackson-databind#681]
Hi guys,

I would like to say that you are making an amazing job with this project.
But i found a problem when deserializing some properties that shouldnt be deserialized. 

I disabled the auto-detection but when i annotate a getter with either @JsonProperty or @JsonGetter the setter also becomes available. 
I can disable it using the @JsonIgnore annotations but it makes my code very verbose.

Is this the expected behavior? 

Please check my code example. The last should not be failling. Thanks.

https://github.com/luissantos/jackson-test

**Comment by cowtowncoder** [comment]
I will have to check to be sure, since rules are quite complicated, and in many cases try to optimize for common case (try to avoid having to add annotations for both getters and setters, for example).

**Comment by cowtowncoder** [comment]
Ok. I had a look at the test, thank you for providing it.

This is actually a feature, since Jackson 1.9: although setter/getter etc are not auto-detected, as per visibility rules, use of annotations will "pull in" the other accessors. This is meant to reduce need for additional annotations.
Since this behavior is the currently defined one, it will not be changed in near future.
To remove these accessors, you will need to add `@JsonIgnore` explicitly; or, remove `@JsonProperty` but make getters visible (as per visibility settings).
