### ISSUE TITLE
Serialization Of Polymorphic Array Failing

### ISSUE THREAD

**Issue by npraveenkumar2020** [FasterXML/jackson-databind#699]
I have enabled Polymorphic serialization support by adding annotations on the base class. I am able to seriazlize an individual object successfully and it is writing the type information as part of serialized data. However, the same is not happening if I store the objects in a list and serialize it.

It seems this issue was fixed in 1.6.3 (http://jira.codehaus.org/browse/JACKSON-362)

I am using Jackson 2.3.2 and still facing the issue.

Does somebody know how to fix this?

Code:

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY,property = "type")
    @JsonSubTypes({@Type(value = Derived.class, name = "derived")})
    public abstract class Base {

    }

    public class Derived extends Base {

        private String field;

        public String getField() {
            return field;
        }

        public void setField(String field) {
            this.field = field;
        }
       
    }

    public class Test {

        public static void main(String[] args) throws JsonProcessingException {
            ObjectMapper mapper = new  ObjectMapper();
            Derived d = new Derived();
            d.setField("Name");
            Base b = d;
            System.out.println(mapper.writeValueAsString(b));
            List<Base> list = new ArrayList<Base>();
            list.add(d);
            System.out.println(mapper.writeValueAsString(list));
        }
    }

Output:
{"type":"derived","field":"Name"}
[{"field":"Name"}]

Thanks,
Praveen

**Comment by cowtowncoder** [comment]
This is due to Java type erasure: when serializing a `List`, all Jackson see as a type is `List<?>` (roughly equivalent to `List<Object>`). And since type `Object` does not have polymorphic type information (annotation), none will be written.
So this is not a bug in Jackson, but an unfortunate feature of Java Type Erasure.
It does not apply to arrays, since they retain element type information (arrays are not generic; arrays of different types are different classes, whereas generic typing is mostly compile-time syntactic sugar).

There are three main ways to deal with this:

* pass full generic type using `TypeReference` (`ObjectMapper` has method like `mapper.writerFor(new TypeReference<List<Base>>() { }).writeValue(....)`
* Sub-class `List` to something like `public class BaseList extends ArrayList<Base>() { }`, and pass that: this type WILL retain type information
* Avoid using root-level `List` and `Maps`

I personally recommend doing (3), since this avoids all related problems with type erasure.
In my opinion JSON root value should always be a JSON Object, usually serialized to/from POJO.

Approach (2) will however work, and this is what most users do. It does require use of an additional helper class.

Approach (1) may or may not work; problem being that forcing type information does also affect actual value serialization. So while it will add type id, it may result in some properties not being serialized.

**Comment by npraveenkumar2020** [comment]
Thank you for the detailed explanation :-)

**Comment by UtopianStorm** [comment]
I don't understand this answer and I've seen it used several places.
It's not the list that contains the type information and thus Jackson should not care.
I mean what you're receiving is a list of items, and the type information is present on the items, not the list, so whether the list is victim of type erasure or not is irrelevant, isn't it?

To me the go to implementation to serialise a list, would be to iterate over the elements of the list and for each of those convert those to json. The fact that List<SomeType> shows up something like List<?> really shouldn't matter, because the elements contained within are the same, and their type information is intact.

However this is rookie stuff, so I assume you're not making that mistake here, and that it is instead me who has failed to grasp something in either the problem or the answer.
Any clarification would be greatly appreciated.

**Comment by cowtowncoder** [comment]
@UtopianStorm Type information of the `List` is highly relevant because there are two separate but related types that Jackson uses

1. Full type of value to use for serialization -- so that all fields of all subtypes do get serialized. Only available during serialization
2. Base type for polymorphic types: this is the static type needed to find out if and how polymorphic information is included. While this is mostly relevant for deserialization (when no other type information is available), serialization must also consider this to make sure base type matches, to allow deserialization to work

Type (1) will indeed be taken from actual items (unless static typing is defined, in which case only static type, that is (2), is used for contents), but type (2) does come from type declaration. This is accurate for properties derived from class declarations, but is NOT typically available for root types.

This means that if a `List` is passed as is, what Jackson sees for elements is:

1. Full type X for items,
2. Base type of `?`, which translates to `java.lang.Object`

from this, check is made to see if `Object` is declared as a polymorphic type. Typically it is not, although via mix-ins and "default typing" this may be changed.

Due to this complexity, the best advice I can give is this: NEVER serialize `Map` or `Collection` types directly. Always use a wrapper POJO.

**Comment by UtopianStorm** [comment]
This still does not make sense to me.

Serialising a list to json quite literally amounts to: [ content ]
So when you're given a list of elements to serialise you could push [, followed by serialising every item for itself; to which you have all the information you need, and everything else you can look up through reflection, the fact that it was ever stored in a list really doesn't matter; terminated by pushing ].

The following cannot be what you're doing, right?
    SomeSuperType superTypeObject = new SomeSubType();
    Object object = superTypeObject;
So if I try to serialise superTypeObject you will try to serialise it as SomeSuperType, but if I try to serialise the same object, you would try to serialise it as Object. Is this the sort of thing, you are doing?

I would think of it as a gross oversight to let *that* be the "default" where as the other much simpler - much more intuitive - way of serialising the object is not even supported.
You will quite often be without the type information in the above example and it is not something one would want to rely on. Also being able to serialise an object as different polymorphic types I would expect to only be something < 1% of your users would be doing.

The thing is I have a list of elements, and the only thing they need for their polymorphic types to work is a simple field of text describing their subtype to be serialised together with them, for which all the information needed is present on the type of the elements and always will be present during serialisation - with or without type erasure.
But I cannot do this, because the framework chooses not to bundle that string with my elements <- it has absolutely no reason not to include it, when it has access to it.

**Comment by cowtowncoder** [comment]
@UtopianStorm You do not understand it since you do not seem to bother reading what I wrote.
At this point I have spent enough time explaining same thing over and over; this at point where code works exactly as I want it to, and expect it to work.

If you truly want to decipher the meaning, try the thought exercise of both serializing AND deserializing content and see how type information must be handled. Handling is anything but simple, except by those who have not had to actually implement a working solution.

**Comment by UtopianStorm** [comment]
Deserialisation is another proces, it is independent of the serialisation.
The deserialisation is independent of what ever context was available at serialisation, its only dependency is the data.

I appreciate you trying to explain it, but I was not able to understand it entirely. Whether that is a fault of mine or yours I will let go undecided.

Are you going to remedy this implementation scheme in a future version?

**Comment by cowtowncoder** [comment]
No plans, as things are working the way I think they should.

That said, I am open to improvements via Pull Requests, with explanation of change and what it tries to achieve.
