### ISSUE TITLE
Support conversion of JDBC ResultSet to JSON

### ISSUE THREAD

**Issue by rhwood** [FasterXML/jackson-databind#717]
I would find it useful to be able to convert a JDBC ResultSet to JSON.

See http://jira.codehaus.org/browse/JACKSON-809 for earlier, similar request.

**Comment by eiden** [comment]
:+1: 

The codehaus issue tracker has been shut down. Here is a copy of the original jira issue:

## Description

This has come up on the list before
http://markmail.org/message/2jcqzbdcl2qvg7a2

but it'd be very handy to be able to convert a JDBC ResultSet to a JSON POJO using the Jackson ObjectMapper stuff, so folks could easily stream JDBC ResultSets as JSON/XML from JAXRS resources. Might be nice to have folks use Jackson and Brian's jDBI together etc.

Extra beer tokens, if Jackson could convert a ResultSet into a (lazy) List<MyPojo> so that folks can use Guava/Java8/Scala/Groovy/Kotlin map/filter stuff on the result set beans first before rendering the JSON.

## Comments 

**Tatu Saloranta added a comment - 16/Mar/12 1:26 PM**
> I have occasionally played with the idea of creating a JsonReader for reading over ResultSet; perhaps somewhat similar to how Jackson CSV module works. One practical challenge is that of mapping names, as JDBC is generally case-insensitive; and Jackson expects fairly rigid name mapping.

> But other than that, it seems like a simpleish thing to do – so maybe I should just go ahead and create a github project for this.

> Jackson and jDBI are indeed commonly used together, and thanks to DropWizard, maybe even more so in future.
 
**Tatu Saloranta added a comment - 16/Mar/12 1:27 PM**
> Oh and thanks for suggesting this: I prefer working on things others suggest, to avoid speculative coding. 

**Tatu Saloranta added a comment - 05/Feb/13 10:52 AM**
> Hmmh. This would seem to like a nice extension module... but there's no good place for "let's write a new module".
> Will probably move to jackson-databind issues soon.

**Tatu Saloranta added a comment - 16/Oct/13 11:50 PM**
> Starting to close down issue tracker here: the idea may still be valid, and can re-file at github if there is still interest.

Created:
15/Mar/12 1:27 AM
Updated:
16/Oct/13 11:50 PM
Resolved:
16/Oct/13 11:50 PM

**Comment by cowtowncoder** [comment]
Since this is basically requesting a datatype module for JDBC types, I re-created it at even more suitable place:

https://github.com/FasterXML/jackson/issues/28
