### ISSUE TITLE
Json deserialization with empty array failed

### ISSUE THREAD

**Issue by agonist** [FasterXML/jackson-databind#718]
I try to deserialize the JSON I received from my api :  
```
{"name":"toto","documents": [], "city":"somewhere","bar": {"test" : "value", "other" : "hello"}}
```

but the "documents": []  seems to cause some problems. I've made a little test class

here the complete code https://gist.github.com/agonist/c11e91e2071f5f2c11bf#file-deserializertest

if I let the JSON like that it's not working, but if I replace it with : 

```
{"name":"toto","documents": "[]", "city":"somewhere","bar": {"test" : "value", "other" : "hello"}}
```

it works. The only things is that my web service return the first version.
So i'd like to know if this is a bug or not ?
Cause I was thinking DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT can solve the problem. But apparently not.

Thank's

**Comment by cowtowncoder** [comment]
So what is the problem in this case. What is not working?

**Comment by agonist** [comment]
The deserialization stop when it come to  "documents": [], there is no error or exception, for example in : 
```
{"name":"toto","documents": [], "city":"somewhere","bar": {"test" : "value", "other" : "hello"}}
```
it return my object only with the name.
in : 
```
{"name":"toto", "city":"somewhere","bar": {"test" : "value", "other" : "hello"}, "documents": []}
```
it return the object with name, city, bar cause documents is the last field to be deserialized.
So the deserialization stop when it come to document

**Comment by cowtowncoder** [comment]
Ok that does sound like a bug. Maybe I can see what gives.

I assume this is with 2.5.1?

**Comment by agonist** [comment]
Yes 2.5.1, and thank's

**Comment by cowtowncoder** [comment]
Actually, your deserializers do not look right: they are not consuming value tokens they should.
I'll have a look to see if that is the root cause, as well as if there is a way to improve on error detection.
However, in general, if using custom (de)serializers, there isn't much core databinding can do to enforce limits (since custom code can traverse token stream any way it wants to). So there is inherent risk there.
But I hope there are ways to make things fail in more transparent fashion.

**Comment by cowtowncoder** [comment]
Ah. Also: since you disable `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`, you are not getting exceptions you would be to indicate mismatch. So this, in combination with do-nothing deserializers is likely causing the issues here.

I usually do not disable `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` for this reason unless I really know it is needed. It can hide all kinds of issues easily.

**Comment by cowtowncoder** [comment]
So. To fix this, I recommend you first leave `FAIL_ON_UNKNOWN_PROPERTIES` enabled to see where problems occur. Second, work on deserializers so that they consume all tokens that they are responsible for -- this means either a single token (for scalars), or single structured value (Object, Array).
You should NOT need to override List/array deserializers, since the default handlers should work; but if you do, you must handle delegation approriately.

**Comment by agonist** [comment]
okay thank you for the precisions, I will take a look at it.
The reason why I override ListProperty and ObservableList deserializer is cause I use JavaFX and jackson tell me that it don't know how to deserialize ListProperty

**Comment by cowtowncoder** [comment]
Without knowing definition of `ListProperty` it is difficult to say if it can be configured; but it may be necessary to have a custom deserializer. If so, it just has to work the way (custom) deserializers are expected to, with respect to handling of value that `JsonParser` points to; it must be fully consumed up to the last token. For scalar values this is easy, as `JsonParser` already points to token so no advancement is needed. But for Array/Object values stream must be read up to and including matching END_OBJECT/END_ARRAY.

**Comment by agonist** [comment]
I updated my list custom deserializer for consuming token and it's now working ! so thank's for your help. btw maybe it could be nice to add ListProperty support in jackson

**Comment by cowtowncoder** [comment]
Where does `ListProperty` come from? Core databind can only support JDK types; but there are many datatype-modules for supporting types of 3rd party libraries (Guava, Joda, HPPC, Hibernate, JDK8 date types etc etc).

**Comment by agonist** [comment]
It come  from jdk since java 8. Since javafx is included in jdk. You have listproperty, map property and some more

**Comment by cowtowncoder** [comment]
Ah. So this could fit in here:

https://github.com/FasterXML/jackson-datatype-jdk8

(baseline for Jackson core is Java6 -- there are modules for jdk7 and jdk8 add-ons).

Could you file an issue for that project? Of course Pull Requests are accepted too, but filing an issue would be a good way to improve chances of support getting added.

**Comment by agonist** [comment]
Done ! I'll try to do PR if I have time :)  anyway thank's for all your precisions, very helpful
