### ISSUE TITLE
Add support for serializing HttpServletRequestSerializer and HttpServletResponseSerializer (datatype module for Servlet API types)

### ISSUE THREAD

**Issue by cemo** [FasterXML/jackson-databind#721]
I have noticed that a few libraries need a Serializer for HttpServletRequest and HttpServletResponse. Do you think that It is worth to implement? It might be used by Logback, Spring and Dropwizard as well. Any chance for it?

**Comment by cowtowncoder** [comment]
That would belong to something like `jackson-datatype-servlet` package, since we try to keep core 
dependencies minimal (and these are part of servlet api). Or, if there was bigger aspect to cover, some more general-purpose module perhaps.

How are these types handled in cases you mention? They are not really data types as much as sources/destinations, so what is the use case?
I guess they could be serialized for supporting something like asynchronous requests, or proxying requests/responses.

**Comment by cemo** [comment]
I am considering to increase readability for loggings especially. 

Use cases:

1. Spring Boot is has a trace endpoint. This endpoint providing request and response information as a human readable format.
2. Jersey has a [LoggingFilter]. There might be something similar to it relies on Jackson.
3. Logback access might use it. Request Logs can be easily parsed in a JSON Structure. There also custom appenders such as Logstash Appenders which are good candidates to use it.

In my use case, I have a Logback Filter which is adding Request Information inside log entry which is also JSON. I can easily find culprit or replicate exception by request information. This is important in many situations. 
  
[LoggingFilter]: https://github.com/jersey/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/filter/LoggingFilter.java

**Comment by cowtowncoder** [comment]
Ok, so primarily for diagnostics, and not as part of data processing. Gotcha.

If anyone is interested in writing a simple datatype module (jackson-datatype-servlet[-api]?), I'd be happy to help. I don't think I have current need myself but others may well have. So I'll leave this issue open for anyone interested.

**Comment by cowtowncoder** [comment]
Bit of re-organizing: I think a better place for ideas for new Jackson components is main `jackson` portal. Hence:

https://github.com/FasterXML/jackson/issues/29
