### ISSUE TITLE
Duplicate property produced

### ISSUE THREAD

**Issue by simopete** [FasterXML/jackson-databind#729]
Hi there, 
I made a simple class with a `@JsonProperty` annotated private field named eSenseValues. The field has getter method named getESenseValues(). 
When I have serialized this class the json output had this field/property twice.
I think, it's a bug.

Here is my class and the json output:
```java
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;

public class WaveValues implements Serializable {

    @JsonProperty(value = "ESenseValues")
    private ESenseValues eSenseValues;

    public WaveValues() {
    }

    public ESenseValues getESenseValues() {
        return eSenseValues;
    }
}
```

```json
{
  "WaveValues" : {
    "esenseValues" : {
      "attention" : 0,
      "meditation" : 0
    },
    "ESenseValues" : {
      "attention" : 0,
      "meditation" : 0
    }
  }
}
```

**Comment by cowtowncoder** [comment]
Ok. This is caused by Jackson's name discovery, which by default considers `getESenseValues()` to mean existence of property `esenseValues`. This is different from Java Bean introspection which would instead infer `ESenseValues`. With Java Bean name handling, you would only get a single property as you expect.

Jackson 2.5 did add `MapperFeature.USE_STD_BEAN_NAMING`, enabling of which gets handling you want. It is disabled by default for backwards-compatibility reasons.

Another alternative (and only choice if you are using an earlier version) would be to annotate getter with `@JsonProperty` as well; if so, field and getter would be properly coupled.

**Comment by simopete** [comment]
Thanks for your answer! I now understand the difference between Jackson and JavaBean serialization. 
Before I wrote this issue I have looked at the wiki pages, but this feature isn't noted. 
Can you write about it to the MapperFeature's wiki page or should I?

**Comment by cowtowncoder** [comment]
@simopete I can add that to Jackson github wiki page -- thank you for pointing it out. Feel free to send PRs for updates, fixes too of course, but I can take care of this one now.

**Comment by simopete** [comment]
Thank you for your work! I read the wiki again! It's good :+1:
