### ISSUE TITLE
@JsonInclude(Include.NON_NULL) is not working while custom serializers are regiestered

### ISSUE THREAD

**Issue by jmayday** [FasterXML/jackson-databind#730]
There is something wrong with way @JsonInclude annotations are handled. It seems like when custom serializers are attached to modules we register then @JsonInclude(Include.NON_NULL) or setSerializationIncludsion(Include.NON_EMPTY) means nothing. 

My requirement is to not serialize keys for which values are null. I also want to trim string values to null (that's why I created custom serializer which extends StdScalarSerializer). 

Example input object of type let's say MyClass:
	
	- name: "nameOfObj1"
	- producerName: "PROD CORP.     " 
	- notes: "      " 

Expected output:
	
	{
	    "name" : "nameOfObj1",
	    "producerName" : "PROD CORP."
	}

I can't get this working with Include.NON_NULL having my module with custom serializers added. Serializer itself works just fine and looks like this:

	 public class MyCustomStringSerializer extends StdScalarSerializer<String> {
	
	
		protected MyCustomStringSerializer () {
			super(String.class);
		}
	
		@Override
		public void serialize(String value, JsonGenerator jgen,
				SerializerProvider provider) throws IOException,
				JsonGenerationException {
			String trimmedValue = StringUtils.trim(value);
			if(StringUtils.isEmpty(trimmedValue)) {
				jgen.writeNull();			
				}
			else {
				jgen.writeString(trimmedValue);
			}
		}
	}

This is my object mapper where I register custom modules/serializers:

	public class MyCustomObjectMapper extends ObjectMapper {
		
		private static final long serialVersionUID = 8125249677131844836L;

		public MyCustomObjectMapper() {
			registerModule(new MyModule());
			setSerializationInclusion(Include.NON_EMPTY);
		}
		
		class MyModule extends SimpleModule {

			private static final long serialVersionUID = 3012609212894483368L;

			public MyModule() {
				addSerializer(String.class, new MyCustomStringSerializer());
			}
		}
	}

Using this approach I will get not exactly what I want:
	
	{
	    "name" : "nameOfObj1",
	    "producerName" : "PROD CORP."
	    "notes" : null
	}

There is a workaround of course. I can use some kind of mapper which will take over the work MyCustomStringSerializer currently does. The output from this mapper would be an object having all String values trimmed to nulls. Then I don't have to register any custom modules in ObjectMapper because all the work has been done. I can rely on @JsonInclude(Include.NON_NULL) annotation on serialized object class or I can set this setting globally with setSerializationIncludsion(Include.NON_EMPTY) in MyCustomOjbectMapper constructor. With such workaround I get what I want. How to achieve t with @JsonInclude annotation ?

I used NON_NULL and NOT_EMPTY interchangeably but I think for String values these annotations mean the same thing. 

Jackson version: 2.5.1

**Comment by cowtowncoder** [comment]
For custom definition of what `empty` means, your `JsonSerializer` implementation needs to override this method:

```json
public boolean isEmpty(SerializerProvider provider, T value);
```

Note that it is the caller that has to handle filtering as it writes field name; serializer will only be called in case actual serialization is needed.

**Comment by jmayday** [comment]
With overridden isEmpty() everything works fine. Somehow I've overseen this method. Thanks for quick response @cowtowncoder

**Comment by cowtowncoder** [comment]
@jmayday No prob, it is somewhat counter-intuitive due to delegation model (which itself is due to requirements of generator etc etc).

**Comment by ilooch** [comment]
@cowtowncoder 
How can I implement this on Jackson 2.2 ?
The method did not work.
`public boolean isEmpty(value);`

Thanks

**Comment by cowtowncoder** [comment]
@ilooch Jackson 2.2 has not been supported for long time (last release 3 years ago) so it is unlikely to work.

**Comment by ilooch** [comment]
@cowtowncoder 
I had update to the latest version, it worked now.
Thanks.

**Comment by andrickd** [comment]
@cowtowncoder 
Piggy backing here, sorry to use an old thread but it seems best for anyone else searching for this question to keep it here since this thread popped up for me.

What is the intended strategy to get `@JsonInclude(JsonInclude.Include.NON_NULL)` to function with a custom implementation of `StdSerializer`? I understand why EMPY would require developer intervention, but null is null, but then again maybe I'm missing something.

The version in question is 2.8.5.

Thanks!

**Comment by cowtowncoder** [comment]
@andrickd Typically `NON_NULL` should work without additional support as it is checked by whatever is including value of property (parent serializer) so most likely `BeanSerializer`. At least for simpler types.

If you are implementing a composite type with properties of its own things get more complicated (of course :) ).
You could see `MapSerializer` or `BeanSerializer` for example (or perhaps `ReferenceTypeSerializer`... not sure of name).

So what kind of custom type are we talking about here?

**Comment by andrickd** [comment]
@cowtowncoder 
Thank you for the quick response. I'm going to spend some time reviewing the code in the suggestions you referenced here, but to answer your question, I was attempting to throw together a simple proof of concept before moving to a more complicated use case. The POC implemented an instance of `StdSerializer` that was associated with a simple POJO with the `@JsonSerializer(using)` annotation.

My custom serializer was correctly found at runtime, and all of the non-complex fields, almost all `String`, with a handful of `boolean`, were directly written using the `JsonGenerator` while a few Maps were written using the generator's associated `ObjectMapper` / `codec` due to the nature of the problem I'm solving being directly interested in only the `String` values.

When serializing this way, everything worked as expected except for the aforementioned include directive against NULL values - my naive assumption here was simply that some form of processing during the generator write would be applied based on such directives, but some sleuthing online did not turn up any detail-filled examples once that proved false. Thankfully my searching did turn up this thread! In the interim, I simply did the easy thing, I did the null checks manually before writing a field.

**Comment by cowtowncoder** [comment]
@andrickd Ah. I think that based on what you are saying, one reason inclusion filtering was not working could be due to Jackson 2.x not being able to use same configuration of `SerializerProvider` instance when using `JsonGenerator.writeObject()` call. If so, one simple improvement would be to instead try calling methods in `SerializerProvider` which should work bit better.
Even better would be fetching serializer instance(s) to delegate to in `createContextual()` method (when implementing `ContextualSerializer`), which would further apply contextual annotations (ones from property).
It all depends on how much of full functionality needs to be supported.

**Comment by andrickd** [comment]
@cowtowncoder 
Simply calling the `SerializerProvider.defaultSerializeField` in place of `JsonGenerator.writeStringField` does not appear to do the job, at least with a quick unit test run. I'll need to experiment with `implements ContextualSerializer` as following a quick look at the Java doc, it is not immediately obvious to me what I might do there to help me with this problem.

I may just have to do an old fashioned step through and read more source to attempt to understand where my problem lies... if I can find the time to do so.

I greatly appreciate you trying to point me in the right direction, you've been helpful!

**Comment by cowtowncoder** [comment]
@andrickd Ok sorry: for simple String it does not change the way value serializer works (except for `@JsonFormat` handling); this would be relevant mostly for structured type serializers (POJOs, Maps, Collections).

However: the whole inclusion filtering is handled by whatever calls these serializers. So if you delegate, yes, that serializer has to handle filtering out of values: delegate/child serializer must simply write out value when requested to do so.
This is partly due to the common case of property value where in field name must be output by that "parent" serializer, so it has to decided for name/value pair, before delegating.

`JsonGenerator.writeStringField()` in particular simply outputs field name, name, and has no concept of anything going on at databind level. Maybe javadoc should be improved to make this clear.

**Comment by andrickd** [comment]
@cowtowncoder 
I don't have a problem directly analyzing any `@JsonInclude` annotations during serialization if that is the way to go in this particular instance. It sort of feels like we've gotten to the bottom of something here, so that is good 👍

**Comment by cowtowncoder** [comment]
@andrickd You should not have to check for annotations yourself, but would need to access information gathered from those and other sources (global defaults, config overrides). However, the system is designed to gather this information for `BeanSerializer` and is mostly accessible through property objects (`BeanProperty` or `BeanPropertyWriter`). So if you are essentially implementing something that is similar to Bean/POJO handling it can become quite a bit of work: if so, having a look at `BeanSerializer` (and its case class... `BeanSerializerBase`?) would be helpful.

**Comment by andrickd** [comment]
@cowtowncoder 
Yep, I'm on the same page here, I don't mean literally pulling it off via reflection or something myself. I'm going to be going the path you suggest here.

**Comment by cowtowncoder** [comment]
@andrickd ok good. Just thought I'd mention. :)
