### ISSUE TITLE
Possibly change <?> generics in BeanSerializerModifier modify*Serializer methods

### ISSUE THREAD

**Issue by rgoldberg** [FasterXML/jackson-databind#759]
In `BeanSerializerModifier`, it might be useful to change the `<?>` generics to be bounded.

I assume that any `JsonSerializer` returned by any `modify*Serializer` method should be able to handle any class that can be handled by the `JsonSerializer` that is passed in as an argument to the `modify*Serializer` method.

If my assumption is incorrect, please let me know why.

If my assumption is correct, then changing the generics would:

 1. indicate the relationship between the argument `JsonSerializer` & the returned `JsonSerializer`
 2. enforce the relationship in compile-time checks.
 3. eliminate explicit casts in the body of `modify*Serializer`

e.g., could:

    JsonSerializer<?> modifySerializer(SerializationConfig sc, BeanDescription bd, JsonSerializer<?> js)

be changed to:

    <T> JsonSerializer<T> modifySerializer(SerializationConfig sc, BeanDescription bd, JsonSerializer<? extends T> js)

And, e.g., could:

    JsonSerializer<?> modifyCollectionSerializer(SerializationConfig sc, CollectionType ct, BeanDescription bd, JsonSerializer<?> js)

be changed to:

    <T> JsonSerializer<T> modifyCollectionSerializer(SerializationConfig sc, CollectionType ct, BeanDescription bd, JsonSerializer<? extends T> js)

**Comment by cowtowncoder** [comment]
Your assumption is correct in that such constraint should hold, and so theoretically change is possible.

However, while using appropriate generic constraints is often helpful, I have found that within interfaces like this one it tends not to have many benefits yet lead to lots of casting.
This because caller (core databind functionality) rarely if ever has proper parameterization available, and ends up having to essentially provide `JsonSerializer<?>` (or, `JsonSerializer<Object>`) anyway.
There is little upside because nothing will be enforced or detected during runtime at the point when method is called.

Do you have a specific use case in mind where this would be helpful? Or is this more an open-ended question on why parameterization was left loose here?

**Comment by rgoldberg** [comment]
It's open-ended.  I implemented a BeanSerializerModifier, and noticed that, from the BeanSerializerModifier implementation side (not from the side of the Jackson code that calls methods on the BeanSerializerModifier), the generics could have been bounded, providing the benefits mentioned in the original issue description.  If they would make the Jackson side of things too complex, the bounds can be left out.

**Comment by cowtowncoder** [comment]
Right, I can see how it could be helpful on modifier implementation. Unfortunately it does complicate things on databind side due to lack of type safety throughout registrations.
I hope explanation makes sense -- will close the issue.
