### ISSUE TITLE
Is SimpleType.withStaticTyping() correct?

### ISSUE THREAD

**Issue by tm2git** [FasterXML/jackson-databind#765]
In line 158 it passes the existing _asStatic value to the constructor for the new instance;  I'm guessing that should really be the constant true.

(I was trying to figure out why neither of the suggested workarounds in #749  has any effect, and happened to notice this while single-stepping;  dunno whether it's related or not).

**Comment by cowtowncoder** [comment]
You are absolutely right, it's a bug. Thank you for reporting this -- I don't know if it is causing any known problems, but obviously it prevents desired behavior.

Given that there could still be unexpected side effects, I will fix this in master (for 2.6.0), and not yet 2.5.x.
This is just because it could affect handling of JAX-RS endpoints. If there are specific problems to fix, I can backport the fix.
