### ISSUE TITLE
Allow injection of 'transient' fields

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#77]
(note: moved from http://jira.codehaus.org/browse/JACKSON-817)

Due to the way Jackson property introspection works, transient fields are ignored and one can not use @JacksonInject for them.
However, it would be nice to be able to do that, since while such fields should not be serialized, it would make sense to be able to inject values for them during deserialization. This may require some changes to property discovery.

**Comment by licarth** [comment]
I guess a workaround for this is to create a @JsonCreator annotated constructor and pass as parameter the field that needs to be injected. 

instead of :
```java
public class Entity{
   @JacksonInject
   private transient Object toBeInjected;
}
```
(@JacksonInject will be ignored in code above)
rather do :
```java
public class Entity{
    private transient Object toBeInjected;

    @JsonCreator
    public Entity(@JacksonInject Object toBeInjected){
        this.toBeInjected = toBeInjected;
    }
}
```
The field itself can remain transient, and will be injected thanks to the @JsonCreator constructor.

**Comment by cowtowncoder** [comment]
Looks like work for #296 allows fixing this, finally.
