### ISSUE TITLE
Add `ObjectMapper setFilterProvider(FilterProvider)` to allow chaining (and deprecate `setFilters(...)`)

### ISSUE THREAD

**Issue by rgoldberg** [FasterXML/jackson-databind#787]
`ObjectMapper.setFilters(FilterProvider)` returns `void`

Can you make it fluent and return `this` `ObjectMapper` instead?

If you don't want to change the return type, you could add the following new method instead:

    public ObjectMapper setFilterProvider(FilterProvider)

**Comment by cowtowncoder** [comment]
It would have made sense when this was added, but unfortunately at this point it can not be changed without breaking binary compatibility -- since return type is part of the method signature, code compiled against current version would have with linkage error if such change was made (Jackson 1.0 -> 1.1 had one such problem, leading to nasty compatibility issues with Hadoop).

But adding a new method makes sense, and then deprecating old one.
I can do that; thank you for suggestion!

**Comment by rgoldberg** [comment]
Thank's for the update, and for Jackson in general.

**Comment by cowtowncoder** [comment]
You are welcome!
