### ISSUE TITLE
UntypedObjectDeserializer.Vanilla not handling xml sequences (same tags) correctly

### ISSUE THREAD

**Issue by Antibrumm** [FasterXML/jackson-databind#799]
I don't know if this applies also for deserializing a json message, but by using the `XmlMapper` the resulting Map does only contain the last child node in case there are some `maxOccurence="unbounded" elements.

The reason seems to be that the `Vanilla` implementation just uses `result.put(key,value)` instead of checking if there already exists an entry. 

I was able to get the expected result by modifying the method `mapObject(JsonParser jp, DeserializationContext ctxt)` and replacing all 'result.put' with an `addValue` delegate which looks like this:

    private void addValue(Map<String, Object> result, String fieldName, Object value) {
                if (!result.containsKey(fieldName)) {
                    result.put(fieldName, value);
                } else {
                    Object existing = result.get(fieldName);
                    if (existing instanceof List) {
                        ((List) existing).add(value);
                    } else {
                        List list = new ArrayList();
                        list.add(existing);
                        list.add(value);
                        result.put(fieldName, list);
                    }
                }
            }

I could provide a pull request if this is considered a bug/improvement and is desired.

**Comment by cowtowncoder** [comment]
Good question. Such logic, if it was to be added, would have to be added just for `XmlMapper`, and not for general databind, since it is an XMLism.

I am not sure if this should be done at all, because this leads to a very common problem with XML: deep difference between handling of a single element (value) and two or more elements (List/array).

Then again, I agree in that just including last (or first) value is not necessary very useful either.

So... could you re-file this for `jackson-dataformat-xml`? Sorry to ask for this, but I am not aware of Gitub feature to do such move myself.

**Comment by Antibrumm** [comment]
Sure, Just done that :) Let me know if i can help.
