### ISSUE TITLE
WRITE_BIGDECIMAL_AS_PLAIN is being ignored in Jackson 2.5.3

### ISSUE THREAD

**Issue by mikalveli** [FasterXML/jackson-databind#842]
This is similar to issue https://github.com/FasterXML/jackson-databind/issues/251, which states the problem has been resolved. 

If I execute the following code:

```java
ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN); 
Map<String, BigDecimal> m = new HashMap<String, BigDecimal>(); 
m.put("test", BigDecimal.valueOf(0.0000000005)); 
System.out.println(mapper.valueToTree(m).toString());
```

The output is:

```json
{"test":5E-10}
```

The desired output is:

```json
{"test":0.0000000005}
```

**Comment by cowtowncoder** [comment]
Hmmh. Not sure what to think of this one, given that it is not about serialization but conversions.
Since code is using `Map.toString()`, it does not go through serialization, and there is no guarantee that this should work.

But I will consider it an improvement idea to try to make conversion force normalization.
Right now `SerializationFeature` is really only guaranteed to work with actual serialization calls.
That is to say, if you did `mapper.writeValueAsString(mapper.valueToTree(m))`, that should produce expected output.

**Comment by mikalveli** [comment]
Ok Interesting. I'm actually looking at this while using Play Framework 2.4. They wrap Ajax with a Json class on the Java side. I verified your suggestion works and prints the expected result.

Here is an example of what worked:

```java
ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN); 
Map<String, BigDecimal> m = new HashMap<>(); 
m.put("test", BigDecimal.valueOf(0.0000000005)); 
System.out.println(mapper.writeValueAsString(mapper.valueToTree(m));
```

However, even though I am setting this value in Play's Object Mapper, I still get the unexpected value. So it looks like there may be a bug in the way they are serializing to a String in Play. Here is a sample to trigger the issue:

```java
ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN);
Json.setObjectMapper(mapper);
Map<String, BigDecimal> m = new HashMap<>(); 
m.put("test", BigDecimal.valueOf(0.0000000005)); 
System.out.println(Json.stringify(Json.toJson(m)));
```

I get this output:

```json
{"test":5E-10}
```

Looking inside of Play's Stringify function, I see it is eventually creating a generator based on the Object Mapper. But this is obviously not using the given object mapper to serialize the data since it is ignoring the setting for BIG_DECIMAL. Here is the relevant code:

```java
StringWriter sw = new StringWriter();
JsonGenerator jgen = new JsonFactory(mapper()).createGenerator(sw);
// Removed for clarity
mapper().writeValue(jgen, o);
sw.flush();
return sw.toString();
```

It appears Play either has a bug in how they are using Jackson or there is maybe a bug in Jackson. Let me know what you think and I'll report it with them if necessary.

Thanks

**Comment by cowtowncoder** [comment]
Hmmh. That code is quite convoluted in Play. They really should just do:

    mapper().writeValueAsString(o);

although that's not, strictly speaking, a bug. Although if `mapper()` creates a new instance, it's a significant performance drain.
I would actually suggest filing a simple RFE or pull request for simpliciation: it is possible that manual construction of `JsonGenerator` may cause lack of conversion, since the assumption is that when an explicitly configured parser or generator is given, its settings have been specified exactly, and thereby overrides may not be applied.

**Comment by mikalveli** [comment]
The mapper() function reuses the same ObjectMapper once one has been created. I will chat with the folks at play and see if we can't get it fixed. Thank you for the help and quick responses!

**Comment by cowtowncoder** [comment]
Ok good. Figured it might be, but always good to verify!

I'll also add a test to see how `convertValue()` behaves, just for my own knowledge, as well.

**Comment by cowtowncoder** [comment]
Ok: just to close the loop here -- `convertValue()` does nothing for `BigDecimal`, for the simple reason that to create a plain version one needs to call "BigDecimal.toPlainString()` -- this is not a property of `BigDecimal` value, but of its String representation. And since `TokenBuffer` retains value as object, not String, it can't really do anything; actual serialization is needed.
This should not matter wrt Play use case, but I thought I will mention it in case someone searches for this issue.
