### ISSUE TITLE
Long/Float serialization and type information

### ISSUE THREAD

**Issue by Conaclos** [FasterXML/jackson-databind#846]
Hi!

I am using Jackson 2.5.4

When I use type information feature, I obtain "strange" serialization results for generic class with Long or Float as effective generic parameter. Indeed, I obtain an array with 2 items. The first item is the type and the second one the value.

```Java
mapper = new ObjectMapper().enableDefaultTyping(
  ObjectMapper.DefaultTyping.NON_FINAL, 
  JsonTypeInfo.As.PROPERTY);

mapper.writeValueAsString(new Tuple1<>(Long.valueOf(1)));
//
// {"@class": "mypackage.Tuple1", item1: ["java.lang.Long",1]}
//
```
Tuple1 fits the next interface:
```Java
interface Tuple1Interface<T extends Serializable> {
  public T getItem1();
}
```

It is not an expected result...

Thanks.

**Comment by cowtowncoder** [comment]
This works as expected, due to combination of two things.

First, thanks to Java type erasure, runtime type of `Tuple1<Long>` can not be detected for anything more specific than `Tuple`<Serializable>` (effectively, then, as `Tuple1<Object>`).
Thanks to this, type information will need to be written for both `Tuple1` and `item1` within,

Second, since scalars are serialized as JSON Scalars and they do not have properties, it is impossible to use `PROPERTY` inclusion: fallback is `AS_ARRAY` which may be used for such types.

If you wanted to avoid type inclusion there are 2 usual ways to work around type erasure:

1. Use a helper class to remove generic type declaration: public class LongTuple1 extends Tuple1<Long> { }
2. Specify type for `ObjectWriter`: something like

    String str = mapper.writerFor(new TypeReference<Tuple1<Long>>() { })
      .writeValueAsString(value);

Hope this helps.

**Comment by Conaclos** [comment]
Thanks,
The second solution is fine.

Yes, I understand the Java type erasure issue (and the polymorphism issue), making the need to embed type information.
However there is no-consistent serialization for boxed types:
Integer and Double don't embed type information, while Long and Float embed type information.

```Java
mapper.writeValueAsString(new Tuple1<>(Long.valueOf(1)));
// {"@class": "mypackage.Tuple1", item1: ["java.lang.Long",1]}

mapper.writeValueAsString(new Tuple1<>(Integer.valueOf(1)));
// {"@class": "mypackage.Tuple1", item1: 1}
````

Why?
For deserializing it is not needed since Jackson is able to choose the best implementation based on the "number length".

**Comment by cowtowncoder** [comment]
`int`/`Integer` and `double`/`Double` are indeed special cases, considered so-called "Native" types, along with `String` and `boolean`/`Boolean`. They are always written without type information as a minor optimization. This is possible because these are the types that matching JSON values would be converted in "untyped" case.
The main reason for adding this optimization was to reduce type information needed for Strings, and it seemed reasonable to then do the same for all 4 JSON scalar types. Whether this is a sensible optimization can be argued, but it is the way polymorphic handling has worked since the beginning (jackson 1.5).

I hope this helps explains this part of handling.

**Comment by Conaclos** [comment]
Thanks much!

I think that it is not really an issue for Float since it is rarely used...
However the optimization of Long could be needed in a near future, since some library designer discusses about to use long by default instead of int (Similar to the evolution from float to double).
