### ISSUE TITLE
Override deserialize in StdDelegatingDeserializer

### ISSUE THREAD

**Issue by varpa89** [FasterXML/jackson-databind#863]
StdDelegatingDeserializer has super JsonDeserializer, where method throws exception by default
```
    public T deserialize(JsonParser p, DeserializationContext ctxt,
            T intoValue)
        throws IOException, JsonProcessingException
    {
        throw new UnsupportedOperationException("Can not update object of type "
                +intoValue.getClass().getName()+" (by deserializer of type "+getClass().getName()+")");
    }
```
Can we override this method with ussage of
```
_delegateDeserializer.deserialize(jp, ctxt, intoValue);
```
?
We need it for usage @JsonDeserialize with converter, by deserialize with BeanDeserializer (_delegateDeserializer)

**Comment by cowtowncoder** [comment]
The problem here is that types involved are not guaranteed (or perhaps even likely) to be compatible; so the call would be likely to cause an exception.
But perhaps it would be legal to dispatch it if the types are compatible -- `_delegateType` does exist, after all, and it'd be possible to add a check to verify that `intoValue` is assignable to `_delegateType`?
If not, specific exception should be thrown; if it is is, forward the call.

**Comment by varpa89** [comment]
Thanks for the answer. But I can't understand where we shoud check "that intoValue is assignable to _delegateType" (I this only in StdDelegatingDeserializer)? Because DeserializeCache uses StdDelegatingDeserializer in _createDeserializer method. DeserializeCache is final class it is not possible to extend this class and override _createDeserializer...
Maybe I don't fully understand but how we can solve this concrete situation?

If it is possible to do in StdDelegatingDeserializer may we wait this feature in next release?

**Comment by cowtowncoder** [comment]
I think your suggestion would be correct, except that there is really no way to convert values as far as I can see. `updateValue()` is expected to use the object as is, and should not create a new value.
So I don't think `convertValue()` would work; however, the idea of using a separate method with default implementation that just throws an exception, is valid and makes sense. Maybe just with different name ("handleIncompatibleValueToUpdate()" or whatever).

The reason I suggest this is because I think there are 2 main use cases for delegating deserializer:

1. Truly converting one, where external type (that Jackson thinks deserializer is for) and internal (intermediate one that is used as temporary type) differ. I don't think `updateValue()` will usually work for this usage
2. Non-converting one used for other kinds of modifications: say, lower-casing of String values, or filling of default values; cases where external/internal types are the same (or at least compatible). If so, updateValue() should work.

**Comment by cowtowncoder** [comment]
FWIW I dd make suggested change, although no unit test to verify yet.

**Comment by varpa89** [comment]
Thanks! In which branch it will be committed?

**Comment by cowtowncoder** [comment]
Will be in `master`, to be part of 2.6.0, which in turn is scheduled to be released over this weekend (that is, in 2-3 days). Theoretically could be backported in 2.5 as well (given that this seems like a safe enough change to me), but it may take a while until 2.5.5 will be released.

**Comment by varpa89** [comment]
I found the commit! Could you explain updateValue() method? I can't find it..
As I see in deserialize(JsonParser p, DeserializationContext ctxt, Object intoValue) method you decided to not call convertValue(), but in case when we use 
```
@JsonDeserialize(converter = MyConverter.class)
```
for example via Spring Data Rest and make POST request there will be calling 
```
deserialize(JsonParser jp, DeserializationContext ctxt)
```
where convertValue() is calling
but when we make PUT method convertValue() does not calling because
```
deserialize(JsonParser p, DeserializationContext ctxt, Object intoValue)
```
used
I'm a little bit confused with this case.

**Comment by cowtowncoder** [comment]
`updateValue()` was just a reference to higher-level functionality that causes this method to be called; did not add any such method.

The reason I do not call `convertValue()` is that semantically this method should not try to create any other object, but to strictly update object given. That is the intent behind method, and should be the default behavior. Or at least that is the expectation.

This is not to say that developers could not override method and add such conversions, if they know what they are doing, and thing that different semantics are needed.
But that is something that I don't think default implementation should do.

You may want to implement an intermediate abstract class if you do want conversions to occur, base your serializers on that.
