### ISSUE TITLE
new module to inject OSGI services

### ISSUE THREAD

**Issue by gdelafosse** [FasterXML/jackson-databind#876]
I've just implemented a Jackson Module that can inject OSGI services in serialized object.
https://github.com/gdelafosse/jackson-module-osgi
Would you accept to take it as a FasterXML project?

**Comment by cowtowncoder** [comment]
That sounds like an excellent addition; we would happy to take it as a FasterXML project if you would like to do that. We will give you full rights for the project as well if so.

**Comment by cowtowncoder** [comment]
I think the only thing we need for this is the Contributor License Agreement from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

which is usually printed, filled+signed, scanned and email to `info` at fasterxml dot com.
This just simplifies life for us and legal help that enterprises use for ensuring that they are using Open Source appropriately.

We can transfer the project before that, but before the first "official" release, we need the CLA I think.

Timing is very good, too, since I think we could do 2.6.0 release as soon as project is ready.

**Comment by gdelafosse** [comment]
Great! I'll print and send it.

**Comment by gdelafosse** [comment]
I've just sent the CLA.

**Comment by cowtowncoder** [comment]
Received. Let me create a new fasterxml team, add you to it.

**Comment by cowtowncoder** [comment]
New team -- OSGi -- created, sent an invitation for you to join.

**Comment by gdelafosse** [comment]
Honored to join your group!
Are there programming conventions I must apply to the jackson-module-osgi to be FasterXML compliant?

**Comment by cowtowncoder** [comment]
Nothing I can think of -- I believe in "when in Rome" style, that is, author chooses something coherent, others try to follow it. But if there are some suggestions I'll make them: usually not much stylistically but rather functional things (prefer use of `final` for constant properties etc).
But appreciate your asking about it, as I know some projects are strict about these things, and it is good to learn this upfront.

**Comment by gdelafosse** [comment]
OK, I noticed the usage of PackageInfo in every Jackson modules, I will add one too to be consistent.
What about building/versionning/releasing/deploying? Do you manage those operations or must I setup something?

**Comment by cowtowncoder** [comment]
Good point, yes. PackageInfo is a simple template used to generate `PackageVersion` class that has Maven version information, accessed via `Version` interface. So it needs to be added, usually in the "main" java package of the module. That package then needs to be specified in `pom.xml`, so that build properly finds it.

Building should work simply using Maven release plugin, with `mvn release:prepare` and `mvn release:perform`, with no special set up. I can do releases as part of the full build of all standard components, unless you specifically want to do that. I am ok either way, but it may be more convenient if I just do it. If you would like to handle releases just let me know.

**Comment by cowtowncoder** [comment]
I created https://github.com/FasterXML/jackson-module-osgi/issues/1 and added relevant pieces: I think that is full set of things new modules need.

**Comment by gdelafosse** [comment]
Because of the time zones, it will be more convenient if you handle releases.
It´s ok to release on 2.6.0. I'm still thinking how I will enhance the module by adding dynamicity support (to avoid stale references when an injected service goes away)

**Comment by cowtowncoder** [comment]
Sounds good. I will proceed with 2.6.0 when I get a chance (maybe later tonight).

**Comment by gdelafosse** [comment]
Perfect, it´s time to close this ticket.
Thanks
