### ISSUE TITLE
Conflicting setter definitions for property in 2.6 not present in 2.5.3

### ISSUE THREAD

**Issue by apatrida** [FasterXML/jackson-databind#900]
This class deserialized fine in 2.5.3 but fails in 2.6 with conflicting setter definitions for setProtocol.

https://t.co/qEXz8VyWBL

Is the change intentional?

**Comment by cowtowncoder** [comment]
It does look like definition (removed other methods that do not contribute)

```java
public class PortMapping implements Serializable, Cloneable
{
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public void setProtocol(TransportProtocol protocol) {
        this.protocol = protocol.toString();
    }
}
```

is indeed ambiguous. But I am surprised that 2.5.3 did not catch this issue -- Jackson does not support variable-type properties, except via `@JsonCreator`. With `@JsonCreator` it is actually possible to have different constructors that take `String`, `int` etc; but same is not allowed via setters or fields.
Existence of otherwise conflicting setters in hierarchy is ok (that is, sub-class can "override" setters, even if signature differs).

So unless I missed something, 2.6 behavior is intentional, and this was a fix to validation. But I don't remember this as being explicitly fixed; most likely it came about as part of solving other problems with implicit names, or other 2.6 changes.
It is unfortunate that this does result in a backwards-compatibility problem.

I am open to suggestions for dealing with this issue. I am not sure there is an obvious interpretation in how to resolve the tie here, between two setters.

**Comment by mashrufkabir** [comment]
I'm looking forward to this.

**Comment by apatrida** [comment]
I think it isn't safe to make an assumption here.  Another dev here pointed out that the String setter agrees with the Getter of the same.  So that agreement should disambiguate.  Me, I think in this one case you could say that, but in general it isn't so likely to be clear.

I think the AWS libraries like to have Enum's or String combinations for setting properties so are littered with this behaviour.

No great way to do a reverse mixin?  Ignore this one setter, but do what you want with the rest?

**Comment by cowtowncoder** [comment]
Right, I think it is bit tricky. One could consider context with setter/getter combination, but that does get complicated quite fast, and understanding what exactly happens in edge cases become difficult.

Actually it should be enough to add `@JsonProperty` on one setter, leave the other(s) without.
Logic should be able to differentiate between explicit (annotated) and implicit (due to name and visibility). If this does not work it is a bug, but I think it does work in 2.6.

**Comment by apatrida** [comment]
" Actually it should be enough to add @JsonProperty on one setter, "

that assumes it is your code, we were trying not to wrap the tons of objects that may get sent around that already exist from library code.

**Comment by cowtowncoder** [comment]
@apatrida true. You may be able to use mix-ins, if it comes to that. Alternatively, as a very specific work-around, it would be possible to sub-class `JacksonAnnotationIntrospector` to indicate that particular would be seen to have `@JsonProperty`.

Anyway, at this point those are the main choices.

For 2.7 one possible thing to consider would be to finally add a way to inject conflict resolvers/handlers -- that is, to let modules register objects that would be called to possibly resolve conflicts between 2 otherwise equivalent accessors. This mechanism would be of particular use for other JVM languages like Scala or Kotlin modules, but could also work for (otherwise) non-conforming types.

**Comment by cowtowncoder** [comment]
Actually, I think #1044 should both resolve this specific case AND allow custom handling of remaining conflicts.
