### ISSUE TITLE
Serialize/deserialize of java.net.URI fails if URI contains backslash

### ISSUE THREAD

**Issue by david-bakin** [FasterXML/jackson-databind#908]
If the URI is, e.g., a `file:` protocol URI on Windows with an embedded backslash as path separator then it is serialized *without* quoting backslashes, then on deserialization:

1. Without `Feature.ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER` you get an error when a backslash appears before a non-quote-necessary character, (e.g., `'T'` or `'D'`)
1. With `Feature.ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER` you get an error when all backslashes are stripped leading to an invalid URI.

The actual problem is that when a URI is serialized the backslashes should be quoted at that time. (I don't understand why that didn't just happen.) (If there's a way to do that please let me know and close this issue, google/stackoverflow didn't supply an answer to me, though.)

**Comment by cowtowncoder** [comment]
Hmmh. That does not sound right: when Jackson writes JSON, `JsonGenerator` will add quoting for backslashes, and that occur regardless of JSON String value being serialized. So URI should not be special case in that sense. No invalid JSON escape should result.

But could it rather be that some system is producing incorrect JSON? Perhaps your problem is with incoming invalid JSON.

**Comment by cowtowncoder** [comment]
Can not reproduce the issue at this point.
