### ISSUE TITLE
ObjectMapper default timezone is GMT, should be UTC

### ISSUE THREAD

**Issue by Infrag** [FasterXML/jackson-databind#915]
ObjectMapper is configured with GMT timezone:
```
protected final static BaseSettings DEFAULT_BASE = new BaseSettings(
            null, // can not share global ClassIntrospector any more (2.5+)
            DEFAULT_ANNOTATION_INTROSPECTOR,
            STD_VISIBILITY_CHECKER, null, TypeFactory.defaultInstance(),
            null, StdDateFormat.instance, null,
            Locale.getDefault(),
//            TimeZone.getDefault()
            TimeZone.getTimeZone("GMT"),  // <= HERE
            Base64Variants.getDefaultVariant() // 2.1
    );
```
(it's on line 280)

But on many places in documentation and even in javadoc it's written that it's configured with UTC timezone. It is even cleaner to use UTC.

**Comment by cowtowncoder** [comment]
Yes, the use of GMT is an old oversight, from the time when I did not realize that the two are not the same. The main concern at this point is simply whether change could cause backwards compatibility issues. For 2.6 I did try out to see how many unit tests would fail; the number was low (I think 2), and none seemed necessarily valid failure.

But this is probably something that should still be discussed on `jackson-dev` list, since there are possibly significant backwards compatibility risks.

**Comment by Infrag** [comment]
Anyway it should definitely be synchronized with javadoc/documentation. I
noticed this problem only when timezone names were serilaside to json and
my tests failed.
Dne 9. 9. 2015 1:00 napsal uživatel "Tatu Saloranta" <
notifications@github.com>:

**Comment by cowtowncoder** [comment]
Agreed. I would prefer move to UTC, as documented, but just wanted to point out the challenge.

**Comment by cowtowncoder** [comment]
Changed for 2.7.0 so that default `TimeZone` for core `jackson-databind` is now UTC, consistently.
No apparent breakage wrt unit tests.

**Comment by cemo** [comment]
@cowtowncoder why not using java's default time zone?

**Comment by cowtowncoder** [comment]
@cemo partly because use of local timezone is mostly an anti-pattern (that is, developers use it without realizing, causing issues). And this because similar to "default encoding" it is often somewhat arbitrary what the timezone might be. I guess this is just one argument in two parts...
But basically use of local timezones seemed to me to be a source of many kinds of preventable problems.

So, to me it is similar to "why default to UTF-8 instead of platform default encoding", although it is not exactly the same thing (because JSON mandates UTF-8 as default etc).

**Comment by cowtowncoder** [comment]
Oh. And probably the bigger reason: since json is typically shared between two systems (sender/receiver) and those often have different default timezones, reliance on shared setting seems especially brittle. While timezone in use should be included in date/time values, and thereby setting should only affect serialization, it also seems likely that there are cases that would implicitly rely on shared setting, which could lead to nasty surprises (works during tests, fails in production).

**Comment by cemo** [comment]
Thanks for great explanation.

**Comment by cowtowncoder** [comment]
@cemo thank you for asking a good question: sometimes there are no good reasons, or reasons seem less convincing than what I thought.

**Comment by francisoliverlee** [comment]
why not follow timezone set by jvm , os?
@cowtowncoder

**Comment by yawkat** [comment]
OS timezone is rarely what you want, so it's better to require making that decision explicitly.

**Comment by francisoliverlee** [comment]
it's not about how rarely it is but how to get timezone by default.
imo, 
1. timezone user set
2. timezone jvm set
3. timezone os set

now, user does not set timezone, but jackson sets UTC by default which should get from jvm

**Comment by yihtserns** [comment]
☝️ https://github.com/FasterXML/jackson-databind/issues/915#issuecomment-291168664:

<img width="1069" height="629" alt="Image" src="https://github.com/user-attachments/assets/a33dc121-de00-4d81-88eb-b83ac8288b1a" />

**Comment by cowtowncoder** [comment]
We should not rely on whatever JVM or OS defaults might be. As per my earlier comments, JSON is data interchange format across systems, so settings of particular OS or JVM are generally meaningless.
UTC seems like the universal default: if user wants something else, let them configure `ObjectMapper`.

**Comment by francisoliverlee** [comment]
> We should not rely on whatever JVM or OS defaults might be. As per my earlier comments, JSON is data interchange format across systems, so settings of particular OS or JVM are generally meaningless. UTC seems like the universal default: if user wants something else, let them configure `ObjectMapper`.

got your idea , CoC.  golang uses UTF8 as default too.

but issue comes, we set java property `user.timezone`, and not work in `ObjectMapper` as expected, it breaks `write onece and run everywhere`. 
jackson is an lib in java, and should follow java-platform rules. it can use its own default value as `UTC` if not set `user.timezone` in java.

**Comment by cowtowncoder** [comment]
Jackson does not use any system properties for configuration (except maybe linefeed somewhere in format modules) and I have no intention of starting now.

If you want such defaulting I'd recommend writing helper code, or possibly Jackson module, to handle use of system property/-ies as configuration source.

**Comment by francisoliverlee** [comment]
tks for your nice response
