### ISSUE TITLE
i - I case convertion problem in Turkish locale

### ISSUE THREAD

**Issue by rmatesz** [FasterXML/jackson-databind#953]
In Turkish language there are two kind of i letter and therefore there is a common issue when trying to convert to lower or upper case (check: http://lotusnotus.com/lotusnotus_en.nsf/dx/dotless-i-tolowercase-and-touppercase-functions-use-responsibly.htm).
When a JSON string which contains field starting with upper case i (e.g. Icon) is being tried to deserialize with caseInsensitive = true property, the mapper is unable to find and fill the "icon" field in the object model because of the convertion issue described above.
Technical info: I've checked the source code of the library and there are some places where toLowerCase and/or toUpperCase is called with default Locale. These calls should be done with English locale when the calls are key-related to avoid this kind of issues.

Here is the specific place for the actual issue: https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/impl/BeanPropertyMap.java#L314

Workaround: JsonProperty annotation have to be set for these fields to exactly set the name case-sensitively.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. There are indeed a few places where leading character(s) are being lower cased, in addition to the code that tries full lower-casing you mention. I'll see if I can figure out a way to tease the problem, although I assume it would require use of the specific letter(s) to have effect, as well as override of the default locale.

I wonder, however, if the turkish handling would be desired in some cases? Since context objects (`SerializerProvider`, `DeserializationContext`) have configured `Locale` (accessible via `getLocale()`), perhaps it would make sense to use that instead of the default system Locale?
Then again, as things are this will be taken from `Locale.getDefault()`. But at least it would then be possible to force it to something else. It would also be possible to change the default `Locale` for Jackson for 2.7.

**Comment by cbsmith** [comment]
I love it. The first bug I've seen in a while that successfully calls out the rather "Turkish I Problem": http://www.salon.com/2004/12/09/spolsky/

**Comment by cowtowncoder** [comment]
@cbsmith :-) -- thank you for sharing that, hadn't seen it.

**Comment by Dimezis** [comment]
@cowtowncoder 
Is it planned to be fixed?
I can make a PR with a fix, if you wish.

**Comment by cowtowncoder** [comment]
@Dimezis I have no active plan -- not aware of efficient way of doing this. So PR (or even to existing impl for other libraries) would be welcome.

**Comment by Dimezis** [comment]
@cowtowncoder please check out the PR and let me know what you think https://github.com/FasterXML/jackson-databind/pull/2554

**Comment by cowtowncoder** [comment]
I added a failing test (slight modification from one in patch), and will see if it'd be easier to address that particular part (case-insensitive properties not matching), first, without worrying about naming strategy part.

**Comment by cowtowncoder** [comment]
Ok, so: I fixed the first part, wherein case-insensitive deserialization should work with Turkish locale too (I have some work for 3.0.0/master to finish) up, and will file another for remaining work that is needed for `PropertyNamingStrategy`.
