### ISSUE TITLE
Change in StringDeserializer behavior on JsonToken.VALUE_NULL from 1.x to 2.x?

### ISSUE THREAD

**Issue by jcdavis** [FasterXML/jackson-databind#986]
I will say upfront that I'm not super knowledgeable about jackson (despite what my name might say otherwise ;)), so I'm not sure if this is even an issue or intended.

I've been working on doing a 1.X -> 2.X jackson upgrade and ran into exceptions from StringDeserializer (used from another lib) on parsing a null. In 1.X, `deserialize` looking at a `JsonToken.VALUE_NULL` as the current token, returns `null`, via

        // Can deserialize any scalar value, but not markers
        if (curr.isScalarValue()) {
            return jp.getText();
        }

(since `VALUE_NULL` passes the check). Now (at least on 2.4.X), this doesn't work due to the null guard:

        // allow coercions for other scalar types
        String text = jp.getValueAsString();
        if (text != null) {
            return text;
        }

so it falls through to the exception.
This isn't the end of the world for my case because I've written a wrapping deserializer to handle this case, but it does seem a little odd, is this an intended behavior change?

Thanks,
-Jackson (the human)

**Comment by cowtowncoder** [comment]
(nice name!)

As a general rule, `JsonDeserializer` instances should never encounter `JsonToken.VALUE_NULL` -- it should always be handled by the parent deserializer (or in case of root value, `ObjectMapper` or `ObjectReader`). So this part of handling should not really matter.

So the bigger question would be why caller is delegating this handling to `StringDeserializer`.

Change itself is not intentional.

**Comment by jcdavis** [comment]
The caller probably didn't know any better :).

I appreciate for the explanation

**Comment by cowtowncoder** [comment]
@jcdavis No problem! Exact rules and responsibilities for components are not that well-defined so it is understandable omission. And in hindsight, making deserializers responsible for null-value handling might have been better choice, since although it adds one more check in deserializer (as opposed to only container-types requiring handling, less numerous than scalar deserializers), doing that would have allowed much much easier coercion of JSON `null` into non-null Java values.
