### ISSUE TITLE
Enable deserialization from multiple files for composite objects

### ISSUE THREAD

**Issue by aryehpro** [FasterXML/jackson-databind#995]
I've searched around quite a bit for a way to do this, but it seems to just not be supported. Please correct me if I'm wrong.

Say I have a composite object, for example:

``` java
class Foo {
    private Bar _bar;
    private string _fooString;
}
```

``` java
class Bar {
    private String _barString;
    private int _barInt;
}
```

When such composite objects become more complex (each object has more fields, multiple levels of composition etc.) the json representing them could become very complicated and uncomfortable to work with. Moreover, in some cases we might want to re-use some of the elements of property-classes among different instances of the composite object.

For the above reasons, I think it would be helpful to implement a way of giving a path to a separate json file holding the description of the property-object, rather than writing out the entire object. So for the above example classes, instead of having:

filename: foo_instance.json

``` json
{
  "bar": {
    "barString": "a string",
    "barInt": 123
  },
  "fooString": "another string"
}
```

we might have these two files:

filename: foo_instance.json

``` json
{
  "bar": "bar_instance.json",
  "fooString": "another string"
}
```

filename: bar_instance.json

``` json
{
    "barString": "a string",
    "barInt": 123
}
```

And the suggested enhancement would enable a regular use of ObjectReader.readValue method that receives foo_instance.json as input to correctly deserialize The Foo object including the information in bar_instance.json.

I think this should require as little change to he POJOs being deserialized as possible, and should enable the POJOs to be agnostic of the json format used (in the above example, both versions of the json representation should be deserialized to the same objects without changing the code of Foo and Bar classes).

**Comment by cowtowncoder** [comment]
Thank you for suggestion.

I am not a big fan of automatic resolution, since it opens immediate security issues (similar to automatic expasion of URLs). It would also be necessary to have speculative expansion of a JSON String value for a POJO. That seems like asking for trouble more than anything else, no matter how convenient it could be.

I would be more willing to allow use of an annotation to indicate that a given POJO value may be external; and perhaps allowing customizable resolvers. So, if POJO did instead have:

```java
class Foo {
    // something like:
    @JsonExternal(using=FileResolver.class,
       allowInline=true) // defaults to `true` but can be set to `false` to disallow inlined value
    private Bar _bar;
    private string _fooString;
}
```

it could allow such resolution, but only in well-defined places.

An alternative mechanism that could do what you are asking for could be to be able to register, globally, sort of fallback handler: an object that would be invoked to handle deserialization from otherwise incompatible type(s). Specifically: while there are cases where POJO can be serialized from JSON String (usually with `@JsonCreator`, or single-String-arg constructor), most of the time this results in an exception. If a handler is registered, it could instead be invoked, and asked to handle deserialization. It could then load the contents; but the specific handling is not done by Jackson core components, so that business logic and security rules are defined by application code (or by extension libs).

So: I think it makes sense to allow some sort of resolution from external sources. But I am not sure this resolution itself should be handled by Jackson, as the details vary a lot for different users, use cases.

**Comment by aryehpro** [comment]
I agree that external source resolution could be problematic, and that the specifics of how and when this resolution occurs should be handled by the application.

I think the use of the JsonExternal annotation is a cleaner and more elegant solution. I'm quite eager to try and implement this enhancement myself. As I am a bit new to development of the jackson library, I have a few questions:

1. Could you point me to some information as to what is the best way to add new annotations to the library? What classes need to be implemented to enable a new annotation? (pointing me to relevant source code is enough if documentation doesn't exist)

2. Should these enhancements go into the databind package (as they enable more functionality in the POJO-to-JSON conversion in a similar way to other parts of databind) or into the annotations package (as they revolve around advanced annotations)?

3. I would think that writing a default file resolver (StdFileResolver?) would be a good idea. Is this ok, or do we want to force all resolution to be done by the application?

4. Do you have any preferred methods for contributions to the project? Should I just fork the project and then post a pull request with the enhanced code?

thanks for the reply :)

**Comment by cowtowncoder** [comment]
The extension point for annotations is `AnnotationIntrospector` (and its default implementation, `JacksonAnnotationIntrospector`). This just reads annotation in question; annotations are defined in `jackson-annotations` project, unless they rely on a type specified in databind, in which case a small number of annotations are defined within `jackson-databind` itself.

Handling of annotations itself must go in databind as annotations package has very little code.

PRs are the common for enhancements, so fork & PR works fabulously. We do need a CLA before merging the first contribution, but that can be handled later on.

Code may not always be the simplest to handle, so it may not be trivial to find the right point for handling. In general, this would be for deserialization side, and probably to be handled via POJO properties (`SettableBeanProperty`, invoked via `BeanDeserializer`). Since annotation(s) would be defined for property (setter, field), access would either need to be from within `createContextual()` method of `BeanDeserializer`, or from wherever `BeanDeserializer` is constructed (`BeanDeserializerFactory`). I can't say offhand what would be the easiest way.

Actually it is possible that delegation model could work best; if it was done outside of `jackson-databind`, I would use `BeanDeserializerModifier`. Code that invokes method of this handler may be good place to look.

**Comment by cowtowncoder** [comment]
I don't think suggestion as indicated is implementable; rather, something like inclusion support should be added outside (above) of databind module.
